#pragma once
#include <vector>
#include "sprite_list.h"
#include "sound_list.h"
#include "room_list.h"


using namespace Organik;
using namespace Utils;

namespace Organik 
{
    void DoHelperSetup();
}

#ifndef CONCATENATE
#define CONCATENATE(s1, s2) s1##s2
#define EXPAND_THEN_CONCATENATE(s1, s2) CONCATENATE(s1, s2)
#endif
#ifndef DUMMYVAR
#define DUMMYVAR(name) \
    EXPAND_THEN_CONCATENATE(name, __COUNTER__)
#endif

#define OBJECTS_DO(THING) \
    THING(obj_null) \
    THING(outgame) \
    THING(obj_stats) \
    THING(obj_control) \
    THING(obj_allgame) \
    THING(obj_ingame_ctrl) \
    THING(obj_room_ctrl) \
    THING(obj_enemy_ctrl) \
    THING(obj_effect_draw_flying) \
    THING(obj_net_rpc) \
    THING(obj_bindings_default) \
    THING(obj_bindings) \
    THING(obj_bindings_french) \
    THING(obj_loca_button) \
    THING(obj_patchhistory) \
    THING(obj_servermessage) \
    THING(obj_patchpage_parent) \
    THING(obj_patchlog_parent) \
    THING(obj_patchlog_about) \
    THING(obj_patchpage_home) \
    THING(obj_patchlog_planned) \
    THING(obj_patchlog_1) \
    THING(obj_patchlog_2) \
    THING(obj_patchlog_currentpatch) \
    THING(obj_separator) \
    THING(obj_patchbutton_parent) \
    THING(obj_patchbutton_about) \
    THING(obj_patchbutton_planned) \
    THING(obj_patchbutton_community) \
    THING(obj_patchbutton_1) \
    THING(obj_patchbutton_2) \
    THING(obj_patchbutton_currentpatch) \
    THING(obj_patchbutton_4) \
    THING(obj_launcher_newsletter) \
    THING(obj_debug_save) \
    THING(obj_start_game) \
    THING(obj_launcher_background) \
    THING(obj_launcher_overlay) \
    THING(obj_launcher_showreel) \
    THING(obj_cutscene_cinematic) \
    THING(obj_cutscene_cinematic_gameend) \
    THING(T_perk_Riotguard_PARENT) \
    THING(T_perk_painkillers) \
    THING(T_perk_fullyloaded) \
    THING(T_perk_powerreload) \
    THING(T_perk_shortbarrel) \
    THING(T_perk_unstoppable) \
    THING(T_perk_powerupdouble) \
    THING(T_perk_riotprestige) \
    THING(T_perk_Breacher_PARENT) \
    THING(T_perk_SWAT_PARENT) \
    THING(T_perk_launcherammo) \
    THING(T_perk_exploresi) \
    THING(T_perk_specialwepprofi) \
    THING(T_perk_dooropener) \
    THING(T_perk_rubbergrenade) \
    THING(T_perk_fastsling) \
    THING(T_perk_shotgunprofi) \
    THING(T_perk_movementaccuracy) \
    THING(T_perk_standingshotgun) \
    THING(T_perk_movespeed1) \
    THING(T_perk_cqbcatalist) \
    THING(T_perk_platingtime) \
    THING(T_perk_maxplating1) \
    THING(T_perk_platingluck) \
    THING(T_perk_scavenging1) \
    THING(T_perk_bitsandpieces) \
    THING(T_perk_reactiveplating) \
    THING(T_perk_healing1) \
    THING(T_perk_methadoneinfusion) \
    THING(T_perk_dangerstim) \
    THING(T_perk_stimulus) \
    THING(T_perk_resilience) \
    THING(T_perk_stunning) \
    THING(T_perk_shockmaster) \
    THING(T_perk_shockmaster2) \
    THING(T_perk_autotaser) \
    THING(T_perk_killshield) \
    THING(T_perk_shieldoverclock) \
    THING(T_perk_shield1) \
    THING(T_perk_aegismk5) \
    THING(T_perk_fusionpower) \
    THING(T_perk_powerrerouting) \
    THING(T_perk_armor1) \
    THING(T_perk_rebuke) \
    THING(T_perk_iframe) \
    THING(T_perk_cqbmastery) \
    THING(T_perk_smgcrit) \
    THING(T_perk_dashcd1) \
    THING(T_perk_grenadecd1) \
    THING(T_perk_underbarrelmaster) \
    THING(obj_research_button_PARENT) \
    THING(rb_skillreset) \
    THING(rb_dailybonus) \
    THING(rb_booster) \
    THING(rb_allweapondata) \
    THING(rb_allitemdata) \
    THING(rb_) \
    THING(obj_talent_selection) \
    THING(obj_talent_screenbutton) \
    THING(obj_talent_screendown) \
    THING(obj_talent_screenup) \
    THING(obj_connecter) \
    THING(obj_levelmarker) \
    THING(obj_godmove) \
    THING(obj_fullhdchecker) \
    THING(obj_viewcenter) \
    THING(T_CTRL) \
    THING(T_PARENT_ALL_BONI) \
    THING(T_Path_PARENT) \
    THING(T_overdrive_token) \
    THING(T_Path_vert) \
    THING(T_Path_hor) \
    THING(T_path_cross) \
    THING(T_path_crosstop) \
    THING(T_path_crossbot) \
    THING(T_path_crossright) \
    THING(T_path_crossleft) \
    THING(T_Path_curve_topright) \
    THING(T_Path_curve_topleft) \
    THING(T_Path_curve_botright) \
    THING(T_Path_curve_botleft) \
    THING(T_Path_start_PARENT) \
    THING(T_Path_start_SWAT) \
    THING(T_Path_start_riotguard) \
    THING(T_Path_start_breacher) \
    THING(T_Path_start_rogue) \
    THING(T_path_start_brightguard) \
    THING(T_Path_start_military) \
    THING(T_path_start_redguard) \
    THING(T_path_start_general) \
    THING(T_path_god_start_PARENT) \
    THING(T_path_start_god0) \
    THING(T_path_start_god1) \
    THING(T_path_start_god2) \
    THING(T_item_PARENT) \
    THING(T_item_grenadehe) \
    THING(T_item_grenadeflash) \
    THING(T_item_grenadeheal) \
    THING(T_item_grenadefrag) \
    THING(T_item_stimpack) \
    THING(T_item_ammopack) \
    THING(T_item_healthvial) \
    THING(T_item_chaos) \
    THING(T_item_injection) \
    THING(T_item_healingcrystal) \
    THING(T_item_vial) \
    THING(T_item_methadone) \
    THING(T_item_amphetamine) \
    THING(T_item_laststand) \
    THING(T_item_teleport) \
    THING(T_slot_PARENT) \
    THING(T_slot_free0) \
    THING(T_slot_free1) \
    THING(T_slot_free2) \
    THING(T_slot_free3) \
    THING(T_slot_free4) \
    THING(T_slot_free5) \
    THING(T_slot_free6) \
    THING(T_slot_free7) \
    THING(T_slot_free8) \
    THING(T_slot_free9) \
    THING(T_slot_free10) \
    THING(T_slot_free11) \
    THING(T_slot_free12) \
    THING(T_slot_free13) \
    THING(T_slot_free14) \
    THING(T_stat_PARENT) \
    THING(T_stat_shield) \
    THING(T_stat_killshield) \
    THING(T_stat_scavenging) \
    THING(T_stat_scavenging2) \
    THING(T_stat_healthy) \
    THING(T_stat_health2) \
    THING(T_stat_terrorlevel) \
    THING(T_stat_threat_plus) \
    THING(T_stat_luck) \
    THING(T_stat_luck2) \
    THING(T_stat_credits) \
    THING(T_stat_credits2) \
    THING(T_stat_dodge) \
    THING(T_stat_dodge2) \
    THING(T_stat_data) \
    THING(T_stat_data2) \
    THING(T_stat_movespeed) \
    THING(T_weapon_PARENT) \
    THING(T_weapon_PXS) \
    THING(T_weapon_PTL) \
    THING(T_weapon_REV) \
    THING(T_weapon_REP) \
    THING(T_weapon_LSPT) \
    THING(T_weapon_HON) \
    THING(T_perk_PARENT) \
    THING(T_perk_general_PARENT) \
    THING(T_perk_addict) \
    THING(T_perk_shortcd) \
    THING(T_perk_longcd) \
    THING(T_perk_recycler) \
    THING(T_perk_reckless) \
    THING(T_perk_pistolultimate) \
    THING(T_perk_vialcharge) \
    THING(T_perk_itemslot) \
    THING(T_perk_healroom) \
    THING(T_perk_bossheal) \
    THING(T_perk_threat_minus) \
    THING(T_perk_elite_PARENT) \
    THING(T_perk_reloadstack) \
    THING(T_perk_recoilctrl) \
    THING(T_perk_nightvision) \
    THING(T_perk_nightvisioncd) \
    THING(T_perk_assaultrifle) \
    THING(T_perk_bleedingmammo) \
    THING(T_perk_hollowpoint) \
    THING(T_perk_ultrashot) \
    THING(T_perk_ultrachance) \
    THING(T_perk_weaponslot) \
    THING(T_perk_combo) \
    THING(T_perk_powerstep) \
    THING(T_perk_powertreads) \
    THING(T_perk_fury) \
    THING(T_perk_drill) \
    THING(T_perk_elitecore) \
    THING(T_perk_itemcdsmall) \
    THING(T_perk_itemcdvariant) \
    THING(T_perk_psyonic_PARENT) \
    THING(T_perk_) \
    THING(T_perk_teleport2) \
    THING(T_perk_laserpen) \
    THING(T_perk_laserfire) \
    THING(T_perk_adrenaline) \
    THING(T_perk_smgspec) \
    THING(T_perk_smallcaliber) \
    THING(T_perk_ascendance) \
    THING(T_perk_killstealth) \
    THING(T_perk_minimapenemies) \
    THING(T_perk_support_PARENT) \
    THING(T_perk_pistolspec) \
    THING(T_perk_commander) \
    THING(T_perk_hitshield) \
    THING(T_perk_mindcontrol) \
    THING(T_perk_infusionvial) \
    THING(T_perk_softpoint) \
    THING(T_perk_pistolvariants) \
    THING(T_perk_commander2) \
    THING(T_perk_riot) \
    THING(T_perk_unitdeath) \
    THING(T_perk_healing) \
    THING(T_perk_platingstart) \
    THING(T_perk_pistolspec2) \
    THING(T_perk_calm) \
    THING(T_perk_grenadier) \
    THING(T_perk_rally) \
    THING(T_perk_poweroverflow) \
    THING(T_perk_statusextender) \
    THING(T_perk_sharingcaring) \
    THING(T_perk_threatminussup) \
    THING(T_perk_sharingcaring2) \
    THING(T_perk_alchemist_PARENT) \
    THING(T_perk_markheal) \
    THING(T_perk_refinement) \
    THING(T_perk_craze) \
    THING(T_perk_dodgeheat) \
    THING(T_perk_dodgeheat2) \
    THING(T_perk_selfrepair) \
    THING(T_perk_selfrepair2) \
    THING(T_perk_elementalpower) \
    THING(T_perk_itemheat) \
    THING(T_perk_contaminate) \
    THING(T_perk_pistolextender) \
    THING(T_perk_ammoregen) \
    THING(T_perk_itempower) \
    THING(T_perk_doublepickup) \
    THING(T_perk_launchers) \
    THING(T_perk_minimapchests) \
    THING(T_perk_reforge) \
    THING(T_perk_shrapnel) \
    THING(T_perk_playfire) \
    THING(T_perk_wepupgrade) \
    THING(T_perk_rogue_PARENT) \
    THING(T_perk_shophack) \
    THING(T_perk_poisonammo) \
    THING(T_perk_bounces) \
    THING(T_perk_deviation) \
    THING(T_perk_dodgeboost) \
    THING(T_perk_reloadsurge) \
    THING(T_perk_ADS) \
    THING(T_perk_coolhead) \
    THING(T_perk_dexterity) \
    THING(T_perk_perfection) \
    THING(T_perk_mastercard) \
    THING(T_perk_shadow) \
    THING(T_perk_discipline) \
    THING(T_perk_markdrone) \
    THING(T_perk_prepared) \
    THING(T_perk_roguecore) \
    THING(T_perk_headshotammo) \
    THING(T_perk_headshotheal) \
    THING(T_perk_moneyshot) \
    THING(T_perk_specialized) \
    THING(T_perk_tank_PARENT) \
    THING(T_perk_aegis) \
    THING(T_perk_laststand) \
    THING(T_perk_shotgunmaster) \
    THING(T_perk_shotgun) \
    THING(T_perk_standfirm) \
    THING(T_perk_lowhpregen) \
    THING(T_perk_scavengerbits) \
    THING(T_perk_platingcapacity) \
    THING(T_perk_shieldoc) \
    THING(T_perk_bloodinfusion) \
    THING(T_perk_laststand2) \
    THING(T_perk_warmup) \
    THING(T_perk_fortify) \
    THING(T_perk_healthreg) \
    THING(T_perk_cover) \
    THING(T_perk_reactivearmor) \
    THING(T_perk_powerbolt) \
    THING(T_perk_scraparmor) \
    THING(T_perk_guardianfate) \
    THING(T_perk_closer) \
    THING(T_perk_heatup) \
    THING(T_perk_hframe) \
    THING(T_perk_lifeline) \
    THING(T_perk_lifesteal) \
    THING(obj_perk_parent) \
    THING(obj_artefact_parent) \
    THING(obj_artefact_weaponcarry) \
    THING(obj_artefact_itemupgrade) \
    THING(obj_artefact_ricochet) \
    THING(obj_artefact_terrorlevel) \
    THING(obj_artefact_elemental) \
    THING(obj_artefact_ultradrop) \
    THING(obj_artefact_friendlyfire) \
    THING(obj_artefact_slowdown) \
    THING(obj_artefact_healing) \
    THING(obj_artefact_shop) \
    THING(obj_artefact_crit) \
    THING(obj_artefact_strafe) \
    THING(obj_artefact_powerup) \
    THING(obj_artefact_buff) \
    THING(obj_artefact_pistol) \
    THING(obj_artefact_madness) \
    THING(obj_artefact_mysterybonus) \
    THING(obj_artefact_instagib) \
    THING(obj_artefact_tactical) \
    THING(obj_artefact_randomrun) \
    THING(obj_chip_parent) \
    THING(obj_chip_health) \
    THING(obj_chip_dodge) \
    THING(obj_chip_scavenging) \
    THING(obj_chip_ammogain) \
    THING(obj_chip_luck) \
    THING(obj_chip_credits) \
    THING(obj_chip_armor) \
    THING(obj_chip_shield) \
    THING(obj_chip_heat) \
    THING(obj_chip_movespeed) \
    THING(obj_chip_accuracy) \
    THING(obj_perk_riotguard) \
    THING(obj_perk_guardian1) \
    THING(obj_perk_breacher) \
    THING(obj_perk_warmup) \
    THING(obj_perk_iframe) \
    THING(obj_perk_aegis) \
    THING(obj_perk_aegis2) \
    THING(obj_perk_enrage) \
    THING(obj_perk_heatup) \
    THING(obj_perk_closer) \
    THING(obj_perk_shotgun) \
    THING(obj_perk_shotgunmaster) \
    THING(obj_perk_shieldoc) \
    THING(obj_perk_bloodinfusion) \
    THING(obj_perk_creditsdisplay) \
    THING(obj_perk_bloodinfusion1) \
    THING(obj_perk_lowhpregen) \
    THING(obj_perk_scavengerbits) \
    THING(obj_perk_recovery) \
    THING(obj_perk_lifeline) \
    THING(obj_perk_return) \
    THING(obj_perk_berserk) \
    THING(obj_perk_reloadsurge2) \
    THING(obj_perk_scraparmor) \
    THING(obj_perk_rogue) \
    THING(obj_perk_assassin) \
    THING(obj_perk_marksman) \
    THING(obj_perk_longrange) \
    THING(obj_perk_ejectsurge) \
    THING(obj_perk_dodgeboost) \
    THING(obj_perk_powertuning) \
    THING(obj_perk_mastercard) \
    THING(obj_perk_crossbow) \
    THING(obj_perk_backstab) \
    THING(obj_perk_diehard) \
    THING(obj_perk_discipline) \
    THING(obj_perk_dance) \
    THING(obj_perk_headshotammo) \
    THING(obj_perk_perfection) \
    THING(obj_perk_specialized) \
    THING(obj_perk_customammo) \
    THING(obj_perk_mindmg) \
    THING(obj_perk_holdbreathold) \
    THING(obj_perk_reactivereload) \
    THING(obj_perk_standstill) \
    THING(obj_perk_stealback) \
    THING(obj_perk_commando) \
    THING(obj_perk_raider) \
    THING(obj_perk_assaultgunner) \
    THING(obj_perk_squadleader) \
    THING(obj_perk_ultrashot) \
    THING(obj_perk_wepupgrade) \
    THING(obj_perk_drill) \
    THING(obj_perk_rankup) \
    THING(obj_perk_fieldration) \
    THING(obj_perk_specializedammo) \
    THING(obj_perk_reloadstack) \
    THING(obj_perk_obsession) \
    THING(obj_perk_powerstep) \
    THING(obj_perk_itemcdvariant) \
    THING(obj_perk_killer) \
    THING(obj_perk_stubborn) \
    THING(obj_perk_reloadsurge) \
    THING(obj_perk_fortify) \
    THING(obj_perk_holdbreath) \
    THING(obj_perk_hollowpoint) \
    THING(obj_perk_cover) \
    THING(obj_perk_edge) \
    THING(obj_perk_scarred) \
    THING(obj_perk_combo) \
    THING(obj_perk_dogtags) \
    THING(obj_perk_explosiveammo) \
    THING(obj_perk_elemental) \
    THING(obj_perk_demolisher) \
    THING(obj_perk_annihilator) \
    THING(obj_perk_lasercaster) \
    THING(obj_perk_engineer) \
    THING(obj_perk_heatcontrol) \
    THING(obj_perk_pistolextender) \
    THING(obj_perk_statusextender) \
    THING(obj_perk_hframe) \
    THING(obj_perk_focus) \
    THING(obj_perk_grenadier) \
    THING(obj_perk_calm) \
    THING(obj_perk_m79) \
    THING(obj_perk_force) \
    THING(obj_perk_dodgeheat) \
    THING(obj_perk_sunrise) \
    THING(obj_perk_selfrepair) \
    THING(obj_perk_ammoregen) \
    THING(obj_perk_heatrecharge) \
    THING(obj_perk_transmutate) \
    THING(obj_perk_drone1) \
    THING(obj_perk_elementalpower) \
    THING(obj_perk_morph) \
    THING(obj_perk_cultist) \
    THING(obj_perk_coolhead) \
    THING(obj_perk_steady) \
    THING(obj_perk_healthcrate) \
    THING(obj_perk_barrier) \
    THING(obj_perk_none) \
    THING(obj_perk_randomperk) \
    THING(obj_buff_talent) \
    THING(obj_perk_healthy) \
    THING(obj_perk_classweapon) \
    THING(obj_perk_killshield) \
    THING(obj_perk_shophack) \
    THING(obj_perk_itemslot) \
    THING(obj_perk_healroom) \
    THING(obj_perk_prepared) \
    THING(obj_perk_credits) \
    THING(obj_perk_luck) \
    THING(obj_perk_scavenging) \
    THING(obj_perk_nimble) \
    THING(obj_perk_terrorlevel) \
    THING(obj_perk_brightguard) \
    THING(obj_perk_ballisticsdiv) \
    THING(obj_perk_orderofzir) \
    THING(obj_kit_p33) \
    THING(obj_kit_hon) \
    THING(obj_kit_lspt) \
    THING(obj_cursor) \
    THING(obj_cursor_camera) \
    THING(obj_cursor_lockon) \
    THING(obj_weapon_mouseover) \
    THING(obj_interest_mouseover) \
    THING(obj_enemyleft_mouseover) \
    THING(obj_passive_mouseover) \
    THING(obj_health_mouseover) \
    THING(obj_buffs_debuffs) \
    THING(obj_buff_statboosts) \
    THING(obj_buff_movespeed) \
    THING(obj_debuff_movespeed) \
    THING(obj_debuff_move_barbed) \
    THING(obj_debuff_maxhealth_curse) \
    THING(obj_debuff_cheat) \
    THING(obj_debuff_hardmode) \
    THING(obj_debuff_loop) \
    THING(obj_buff_healthreg) \
    THING(obj_buff_firerate) \
    THING(obj_buff_healing) \
    THING(obj_buff_overclock) \
    THING(obj_debuff_healing) \
    THING(obj_buff_shield) \
    THING(obj_buff_invulner) \
    THING(obj_buff_explosion) \
    THING(obj_buff_mines) \
    THING(obj_buff_thunder) \
    THING(obj_buff_fire) \
    THING(obj_buff_drones) \
    THING(obj_buff_drones_target) \
    THING(obj_buff_fanOfKnives) \
    THING(obj_buff_turrets) \
    THING(obj_buff_slowmo) \
    THING(obj_buff_keycard) \
    THING(obj_buff_shieldreg) \
    THING(obj_buff_incdamage) \
    THING(obj_buff_damageresi) \
    THING(obj_buff_instagib) \
    THING(obj_buff_enmdmgresi) \
    THING(obj_buff_timed) \
    THING(obj_buff_dodge) \
    THING(obj_buff_ammoreg) \
    THING(obj_buff_reloadspeed) \
    THING(obj_buff_spreadcontrol) \
    THING(obj_buff_flaregun) \
    THING(obj_buff_smokescreen) \
    THING(obj_buff_psycloud) \
    THING(obj_buff_critchance) \
    THING(obj_buff_crystal) \
    THING(obj_buff_ammo2) \
    THING(obj_debuff_poison) \
    THING(obj_debuff_bleeding) \
    THING(obj_debuff_burning) \
    THING(obj_debuff_stun) \
    THING(obj_debuff_antishield) \
    THING(obj_buff_speedboost) \
    THING(obj_buff_stimpack) \
    THING(obj_buff_airhorn) \
    THING(obj_buff_ministim) \
    THING(obj_buff_expboost) \
    THING(obj_buff_expboost_onlyexp) \
    THING(obj_buff_firsttime) \
    THING(obj_tooltip_gold) \
    THING(obj_tooltip_hp) \
    THING(obj_delete_newgame) \
    THING(obj_menu_visibility) \
    THING(obj_creditsdisplay) \
    THING(obj_audiovoice) \
    THING(obj_lastkill) \
    THING(obj_hit_circle_marker) \
    THING(obj_levelup) \
    THING(obj_combos) \
    THING(obj_upgrademenu) \
    THING(obj_loadingscreen) \
    THING(obj_splash_screen) \
    THING(obj_main_ui) \
    THING(obj_main_ui_S1) \
    THING(obj_main_ui_weapon) \
    THING(obj_selection_menu) \
    THING(obj_selection_menu_perk) \
    THING(obj_roll_classitem) \
    THING(obj_selection_menu_artefact) \
    THING(obj_selection_menu_stat) \
    THING(obj_selection_menu_ammo) \
    THING(obj_escapesettings) \
    THING(obj_androidconsole) \
    THING(obj_dialog_ui) \
    THING(obj_poison_area) \
    THING(obj_escapescreen) \
    THING(obj_pausemenu) \
    THING(obj_reloading) \
    THING(obj_helpmenu) \
    THING(obj_logmenu) \
    THING(obj_quests) \
    THING(obj_deathstatistics) \
    THING(obj_questlog_slots) \
    THING(obj_questlog_parent) \
    THING(obj_questlog_generic) \
    THING(obj_weaponstats) \
    THING(obj_itemstats) \
    THING(obj_statistics) \
    THING(obj_color) \
    THING(obj_colorpicker) \
    THING(obj_overlays_aboveui) \
    THING(obj_overlays_belowui) \
    THING(obj_kill_marker) \
    THING(obj_terrorlevel) \
    THING(obj_badge_display) \
    THING(obj_decaldraw) \
    THING(obj_class_upgrade) \
    THING(obj_tooltip_terrorlevel) \
    THING(obj_tooltip) \
    THING(obj_tooltipbig_weapons) \
    THING(obj_tooltipbig) \
    THING(obj_tooltip_damagetext) \
    THING(obj_popup_notice) \
    THING(obj_popup_skillduration) \
    THING(obj_popup_announcement) \
    THING(obj_popup_exp) \
    THING(obj_console) \
    THING(obj_music_track_loop) \
    THING(obj_eula_popup) \
    THING(obj_bigbrother_mode) \
    THING(obj_deathscreenshot) \
    THING(obj_chromaticabberation) \
    THING(obj_difficultyselection_overlay) \
    THING(obj_classselection) \
    THING(obj_factionselection) \
    THING(obj_difficultyselection_1) \
    THING(obj_difficultyselection_2) \
    THING(obj_difficultyselection_class) \
    THING(obj_difficultyselection_language) \
    THING(obj_demoscreen) \
    THING(obj_wave_effect) \
    THING(obj_towerprogress) \
    THING(obj_surface_light) \
    THING(obj_surface_Fog) \
    THING(obj_blur_surface) \
    THING(obj_blur_draw) \
    THING(obj_blur_background) \
    THING(obj_blur_pregame) \
    THING(obj_blur_slomo) \
    THING(obj_blur_bokeh) \
    THING(DirtyBloom_obj) \
    THING(obj_FogOfWar) \
    THING(obj_LUT_end) \
    THING(obj_LUT_start) \
    THING(obj_player) \
    THING(obj_localPlayer) \
    THING(obj_remotePlayer) \
    THING(obj_turret_spwn) \
    THING(obj_turret_boss_spawn_parent) \
    THING(obj_turret_boss_spawn_sniper) \
    THING(obj_turret_boss_spawn_mortar) \
    THING(obj_turret_boss_spawn_random) \
    THING(obj_turret_boss_spawn_radar) \
    THING(obj_turret_boss_spawn_rocket) \
    THING(obj_turret_boss_spawn_healing) \
    THING(obj_enm_turret_parent) \
    THING(obj_enm_turret_sniper) \
    THING(obj_enm_turret_rocket) \
    THING(obj_enm_turret_vierling) \
    THING(obj_enm_turret_laser) \
    THING(obj_enm_turret_flamer) \
    THING(obj_enm_turret_radar) \
    THING(obj_enm_turret_grenade) \
    THING(obj_enm_turret_aura) \
    THING(obj_enm_turret_healing) \
    THING(obj_enm_turret_point_defense) \
    THING(obj_enm_turret_mortar) \
    THING(obj_enm_crystalturret_mortar) \
    THING(obj_enm_crystalturret_laser) \
    THING(obj_turret_dummie) \
    THING(obj_firingrange_dummy_parent) \
    THING(obj_firingrange_dummy_standard) \
    THING(obj_firingrange_dummy_armored) \
    THING(obj_firingrange_dummy_cover) \
    THING(obj_firingrange_dummy_shield) \
    THING(obj_firingrange_dummy_plating) \
    THING(obj_enm_sentryturret) \
    THING(obj_enm_minisentry) \
    THING(obj_enm_sentrysniper) \
    THING(obj_enm_turret_striker) \
    THING(obj_mars_turret_sniper) \
    THING(obj_enm_turret_prisma_mars) \
    THING(obj_enm_turret_lightning_mars) \
    THING(obj_enm_turret_prisma) \
    THING(obj_enm_turret_lightningbolt) \
    THING(obj_enm_custom_parent) \
    THING(obj_boss_parent) \
    THING(obj_enm_bossweapon_parent) \
    THING(obj_enm_BW_jet_mg) \
    THING(obj_enm_BW_heli_turret) \
    THING(obj_deathlocation_boss) \
    THING(obj_boss_treadmill) \
    THING(obj_conveyorbelt) \
    THING(obj_conveyorbeltMirror) \
    THING(obj_blockpath) \
    THING(obj_damagezone) \
    THING(obj_boss_intro) \
    THING(obj_boss2_Jet) \
    THING(obj_boss_heart) \
    THING(obj_heart_kill) \
    THING(obj_heart_room_events) \
    THING(obj_quest_hearthack) \
    THING(obj_boss_APC) \
    THING(obj_boss_heartwall1) \
    THING(obj_boss_fortress) \
    THING(obj_boss_armageddon) \
    THING(obj_boss_triple_spawn) \
    THING(obj_boss_triple) \
    THING(obj_boss_sam) \
    THING(obj_boss_helicopter) \
    THING(obj_boss_blob_core) \
    THING(obj_boss_blob_add) \
    THING(obj_boss_blob_spawner) \
    THING(obj_boss_spider) \
    THING(obj_enm_RG_plasma_boss) \
    THING(obj_enm_RG_riotshield_boss) \
    THING(obj_enm_RG_sniper_boss) \
    THING(obj_boss1_cube) \
    THING(obj_boss1_cubecore) \
    THING(obj_helicopterBoss_parent) \
    THING(obj_helicopterBoss_dynTest) \
    THING(obj_helicopterBoss_rocket1) \
    THING(obj_helicopterBoss_rocket2) \
    THING(obj_helicopterBoss_cylinder) \
    THING(obj_helicopterBoss_tankShell) \
    THING(obj_helicopterBoss_tankShellStack) \
    THING(obj_helicopterBoss_rocketStack) \
    THING(obj_specialcodewarning) \
    THING(obj_cratesmall_spawner) \
    THING(obj_barrel_spawner) \
    THING(obj_cylinderspawn) \
    THING(obj_wall_barrier_hor) \
    THING(obj_wall_barrier_vert) \
    THING(obj_wall_top) \
    THING(obj_wall_test) \
    THING(obj_chunkedge_grid_right) \
    THING(obj_chunkedge_grid_top) \
    THING(obj_chunkedge_pillar_right) \
    THING(obj_container_horizontal) \
    THING(obj_container_vertical) \
    THING(obj_ventilationground_large) \
    THING(obj_rectpipe_stack) \
    THING(obj_cablestack) \
    THING(obj_rectpipe_stack2) \
    THING(obj_rectpipe_stack2_hor) \
    THING(obj_rectcable_stack_hor) \
    THING(obj_stack_spawner_ver) \
    THING(obj_stack_spawner_hor) \
    THING(obj_containeroil_vert_spawner) \
    THING(obj_containeroil_hor_spawner) \
    THING(obj_stack_crates) \
    THING(obj_stack_crate_small) \
    THING(obj_tcarrier_rect) \
    THING(obj_plywoodstack) \
    THING(obj_tcarrier_hor) \
    THING(obj_tcarrierstack_big) \
    THING(obj_tcarrier_big) \
    THING(obj_trashcontainer_vertical) \
    THING(obj_trashcontainer_horizontal) \
    THING(obj_tcarrierstack_big_vert) \
    THING(obj_tcarrierstack_big_hor) \
    THING(obj_woodcrate_big_horizontal) \
    THING(obj_woodcrate_normal) \
    THING(obj_woodcrate_big_vertical) \
    THING(obj_woodcrate_decal) \
    THING(obj_concrete_decal) \
    THING(obj_metal_decal) \
    THING(obj_metalcrate_normal) \
    THING(obj_barrel) \
    THING(obj_barrel_oil) \
    THING(obj_barrel_poison) \
    THING(obj_barrel_explosive) \
    THING(obj_barrel_electric) \
    THING(obj_barrel_explosive_gaz) \
    THING(obj_barrel_tankshell) \
    THING(obj_noncombat_propsHover) \
    THING(obj_noncombat_drone_randomMove) \
    THING(obj_noncombat_target) \
    THING(obj_nonbombat_vacuum_randomMove) \
    THING(obj_noncombat_ground_Parent) \
    THING(obj_drone_parent) \
    THING(obj_drone_mainmenu) \
    THING(obj_drone_antibullet) \
    THING(obj_drone_player) \
    THING(obj_drone_healing_turret) \
    THING(obj_drone_health_leech) \
    THING(obj_drone_laserline) \
    THING(obj_drones_shadow) \
    THING(obj_circlemotion) \
    THING(obj_drone_engineer) \
    THING(obj_drone_sniper) \
    THING(obj_drone_player_support) \
    THING(obj_enm_room_spawn) \
    THING(obj_enm_target_point) \
    THING(obj_enm_dissolve) \
    THING(obj_enm_worldspaceui) \
    THING(obj_enm_parent_all) \
    THING(obj_enm_base_parent) \
    THING(obj_enm_humanoid) \
    THING(____HUMANOIDS____) \
    THING(obj_enm_enforcer) \
    THING(obj_enm_redguard_sniper) \
    THING(obj_enm_redguard_sniper_arena) \
    THING(obj_enm_redguard_riotshield) \
    THING(obj_enm_redguard_riotshield_arena) \
    THING(obj_enm_headhunter_arena_parent) \
    THING(obj_enm_mechromancer) \
    THING(obj_enm_engineer) \
    THING(obj_enm_redguard_plasma) \
    THING(obj_enm_redguard_plasma_arena) \
    THING(obj_enm_headhunter) \
    THING(obj_enm_headhunter_arena) \
    THING(obj_enm_headhunter_quest) \
    THING(obj_enm_workerbot) \
    THING(obj_enm_workerbot_quest) \
    THING(obj_enm_redguard_rocketeer) \
    THING(obj_enm_redguard_rocketeer_arena) \
    THING(obj_enm_mg) \
    THING(obj_enm_hypertrooper) \
    THING(obj_enm_railgunner) \
    THING(obj_enm_flamer) \
    THING(obj_enm_riotshield) \
    THING(obj_enm_medic) \
    THING(obj_enm_chrono) \
    THING(obj_enm_elite_sg) \
    THING(obj_enm_elite_sg_red) \
    THING(obj_enm_elite_sg_crystal) \
    THING(obj_enm_assassin) \
    THING(obj_enm_phaser) \
    THING(obj_enm_phaser_quest) \
    THING(obj_enm_sniper) \
    THING(obj_enm_sniper_black) \
    THING(obj_enm_sniper_crystal) \
    THING(obj_enm_sniper_itemoff) \
    THING(____SPIDERBOTS____) \
    THING(obj_enm_spider_explo) \
    THING(obj_enm_spider_nano) \
    THING(obj_enm_doomba) \
    THING(obj_enm_slowmissile) \
    THING(obj_enm_spider_disco) \
    THING(obj_enm_spider_rocket) \
    THING(obj_enm_spider_antibullet) \
    THING(obj_enm_alarm_o_bot) \
    THING(obj_enm_treasureroomba) \
    THING(____HOVERBOTS___) \
    THING(obj_enm_hover_parent) \
    THING(obj_enm_balldefender) \
    THING(obj_enm_ballmedic) \
    THING(obj_enm_balldefender_red) \
    THING(obj_enm_balldefender_red_small) \
    THING(obj_enm_balldefender_red_small2) \
    THING(obj_enm_drone_mg) \
    THING(obj_enm_drone_particleball) \
    THING(obj_enm_drone_mortar) \
    THING(obj_enm_drone_heavymortar) \
    THING(obj_enm_drone_shield) \
    THING(obj_enm_drone_shield_arena) \
    THING(obj_enm_drone_missile) \
    THING(obj_enm_dronemissile_x57) \
    THING(obj_enm_dronemissile_item) \
    THING(obj_enm_gliderrailgun) \
    THING(obj_enm_glidershotgun) \
    THING(obj_enm_gliderjet) \
    THING(obj_enm_glidergatling) \
    THING(obj_enm_gliderstriker) \
    THING(obj_enm_hovertank) \
    THING(____OTHERBOTS____) \
    THING(obj_enm_spidertruck) \
    THING(obj_enm_radartruck) \
    THING(obj_enm_antibulletbot) \
    THING(obj_enm_flamethrower) \
    THING(obj_enm_threadedshotgun) \
    THING(obj_enm_minitank) \
    THING(obj_enm_overseer) \
    THING(obj_enm_carrierbot) \
    THING(obj_enm_MELEE) \
    THING(obj_enm_ballretract) \
    THING(obj_enm_ballbot) \
    THING(obj_enm_sawbladebot) \
    THING(obj_enm_tank_parent) \
    THING(obj_enm_mainbattletank) \
    THING(obj_boss_mainbattletank) \
    THING(obj_enm_flaktank) \
    THING(____W_I_P_BOTS____) \
    THING(obj_enm_camera_right) \
    THING(obj_enm_crystal) \
    THING(obj_enm_sawblade) \
    THING(obj_enm_vacuumbot) \
    THING(obj_enm_ghost) \
    THING(obj_enm_crystalmarker) \
    THING(obj_enm_crystal_trail) \
    THING(obj_vehiclespawn) \
    THING(obj_boss1_head) \
    THING(obj_boss1_base) \
    THING(obj_boss1_serverblock) \
    THING(obj_boss_1Server) \
    THING(obj_enm_destroyed) \
    THING(obj_enm_hitcollision) \
    THING(obj_dynamic_collision) \
    THING(obj_headshot_collision_parent) \
    THING(obj_moving_entity_PARENT) \
    THING(obj_enm_wavespawner) \
    THING(obj_weapon_toggler) \
    THING(obj_weapon_PARENT) \
    THING(obj_weapon_SRP_1) \
    THING(obj_weapon_CL_2) \
    THING(obj_weapon_OICW_3) \
    THING(obj_weapon_DB_4) \
    THING(obj_weapon_MG5_5) \
    THING(obj_weapon_PTL_6) \
    THING(obj_weapon_BFR_7) \
    THING(obj_weapon_CLG_8) \
    THING(obj_weapon_REV_9) \
    THING(obj_weapon_PXS_10) \
    THING(obj_weapon_REP_11) \
    THING(obj_weapon_DMR_12) \
    THING(obj_weapon_SPC_13) \
    THING(obj_weapon_FMG_14) \
    THING(obj_weapon_R5K_15) \
    THING(obj_weapon_4G_16) \
    THING(obj_weapon_LSG_17) \
    THING(obj_weapon_LSMG_18) \
    THING(obj_weapon_12G_19) \
    THING(obj_weapon_GM6_20) \
    THING(obj_weapon_LSP_21) \
    THING(obj_weapon_LDMR_22) \
    THING(obj_weapon_M32_23) \
    THING(obj_weapon_AMD_24) \
    THING(obj_weapon_ION_25) \
    THING(obj_weapon_MG42_26) \
    THING(obj_weapon_CAR_27) \
    THING(obj_weapon_DMN_28) \
    THING(obj_weapon_CRGE_29) \
    THING(obj_weapon_VEC_30) \
    THING(obj_weapon_S12_31) \
    THING(obj_weapon_ML_32) \
    THING(obj_weapon_TMP_33) \
    THING(obj_weapon_HON_34) \
    THING(obj_weapon_FT_35) \
    THING(obj_weapon_FC_36) \
    THING(obj_weapon_CG_37) \
    THING(obj_weapon_CP_38) \
    THING(obj_weapon_DS_39) \
    THING(obj_weapon_LAR_40) \
    THING(obj_weapon_AEK_41) \
    THING(obj_weapon_VAL_42) \
    THING(obj_weapon_AA_43) \
    THING(obj_weapon_RPK_44) \
    THING(obj_weapon_SB_45) \
    THING(obj_weapon_RG_46) \
    THING(obj_weapon_HMG_47) \
    THING(obj_weapon_NG_48) \
    THING(obj_weapon_PC_49) \
    THING(obj_weapon_BRN_50) \
    THING(obj_weapon_EXP_51) \
    THING(obj_weapon_FB_52) \
    THING(obj_weapon_BOW_53) \
    THING(obj_weapon_INT_54) \
    THING(obj_weapon_A9_55) \
    THING(obj_weapon_AB_56) \
    THING(obj_weapon_RPG_57) \
    THING(obj_weapon_ACR_58) \
    THING(obj_weapon_K98_59) \
    THING(obj_weapon_KSG_60) \
    THING(obj_weapon_DE_61) \
    THING(obj_weapon_MC_62) \
    THING(obj_weapon_G17_63) \
    THING(obj_weapon_HLP_64) \
    THING(obj_weapon_UMP_65) \
    THING(obj_weapon_ANH_66) \
    THING(obj_weapon_SUP_67) \
    THING(obj_weapon_YL_68) \
    THING(obj_weapon_STY_69) \
    THING(obj_weapon_LEV_70) \
    THING(obj_weapon_IMP_71) \
    THING(obj_weapon_GAT_72) \
    THING(obj_weapon_LC_73) \
    THING(obj_weapon_AKS_74) \
    THING(obj_weapon_K95_75) \
    THING(obj_weapon_UMP_76) \
    THING(obj_weapon_LEV_77) \
    THING(obj_weapon_GL_78) \
    THING(obj_weapon_RS_79) \
    THING(obj_weapon_AR15_80) \
    THING(obj_weapon_ROD_80) \
    THING(obj_weapon_A5C_81) \
    THING(obj_weapon_AN94_82) \
    THING(obj_weapon_P90_83) \
    THING(obj_weapon_TEC_84) \
    THING(obj_weapon_LG_85) \
    THING(obj_weapon_M16_86) \
    THING(obj_weapon_M14_87) \
    THING(obj_weapon_STG_88) \
    THING(obj_weapon_SC_89) \
    THING(obj_weapon_M163_90) \
    THING(obj_weapon_M14T_91) \
    THING(obj_weapon_FMG_92) \
    THING(obj_weapon_m75_93) \
    THING(obj_weapon_DE_94) \
    THING(obj_weapon_PSG_95) \
    THING(obj_weapon_QBZ_96) \
    THING(obj_weapon_T89_97) \
    THING(obj_weapon_12G_97) \
    THING(obj_weapon_K7_98) \
    THING(obj_wep_burstspecial) \
    THING(obj_weapon_spawner) \
    THING(obj_weapon_uber_parent) \
    THING(obj_weapon_item_parent) \
    THING(obj_weapon_buff_parent) \
    THING(obj_weapon_enm_taser) \
    THING(obj_weapon_enm_masterkey) \
    THING(obj_weapon_enm_grenade) \
    THING(obj_weapon_enm_plasmagrenade) \
    THING(obj_weapon_enm_plasmagrenade_arena) \
    THING(obj_weapon_enm_plasmagrenade_boss) \
    THING(obj_weapon_enm_stungrenade) \
    THING(obj_weapon_enm_stungrenade2) \
    THING(obj_weapon_enm_stungrenade3) \
    THING(obj_weapon_enm_psyGrenade) \
    THING(obj_weapon_enm_stungrenade_boss) \
    THING(obj_weapon_itemMissile) \
    THING(obj_weapon_minelayer) \
    THING(obj_weapon_lasermineitem) \
    THING(obj_weapon_acidmineitem) \
    THING(obj_weapon_stunmineitem) \
    THING(obj_weapon_breachingcharge) \
    THING(obj_weapon_itemLaser) \
    THING(obj_weapon_itemLasercaster) \
    THING(obj_weapon_droneplayer_laser) \
    THING(obj_weapon_droneplayer_sniper) \
    THING(obj_weapon_droneplayer_sniper_challenge) \
    THING(obj_weapon_droneplayer_laserfire) \
    THING(obj_weapon_droneplayer_plasma) \
    THING(obj_weapon_itemRailgun) \
    THING(obj_weapon_itemShieldburst) \
    THING(obj_weapon_itemHomingMissile) \
    THING(obj_weapon_itemlightningorb) \
    THING(obj_weapon_itemironorb) \
    THING(obj_weapon_itemSeekers) \
    THING(obj_weapon_itemBloodbolt) \
    THING(obj_weapon_itemGrenadelauncher) \
    THING(obj_weapon_itemStickybomb) \
    THING(obj_weapon_itemPowerbolt) \
    THING(obj_weapon_itemMagnum) \
    THING(obj_weapon_itemMasterkey) \
    THING(obj_weapon_itemHeatsink) \
    THING(obj_weapon_itemMasterkey2) \
    THING(obj_weapon_itemTaser) \
    THING(obj_weapon_itemFlare) \
    THING(obj_weapon_itemFireorb) \
    THING(obj_weapon_item_kunai) \
    THING(obj_weapon_item_shuriken1) \
    THING(obj_weapon_item_shuriken2) \
    THING(obj_weapon_item_tomahawk) \
    THING(obj_weapon_item_fanknives) \
    THING(obj_weapon_item_flyingknife) \
    THING(obj_weapon_buff_crystal_crush) \
    THING(obj_weapon_helicopter_seeking) \
    THING(obj_weapon_jet_rocketbarrage) \
    THING(obj_weapon_helicopter_missile) \
    THING(obj_weapon_APC_seeker) \
    THING(obj_weapon_APC_minelayer) \
    THING(obj_weapon_Heart_minelayer) \
    THING(obj_weapon_Heart_missile) \
    THING(obj_weapon_Heart_main) \
    THING(obj_weapon_bosscube_rocket) \
    THING(obj_weapon_bosscube_rocket_homing) \
    THING(obj_weapon_bosscube_laser) \
    THING(obj_weapon_bullethell) \
    THING(obj_weapon_boss_hmg) \
    THING(obj_weapon_APC_mg) \
    THING(obj_weapon_boss_vierling) \
    THING(obj_weapon_OICWGrenade) \
    THING(obj_weapon_M16Grenade) \
    THING(obj_weapon_T89Grenade) \
    THING(obj_weapon_Damnation) \
    THING(obj_weapon_sawblade) \
    THING(WeaponSystem) \
    THING(obj_bullet_sniperturret) \
    THING(obj_bullet_enemysniper) \
    THING(obj_bullet_enemy_stun) \
    THING(obj_bullet_enemy_poison) \
    THING(obj_bullet_enemypistol) \
    THING(obj_bullet_enemyrifle) \
    THING(obj_bullet_laser_worker) \
    THING(obj_bullet_turret_grenade) \
    THING(obj_bullet_turret_mortar) \
    THING(obj_bullet_drone_mortar) \
    THING(obj_bullet_drone_mortar_ballistic) \
    THING(obj_bullet_turret_crystalmortar) \
    THING(obj_bullet_buff_crystalmortar) \
    THING(obj_bullet_rocket_parent) \
    THING(obj_bullet_rocket_boss2_A) \
    THING(obj_bullet_rocket_boss2_B) \
    THING(obj_bullet_rocket_heart) \
    THING(obj_bullet_rocket_turret) \
    THING(obj_bullet_rocket_turret_2) \
    THING(obj_bullet_rocket_turret_3) \
    THING(obj_bullet_rocket_turret_crazy) \
    THING(obj_bullet_rocket_upvote) \
    THING(obj_bullet_rocket_particle) \
    THING(obj_bullet_rocket_particle2) \
    THING(obj_bullet_rocket_psyBall) \
    THING(obj_bullet_rocket_rapidfire) \
    THING(obj_bullet_rocket_rapidfire_xm29) \
    THING(obj_bullet_rocket_homing) \
    THING(obj_bullet_rocket_homingslow) \
    THING(obj_bullet_bloodbolt) \
    THING(obj_bullet_bloodbolt_chaos) \
    THING(obj_bullet_bloodbolt_damn) \
    THING(obj_bullet_bloodbolt_boss) \
    THING(obj_bullet_flyingknife) \
    THING(obj_bullet_sawblade_huge) \
    THING(obj_bullet_seeker_item) \
    THING(obj_bullet_needler) \
    THING(obj_bullet_rocket_followmouse) \
    THING(obj_bullet_jetmg) \
    THING(obj_bullet_turretvierling) \
    THING(obj_bullet_bullethell) \
    THING(obj_bullet_beam_parent) \
    THING(obj_bullet_beam_1) \
    THING(obj_all_bullets) \
    THING(obj_bullet_lists) \
    THING(obj_player_bullets) \
    THING(bulletSystem) \
    THING(SHEAVY_______________) \
    THING(obj_bullet_144_sc) \
    THING(obj_bullet_144_krkn) \
    THING(obj_bullet_144_sabot) \
    THING(obj_bullet_127_sc) \
    THING(obj_bullet_127_toxic) \
    THING(obj_bullet_127_sabot) \
    THING(obj_bullet_127_explo) \
    THING(obj_bullet_arrow_sc) \
    THING(obj_bullet_arrow_stun) \
    THING(obj_bullet_arrow_sleep) \
    THING(obj_bullet_arrow_toxic) \
    THING(HEAVY_______________) \
    THING(obj_bullet_88_sc) \
    THING(obj_bullet_88_ap) \
    THING(obj_bullet_88_explo) \
    THING(obj_bullet_88_hs) \
    THING(obj_bullet_88_cata) \
    THING(obj_bullet_88_toxic) \
    THING(MED_________________) \
    THING(obj_bullet_556_sc) \
    THING(obj_bullet_556_toxic) \
    THING(obj_bullet_556_hp) \
    THING(obj_bullet_556_sabot) \
    THING(obj_bullet_556_sp) \
    THING(obj_bullet_473_sc) \
    THING(obj_bullet_473_alt) \
    THING(SMALL_______________) \
    THING(obj_bullet_9mm_sc) \
    THING(obj_bullet_9mm_ap) \
    THING(obj_bullet_9mm_hs) \
    THING(obj_bullet_9mm_hp) \
    THING(obj_bullet_9mm_sp) \
    THING(obj_bullet_9mm_sp_magnum) \
    THING(object1451) \
    THING(obj_bullet_vierling) \
    THING(PELLETS_____________) \
    THING(obj_bullet_10g_buck) \
    THING(obj_bullet_10g_bird) \
    THING(obj_bullet_10g_flech) \
    THING(obj_bullet_10g_slug) \
    THING(obj_bullet_10g_fire) \
    THING(obj_bullet_10g_masterkey) \
    THING(obj_bullet_10g_masterkey2) \
    THING(obj_bullet_10g_bolt) \
    THING(obj_bullet_10g_helsing) \
    THING(obj_bullet_nail_sc) \
    THING(obj_bullet_nail_bleed) \
    THING(obj_bullet_coil_x4) \
    THING(obj_bullet_coil_x1) \
    THING(GRENADES__________) \
    THING(obj_bullet_fireball) \
    THING(obj_bullet_flamethrower) \
    THING(obj_bullet_flak1) \
    THING(obj_bullet_scatter) \
    THING(obj_bullet_grenade_impact) \
    THING(obj_bullet_grenade_bounce) \
    THING(obj_bullet_grenade_rubber) \
    THING(obj_bullet_grenade_stickyitem) \
    THING(obj_bullet_particle_explo) \
    THING(obj_bullet_annihilator) \
    THING(obj_bullet_grenade_enm) \
    THING(obj_bullet_mineemp) \
    THING(obj_bullet_minelaser) \
    THING(obj_bullet_minelaseritem) \
    THING(obj_bullet_mineaciditem) \
    THING(obj_bullet_minestunitem) \
    THING(obj_bullet_breachingcharge) \
    THING(obj_bullet_grenade_enm_aircom) \
    THING(obj_bullet_grenade_enm_stun) \
    THING(obj_bullet_sawblade) \
    THING(obj_bullet_sawblade_ultra) \
    THING(obj_bullet_sawblade_item) \
    THING(obj_bullet_kunai) \
    THING(obj_bullet_tomahawk) \
    THING(obj_bullet_fanknives) \
    THING(obj_bullet_fanknives_pickup) \
    THING(obj_bullet_shuriken) \
    THING(obj_bullet_shuriken2) \
    THING(obj_bullet_rocket_flare) \
    THING(obj_bullet_ironorb) \
    THING(obj_bullet_ironorb_enemy) \
    THING(obj_bullet_taser) \
    THING(obj_bullet_taser_enm) \
    THING(LASER_____________) \
    THING(obj_bullet_laser_parent) \
    THING(obj_bullet_laser_line) \
    THING(obj_bullet_laser_line_drone) \
    THING(obj_bullet_laser_line_item) \
    THING(obj_bullet_laser_line_drone_challenge) \
    THING(obj_bullet_laser_line_gold) \
    THING(obj_bullet_laser_line_cannon) \
    THING(obj_bullet_laser_line_gold_pen) \
    THING(obj_bullet_laser_shieldnuke) \
    THING(obj_bullet_laser_line_reducedDMG) \
    THING(obj_bullet_laser_line_fire) \
    THING(obj_bullet_laser_line_pellet) \
    THING(obj_bullet_laser_line_pellet_fire) \
    THING(obj_bullet_laser_spray) \
    THING(obj_bullet_laser_beam) \
    THING(obj_bullet_laser_crystal) \
    THING(obj_bullet_laser_slow) \
    THING(obj_bullet_laser_ion) \
    THING(obj_bullet_laser_fusion) \
    THING(obj_bullet_laser_fusion_slow) \
    THING(obj_bullet_laser_railgun) \
    THING(obj_bullet_laser_railgun2) \
    THING(obj_bullet_laser_plasma) \
    THING(obj_shell_parentOLD) \
    THING(obj_shell_big_4) \
    THING(obj_shell_big_3) \
    THING(obj_shell_grenade) \
    THING(obj_shell_shotgun) \
    THING(obj_shell_cl) \
    THING(obj_shell_2) \
    THING(obj_shell_1) \
    THING(obj_bullet_chain) \
    THING(obj_bullet_chain_orb) \
    THING(obj_bullet_chain_turret) \
    THING(obj_bullet_chain_inverse) \
    THING(obj_bullet_chain_beam) \
    THING(obj_bullet_laser_railgun_item) \
    THING(obj_bullet_laser_beam_item) \
    THING(obj_chest_spwn) \
    THING(obj_chest_parent) \
    THING(obj_chest_weapon_wood) \
    THING(obj_chest_weapon_wood_arena) \
    THING(obj_chest_weapon_metal) \
    THING(obj_chest_weapon_boss) \
    THING(obj_chest_weapon_metal_cost) \
    THING(obj_chest_weapon_challenge) \
    THING(obj_chest_weapon_cursed) \
    THING(obj_chest_weapon_timed) \
    THING(obj_chest_ammo) \
    THING(obj_chest_health) \
    THING(obj_chest_item_wood) \
    THING(obj_chest_item_metal) \
    THING(obj_chest_item_metal_cost) \
    THING(obj_chest_item_cursed) \
    THING(obj_chest_item_boss) \
    THING(obj_chest_item_timed) \
    THING(obj_chest_upgrade) \
    THING(obj_chest_radio) \
    THING(obj_chest_wepupgrade) \
    THING(obj_chest_artefact) \
    THING(obj_chest_classperk) \
    THING(obj_chest_unlockammo) \
    THING(obj_chest_mystery) \
    THING(obj_chest_mysteryboost) \
    THING(obj_chest_mysteryarena) \
    THING(obj_chest_currency) \
    THING(obj_chest_goldensmall) \
    THING(obj_shrine) \
    THING(obj_shrine_tooltip) \
    THING(obj_shrine_spawn) \
    THING(obj_shrine_spawn_normal) \
    THING(obj_shrine_spawn_atm) \
    THING(obj_shrine_spawn_item) \
    THING(obj_shrine_spawn_curse) \
    THING(obj_shrine_spawn_itemupgr) \
    THING(obj_shrine_spawn_weaponbuy) \
    THING(obj_shrine_spawn_arenaweapon) \
    THING(obj_shrine_spawn_weaponupgrade) \
    THING(obj_shrine_spawn_synergy) \
    THING(obj_shrine_spawn_classitem) \
    THING(obj_shrine_spawn_classweapon) \
    THING(obj_shrine_spawn_supplyweapon) \
    THING(obj_shrine_spawn_supplyitem) \
    THING(obj_shrine_spawn_perkshop) \
    THING(obj_shrine_spawn_variantshop) \
    THING(obj_shrine_spawn_unitshop) \
    THING(obj_upgrade_station) \
    THING(obj_shrine_spawn_god) \
    THING(obj_shrine_spawn_teleport) \
    THING(obj_station_trigger) \
    THING(obj_firingrange_trigger) \
    THING(obj_tutorial2_trigger) \
    THING(obj_firingrange_tutorial) \
    THING(obj_station_spawner) \
    THING(obj_c4station) \
    THING(obj_buffstation) \
    THING(obj_enm_building_parent) \
    THING(obj_enm_building_constructor) \
    THING(obj_enm_building_landingpod) \
    THING(obj_enm_building_extractor) \
    THING(obj_enm_building_solarpanel) \
    THING(obj_enm_building_battery) \
    THING(obj_enm_building_silo) \
    THING(obj_enm_building_weaponprinter) \
    THING(obj_enm_building_plasmagen) \
    THING(obj_enm_building_plasmablock) \
    THING(obj_enm_building_researchlab) \
    THING(obj_enm_building_research_ammo) \
    THING(obj_enm_building_research_android) \
    THING(obj_enm_building_plasmaconverter) \
    THING(obj_enm_building_mechbay) \
    THING(obj_enm_building_infantrybay) \
    THING(obj_enm_building_storagebig) \
    THING(obj_enm_building_ammoblock) \
    THING(obj_enm_building_research_health) \
    THING(obj_enm_building_research_armor) \
    THING(obj_enm_building_research_damage) \
    THING(obj_enm_building_research_other) \
    THING(obj_enm_building_research_turbine) \
    THING(obj_enm_building_rangeextender) \
    THING(obj_enm_building_radar) \
    THING(obj_enm_turret_marsrepair) \
    THING(obj_enm_resource_crystal) \
    THING(obj_mars_ironore) \
    THING(obj_mars_wreck_small) \
    THING(obj_mars_wreck_large) \
    THING(obj_mars_airdrop) \
    THING(obj_station_cost) \
    THING(obj_station_cost_weaponarena) \
    THING(obj_station_cost_weaponupgrade) \
    THING(obj_station_cost_perkshop) \
    THING(obj_station_cost_itemupgrade) \
    THING(obj_station_cost_itemshop) \
    THING(obj_station_cost_variantshop) \
    THING(obj_station_cost_atm) \
    THING(obj_station_cost_curse) \
    THING(obj_station_cost_turret) \
    THING(obj_station_cost_missileturret) \
    THING(obj_station_cost_laserturret) \
    THING(obj_turret_cost_lightningbolt) \
    THING(obj_turret_cost_prisma) \
    THING(obj_turret_cost_sniper) \
    THING(obj_generator) \
    THING(obj_defuseammostation) \
    THING(obj_questvalve) \
    THING(obj_questhack) \
    THING(obj_hearthack_station) \
    THING(obj_pointdefense_station) \
    THING(obj_pointdefense_station_armageddon) \
    THING(obj_heart_station) \
    THING(obj_dronechallengeroom) \
    THING(obj_enemy_spawner_simple) \
    THING(obj_pointdefense_spawnpos) \
    THING(obj_soulcatcher) \
    THING(obj_alarmpole) \
    THING(obj_alarmpole_arena) \
    THING(obj_lightpole) \
    THING(obj_auratower) \
    THING(obj_constructor) \
    THING(obj_mine_c4) \
    THING(obj_mine_dynamite) \
    THING(obj_trap_mine_parent) \
    THING(obj_trap_mine_stealthparent) \
    THING(obj_trap_mine_stun) \
    THING(obj_trap_mine_stun_player) \
    THING(obj_trap_mine_antishield) \
    THING(obj_trap_mine_toxic) \
    THING(obj_trap_mine_toxic_player) \
    THING(obj_trap_mine_laserspike_player) \
    THING(obj_trap_mine_laserspike) \
    THING(obj_trap_parent) \
    THING(obj_trap_minelayer) \
    THING(obj_trap_minimine) \
    THING(obj_trap_chainmine) \
    THING(obj_trap_firespewer) \
    THING(obj_trap_spike) \
    THING(obj_trap_electrofield) \
    THING(obj_trap_slow) \
    THING(obj_trap_slowfield) \
    THING(obj_trap_barbedwire) \
    THING(obj_trap_barbedwire_vert) \
    THING(obj_movingspikes_hor) \
    THING(obj_movingspikes_ver) \
    THING(obj_movingwall_metal_vert) \
    THING(obj_movingwall_parent) \
    THING(obj_minecart_vertical_spwn) \
    THING(obj_minecart_vertical) \
    THING(obj_treadmill) \
    THING(obj_treadmill_picker_holder) \
    THING(obj_treadmill_band) \
    THING(obj_treadmill_picker) \
    THING(obj_disco_tile) \
    THING(obj_all_solid) \
    THING(obj_props_solid_parent) \
    THING(obj_props_notsolid_parent) \
    THING(obj_hazards) \
    THING(obj_props_destructible) \
    THING(obj_pickup_parent) \
    THING(obj_prop_destroyed) \
    THING(obj_quest_headhunter_spawn) \
    THING(obj_spawnnextroom) \
    THING(obj_questcontrol_parent) \
    THING(obj_questcontrol_defuseammo) \
    THING(obj_questcontrol_valve) \
    THING(obj_questcontrol_hack) \
    THING(obj_questcontrol_headhunters) \
    THING(obj_questcontrol_soulcatcher) \
    THING(obj_questcontrol_defense) \
    THING(obj_questcontrol_buffstation) \
    THING(obj_questcontrol_c4station) \
    THING(obj_questcontrol_emp) \
    THING(obj_questcontrol_nightvision) \
    THING(obj_questcontrol_alert) \
    THING(obj_questcontrol_patrol) \
    THING(obj_questcontrol_instagib) \
    THING(obj_questcontrol_massacre) \
    THING(obj_questcontrol_generator) \
    THING(obj_questcontrol_dummies) \
    THING(obj_questcontrol_arena_defense) \
    THING(obj_quest_arrow) \
    THING(obj_quest_destroy_generator) \
    THING(obj_quest_destroy_emp) \
    THING(obj_quest_hold_shrine) \
    THING(obj_bumper_direction) \
    THING(obj_sawbig_parent) \
    THING(obj_sawbig_horizontal) \
    THING(obj_sawbig_vertical) \
    THING(obj_sawpillar_vertical) \
    THING(obj_sawpillar_horizontal) \
    THING(obj_PropsBlock) \
    THING(obj_tutorial2_accuracyTrigger) \
    THING(obj_tutorial2_chestTrigger) \
    THING(obj_pickup_outgame) \
    THING(obj_pickup_ring) \
    THING(obj_pickup_chip) \
    THING(obj_pickup_item) \
    THING(obj_pickup_item_shared) \
    THING(obj_pickup_quest) \
    THING(obj_pickup_arenatoken) \
    THING(obj_pickup_upgrade) \
    THING(obj_pickup_vial) \
    THING(obj_pickup_medikit) \
    THING(obj_pickup_ammopack) \
    THING(obj_pickup_keycard) \
    THING(obj_pickup_artefact) \
    THING(obj_pickup_bolt) \
    THING(obj_pickup_scrap) \
    THING(obj_pickup_transistor) \
    THING(obj_pickup_dogtag) \
    THING(obj_pickup_upgradetool) \
    THING(obj_pickup_weppart) \
    THING(obj_pickup_heartcore) \
    THING(obj_pickup_armageddon) \
    THING(obj_pickup_perkkit) \
    THING(obj_pickup_credits) \
    THING(obj_pickup_data) \
    THING(obj_pickup_battery) \
    THING(obj_pickup_spirit) \
    THING(obj_pickup_shield) \
    THING(obj_pickup_invulner) \
    THING(obj_pickup_explosion) \
    THING(obj_pickup_mines) \
    THING(obj_pickup_thunder) \
    THING(obj_pickup_ironorb) \
    THING(obj_pickup_fanOfKnives) \
    THING(obj_pickup_turrets) \
    THING(obj_pickup_slowmo) \
    THING(obj_pickup_drones) \
    THING(obj_pickup_ammoreg) \
    THING(obj_pickup_speed) \
    THING(obj_pickup_crystal) \
    THING(obj_pickup_crystal_mars) \
    THING(obj_pickup_crystal_preview) \
    THING(obj_pickup_doubleexp) \
    THING(obj_pickup_damage) \
    THING(obj_all_items) \
    THING(obj_item_drop) \
    THING(itemSystem) \
    THING(perkSystem) \
    THING(obj_item_parent) \
    THING(obj_item1_chaospotion) \
    THING(obj_item2_hyperfeed) \
    THING(obj_item3_splash) \
    THING(obj_item4_cloak) \
    THING(obj_item5_crystal) \
    THING(obj_item6_reloader) \
    THING(obj_item7_vial) \
    THING(obj_item8_injection) \
    THING(obj_item9_fang) \
    THING(obj_item10_overdrive) \
    THING(obj_item11_revive) \
    THING(obj_item12_reflector) \
    THING(obj_item13_devilsdice) \
    THING(obj_item14_goggles) \
    THING(obj_item15_shield) \
    THING(obj_item16_upgradekit) \
    THING(obj_item17_ironorb) \
    THING(obj_item18_potion) \
    THING(obj_item19_lightningorb) \
    THING(obj_item20_fireorb) \
    THING(obj_item21_orbwind) \
    THING(obj_item148_fusionorb) \
    THING(obj_item22_bloodrite) \
    THING(obj_item23_extrashot) \
    THING(obj_item24_heart) \
    THING(obj_item25_refresher) \
    THING(obj_item26_statskit) \
    THING(obj_item27_berserk) \
    THING(obj_item28_dronelaser) \
    THING(obj_item29_slowmo) \
    THING(obj_item30_methadone) \
    THING(obj_item31_vampirism) \
    THING(obj_item32_tsunami) \
    THING(obj_item33_shieldburst) \
    THING(obj_item34_grenade_he) \
    THING(obj_item35_grenade_flash) \
    THING(obj_item36_grenade_stun) \
    THING(obj_item37_grenade_plasma) \
    THING(obj_item38_grenade_toxic) \
    THING(obj_item39_slowfield) \
    THING(obj_item40_steeltrap) \
    THING(obj_item41_powershot) \
    THING(obj_item42_plating) \
    THING(obj_item43_switcher) \
    THING(obj_item44_exploheadshot) \
    THING(obj_item45_uranium) \
    THING(obj_item46_missile) \
    THING(obj_item47_missilehoming) \
    THING(obj_item48_laser) \
    THING(obj_item49_mindcontrol) \
    THING(obj_item50_laststand) \
    THING(obj_item51_stinger) \
    THING(offrail) \
    THING(obj_item52_bombardment) \
    THING(obj_item53_chargeshot) \
    THING(obj_item54_c4) \
    THING(obj_item55_stim) \
    THING(obj_item56_spawner) \
    THING(obj_item57_gundrone) \
    THING(obj_item58_seekers) \
    THING(obj_item59_noobtube) \
    THING(obj_item60_aimbot) \
    THING(obj_item61_rosarius) \
    THING(obj_item62_colibri) \
    THING(obj_item63_cellreplacer) \
    THING(obj_item64_chalice) \
    THING(obj_item65_stunbolt) \
    THING(obj_item66_akira) \
    THING(obj_item67_boots) \
    THING(obj_item68_ring) \
    THING(obj_item69_taser) \
    THING(obj_item70_bloodbolt) \
    THING(obj_item71_sentry) \
    THING(obj_item72_snipersentry) \
    THING(obj_item73_sentryfuture) \
    THING(obj_item74_perkkit) \
    THING(obj_item75_glass) \
    THING(obj_item76_bloodthirst) \
    THING(obj_item77_chip) \
    THING(obj_item78_sawblade) \
    THING(obj_item79_bolt) \
    THING(obj_item80_masterkey) \
    THING(obj_item81_tanto) \
    THING(obj_item82_flare) \
    THING(obj_item83_grenade_smoke) \
    THING(obj_item84_flechette) \
    THING(obj_item85_kunai) \
    THING(obj_item86_commandoflare) \
    THING(obj_item87_beamblue) \
    THING(obj_item88_beampurple) \
    THING(obj_item89_beamred) \
    THING(obj_item90_shuriken1) \
    THING(obj_item91_shuriken2) \
    THING(obj_item92_fanknives) \
    THING(obj_item93_flyingknife) \
    THING(obj_item94_dagger) \
    THING(obj_item95_livingbomb) \
    THING(obj_item96_stickybomb) \
    THING(obj_item97_minelaser) \
    THING(obj_item98_minisentry) \
    THING(obj_item99_battlecry) \
    THING(obj_item100_breachingcharge) \
    THING(obj_item101_resonator) \
    THING(obj_item102_airhorn) \
    THING(obj_item103_brawndo) \
    THING(obj_item104_eclipse) \
    THING(obj_item107_ministim) \
    THING(obj_item108_toolbox) \
    THING(obj_item109_reloader2) \
    THING(obj_item110_spider) \
    THING(obj_item111_heatsink) \
    THING(obj_item112_tptp) \
    THING(obj_item113_button) \
    THING(obj_item114_fireaura) \
    THING(obj_item115_decoy) \
    THING(obj_item116_decoyshield) \
    THING(obj_item117_gps) \
    THING(obj_item118_goldnugget) \
    THING(obj_item119_upgradekit2) \
    THING(obj_item120_detector) \
    THING(obj_item121_tomahawk) \
    THING(obj_item122_targetcpu) \
    THING(obj_item123_cover) \
    THING(obj_item124_gunner) \
    THING(obj_item125_powerpack) \
    THING(obj_item126_missiledrone) \
    THING(obj_item127_building) \
    THING(obj_item128_remover) \
    THING(obj_item129_research) \
    THING(obj_item_empty) \
    THING(obj_item130_riotguard) \
    THING(obj_item131_command) \
    THING(obj_item132_dynamite) \
    THING(obj_item133_magnum2) \
    THING(obj_item133_magnum) \
    THING(obj_item134_bandana) \
    THING(obj_item135_relay) \
    THING(obj_item136_missilecontrol) \
    THING(obj_item137_trapper) \
    THING(obj_item138_pets) \
    THING(obj_item139_underbarrel) \
    THING(obj_item140_shaker) \
    THING(obj_item141_intensifier) \
    THING(obj_item142_fire) \
    THING(obj_item143_itemlink) \
    THING(obj_item144_nitro) \
    THING(obj_item145_stunmine) \
    THING(obj_item146_acidmine) \
    THING(obj_item147_armageddon) \
    THING(obj_item149_lasercaster) \
    THING(obj_item150_psycloud) \
    THING(obj_item151_grenade_fire) \
    THING(obj_item152_attackdrones) \
    THING(obj_item153_swarm) \
    THING(obj_item98_) \
    THING(obj_item_slot) \
    THING(obj_orb_parent) \
    THING(obj_orb_lightning) \
    THING(obj_orb_class) \
    THING(obj_orb_fire) \
    THING(obj_orb_wind) \
    THING(obj_orb_fusion) \
    THING(obj_orb_ripper) \
    THING(obj_orb_iron) \
    THING(obj_aura_effect) \
    THING(obj_mysterybonus) \
    THING(obj_mystery_item) \
    THING(obj_mystery_perk) \
    THING(obj_mystery_starterweapon) \
    THING(obj_mystery_madness) \
    THING(obj_mystery_tactical) \
    THING(obj_mystery_randomrun) \
    THING(obj_mystery_instagib) \
    THING(obj_beartrap) \
    THING(obj_ammo_pack) \
    THING(obj_resonator_location) \
    THING(obj_ammo_pack2) \
    THING(obj_effect_parent) \
    THING(obj_lightemitter_arealight) \
    THING(obj_lightemitter_heart0) \
    THING(obj_lightemitter_heart1) \
    THING(obj_lightemitter_heart2) \
    THING(obj_lightemitter_flickering) \
    THING(obj_lightemitter_arealight_huge) \
    THING(obj_lightemitter_arealight_firingrange) \
    THING(obj_lightemitter_arealight_boss) \
    THING(obj_lightemitter_alarm_ctrl) \
    THING(obj_lightemitter_alarm) \
    THING(obj_lightemitter_mainmenu) \
    THING(obj_lightemitter_mainmenu_small) \
    THING(obj_debris_metal1) \
    THING(obj_debris_wood1) \
    THING(obj_blood_1) \
    THING(obj_impactparticles_blood1) \
    THING(obj_blood_splats) \
    THING(obj_blood_splashes) \
    THING(obj_blood_sprinkles) \
    THING(obj_kill_splat) \
    THING(obj_status_burn) \
    THING(obj_status_slow) \
    THING(obj_status_stun) \
    THING(obj_status_slow_effect) \
    THING(obj_status_toxicblob) \
    THING(obj_status_healing) \
    THING(obj_status_healing_particle) \
    THING(obj_status_healing_particle_spark) \
    THING(obj_fangs_effect) \
    THING(obj_battlecry_effect) \
    THING(obj_airhorn_effect) \
    THING(obj_stickygrenade_item) \
    THING(obj_shieldbreak_particle) \
    THING(obj_tsunami_effect) \
    THING(obj_shieldboost_effect) \
    THING(obj_tanto_swing) \
    THING(obj_dagger_stab_effect) \
    THING(obj_shield_effect) \
    THING(obj_shield_effect_jet) \
    THING(obj_shield_gone_effect) \
    THING(obj_steeltrap_effect) \
    THING(obj_lightning_strike) \
    THING(obj_lightning_strike_divine) \
    THING(obj_lightning_strike_stun) \
    THING(obj_overclock_effect) \
    THING(obj_lightning_hit) \
    THING(obj_shield_explode_particle) \
    THING(obj_shield_explode) \
    THING(obj_breachmarker) \
    THING(obj_breachradius) \
    THING(obj_particle_multiplayer) \
    THING(obj_explosion_parent) \
    THING(obj_explosion_big) \
    THING(obj_explosion_small) \
    THING(obj_explosion_frag) \
    THING(obj_3_explos) \
    THING(obj_explo_neutrino) \
    THING(obj_2_epxlos) \
    THING(obj_explosion_akira) \
    THING(obj_explosion_plasma) \
    THING(obj_explosion_red) \
    THING(obj_explosion_simple) \
    THING(obj_explosion_reso) \
    THING(obj_explosion_resowave) \
    THING(obj_explosion_sphere) \
    THING(obj_explosion_player) \
    THING(obj_explosion_crystal) \
    THING(obj_explosion_crystal_weak) \
    THING(obj_explosion_drone) \
    THING(obj_explosion_flak) \
    THING(obj_explosion_bullet) \
    THING(obj_explosion_stun) \
    THING(obj_explosion_laserspike) \
    THING(obj_explosion_antishield) \
    THING(obj_explosion_flash) \
    THING(obj_explosion_flare) \
    THING(obj_explosion_roadflare) \
    THING(obj_explosion_smoke) \
    THING(obj_explosion_psycloud) \
    THING(obj_explosion_scatter) \
    THING(obj_explosion_beam_parent) \
    THING(obj_explosion_beam_bigred) \
    THING(obj_explosion_beam_heartbig) \
    THING(obj_explosion_beam_heartsmall) \
    THING(obj_explosion_beam_item_blue) \
    THING(obj_explosion_beam_item_eclipse) \
    THING(obj_explosion_beam_item_purple) \
    THING(obj_explosion_beam_item_red) \
    THING(obj_beam_armageddon) \
    THING(obj_explosion_stun_colorgrading) \
    THING(obj_explosion_poison) \
    THING(obj_explosion_fire) \
    THING(obj_trail_rocket) \
    THING(obj_trail_rocket_dark) \
    THING(obj_trail_rocket_meddark) \
    THING(obj_trail_rocket_spiky) \
    THING(obj_trail_bloodbolt) \
    THING(obj_trail_drill) \
    THING(obj_trail_needler) \
    THING(obj_trail_seeker) \
    THING(obj_trail_crazyrocket) \
    THING(obj_smoke_parent) \
    THING(obj_particle_gravity_parent) \
    THING(obj_crystal_spritechange_ring) \
    THING(obj_teleporter_circle) \
    THING(obj_shielddrone_effect) \
    THING(obj_offrail_marker) \
    THING(obj_grenade_marker) \
    THING(obj_grenade_marker_he) \
    THING(obj_grenade_marker_plasma) \
    THING(obj_grenade_marker_flash) \
    THING(obj_grenade_marker_stun) \
    THING(obj_grenade_marker_poison) \
    THING(obj_grenade_marker_fire) \
    THING(obj_grenade_marker_cluster) \
    THING(obj_grenade_marker_aircom) \
    THING(obj_grenade_marker_slowfield) \
    THING(obj_grenade_primer) \
    THING(obj_primer_he) \
    THING(obj_primer_plasma) \
    THING(obj_primer_flash) \
    THING(obj_primer_stun) \
    THING(obj_primer_poison) \
    THING(obj_primer_fire) \
    THING(obj_primer_cluster) \
    THING(obj_strafe_ghosting_spawner) \
    THING(obj_strafe_ghosting_spawner_support) \
    THING(obj_strafe_ghosting_spawner_suport) \
    THING(obj_strafe_ghosting) \
    THING(obj_strafe_supporter) \
    THING(obj_strafe_suporter) \
    THING(obj_dodge_ghosting) \
    THING(obj_dodge_ghosting_building) \
    THING(obj_smoke_impact) \
    THING(obj_smoke_player) \
    THING(obj_smoke_explo_effect) \
    THING(obj_smoke_firing_effect) \
    THING(obj_smoke_firing_effect1) \
    THING(obj_oil_pool) \
    THING(obj_poison_pool) \
    THING(obj_groundeffect_crystal) \
    THING(obj_decal_bullet_metal) \
    THING(obj_decal_bullet_metal_medium) \
    THING(obj_decal_bullet_metal_big) \
    THING(obj_line_effect) \
    THING(obj_healing_circle) \
    THING(obj_effect_laststand) \
    THING(obj_followunit_parent) \
    THING(obj_followunit_beam) \
    THING(obj_voidzone_parent) \
    THING(obj_voidzone_antiheal) \
    THING(obj_voidzone_spiderboss) \
    THING(obj_voidzone_mechromancer) \
    THING(obj_voidzone_heart) \
    THING(obj_voidzone_heart_safe) \
    THING(obj_voidzone_ballbot) \
    THING(obj_effect_slowcircle) \
    THING(obj_enemyteleport_spot) \
    THING(obj_enemyteleport_dronemg) \
    THING(obj_enemyteleport_spiderdisco) \
    THING(obj_enmemyteleport_) \
    THING(obj_enmteleport_dronemissile) \
    THING(obj_effect_slowcircle_spark) \
    THING(obj_turret_auraspark) \
    THING(obj_notification_circle) \
    THING(obj_inspire_effect) \
    THING(obj_hit_circle_effect) \
    THING(obj_splash_effect) \
    THING(obj_plating_effect) \
    THING(obj_particle_parent) \
    THING(obj_impact_spark1) \
    THING(obj_impact_spark2) \
    THING(obj_impact_spark3) \
    THING(obj_impact_sparks_large) \
    THING(obj_impact_sparks_cracker) \
    THING(obj_impact_dust) \
    THING(obj_bullettrail_curvedsmoke) \
    THING(obj_spark_explosion) \
    THING(obj_impact_spark_bounce) \
    THING(obj_impact_spark_effect) \
    THING(obj_levelup_spark) \
    THING(obj_hit_decal_glow) \
    THING(obj_muzzleflash_1) \
    THING(obj_muzzleflash_glow) \
    THING(obj_muzzleflash_laser) \
    THING(obj_muzzleflashparticles) \
    THING(obj_muzzleflashparticles2) \
    THING(obj_curse_star) \
    THING(obj_mortarshot_parent) \
    THING(obj_mortarshot) \
    THING(obj_mortarshot_ballistic) \
    THING(obj_mortarshot_small) \
    THING(obj_mortarshot_drone) \
    THING(obj_mortarshot_crystal) \
    THING(obj_mortarshot_shadow) \
    THING(obj_sonar_ping_effect) \
    THING(obj_sonar_ping_effect_reverse) \
    THING(obj_lightemitter_firing) \
    THING(obj_lightemitter_hit) \
    THING(obj_menu_particle) \
    THING(obj_menu_particleemitter) \
    THING(obj_lightemitter_parent) \
    THING(obj_flamethrower_particle) \
    THING(obj_flamethrower_particle_ball) \
    THING(obj_flamethrower_particle_old) \
    THING(obj_exp_anchor) \
    THING(obj_exp_gain_ring) \
    THING(obj_soulcatcher_soul) \
    THING(obj_exp_particle_death) \
    THING(obj_credits_particle) \
    THING(obj_credits_particle_white) \
    THING(obj_plus_particle) \
    THING(obj_downvote_particle) \
    THING(obj_eraser_particle) \
    THING(obj_dust_particle) \
    THING(obj_exp_particle_death2) \
    THING(obj_hit_circle) \
    THING(obj_hitmarker_world) \
    THING(obj_fire_tiny) \
    THING(obj_particle_base) \
    THING(obj_particles_laserline_spark) \
    THING(obj_particles_rockettrail) \
    THING(obj_particles_explo_dirt) \
    THING(obj_particle_laser_sprinkles) \
    THING(obj_particles_explo_chunky_metal) \
    THING(obj_particles_explo_concrete) \
    THING(obj_particles_explo_chunky_metal_big) \
    THING(obj_particles_explo_chunky_wood) \
    THING(obj_particles_huge_chunks) \
    THING(obj_particles_huge_chunks2) \
    THING(obj_particles_impact_metal) \
    THING(obj_particles_impact_concrete) \
    THING(obj_particles_impact_oil) \
    THING(obj_particles_oilpools_small) \
    THING(obj_particles_oilpools_flying) \
    THING(obj_particles_impact_concrete_chunky) \
    THING(obj_particles_impact_wood_chunky) \
    THING(obj_particles_impact_wood_chunky2) \
    THING(obj_particles_impact_wood) \
    THING(obj_particles_shell) \
    THING(obj_destructible_flash) \
    THING(obj_particles_impact_sparks) \
    THING(obj_aura_crystal) \
    THING(obj_defense_buyprop) \
    THING(obj_buy_defense_2x1) \
    THING(obj_buy_constructor) \
    THING(obj_ground_text_parent) \
    THING(obj_building_grid) \
    THING(obj_tutorial_mode) \
    THING(obj_defense_mode) \
    THING(obj_firingrange_mode) \
    THING(obj_survival_mode) \
    THING(obj_arena_modeOld) \
    THING(obj_firingrange_spawner_1) \
    THING(obj_firingrange_spawner_auto) \
    THING(obj_player_spawn) \
    THING(obj_building_effect) \
    THING(obj_tutorial_overlay) \
    THING(obj_mars_mode) \
    THING(obj_arena_mode) \
    THING(obj_conc_pillar_solo) \
    THING(obj_conc_pillar_wall_left) \
    THING(obj_conc_pillar_wall) \
    THING(obj_conc_pillar_destroyed) \
    THING(obj_conc_pyramid) \
    THING(obj_conc_tankbarrier) \
    THING(obj_conc_milestone) \
    THING(obj_conc_cube) \
    THING(obj_conc_rect_hor) \
    THING(obj_conc_rect_vert) \
    THING(obj_conc_barrier_hor) \
    THING(obj_conc_barrier_vert) \
    THING(obj_conc_wall_hor) \
    THING(obj_wall_parent) \
    THING(obj_wall_vert_center) \
    THING(obj_wall_fence_vert_center) \
    THING(obj_wall_metal_vert_center) \
    THING(obj_wall_conc_vert_center) \
    THING(obj_wall_vert_bot) \
    THING(obj_wall_vert_top) \
    THING(obj_wall_hor_center) \
    THING(obj_wall_leftend) \
    THING(obj_wall_rightend) \
    THING(obj_wall_fence_hor) \
    THING(obj_wall_fence_gate) \
    THING(obj_wall_metal_hor) \
    THING(obj_wall_metal_hor2) \
    THING(obj_wall_metal_fat2) \
    THING(obj_wall_metal_fat1) \
    THING(obj_door_parent) \
    THING(obj_door_spawner) \
    THING(obj_door_hearthack) \
    THING(obj_wall_heliBoss_vert) \
    THING(obj_wall_heliBoss_hor) \
    THING(obj_door_hearttank) \
    THING(obj_door_heartenter) \
    THING(obj_cylinder_f1_spawn) \
    THING(obj_cylinder_f1) \
    THING(obj_oiltank_long) \
    THING(obj_oiltank_long_hor) \
    THING(obj_oiltank_high) \
    THING(obj_oiltank_low) \
    THING(obj_oilconv_low) \
    THING(obj_pipes_large_stack) \
    THING(obj_pipes_large_vert) \
    THING(obj_pipes_valveprop) \
    THING(obj_generator_copper) \
    THING(obj_generator_turbine2) \
    THING(obj_oiltank_pipes) \
    THING(obj_generator_turbine) \
    THING(obj_oiltank_ball) \
    THING(obj_pillar_platform) \
    THING(obj_pillar_platform_below) \
    THING(obj_concpipe) \
    THING(obj_ventilation_floor1) \
    THING(obj_pipe_center_parent) \
    THING(obj_pipelow_leftend) \
    THING(obj_pipelow_center) \
    THING(obj_pipelow_rightend) \
    THING(obj_pipelow_topend) \
    THING(obj_pipelow_vertcenter) \
    THING(obj_pipelow_botend) \
    THING(obj_pipehigh_leftend) \
    THING(obj_pipehigh_center) \
    THING(obj_pipeshigh_rightend) \
    THING(obj_stack_canister) \
    THING(obj_oiltank_huge) \
    THING(obj_bindercage_double) \
    THING(obj_cablebinder_single) \
    THING(obj_bindercage_hor) \
    THING(obj_bindercage_vert) \
    THING(obj_cylinder_electro) \
    THING(obj_soultower) \
    THING(obj_soulgenerator) \
    THING(obj_lightning_rod) \
    THING(obj_bindercage_cable) \
    THING(obj_generator_alu_cube2) \
    THING(obj_generator_alu_cube3) \
    THING(obj_generator_alu_cube4) \
    THING(obj_generator_alu_cube) \
    THING(obj_generator_alu_high) \
    THING(obj_electroblock) \
    THING(obj_electrohouse_vert) \
    THING(obj_electrohouse_hor) \
    THING(obj_stackelectro_hor) \
    THING(obj_stackelecto_ver) \
    THING(obj_generatoralu_battery) \
    THING(obj_generator_alu_hor) \
    THING(obj_generator_alu_ver) \
    THING(obj_generatoralu_tube) \
    THING(obj_ground_transformator) \
    THING(obj_ground_vrm) \
    THING(obj_cylinder_f2) \
    THING(obj_cylinder_f2_b) \
    THING(obj_sandbags_vert) \
    THING(obj_sandbags_vert_small) \
    THING(obj_sandbags_hor) \
    THING(obj_sandbags_circle_bot) \
    THING(obj_sandbags_circle_top) \
    THING(obj_crawlpipe) \
    THING(obj_sculpt_quad) \
    THING(obj_clothbox) \
    THING(obj_radar_cube) \
    THING(obj_sculpt_rect) \
    THING(obj_conctext_02) \
    THING(obj_conc_tent_vert) \
    THING(obj_conc_tent_hor) \
    THING(obj_climbblock_vert) \
    THING(obj_conc_tank_vert) \
    THING(obj_conc_tank_hor) \
    THING(obj_conc_btr_hor) \
    THING(obj_conc_btr_vert) \
    THING(obj_climbwall) \
    THING(obj_tirejump) \
    THING(obj_trainingcontainer_hor) \
    THING(obj_trainingcontainer_ver) \
    THING(obj_tirestack_medium) \
    THING(obj_tirestack_low) \
    THING(obj_concback_parent) \
    THING(obj_house_a0) \
    THING(obj_house_a1) \
    THING(obj_euro_sandbags) \
    THING(obj_crystal_greenglow) \
    THING(obj_crystal_groundstones) \
    THING(obj_crystal_d_rect) \
    THING(obj_crystal_d_rect_vert) \
    THING(obj_crystal_d_pyramid) \
    THING(obj_crystal_d_milestone) \
    THING(obj_crystal_d_cube) \
    THING(obj_crystal_d_milestone45) \
    THING(obj_crystal_floating_big) \
    THING(obj_crystal_floating_medium) \
    THING(obj_crystal_milestone_medium) \
    THING(obj_crystal_medium) \
    THING(obj_crystal_low) \
    THING(obj_crystal_big) \
    THING(obj_crystal_milestone_big) \
    THING(obj_crystal_generator) \
    THING(obj_crystal_genetorline) \
    THING(obj_crystal_solopillar_med) \
    THING(obj_crystal_solopillar_low) \
    THING(obj_crystal_lamp) \
    THING(obj_crystal_smallwall) \
    THING(obj_crystal_bigwall) \
    THING(spr_crystal_spire_milestone) \
    THING(obj_crystal_pillarspike_medium) \
    THING(obj_crystal_pillarspike_big) \
    THING(obj_crystal_spire_small) \
    THING(obj_crystal_spire_big) \
    THING(obj_flyingcrystals_tiny) \
    THING(obj_crystal_teleporter_A) \
    THING(obj_crystal_decal) \
    THING(obj_cogwheelground_large) \
    THING(obj_machine_ground_A) \
    THING(obj_cogwheel_A) \
    THING(obj_rocketfuel_hor) \
    THING(obj_rocketfuel_ver) \
    THING(obj_rocketcover_hor0) \
    THING(obj_rocketstack_big_hor0) \
    THING(obj_rocketstackred_big_hor) \
    THING(obj_missilepartred_hor) \
    THING(obj_rocketstack_big_hor1) \
    THING(obj_rocketstack_big_hor2) \
    THING(obj_rocketstack_big_hor4) \
    THING(obj_rocketstack_big_ver0) \
    THING(obj_rocketstackred_big_ver) \
    THING(obj_missilepartred_ver) \
    THING(obj_rocketstack_big_ver1) \
    THING(obj_rocketstack_big_ver2) \
    THING(obj_tankshells) \
    THING(obj_quadstackrocket) \
    THING(obj_shellscylinders) \
    THING(obj_shellscylinders2) \
    THING(obj_rocketstack_small) \
    THING(obj_heart_electropole) \
    THING(obj_militarycrate_hor) \
    THING(obj_militarycrate_ver) \
    THING(obj_militarycrate_cube) \
    THING(obj_cylinder_f4) \
    THING(obj_rocketstack) \
    THING(obj_tower_radar) \
    THING(obj_tower_missile0) \
    THING(obj_tower_missile1) \
    THING(obj_heart_reactor) \
    THING(obj_globe_statue) \
    THING(obj_cylinder_f5) \
    THING(obj_cylinder_silo) \
    THING(obj_missilepart_low) \
    THING(obj_missilepart_high) \
    THING(obj_missilesilo_big) \
    THING(obj_missilesilo_quad) \
    THING(obj_missilepod_large) \
    THING(obj_doublemissilestack) \
    THING(obj_missilelarge_vert) \
    THING(obj_missilecurve) \
    THING(obj_alublock_big) \
    THING(obj_alublock_round) \
    THING(obj_alublock_bigwide) \
    THING(obj_ventilation_floor4) \
    THING(obj_cylinder_f6) \
    THING(obj_transistor_high) \
    THING(obj_transistor_medium) \
    THING(obj_transistor_stack) \
    THING(obj_transistor_tub) \
    THING(obj_transistor_6tube) \
    THING(obj_transistor_12tube) \
    THING(obj_transistor_transformator) \
    THING(obj_transistor_battery) \
    THING(obj_transistor_dualtower) \
    THING(obj_transistor_heatsink_huge) \
    THING(obj_transistor_heatsink_cube) \
    THING(obj_transistor_heatsink_small) \
    THING(obj_transistor_heatsink_tiny) \
    THING(obj_cursor_mainmenu) \
    THING(obj_mm_research_trigger) \
    THING(obj_mm_ground) \
    THING(obj_mm_arrowwobble) \
    THING(obj_mm_creditsdisplay) \
    THING(obj_pregame_darkoverlay) \
    THING(obj_mm_weaponlocker) \
    THING(obj_mm_computer) \
    THING(obj_mm_kitselect) \
    THING(obj_mm_progress) \
    THING(obj_scrolling_log) \
    THING(obj_mainmenu) \
    THING(obj_mm_cityscreen) \
    THING(obj_mm_menu_parent) \
    THING(obj_player_mainmenu) \
    THING(obj_mm_startgamedecal) \
    THING(obj_mm_readylobby) \
    THING(obj_mm_readylobby_S2) \
    THING(obj_mm_talentselection_menu) \
    THING(obj_mm_multiplayer_menu) \
    THING(obj_mm_itemselect_menu) \
    THING(obj_mm_weaponmenu) \
    THING(obj_mm_secret_menu) \
    THING(obj_mm_statistics_menu) \
    THING(obj_mm_community_menu) \
    THING(obj_mm_difficultymenu) \
    THING(obj_mm_unlocks_menu) \
    THING(obj_mm_classes_menu) \
    THING(obj_mm_faction_menu) \
    THING(obj_mm_classes_menu1) \
    THING(obj_mm_mission_menu) \
    THING(obj_mm_clan_menu) \
    THING(obj_intro_notes) \
    THING(obj_startgame) \
    THING(obj_bigbrothermode_) \
    THING(obj_mm_switchtalent_effect) \
    THING(obj_mm_research) \
    THING(obj_mm_glow) \
    THING(obj_threadmill_creator) \
    THING(obj_threadmill_start) \
    THING(obj_treadmill_contains) \
    THING(obj_threadmill_end) \
    THING(obj_treadmill_rollband) \
    THING(obj_treadmill_extractor) \
    THING(obj_mainmenu_backgroundglow) \
    THING(obj_research_button) \
    THING(obj_researchmenu) \
    THING(obj_research_box) \
    THING(obj_research_box_cursor) \
    THING(obj_research_box_daily) \
    THING(obj_research_box_patchlog) \
    THING(obj_research_box_activitylog) \
    THING(obj_research_box_income) \
    THING(obj_research_box_visor) \
    THING(obj_research_box_weapon) \
    THING(obj_research_box_cores) \
    THING(obj_research_box_bios) \
    THING(obj_research_cursor) \
    THING(obj_mm_acc_input_parent) \
    THING(obj_mm_login_box) \
    THING(obj_mm_reset_password) \
    THING(obj_set_lobby_config) \
    THING(obj_mm_generic_input_box) \
    THING(obj_name_input) \
    THING(obj_mm_new_pw_box) \
    THING(obj_mm_network_error) \
    THING(obj_mm_xbox_different_acc) \
    THING(obj_mm_join_lobby_pw) \
    THING(obj_mm_portforwarding) \
    THING(obj_mm_create_account_box) \
    THING(obj_mm_referal_box) \
    THING(obj_enm_spawn_point) \
    THING(obj_enm_POI) \
    THING(obj_enm_spawn_point_small) \
    THING(obj_enm_spawn_point_medium) \
    THING(obj_enm_spawn_point_big) \
    THING(obj_enm_alarm) \
    THING(obj_enm_budget_parent) \
    THING(obj_enm_budget_plus5) \
    THING(obj_enm_budget_plus10) \
    THING(obj_enm_budget_minus5) \
    THING(obj_nem_budget_minus10) \
    THING(obj_teleporter) \
    THING(obj_teleporter_challenge) \
    THING(obj_field_special) \
    THING(obj_turretshrinespawn) \
    THING(obj_specialobject_small) \
    THING(obj_specialobject_big) \
    THING(obj_railing_parent) \
    THING(obj_railing_straights) \
    THING(obj_railing_corner) \
    THING(obj_railing_end_vert_bot) \
    THING(obj_railing_end_vert_top) \
    THING(obj_railing_end_top_R) \
    THING(obj_railing_end_top_L) \
    THING(obj_railing_end_bot_R) \
    THING(obj_railing_end_bot_L) \
    THING(obj_railing_top) \
    THING(obj_railing_bot) \
    THING(obj_railing_right) \
    THING(obj_railing_topleft) \
    THING(obj_railing_left) \
    THING(obj_railing_topright) \
    THING(obj_railing_botleft) \
    THING(obj_railing_botright) \
    THING(obj_railing_inner_botleft) \
    THING(obj_railing_inner_botright) \
    THING(obj_railing_inner_topleft) \
    THING(obj_railing_inner_topright) \
    THING(obj_bossroom) \
    THING(obj_challengeroom) \
    THING(obj_prebossroom) \
    THING(obj_boss_transition) \
    THING(obj_walls_fog) \
    THING(obj_walls) \
    THING(obj_wall_lab1) \
    THING(obj_wall_lab3) \
    THING(obj_wall_lab1_s) \
    THING(obj_wall_lab1_triple) \
    THING(obj_wall_lab1_doorframe) \
    THING(obj_wall_lab1_door_open) \
    THING(obj_wall_lab1_door_closed) \
    THING(obj_wall_borderright_x1) \
    THING(obj_wall_cornertopright_x1) \
    THING(obj_collision_blockout_parent) \
    THING(obj_collision_blockout_A) \
    THING(obj_collision_blockout_B) \
    THING(obj_collision_blockout_C) \
    THING(obj_collision_blockout_D) \
    THING(obj_collision_blockout_E) \
    THING(obj_collision_blockout_F) \
    THING(obj_collision_blockout_1X) \
    THING(obj_collision_blockout_2X) \
    THING(obj_collision_blockout_3Y) \
    THING(obj_collision_blockout_4Y) \
    THING(obj_collision_blockout_5Z) \
    THING(obj_collision_blockout_6Z) \
    THING(obj_collision_blockout_RAND) \
    THING(obj_collision_blockout_fog) \
    THING(obj_floor_blockout_parent) \
    THING(obj_floor1_blockout) \
    THING(obj_floor2_blockout) \
    THING(obj_field_node) \
    THING(obj_force_surfacedraw) \
    THING(obj_field_parent) \
    THING(obj_special_2x2) \
    THING(obj_shrine_2x2) \
    THING(obj_special_3x3) \
    THING(obj_field_1x1) \
    THING(obj_field_1x2) \
    THING(obj_field_1x3) \
    THING(obj_field_2x1) \
    THING(obj_field_2x2) \
    THING(obj_field_2x3) \
    THING(obj_field_3x1) \
    THING(obj_field_3x2) \
    THING(obj_field_3x3) \
    THING(obj_field_3x4) \
    THING(obj_field_4x3) \
    THING(obj_field_4x4) \
    THING(obj_path_horizontal) \
    THING(obj_path_vertical) \
    THING(obj_path_left_bot) \
    THING(obj_path_bot_right) \
    THING(obj_path_right_top) \
    THING(obj_path_top_left) \
    THING(obj_field_pillar) \
    THING(obj_field_godShrine) \
    THING(obj_field_bossHelicopter) \
    THING(obj_field_forcePath) \
    THING(obj_field_forceInvisiblePath) \
    THING(obj_field_forceDummyPath) \
    THING(obj_field_forceSpecialPath) \
    THING(obj_field_forceField) \
    THING(obj_field_forceFree) \
    THING(obj_field_forceSpecial) \
    THING(obj_field_forceShrine) \
    THING(obj_field_teleporter) \
    THING(obj_field_teleporter_start) \
    THING(obj_field_teleporter_end) \
    THING(obj_fields_parent) \
    THING(obj_chunk_A) \
    THING(obj_chunk_B) \
    THING(obj_chunk_X) \
    THING(obj_chunk_Y) \
    THING(obj_chunk_Z) \
    THING(obj_FOG_back) \
    THING(obj_FOG_top) \
    THING(obj_back_colorchange) \
    THING(obj_back_ambientlight) \
    THING(obj_background_pipes) \
    THING(obj_background_tiled) \
    THING(obj_memory_manager) \
    THING(obj_levelAsObj) \
    THING(obj_levelManager) \
    THING(obj_bridge_1) \
    THING(obj_bridge_TypeB) \
    THING(obj_bridge_TypeA) \
    THING(obj_bridge_1_rng) \
    THING(obj_pathfinding_allowed) \
    THING(obj_chunk) \
    THING(obj_chunk_parent) \
    THING(obj_chunk_surfacedraw) \
    THING(obj_chunk_ao) \
    THING(obj_chunk_floor) \
    THING(obj_placeroom_movablespace) \
    THING(obj_placeroom_manualfloor) \
    THING(obj_placeroomchunk_extra) \
    THING(obj_placeroomchunk_small) \
    THING(obj_placeroomchunk_medium) \
    THING(obj_placeroomchunk_small_walls) \
    THING(obj_placeroomchunk_medium_walls) \
    THING(obj_nowall_manual) \
    THING(obj_nowall_extra) \
    THING(obj_nowall_small) \
    THING(obj_nowall_medium) \
    THING(obj_nowall_quest) \
    THING(obj_wall_small) \
    THING(obj_wall_medium) \
    THING(obj_room_config) \
    THING(obj_networking_server) \
    THING(obj_networking_client) \
    THING(obj_networking_parent) \
    THING(obj_net_MS_client) \
    THING(obj_net_matchmaking) \
    THING(obj_net_matchmaking_xbox) \
    THING(obj_net_machtmaking_ps4) \
    THING(obj_networking_lobby_ping) \
    THING(MasterServerHTTPReq) \
    THING(obj_chat_parent) \
    THING(obj_net_chat) \
    THING(obj_net_global_chat) \
    THING(obj_multiplayer_marker) \
    THING(obj_marker_come) \
    THING(obj_marker_generic) \
    THING(obj_marker_shop) \
    THING(obj_marker_help) \
    THING(obj_marker_care) \
    THING(obj_marker_object) \
    THING(obj_marker_enemy) \
    THING(obj_marker_enemyradio) \
    THING(obj_net_add_newsletter) \
    THING(obj_net_beta_forceOnline) \
    THING(obj_net_file_upload) \
    THING(obj_voice_chat) \
    THING(obj_analytics) \
    THING(obj_net_station_spawn) \
    THING(objSolidCircle) \
    THING(objSolidRectangle) \
    THING(obj_progressbar) \
    THING(o_controller_lut) \
    THING(obj_blur_test) \
    THING(obj_background_linespregame) \
    THING(obj_radio_button) \
    THING(obj_slider_input) \
    THING(obj_slider_input_mastervol) \
    THING(obj_slider_input_musicvol) \
    THING(obj_text_input) \
    THING(obj_list_debugger) \
    THING(obj_Localization) \
    THING(obj_Localization_ConsoleSelection) \
    THING(obj_HTML_fakeINI) \
    THING(o_shader_start) \
    THING(obj_steam_init) \
    THING(obj_random) \
    THING(o_shader_end) \
    THING(obj_last) \
    THING(obj_mystery_reward) \
    THING(obj_mystery_reward_weapon) \
    THING(obj_bullet_mortar_parent) \
    THING(obj_GOG) \
    THING(obj_Origin) \
    THING(obj_PSN) \
    THING(obj_Xbox) \
    THING(o_grid) \
    THING(o_magnifier) \
    THING(o_shockwave) \
    THING(o_laserturret) \
    THING(o_bullet) \
    THING(o_magnifier_path) \
    THING(tmc_vect_test_obj) \
    THING(obj_restart) \
    THING(obj_scaling) \
    THING(obj_glow1) \
    THING(obj_chromatic) \
    THING(obj_audio_emitter) \
    THING(obj_audio_emitter_water) \
    THING(obj_arena_parent) \
    THING(obj_arena_defense_core) \
    THING(obj_arena_mars) \
    THING(obj_arena_attack_headhunter) \
    THING(obj_arena_survive_crystal) \
    THING(obj_arena_survive_soulcharger) \
    THING(obj_soulcharger) \
    THING(obj_arena_shopspawner) \
    THING(obj_arena_crystal) \
    THING(obj_arena_crystal_small) \
    THING(obj_arena_crystal_big) \
    THING(obj_arena_crystal_big_preview) \
    THING(obj_arena_selfSpawner) \
    THING(obj_arena_crystalSpawner_small) \
    THING(obj_arena_crystalSpawner_big) \
    THING(obj_cameratarget_0) \
    THING(obj_cameratarget_1) \
    THING(obj_cameratarget_2) \
    THING(obj_cameratarget_3) \
    THING(obj_cameratarget_4) \
    THING(obj_arena_survival) \
    THING(obj_MOBA_Waypoint) \
    THING(obj_enm_turret_MOBA_Base) \
    THING(obj_enm_workerbot_MOBA) \
    THING(obj_MOBA_ctrl)

#ifndef MAKE_STRINGS
#define MAKE_STRINGS(THINGNAME) #THINGNAME,
#endif
#ifndef MAKE_ENUM
#define MAKE_ENUM(THINGNAME) THINGNAME,
#endif
#ifndef LIST_COUNTS
#define LIST_COUNTS
#define VARNAMES_COUNT (sizeof(Organik::Variables::VariableNamesArr) / 4)
#define OBJECTS_COUNT (sizeof(Organik::Objects::ObjectNamesArr) / 4)
#endif

#ifndef ORGANIK_OBJECTS
#define ORGANIK_OBJECTS
namespace Organik
{
    struct Objects 
    {
        enum : int32_t
        {
            OBJECTS_DO(MAKE_ENUM)
        };
        static const char* const ObjectNamesArr[];
        static std::vector<int32_t> ObjIndexes;
    };
    struct Sprites
    {
        enum : int32_t
        {
            SPRITES_DO(MAKE_ENUM)
        };
        static const char* const SpriteNamesArr[];
        static std::vector<int32_t> SpriteIndexes;
    };
    struct Sounds
    {
        enum : int32_t
        {
            SOUNDS_DO(MAKE_ENUM)
        };
        static const char* const SoundNamesArr[];
        static std::vector<int32_t> SoundIndexes;
    };
    struct Rooms
    {
        enum : int32_t
        {
            ROOMS_DO(MAKE_ENUM)
        };
        static const char* const RoomNamesArr[];
        static std::vector<int32_t> AssetIndexes;
    };
}
#define ROOM_ID(RNAME) Organik::Rooms::AssetIndexes[Organik::Rooms::##RNAME]
#endif