#pragma once
#define SOUNDS_DO(THING) \
    THING(sound_ModWeaponEject1) \
    THING(sound_ModWeaponPerfect1) \
    THING(sound_ambient_sound1) \
    THING(music_noncombat3) \
    THING(sound_noncombat_4_gergely) \
    THING(sound_Ambient_full_simple) \
    THING(sound_Ambient_full_olddrums) \
    THING(music_tension_loop_extended) \
    THING(sound_Terminal_OST_Test_1) \
    THING(sound_tim_bosstheme) \
    THING(sound_bosstheme_jet) \
    THING(sound_noncombat_efe_crystal) \
    THING(sound_combat_new_1_2_efe) \
    THING(sound_combat_new_2_efe) \
    THING(music_main_menu) \
    THING(sound_combat_efe3) \
    THING(sound_noncombat_efe) \
    THING(sound_combat_efe2) \
    THING(sound_combat_new_efe) \
    THING(sound364_Test_Song_1_Allert_1) \
    THING(sound365_Test_Song_2_Allert_1) \
    THING(sound366_Test_Song_3_Allert_1) \
    THING(sound363_Test_Song_4_Allert_1) \
    THING(sound367_Test_Song_5_Allert_1) \
    THING(sound_noncombat_gergely) \
    THING(sound_matt_idle) \
    THING(sound_matt_boss) \
    THING(sound_song_2_1_combat) \
    THING(sound_song_3_1_combat) \
    THING(sound_military_hendrik_combat_1) \
    THING(sound_military_hendrik_combat_2) \
    THING(sound_military_hendrik_combat_3) \
    THING(sound_military_hendrik_combat_4) \
    THING(sound_military_hendrik_combat_5) \
    THING(sound_military_hendrik_idle) \
    THING(music_electro_hendrik_combat_1) \
    THING(music_electro_hendrik_combat_2) \
    THING(music_electro_hendrik_combat_3) \
    THING(music_electro_hendrik_combat_4) \
    THING(music_electro_hendrik_combat_5) \
    THING(music_electro_hendrik_idle) \
    THING(music_song_6_2_combat) \
    THING(music_song_lab_1_1_idle) \
    THING(music_deepdarksynth_mainmenu) \
    THING(music_psy_eternallord) \
    THING(music_psy_hypernoma) \
    THING(music_psy_supremers) \
    THING(music_darksynth_outro) \
    THING(music_cyberpunk_intro) \
    THING(music_cyberpunk_combat1) \
    THING(music_cyberpunk_combat2) \
    THING(sound_cyberpunk_intro_full) \
    THING(sound_voice_BreachDetected) \
    THING(sound_voice_FlankingTarget) \
    THING(sound_voice_ChargingAndroid) \
    THING(sound_voice_DefendingPosition) \
    THING(sound_voice_OpenFire) \
    THING(sound_voice_Engage) \
    THING(sound_DamageReport) \
    THING(sound_voice_DieAndroid) \
    THING(sound_voice_HoldPerimeter) \
    THING(sound_voice_OverdriveEnabled) \
    THING(sound_voice_Evacuate) \
    THING(sound_voice_Hold) \
    THING(sound_voice_InspectingPerimeter) \
    THING(sound_voice_PurgeInvaders) \
    THING(sound_voice_HuntingAndroid) \
    THING(sound_voice_ProtocolInvestigation) \
    THING(sound_voice_ScanningEnvironment) \
    THING(sound_voice_PlottingTarget) \
    THING(sound_voice_SystemError) \
    THING(sound_voice_UnsafeEnvironment) \
    THING(sound_voice_ProtocolSearch) \
    THING(sound_voice_ProtocolDefence) \
    THING(sound_voice_SecuringCoordinates) \
    THING(sound_voice_WatchpostEnabled) \
    THING(sound_voice_RestockBullets) \
    THING(sound_voice_RefreshMunition) \
    THING(sound_voice_ImpactDetected) \
    THING(sound_voice_Patrolling) \
    THING(sound_voice_LoadingProjectiles) \
    THING(sound_voice_Order42) \
    THING(sound_voice_MovementDetected) \
    THING(sound_voice_DamageReceived) \
    THING(sound_voice_ModeSuspicious) \
    THING(sound_voice_MaintainLocation) \
    THING(sound_voice_InspectArea) \
    THING(sound_voice_Alarm) \
    THING(sound_voice_DieBetrayer) \
    THING(sound_voice_Guarding) \
    THING(sound_voice_CallingBackup) \
    THING(sound_voice_OnSet) \
    THING(sound_voice_Initiating) \
    THING(sound_voice_CombatModule) \
    THING(sound_voice_AssaultingBandit) \
    THING(sound_voice_Engaging) \
    THING(sound_voice_Active) \
    THING(sound_voice_OnView) \
    THING(sound_voice_Target) \
    THING(sound_voice_Reload) \
    THING(sound_voice_InRange) \
    THING(sound_voice_Status) \
    THING(sound_voice_StaySharp) \
    THING(sound_voice_Flanking) \
    THING(sound_voice_Violation) \
    THING(sound_voice_InSight) \
    THING(sound_voice_InflictedDamage) \
    THING(sound_voice_Enemy) \
    THING(sound_voice_Regroup) \
    THING(sound_voice_Oa) \
    THING(sound_voice_Wary) \
    THING(sound_voice_Attacking) \
    THING(sound_voice_Scanning) \
    THING(sound_voice_Protocol93) \
    THING(sound_voice_PatrollingPerimeter) \
    THING(sound_voice_ProtocolS) \
    THING(sound_voice_ReinforcementsNeeded) \
    THING(sound_voice_Ready_Up) \
    THING(sound_voice_Intrusion) \
    THING(sound_voice_FOV) \
    THING(sound_voice_Storming) \
    THING(sound_voice_Purging) \
    THING(sound_voice_Reloading) \
    THING(sound_voice_Reposition) \
    THING(sound_voice_Retreating) \
    THING(sound_voice_ReturningToBase) \
    THING(sound_voice_Charging) \
    THING(sound_voice_SearchAndDestroy1) \
    THING(sound_voice_SearchingPerimeter) \
    THING(sound_voice_Searching) \
    THING(sound_voice_SystemCorrupted) \
    THING(sound_voice_Alert) \
    THING(sound_voice_SystemFailure) \
    THING(sound_voice_Spotting) \
    THING(sound_voice_TargetDetected) \
    THING(sound_voice_Terminating) \
    THING(sound_collision_metal_2_1_headshot) \
    THING(sound_enemy_m4) \
    THING(sound_alarm_bot) \
    THING(sound_hover_2) \
    THING(sound_enemy_error) \
    THING(sound_enemy_g36) \
    THING(sound_spiderjeep_spawn) \
    THING(sound_robot_servo) \
    THING(sound_robot_burstfire) \
    THING(sound_beeps_explosion) \
    THING(sound_Stealth_Soldier_Invisibility_1) \
    THING(sound_enm_sniperrobotcharge) \
    THING(sound_enm_lockonsniper) \
    THING(sound_mortar_turret) \
    THING(sound_robot_hurt1) \
    THING(sound_enm_sniperriflegeneric) \
    THING(sound_enmpistol_ar15fire) \
    THING(sound_railgun_shot) \
    THING(sound_enemy_fire1) \
    THING(sound_REP_fire) \
    THING(sound_enm_lockonrocket) \
    THING(sound_laserbeamsmall) \
    THING(sound_tankengine) \
    THING(sound_jet_engine_loop) \
    THING(sound_lock_on_radar_laser) \
    THING(sound_Lock_On_Radar_Rocket) \
    THING(sound_robot_killed) \
    THING(sound_enm_chrono_target) \
    THING(sound_enm_enforcer_shot) \
    THING(sound_enm_teleport) \
    THING(sound_enm_teleport_start7) \
    THING(sound_robot_charge_misc11) \
    THING(sound_robot_charge8) \
    THING(sound_robot_charge6) \
    THING(sound_robot_charge5) \
    THING(sound_robot_charge_a) \
    THING(sound_Ball_Bot_Attackmod) \
    THING(sound_robot_charge_b) \
    THING(sound_robot_charge_mg) \
    THING(sound_robot_charge_mg2) \
    THING(sound_robot_charge10) \
    THING(sound_robot_charge_11) \
    THING(sound_flaktank_shot) \
    THING(sound_flaktank_charge) \
    THING(sound_enm_teleport_start3) \
    THING(sound_railgun_A) \
    THING(sound_railgun_B) \
    THING(sound_railgun_chargeup) \
    THING(sound_Lock_On_rocket_4) \
    THING(sound_turret_auraloop) \
    THING(sound_railgun_discharge) \
    THING(sound_railgun_charge) \
    THING(sound_railgun_firing) \
    THING(sound_sawbladebot_saw) \
    THING(sound_enemy_hovertank) \
    THING(sound_enm_machine_4) \
    THING(sound_enm_machine_6) \
    THING(sound_enm_machine_7) \
    THING(sound_enm_machine_1) \
    THING(sound_enemy_machine_10) \
    THING(sound_enemy_chargedown) \
    THING(sound_enemy_machine_8) \
    THING(sound_enemy_machine_9) \
    THING(sound_enemy_car) \
    THING(sound_flying_drone_charge) \
    THING(sound_background_noise) \
    THING(sound_tank_shot) \
    THING(sound_robot_charge_mg4) \
    THING(sound_robot_charge9) \
    THING(sound_enemy_radio) \
    THING(sound_player_Guardian) \
    THING(sound_player_Ready) \
    THING(sound_player_Rogue) \
    THING(sound_player_Commando) \
    THING(sound_player_Elemental) \
    THING(sound_Character_Move_Rotate_1_1) \
    THING(sound_Character_Move_Rotate_1_2) \
    THING(sound_player_Specialist) \
    THING(sound_Character_Move_Stop_1_1) \
    THING(sound_trap_spike) \
    THING(sound_player_hurt2) \
    THING(sound_bass_generic) \
    THING(sound_hitsplash) \
    THING(sound_hitmarker1) \
    THING(sound_hitmarker2) \
    THING(sound_coilpistol_ready) \
    THING(sound_VAL_shot) \
    THING(sound_twinmill_shot) \
    THING(sound_crossbow_eject) \
    THING(sound_crossbow_small) \
    THING(sound_crossbow2_edit) \
    THING(sound_crossbow_ready) \
    THING(sound_turret_shot) \
    THING(sound_MAC_shot) \
    THING(sound_SPC_eject) \
    THING(sound_ump_shot2) \
    THING(sound_SPC_shot) \
    THING(sound_vec_eject) \
    THING(sound_viking_shot) \
    THING(sound_spectre_reload) \
    THING(sound_viking_ready) \
    THING(sound_fmg_shot) \
    THING(sound_K7_shot) \
    THING(sound_K7_ready) \
    THING(sound_UI_Weapons_Upgrade_18) \
    THING(sound_UI_Weapons_Upgrade_7) \
    THING(sound_car_reload) \
    THING(sound_pistol_shot_car) \
    THING(sound_acr_rel0) \
    THING(sound_acr_ready) \
    THING(sound_acr_rel1) \
    THING(sound_acr_shot) \
    THING(sound_car_ready) \
    THING(sound_m16_shot) \
    THING(sound_m16_eject) \
    THING(sound_m16_reload) \
    THING(sound_m16_ready) \
    THING(sound_m14_reload) \
    THING(sound_m14_ready) \
    THING(sound_m14_shot) \
    THING(sound_m14mini_shot) \
    THING(sound_heavynailgun_shot) \
    THING(sound_reload_sharp) \
    THING(sound_m14_eject) \
    THING(sound_T89_shot) \
    THING(sound_amd_shot) \
    THING(sound_amd_shot2) \
    THING(sound_amd_eject) \
    THING(sound_amd_reload_carrdy) \
    THING(sound_RPK12_shot) \
    THING(sound_RPK_shot2) \
    THING(sound_AEK_shot) \
    THING(sound_AEK_release) \
    THING(sound_AEK_ready) \
    THING(sound_RPK_ready) \
    THING(sound_RPK_reload) \
    THING(sound_amd_ready) \
    THING(sound_AKSU_shot) \
    THING(sound_AN94_magout) \
    THING(sound_AN94_ready) \
    THING(sound_STG_Shot) \
    THING(sound_deagle_baby_magin) \
    THING(sound_deagle_baby_ready) \
    THING(sound_deagle_shot) \
    THING(sound_deagle2_shot) \
    THING(sound_rev_heavy_shot) \
    THING(sound_rev_heavy_shot_2) \
    THING(sound_HON_shot) \
    THING(sound_rev_shot) \
    THING(sound_rev_eject) \
    THING(sound_rev_ready2) \
    THING(sound_rev_spin2) \
    THING(sound_rev_spin) \
    THING(sound_rev_ready) \
    THING(sound_Empty_Mag_MachineGun_2_2) \
    THING(sound_heavy_mg_reload) \
    THING(sound_sound_hmg_shot) \
    THING(sound_mg_ready) \
    THING(sound_mg_shot) \
    THING(sound_minigun_spinup) \
    THING(sound_gat_shot) \
    THING(sound_gat_spin) \
    THING(sound_FC_Shot) \
    THING(sound_DMR_shot2) \
    THING(sound_kar98_ready) \
    THING(sound_kar98_reload) \
    THING(sound_m1_garand) \
    THING(sound_K9800_shot) \
    THING(sound_heavy_shot) \
    THING(sound_gm6_shot) \
    THING(sound_intervention_eject) \
    THING(sound_intervention_360) \
    THING(sound_sci_fi_weapon_reload_04) \
    THING(sound_srp_shot) \
    THING(sound_srp_shot2) \
    THING(sound_srp_boltback) \
    THING(sound_srp_garand) \
    THING(sound_srp_ready) \
    THING(sound_srp_ready2) \
    THING(sound_srp_reload) \
    THING(sound_gurren_eject) \
    THING(sound_gurren_ready) \
    THING(sound_gurren_reload) \
    THING(sound_gurren_shot) \
    THING(sound_k95_shot) \
    THING(sound_M98_ready) \
    THING(sound_M98_eject) \
    THING(sound_M98_reload) \
    THING(sound_M98_shot) \
    THING(sound_M98_charged) \
    THING(sound_M98_ping) \
    THING(sound_ocw_ready) \
    THING(sound_ocw_shot) \
    THING(sound_ocw_clipin) \
    THING(sound_ocw_clipout) \
    THING(sound_grenade_launcher) \
    THING(sound_ocw_cliptap) \
    THING(sound_coilgun_shot2) \
    THING(sound_coilgun) \
    THING(sound_spas_pump) \
    THING(sound_hk_reload) \
    THING(sound_shotgun_flech) \
    THING(sound_shotgun_cock_kalash) \
    THING(sound_shotgun_cock_kalash3) \
    THING(sound_shotgun_eject) \
    THING(sound_masterkey_shot) \
    THING(sound_masterkey2_shot) \
    THING(sound_KSG_shot2) \
    THING(sound_4g_shot) \
    THING(sound_4g_shot_B) \
    THING(sound_asg_ready) \
    THING(sound_asg_shot) \
    THING(sound_asg_reload) \
    THING(sound_lever_reload) \
    THING(sound_lever_ready) \
    THING(sound_lever_eject) \
    THING(sound_lever_shot) \
    THING(sound_lever_fullreload) \
    THING(sound_lever_fulleject) \
    THING(sound_shotgun_impaler) \
    THING(sound_impaler_ready) \
    THING(sound_impaler_charge) \
    THING(sound_shotgun_generic) \
    THING(sound_shotgun_heavy) \
    THING(sound_shotgun_generic_eject) \
    THING(sound_shotgun_generic_ready) \
    THING(sound_shorty_shot) \
    THING(sound_scrapcannon_eject) \
    THING(sound_scrapcannon_ready) \
    THING(sound_scrapcannon_reload) \
    THING(sound_DB_shot) \
    THING(sound_DB_ready) \
    THING(sound_shotgun_ready) \
    THING(sound_shotgun_reloadsingle) \
    THING(sound_shotgun_shot) \
    THING(sound_cl_ejection) \
    THING(sound_cl_ready) \
    THING(sound_cl_reload) \
    THING(sound_chaoslauncher_fire) \
    THING(sound_ldmr_ready) \
    THING(sound_ldmr_shot) \
    THING(sound_DMR_shot) \
    THING(sound_Energy_Rifle_Eject_1_1) \
    THING(sound_SA58_Fire_1_4) \
    THING(sound_SA58_Fire_1_5) \
    THING(sound_SA58_Eject_1_1) \
    THING(sound_SA58_Active_Reload_1_1) \
    THING(sound_SA58_Reload_1_1) \
    THING(sound_pistol_generic) \
    THING(sound_MC_shot) \
    THING(sound_ptl_reload) \
    THING(sound_ptl_ready) \
    THING(sound_lspt_ready) \
    THING(sound_P33_Fire_1_6) \
    THING(sound_P33_Fire_1_4) \
    THING(sound_P33_Fire_1_3) \
    THING(sound_P33_Fire_1_2) \
    THING(sound_P33_Fire_1) \
    THING(sound_UI_Weapons_Upgrade_8) \
    THING(sound_UI_Weapons_Upgrade_24) \
    THING(sound_UI_Weapons_Upgrade_21) \
    THING(sound_UI_Weapons_Upgrade_14) \
    THING(sound_UI_Weapons_Upgrade_12) \
    THING(sound_UI_Weapons_Upgrade_5) \
    THING(sound_UI_Weapons_Upgrade_11) \
    THING(sound_UI_Weapons_Upgrade_23) \
    THING(sound_ptl_shot_silenced) \
    THING(sound_g18_eject) \
    THING(sound_g18_ready) \
    THING(sound_g18_reload) \
    THING(sound_gunnoise_01) \
    THING(sound_gunnoise_02) \
    THING(sound_pistol_heavy) \
    THING(sound_rep_ready) \
    THING(sound_silencedgunshot2) \
    THING(sound_g18_ump_shot) \
    THING(sound_pistol_eject2) \
    THING(sound_pistol_ready3) \
    THING(sound_pistol_eject) \
    THING(sound_pistol_ready2) \
    THING(sound_pistol_ready) \
    THING(sound_SilencedGunshot) \
    THING(sound_sup_eject) \
    THING(sound_sup_shot) \
    THING(sound_sup_mageject) \
    THING(sound_tec9_shot) \
    THING(sound_tec9_ready) \
    THING(sound_silencer_smg) \
    THING(sound_clg_spark_eject) \
    THING(sound_clg_eject) \
    THING(sound_clg_reload) \
    THING(sound_electro_impact) \
    THING(sound_chain_lightning) \
    THING(sound_plasma_shot) \
    THING(sound_ammo_recharge) \
    THING(sound_plasma_shotgun_shot) \
    THING(sound_Flamethrower_Equip_1_1) \
    THING(sound_Flamethrower_Eject_1_1) \
    THING(sound_Flamethrower_Idle_Loop_1_1) \
    THING(sound_Flamethrower_empty) \
    THING(sound_Flamethrower_Reload_1_1) \
    THING(sound_Flamethrower_Active_Reload_1_1) \
    THING(sound_Flamethrower_Fire_Start_1_1) \
    THING(sound_Flamethrower_Fire_Loop_1_1) \
    THING(sound_Flamethrower_Fire_Stop_1_1) \
    THING(sound_ejection_mechanic) \
    THING(sound_generic_eject) \
    THING(sound_metal_movement_equip) \
    THING(sound_empty_mag_plasma_1_1) \
    THING(sound_empty_mag_plasma_1_2) \
    THING(sound_empty_mag_plasma_1_3) \
    THING(sound_empty_mag_plasma_1_4) \
    THING(sound_empty_mag_plasma_2_1) \
    THING(sound_Empty_Mag_Gun_1_1) \
    THING(sound_Empty_Mag_Gun_1_2) \
    THING(sound_Empty_Mag_Gun_1_3) \
    THING(sound_Empty_Mag_Gun_2_1) \
    THING(sound_Empty_Mag_Rifle_1_3) \
    THING(sound_Empty_Mag_Rifle_1_5) \
    THING(sound_Empty_Mag_Rifle_1_7) \
    THING(sound_Empty_Mag_Rifle_2_1) \
    THING(sound_Empty_Mag_Rifle_2_2) \
    THING(sound_Empty_Mag_Heat) \
    THING(sound_UI_Heat_Bar_Overheat) \
    THING(sound_UI_Heat_Bar_Overheatnew) \
    THING(sound_jamming_hit) \
    THING(sound_weapon_jamming) \
    THING(sound_weaponready_1) \
    THING(sound_insertmag1) \
    THING(sound_critical_hit_splash2_Ballbot5) \
    THING(sound_critical_hit_splash_mixed) \
    THING(sound_critical_hit_splash) \
    THING(sound_ammo_procc) \
    THING(sound_shotgun_shell) \
    THING(sound_shotgun_shell2) \
    THING(sound_shell2) \
    THING(sound_shell3) \
    THING(sound_shell1) \
    THING(sound_Bullet_Shell_Drop_14) \
    THING(sound_Bullet_Shell_Drop_11) \
    THING(sound_Bullet_Shell_Drop_8) \
    THING(sound_Bullet_Shell_Drop_7) \
    THING(sound_weapon_drop) \
    THING(sound_noammo) \
    THING(sound_noammo_energy) \
    THING(sound_ready_generic) \
    THING(sound_ready_generic_shorter) \
    THING(sound_ready_generic_tavor) \
    THING(sound_shell_shotgun2) \
    THING(sound_shell_shotgun1) \
    THING(sound_weaponswitch) \
    THING(sound_ammoswitch) \
    THING(sound_weaponswitch_16) \
    THING(sound_weaponswitch_14) \
    THING(sound_mine_trigger) \
    THING(sound_ammo_upgrade) \
    THING(sound_Ammo_Resupply_1_1) \
    THING(sound_Ammo_Resupply_1_2) \
    THING(sound_Ammo_Resupply_1_3) \
    THING(sound_Machinegun_Mechanics_1_1) \
    THING(sound_Machinegun_Mechanics_1_2) \
    THING(sound_Machinegun_Mechanics_1_7) \
    THING(sound_Machinegun_Mechanics_1_4) \
    THING(sound_baby_magazine_in) \
    THING(sound_GP_magazine_in) \
    THING(sound_GP_trigger) \
    THING(sound_Machinegun_Mechanics_1_9) \
    THING(sound_activereload_nightvision) \
    THING(sound_pressure_charge_deny) \
    THING(sound_ammogain_tail) \
    THING(sound_ricochet_1) \
    THING(sound_ricochet_2) \
    THING(sound_ricochet_3) \
    THING(sound_m79_shot) \
    THING(sound_m79_ready) \
    THING(sound_m79_reload) \
    THING(sound_m79_eject) \
    THING(sound_explo_particle) \
    THING(sound_explo_cyber_large) \
    THING(sound_explo_cyber_large2) \
    THING(sound_grenade_acid2) \
    THING(sound_shellshock_flash) \
    THING(sound_shellshock) \
    THING(sound_flash_camera) \
    THING(sound_explosion_flare) \
    THING(sound_shieldmine) \
    THING(sound_laser_mine) \
    THING(sound_flash_explo) \
    THING(sound_explosion_deepdrop) \
    THING(sound_ares_shot) \
    THING(sound_ares_eject) \
    THING(sound_ares_ready) \
    THING(sound_multigrenade_shot) \
    THING(sound_laser_mine_trap) \
    THING(sound_explosiveammo) \
    THING(sound_Darkspace_plasmagrenade) \
    THING(sound_explosion_1) \
    THING(sound_explosion_B_3_1) \
    THING(sound_explosion_frag) \
    THING(sound_Cyber_Explosion) \
    THING(sound_missile_drum_fire) \
    THING(sound_rocket_2_1) \
    THING(sound_turret_shot_rocket) \
    THING(sound_nightvision_toggle) \
    THING(sound_nightvision_toggle_off) \
    THING(sound_item_globallightning) \
    THING(sound_item_lightningstrike) \
    THING(sound_katana_attack) \
    THING(sound_dagger_cling) \
    THING(sound_dagger_stabv) \
    THING(sound_sticky_stick) \
    THING(sound_item_bombardment) \
    THING(sound_ammocrate) \
    THING(sound_beam_loop) \
    THING(sound_beam_down) \
    THING(sound_beam_hit) \
    THING(sound_redline_loop) \
    THING(sound_redline_loop2) \
    THING(sound_redline_ready) \
    THING(sound_redline_start) \
    THING(sound_redline_end) \
    THING(sound_smoke_grenade) \
    THING(sound_item_bombardment_rdy) \
    THING(sound_item_ready_full) \
    THING(sound_item_cdready) \
    THING(sound_mem_powershot) \
    THING(sound_flask_drink) \
    THING(sound_orbwind_woosh_start) \
    THING(sound_orbwind_woosh) \
    THING(sound_Health_Potion) \
    THING(sound_item_generic) \
    THING(sound_thunderstrike) \
    THING(sound_clock_ticking) \
    THING(sound_Stimpack_1_1) \
    THING(sound_stimpack_part2) \
    THING(sound_stimpack_part1) \
    THING(sound_Throwing_Grenade_4) \
    THING(sound_item_refresher_teleport) \
    THING(sound_chrono_teleport_2) \
    THING(sound_explo_akira2) \
    THING(sound_explo_akira) \
    THING(sound_doubleshot_dingg) \
    THING(sound_item_throw) \
    THING(sound_tsunamitalisman) \
    THING(sound_colibri) \
    THING(sound_UI_General_Equip_1_1) \
    THING(sound_weapon_upgrade) \
    THING(sound_item_pickup_wepupgr3) \
    THING(sound_equip_1) \
    THING(sound_equip_2) \
    THING(sound_equip_3) \
    THING(sound_weaponready_2) \
    THING(sound_strafe_dodge) \
    THING(sound_dash_3) \
    THING(sound_dash_2) \
    THING(sound_dash_1) \
    THING(sound_ring_shatter) \
    THING(sound_amp_stutter) \
    THING(sound_camera_click) \
    THING(sound_cassette_load) \
    THING(sound_item_upgrade) \
    THING(sound_item_recycling) \
    THING(sound_procc_ding) \
    THING(sound_closed_door) \
    THING(sound_plating_pickup) \
    THING(sound_pickup_drop) \
    THING(sound_item_active_telephone) \
    THING(sound_talents_reset) \
    THING(sound_boots_dash) \
    THING(sound_powerup) \
    THING(sound_armor_up) \
    THING(sound_char_upgrade_6) \
    THING(sound_char_upgrade_3) \
    THING(sound_Weapon_Upgrade_Test_1_2) \
    THING(sound_Weapon_Upgrade_Test_1_3) \
    THING(sound_Weapon_Upgrade_Test_1_4) \
    THING(sound_pick_up_loadout_upgrade) \
    THING(sound_Weapon_Upgrade_Normal_1) \
    THING(sound_Weapon_Upgrade_Normal_3) \
    THING(sound_Weapon_Upgrade_Normal_5) \
    THING(sound_Weapon_Upgrade_Normal_4) \
    THING(sound_Weapon_Upgrade_Normal_7) \
    THING(sound_Weapon_Upgrade_Normal_6) \
    THING(sound_Weapon_Upgrade_Normal_2) \
    THING(sound_Lock_On_Aggro_2) \
    THING(sound_fangs_bite) \
    THING(sound_fangs_clank) \
    THING(sound604_sound_katana_start) \
    THING(sound_brawndo) \
    THING(sound_brawndo_song) \
    THING(sound_airhorn) \
    THING(sound_drill_use) \
    THING(sound_beep_confirm) \
    THING(sound_beep_standing) \
    THING(sound_katana_crit) \
    THING(sound_dogtag_pickup) \
    THING(sound_airwrench) \
    THING(sound_ironorb) \
    THING(sound_onslaught_loop) \
    THING(sound_onslaught_down) \
    THING(sound_onslaught_start) \
    THING(sound_Collision_Bullet_Metal_2_15_shield) \
    THING(sound_Energy_Shield_Empty_Loopable_4) \
    THING(sound_Energy_Shield_Empty_1_1) \
    THING(sound_Energy_Shield_Full_1_1) \
    THING(sound_Energy_Shield_Empty_Loopable_3) \
    THING(sound_Energy_Shield_Recharge_1_1) \
    THING(sound_Double_Damage_Activation_2_1) \
    THING(sound_crystal_laser) \
    THING(sound_crystal_mortar) \
    THING(sound_crystal_impact) \
    THING(sound_crystal_explo_fired) \
    THING(sound_particlecannon_shot2) \
    THING(sound_railgun_shot2) \
    THING(sound_railgun_gun_shot) \
    THING(sound_railgun_ready) \
    THING(sound_railgun_reload) \
    THING(sound_railgun_eject) \
    THING(sound_sci_fi_weapon_reload_07) \
    THING(sound_sci_fi_weapon_reload_02) \
    THING(sound_annihilator_relaoad) \
    THING(sound_particlecannon_shot) \
    THING(sound_sound_beam_up) \
    THING(sound_laser_beam_04_powerdown) \
    THING(sound_Eraser_DMR_Reload_1_10) \
    THING(sound_Eraser_DMR_Fire_1_7) \
    THING(sound_GM6_Linx_Evo_Eject_1_1) \
    THING(sound_GM6_Linx_Evo_Reload_1_1) \
    THING(sound_GM6_Linx_Evo_Active_Reload_1_1) \
    THING(sound_GM6_Linx_Evo_Fire_1_8) \
    THING(sound_GM6_Linx_Evo_Fire_1_2) \
    THING(sound_weapon_energy) \
    THING(sound_laser_absorb) \
    THING(sound_laser_9_shotgunedit) \
    THING(sound_laser9) \
    THING(sound_laser_Rifle_stretched) \
    THING(sound_laser_Rifle_1) \
    THING(sound_Eraser_DMR_Fire_1_2) \
    THING(sound_laser_activereload) \
    THING(sound_laser_reload_clgrdy) \
    THING(sound_heavylaserpistol_shot) \
    THING(sound_LSMG_fire) \
    THING(sound_laser_eject_2) \
    THING(sound_laser_eject_1) \
    THING(sound_laser_eject2) \
    THING(sound_laserloop) \
    THING(sound_marcuslee_laser_wrath_turret) \
    THING(sound_laserion_ready) \
    THING(sound_laserion_eject) \
    THING(sound_laserIonRecharge) \
    THING(sound_ion_cannon_shot) \
    THING(sound_proton_cannon_edited) \
    THING(sound_LaserSapEditedglock) \
    THING(sound_laserdeepburst) \
    THING(sound_P90_shot) \
    THING(sound_P90_eject) \
    THING(sound_P90_ready) \
    THING(sound_electroline_shot) \
    THING(sound_laser_qbz_shot) \
    THING(sound_laser_powershot) \
    THING(sound_LSP_fire) \
    THING(sound_Hit1) \
    THING(sound_Hit2) \
    THING(sound_Hit3) \
    THING(sound_Hit4) \
    THING(sound_Hit5) \
    THING(sound_Hit6) \
    THING(sound_Collision_Bullet_Concrete_2_12) \
    THING(sound_Collision_Bullet_Concrete_2_19) \
    THING(sound_Collision_Concrete_Broked_1) \
    THING(sound_Collision_Concrete_Broked_2) \
    THING(sound_Collision_Concrete_Broked_5) \
    THING(sound_hit_barrel) \
    THING(sound_critical_hit_electro) \
    THING(sound_critical_hit1) \
    THING(sound_critical_hit2) \
    THING(sound_Collision_Bullet_Metal_2_7) \
    THING(sound_Collision_Bullet_Metal_2_14) \
    THING(sound_Collision_Bullet_Metal_2_17) \
    THING(sound_Collision_Bullet_Metal_2_21) \
    THING(sound_Collision_Bullet_Metal_2_2) \
    THING(sound_Collision_Bullet_Wood_2_11) \
    THING(sound_Collision_Bullet_Wood_2_4) \
    THING(sound_Collision_Bullet_Wood_2_1) \
    THING(sound_collision_crate) \
    THING(sound_UI_Stinger_1_6) \
    THING(sound_UI_Stinger_1_7) \
    THING(sound_UI_Stinger_1_8) \
    THING(sound_UI_Stinger_1_9) \
    THING(sound_UI_Stinger_1_10) \
    THING(sound_UI_Stinger_1_11) \
    THING(sound_artefact_use) \
    THING(sound_Cinematic_Fatal_Horn_2) \
    THING(sound_alert_synth) \
    THING(sound_deep_aggro2) \
    THING(sound_deep_aggro) \
    THING(sound_item_levelup) \
    THING(sound_unlock_cling) \
    THING(sound_Electric_Hit_Reveal) \
    THING(sound_80s_hit1) \
    THING(sound_80s_hit2) \
    THING(sound_Cinematic_Metallic_Hit) \
    THING(sound370_Metal_Big_Impact_1) \
    THING(sound372_Metal_Big_Impact_2) \
    THING(sound371_Metal_Big_Impact_3) \
    THING(sound373_Metal_Big_Impact_4) \
    THING(sound_Failled_Challenge_46) \
    THING(sound_levelup_1) \
    THING(sound_levelup_2) \
    THING(sound_intense_1) \
    THING(sound_intense_2) \
    THING(sound374_Epic_Impacts_01) \
    THING(sound375_Epic_Impacts_06) \
    THING(sound_death_1) \
    THING(sound_levelup_select) \
    THING(sound_levelup_enter) \
    THING(sound_levelup_intro) \
    THING(sound_feedback_1) \
    THING(sound_feedback_2) \
    THING(sound_feedback_3) \
    THING(sound_feedback_legendary) \
    THING(sound_feedback_rare) \
    THING(sound_feedback_epic) \
    THING(sound_feedback_common) \
    THING(sound_feedback_levelup) \
    THING(sound_UI_Crate_Event_Weapon_1_1) \
    THING(sound_UI_Crate_Event_Weapon_2_1) \
    THING(sound_UI_Crate_Event_Weapon_3_1) \
    THING(sound_UI_Crate_Event_Weapon_4_1) \
    THING(sound_player_hurt) \
    THING(sound_feedback_slam1) \
    THING(sound_intense_hall_terminator) \
    THING(sound_feedback_dropmetal) \
    THING(sound_boss_message2) \
    THING(sound_boss_message1) \
    THING(sound_switch) \
    THING(sound_stinger1_intense) \
    THING(sound_feeback_impact1) \
    THING(sound_laseralarm) \
    THING(sound_slowmo) \
    THING(sound_impact_wavestart) \
    THING(sound_powerup_commando) \
    THING(sound_terror_alert) \
    THING(sound_terrorlevel_impact) \
    THING(sound_terroralert_medium_reverb) \
    THING(sound_terroralert_long_reverb) \
    THING(sound_feedback_impact2) \
    THING(sound_feedback_blue) \
    THING(sound_feedback_purple) \
    THING(sound_feedback_pink) \
    THING(sound_feedback_red) \
    THING(sound_feedback_yellow) \
    THING(sound_triplealert) \
    THING(sound_absorb2_soul) \
    THING(sound_feedback_cling) \
    THING(sound_lastkill) \
    THING(sound_chat_message) \
    THING(sound_scifi) \
    THING(sound_modem_intermission1) \
    THING(sound_modem_intermission0) \
    THING(sound_collision_metal) \
    THING(sound_button_impact) \
    THING(sound_button_retro4) \
    THING(sound_button_retro3) \
    THING(sound_button_retro2) \
    THING(sound_button_retro1) \
    THING(sound_sound_snappy_button) \
    THING(sound_processing) \
    THING(sound_impact_crystal) \
    THING(sound_UI_Shrine_Button_1_1) \
    THING(sound_key_press) \
    THING(sound_AKSU_shot_old) \
    THING(sound_typewriter_procc) \
    THING(sound_coin_flip) \
    THING(sound_terminal_trigger) \
    THING(sound_chest_locked) \
    THING(sound_button_generic) \
    THING(sound_terminal_trigger2) \
    THING(sound_computer_beep) \
    THING(sound_terminal_confirm) \
    THING(sound_enemy_scan) \
    THING(sound_unlock) \
    THING(sound_cash_register) \
    THING(sound_floppy_button) \
    THING(sound_floppy_eject) \
    THING(sound_shrine_button_1_1) \
    THING(sound_floppy_eject2) \
    THING(sound_quest_completed) \
    THING(sound_quest_appear) \
    THING(sound_aimlowswitch) \
    THING(sound_treadmill_coin) \
    THING(sound_japanese_ricochet) \
    THING(sound_quest_newquest) \
    THING(sound_exp_death) \
    THING(sound_get_cash) \
    THING(sound_questcomplete2) \
    THING(sound_squad_siren) \
    THING(sound_Entering_New_Room_1_1) \
    THING(sound_Entering_New_Room_1_4) \
    THING(sound_door_open) \
    THING(sound_room_cleared) \
    THING(sound_teleport_start) \
    THING(sound_radio_beep_activation_roomchange) \
    THING(sound_teleport_end) \
    THING(sound_Aircondition_1) \
    THING(sound_Discharge_1) \
    THING(sound_Engine_1_1) \
    THING(sound_Engine_2) \
    THING(sound_Generator_1) \
    THING(sound_Tesla_Coil_1_1) \
    THING(sound_Turbine_1) \
    THING(sound_TurbineWater_1) \
    THING(sound_power_on) \
    THING(sound_Vacum_1_2) \
    THING(sound_Powerlines_1) \
    THING(sound_VentTick_1) \
    THING(sound_Vent_1) \
    THING(sound_Vent_2) \
    THING(sound_Vent_3) \
    THING(sound_WaterInPipes_1) \
    THING(sound_WaterInPipes_2) \
    THING(sound_WaterInPipes_3) \
    THING(sound_WaterInPipes_4) \
    THING(sound_enemy_down) \
    THING(sound_kill_confirmed) \
    THING(sound_target_down) \
    THING(sound_subject_down) \
    THING(sound_confirmed) \
    THING(sound_target_eliminated) \
    THING(sound_reload) \
    THING(sound_ready) \
    THING(sound_no_ammunition) \
    THING(sound_no_ammunition_left) \
    THING(sound_critical_hit) \
    THING(sound_software_upgrade_ready) \
    THING(sound_i_have_to_stop_it) \
    THING(sound_maybe_i_find_equipment_in_the_labors) \
    THING(sound_alright_i_can_do_it) \
    THING(sound_here_we_go) \
    THING(sound_health_critical) \
    THING(sound_danger) \
    THING(sound_damn) \
    THING(sound_environment_cleared) \
    THING(sound_room_clear) \
    THING(sound_mars_building) \
    THING(sound_mars_building2) \
    THING(sound_mars_building3) \
    THING(sound_mars_building4) \
    THING(sound_mars_energy) \
    THING(sound_mars_energy2) \
    THING(sound_drone_b) \
    THING(sound_drone_c) \
    THING(sound_drone_a) \
    THING(sound_kunai_hit) \
    THING(sound_kunai_throw) \
    THING(sound_shuriken_throw) \
    THING(sound_sawbladegun_ready) \
    THING(sound_sawbladegun_eject) \
    THING(sound_sawbladegun_shot) \
    THING(sound_ejection_bonus) \
    THING(sound_nailgun_shot0) \
    THING(sound_nailgun_shot1) \
    THING(sound_nailgun_shot2) \
    THING(sound_taser_shot) \
    THING(sound_intro) \
    THING(sound_rpg7_shot) \
    THING(sound_ModWeaponReload1) \
    THING(sound_ModWeaponFire1)
