#pragma once
#define SPRITES_DO(THING) \
    THING(spr_player_walk_bot) \
    THING(spr_player_walk_botleft) \
    THING(spr_player_walk_botright) \
    THING(spr_player_walk_left) \
    THING(spr_player_walk_right) \
    THING(spr_player_walk_top) \
    THING(spr_player_walk_topleft) \
    THING(spr_player_walk_topright) \
    THING(spr_charblobshadow) \
    THING(spr_player_torso_gat_high) \
    THING(spr_player_torso_ptl_high) \
    THING(spr_player_torso_ptl_med) \
    THING(spr_player_torso_ptl_low) \
    THING(spr_player_torso_pxs_high) \
    THING(spr_player_torso_pxs_med) \
    THING(spr_player_torso_pxs_low) \
    THING(spr_player_torso_hon_high) \
    THING(spr_player_torso_hon_med) \
    THING(spr_player_torso_hon_low) \
    THING(spr_player_torso_lspt_high) \
    THING(spr_player_torso_lspt_med) \
    THING(spr_player_torso_lspt_low) \
    THING(spr_player_torso_rev_high) \
    THING(spr_player_torso_rev_med) \
    THING(spr_player_torso_rev_low) \
    THING(spr_player_torso_4g_high) \
    THING(spr_player_torso_4g_low) \
    THING(spr_player_torso_4g_med) \
    THING(spr_player_torso_12g_low) \
    THING(spr_player_torso_12g_med) \
    THING(spr_player_torso_12g_high) \
    THING(spr_player_torso_amd65_med) \
    THING(spr_player_torso_amd65_low) \
    THING(spr_player_torso_amd65_high) \
    THING(spr_player_torso_bfr_high) \
    THING(spr_player_torso_bfr_med) \
    THING(spr_player_torso_bfr_low) \
    THING(spr_player_torso_clg_high) \
    THING(spr_player_torso_clg_med) \
    THING(spr_player_torso_clg_low) \
    THING(spr_player_torso_r2k_high) \
    THING(spr_player_torso_r2k_med) \
    THING(spr_player_torso_r2k_low) \
    THING(spr_player_torso_db_high) \
    THING(spr_player_torso_db_med) \
    THING(spr_player_torso_db_low) \
    THING(spr_player_torso_gm6_low) \
    THING(spr_player_torso_gm6_med) \
    THING(spr_player_torso_gm6_high) \
    THING(spr_player_torso_ion_high) \
    THING(spr_player_torso_ion_med) \
    THING(spr_player_torso_ion_low) \
    THING(spr_player_torso_lsg_high) \
    THING(spr_player_torso_lsg_med) \
    THING(spr_player_torso_lsg_low) \
    THING(spr_player_torso_lsmg_high) \
    THING(spr_player_torso_lsmg_med) \
    THING(spr_player_torso_lsmg_low) \
    THING(spr_player_torso_m32_high) \
    THING(spr_player_torso_m32_med) \
    THING(spr_player_torso_m32_low) \
    THING(spr_player_torso_mg5_high) \
    THING(spr_player_torso_mg5_low) \
    THING(spr_player_torso_mg5_med) \
    THING(spr_player_torso_mg42_high) \
    THING(spr_player_torso_mg42_med) \
    THING(spr_player_torso_mg42_low) \
    THING(spr_player_torso_spc_high) \
    THING(spr_player_torso_spc_med) \
    THING(spr_player_torso_spc_low) \
    THING(spr_player_torso_srp_high) \
    THING(spr_player_torso_srp_med) \
    THING(spr_player_torso_srp_low) \
    THING(spr_player_torso_cl_high) \
    THING(spr_player_torso_cl_med) \
    THING(spr_player_torso_cl_low) \
    THING(spr_player_torso_vec_high) \
    THING(spr_player_torso_vec_med) \
    THING(spr_player_torso_vec_low) \
    THING(spr_player_torso_ML_high) \
    THING(spr_player_torso_ML_med) \
    THING(spr_player_torso_ML_low) \
    THING(spr_player_torso_fc_high) \
    THING(spr_player_torso_fc_med) \
    THING(spr_player_torso_fc_low) \
    THING(spr_player_torso_rs_high) \
    THING(spr_player_torso_rs_med) \
    THING(spr_player_rpg_high) \
    THING(spr_player_rpg_med) \
    THING(spr_player_rpg_low) \
    THING(spr_torso_m79_high) \
    THING(spr_torso_m79_med) \
    THING(spr_torso_m79_low) \
    THING(spr_torso_bow_med) \
    THING(spr_torso_bow_high) \
    THING(spr_torso_bow_low) \
    THING(spr_torso_sc_high) \
    THING(spr_torso_sc_med) \
    THING(spr_torso_sc_low) \
    THING(spr_torso_p90_high) \
    THING(spr_torso_p90_low) \
    THING(spr_torso_p90_med) \
    THING(spr_torso_m14_high) \
    THING(spr_torso_m14_med) \
    THING(spr_torso_m14_low) \
    THING(spr_torso_lc_high) \
    THING(spr_torso_lc_med) \
    THING(spr_torso_lc_low) \
    THING(spr_torso_ft_high) \
    THING(spr_torso_ft_low) \
    THING(spr_torso_ft_med) \
    THING(spr_torso_m75_high) \
    THING(spr_torso_m75_med) \
    THING(spr_torso_m75_low) \
    THING(spr_torso_gunner) \
    THING(spr_torso_gunner_low) \
    THING(spr_torso_gunner_med) \
    THING(spr_torso_gunner_pistol) \
    THING(spr_torso_riotguard) \
    THING(spr_torso_riotguard_low) \
    THING(spr_torso_riotguard_pistol) \
    THING(spr_torso_riotguard_med) \
    THING(spr_torso_breacher) \
    THING(spr_torso_breacher_med) \
    THING(spr_torso_breacher_low) \
    THING(spr_torso_breacher_pistol) \
    THING(spr_torso_assassin) \
    THING(spr_torso_assassin_low) \
    THING(spr_torso_assassin_med) \
    THING(spr_torso_assassin_pistol) \
    THING(spr_torso_raider) \
    THING(spr_torso_raider_med) \
    THING(spr_torso_raider_low) \
    THING(spr_torso_raider_pistol) \
    THING(spr_torso_demolisher) \
    THING(spr_torso_demolisher_pistol) \
    THING(spr_torso_demolisher_med) \
    THING(spr_torso_demolisher_low) \
    THING(spr_torso_engineer) \
    THING(spr_torso_engineer_med) \
    THING(spr_torso_engineer_low) \
    THING(spr_torso_engineer_pistol) \
    THING(spr_torso_sniper) \
    THING(spr_torso_sniper_medium) \
    THING(spr_torso_sniper_lower) \
    THING(spr_torso_sniper_pistol) \
    THING(spr_weapon1_SRP_icon) \
    THING(spr_weapon2_CL_icon) \
    THING(spr_weapon3_XM29_icon) \
    THING(spr_weapon4_DB_icon) \
    THING(spr_crate_weapon_wood_arena) \
    THING(spr_weapon5_MG_icon) \
    THING(spr_weapon6_PTL_icon) \
    THING(spr_weapon7_BFR_icon) \
    THING(spr_weapon8_CLG_icon) \
    THING(spr_weapon9_REV_icon) \
    THING(spr_weapon10_PXS_icon) \
    THING(spr_weapon11_REP_icon) \
    THING(spr_weapon12_DMR_icon) \
    THING(spr_weapon13_SPC_icon) \
    THING(spr_weapon16_ELC_icon) \
    THING(spr_weapon14_FMG_icon) \
    THING(spr_weapon15_R5K_icon) \
    THING(spr_weapon16_4G_icon) \
    THING(spr_weapon17_LSG_icon) \
    THING(spr_weapon18_LSMG_icon) \
    THING(spr_weapon19_12G_icon) \
    THING(spr_weapon20_GM6_icon) \
    THING(spr_weapon21_LSPT_icon) \
    THING(spr_weapon22_LDR_icon) \
    THING(spr_weapon23_M32_icon) \
    THING(spr_weapon24_AMD_icon) \
    THING(spr_weapon25_ION_icon) \
    THING(spr_weapon26_4200_icon) \
    THING(spr_weapon27_CAR_icon) \
    THING(spr_weapon28_DMN_icon) \
    THING(spr_weapon29_CRGR_icon) \
    THING(spr_weapon30_VEC_icon) \
    THING(spr_weapon31_S12_icon) \
    THING(spr_weapon32_ML_icon) \
    THING(spr_weapon33_TMP_icon) \
    THING(spr_weapon34_HON_icon) \
    THING(spr_weapon35_FT_icon) \
    THING(spr_weapon36_FC_icon) \
    THING(spr_weapon37_CG_icon) \
    THING(spr_weapon38_CP_icon) \
    THING(spr_weapon39_DS_icon) \
    THING(spr_weapon40_LAR_icon) \
    THING(spr_weapon41_AEK_icon) \
    THING(spr_weapon42_VAL_icon) \
    THING(spr_weapon43_AA_icon) \
    THING(spr_weapon44_RPK_icon) \
    THING(spr_weapon45_SB_icon) \
    THING(spr_weapon46_RG_icon) \
    THING(spr_weapon47_HMG_icon) \
    THING(spr_weapon48_NG_icon) \
    THING(spr_weapon49_PC_icon) \
    THING(spr_weapon50_BRN_icon) \
    THING(spr_weapon51_EX_icon) \
    THING(spr_weapon52_FB_icon) \
    THING(spr_weapon53_BOW_icon) \
    THING(spr_weapon54_INT_icon) \
    THING(spr_weapon55_A9_icon) \
    THING(spr_weapon56_AB_icon) \
    THING(spr_weapon57_RPG_icon) \
    THING(spr_weapon58_ACR_icon) \
    THING(spr_weapon59_K98_icon) \
    THING(spr_weapon60_KSG_icon) \
    THING(spr_weapon61_DE_icon) \
    THING(spr_weapon94_DE_icon) \
    THING(spr_weapon62_MC_icon) \
    THING(spr_weapon63_G18_icon) \
    THING(spr_weapon64_HLP_icon) \
    THING(spr_weapon65_UMP_icon) \
    THING(spr_weapon66_ANH_icon) \
    THING(spr_weapon69_SR_icon) \
    THING(spr_weapon67_SUP_icon) \
    THING(spr_weapon68_YL_icon) \
    THING(spr_weapon69_STY_icon) \
    THING(spr_weapon70_LEV_icon) \
    THING(spr_weapon71_IMP_icon) \
    THING(spr_weapon72_GAT_icon) \
    THING(spr_weapon73_LC_icon) \
    THING(spr_weapon74_AKS_icon) \
    THING(spr_weapon75_K95_icon) \
    THING(spr_weapon76_UMP_icon) \
    THING(spr_weapon77_LEV_icon) \
    THING(spr_weapon78_GL_icon) \
    THING(spr_weapon78_GL_icon2) \
    THING(spr_weapon79_RS_icon) \
    THING(spr_weapon80_AR15_icon) \
    THING(spr_weapon81_A5C_icon) \
    THING(spr_weapon82_AN94_icon) \
    THING(spr_weapon83_P90_icon) \
    THING(spr_weapon_COPYIMG) \
    THING(spr_weapon85_LG_icon) \
    THING(spr_weapon84_Tec_icon) \
    THING(spr_weapon87_M14_icon) \
    THING(spr_weapon86_M16_icon) \
    THING(spr_weapon88_STG_icon) \
    THING(spr_weapon89_SC_icon) \
    THING(spr_weapon90_M163_icon) \
    THING(spr_weapon91_M14T_icon) \
    THING(spr_weapon92_FMG_icon) \
    THING(spr_weapon93_m75_icon) \
    THING(spr_weapon94_DE2_icon) \
    THING(spr_weapon95_PSG_icon) \
    THING(spr_weapon96_QBZ_icon) \
    THING(spr_weapon97_T89_icon) \
    THING(spr_weapon98_K7_icon) \
    THING(spr_weapontype_assault) \
    THING(spr_weapontype_launcher) \
    THING(spr_weapontype_handgun) \
    THING(spr_weapontype_marksman) \
    THING(spr_weapontype_special) \
    THING(spr_weapontype_smg) \
    THING(spr_weapontype_shotgun) \
    THING(spr_weapontype_lmg) \
    THING(spr_bullet_jammed) \
    THING(spr_bullet_srp_1) \
    THING(spr_bullet_srp_2) \
    THING(spr_bullet_srp_3) \
    THING(spr_bullet_srp_poison) \
    THING(spr_bullet_srp_yl) \
    THING(spr_bullet_473_sc) \
    THING(spr_bullet_473_alt) \
    THING(spr_bullet_12g_buck) \
    THING(spr_bullet_12g_flech) \
    THING(spr_bullet_12g_bird) \
    THING(spr_bullet_12g_slug) \
    THING(spr_bullet_12g_flak) \
    THING(spr_bullet_12g_bolt) \
    THING(spr_bullet_88_sc) \
    THING(spr_bullet_88_cata) \
    THING(spr_bullet_88_toxic) \
    THING(spr_bullet_88_ap) \
    THING(spr_bullet_88_sp) \
    THING(spr_bullet_88_sub) \
    THING(spr_bullet_556_sc) \
    THING(spr_bullet_556_toxic) \
    THING(spr_bullet_556_hp) \
    THING(spr_bullet_556_sp) \
    THING(spr_bullet_556_sab) \
    THING(spr_bullet_9mm_sc) \
    THING(spr_bullet_9mm_sp) \
    THING(spr_bullet_9mm_hp) \
    THING(spr_bullet_9mm_ap) \
    THING(spr_bullet_9mm_sub) \
    THING(spr_bullet_rocket_crazy) \
    THING(spr_bullet_rocket_direct) \
    THING(spr_bullet_rocket_homing) \
    THING(spr_bullet_rocket_target) \
    THING(spr_bullet_40_bounce) \
    THING(spr_bullet_40_impact) \
    THING(spr_bullet_40_rubber) \
    THING(spr_bullet_coil1) \
    THING(spr_bullet_coil2) \
    THING(spr_bullet_nail_sc) \
    THING(spr_bullet_nail_bleed) \
    THING(spr_bullet_arrow_sc) \
    THING(spr_bullet_arrow_shock) \
    THING(spr_bullet_arrow_poison) \
    THING(spr_bullet_plasma) \
    THING(spr_bullet_laser_1) \
    THING(spr_bullet_laser_2) \
    THING(spr_bullet_laser_3) \
    THING(spr_bullet_laser_sg) \
    THING(spr_bullet_laser_sg_fire) \
    THING(spr_bullet_ion) \
    THING(spr_bullet_chainltn) \
    THING(spr_bullet_fusion) \
    THING(spr_bullet_fusion_slow) \
    THING(spr_bullet_flame0) \
    THING(spr_upgrade_ammo_sc) \
    THING(spr_upgrade_ammo_sp) \
    THING(spr_bullet_12g_dragon) \
    THING(spr_bullet_railgun) \
    THING(spr_bullet_saw) \
    THING(spr_bullet_trail_sharp) \
    THING(spr_bullet_trail) \
    THING(spr_bullet_trail1) \
    THING(spr_bullet_trail_inv) \
    THING(spr_bullet_arrow) \
    THING(spr_bullet_arrow_acid) \
    THING(spr_bullet_arrow_stun) \
    THING(spr_bullet_vierling) \
    THING(spr_bullet_vierling2) \
    THING(spr_bullet_laser_red) \
    THING(spr_rocket_homing) \
    THING(Spr_Bullet) \
    THING(Spr_Bullet1) \
    THING(spr_bullet_asg1) \
    THING(spr_bullet_asg2) \
    THING(spr_bullet_cl1) \
    THING(spr_bullet_ocw1) \
    THING(spr_bullet_kunai) \
    THING(spr_bullet_shuriken1) \
    THING(spr_bullet_shuriken2) \
    THING(spr_bullet_fanknives) \
    THING(spr_bullet_flyingknife) \
    THING(spr_enm_defaultbullet) \
    THING(spr_turret_grenade) \
    THING(spr_grenade_40mm) \
    THING(spr_grenade_40mm2) \
    THING(spr_grenade_40mm3) \
    THING(spr_bullet_grenade_sticky) \
    THING(spr_bullet_sawblade) \
    THING(spr_bullet_sawblade_huge) \
    THING(spr_bullet_taser) \
    THING(spr_bullet_bullethell) \
    THING(spr_enm_sniperbullet) \
    THING(spr_shell_grenade) \
    THING(spr_shell_shotgun) \
    THING(spr_shell_big_3) \
    THING(spr_shell_big_4) \
    THING(spr_shell_med_2) \
    THING(spr_shell_med_3) \
    THING(spr_shell_med_cl) \
    THING(spr_shell_med_cl2) \
    THING(testline) \
    THING(spr_enemy_headshot_parentOLD) \
    THING(spr_enemy_headshot_parent) \
    THING(spr_voicemessage_icon) \
    THING(spr_enemy_ammo) \
    THING(spr_mortarshot) \
    THING(spr_mortarshot_ballistic) \
    THING(spr_mortarshot_small) \
    THING(spr_mortarshot_crystal) \
    THING(spr_enm_skull_back) \
    THING(spr_enm_skull) \
    THING(spr_mortarshot_old) \
    THING(spr_enm_alarmed) \
    THING(spr_enm_enemy) \
    THING(spr_enm_alert) \
    THING(spr_enm_marked) \
    THING(spr_enemytext_left) \
    THING(spr_enemytext_right) \
    THING(spr_rank_1) \
    THING(spr_rank_23d) \
    THING(spr_rank_2) \
    THING(spr_rank_33d) \
    THING(spr_rank_3) \
    THING(spr_rank_3_old) \
    THING(spr_state_icons) \
    THING(spr_enm_overseer) \
    THING(spr_enm_threadedbot_1) \
    THING(spr_enm_threadedbot_des) \
    THING(spr_enm_threadedbot_shotgun) \
    THING(spr_minitank) \
    THING(spr_en__spiderbot_mine) \
    THING(spr_enm_spiderbot_rocket) \
    THING(spr_enm_spiderbot_explo) \
    THING(spr_enm_spiderbot_explo2) \
    THING(spr_enm_spiderbot_explo_des) \
    THING(spr_enm_spiderbot_alarm) \
    THING(spr_enm_spiderbot_alarm2) \
    THING(spr_enm_spiderbot_alarm_des) \
    THING(spr_enm_spiderbot_disco) \
    THING(spr_enm_spiderbot_disco2) \
    THING(spr_enm_spiderbot_anti) \
    THING(spr_enm_spiderbot_anti_attack) \
    THING(spr_torso_worker_high) \
    THING(spr_torso_worker_med) \
    THING(spr_torso_worker_low) \
    THING(spr_torso_elite_sg_high) \
    THING(spr_torso_elite_sg_med) \
    THING(spr_torso_elite_sg_low) \
    THING(spr_torso_elite_low) \
    THING(spr_torso_elite_med) \
    THING(spr_torso_elite_high) \
    THING(spr_torso_chrono_high) \
    THING(spr_torso_chrono_med) \
    THING(spr_torso_chrono_low) \
    THING(spr_torso_psyonic_med) \
    THING(spr_torso_psyonic_high) \
    THING(spr_torso_psyonic_low) \
    THING(spr_torso_sniper_high) \
    THING(spr_torso_sniper_med) \
    THING(spr_torso_sniper_low) \
    THING(spr_hovertank) \
    THING(spr_flak_turret) \
    THING(spr_tank_turret) \
    THING(spr_tank_base) \
    THING(spr_torso_enforcer_high) \
    THING(spr_torso_enforcer_med) \
    THING(spr_torso_enforcer_low) \
    THING(spr_torso_enforcer_ar_high) \
    THING(spr_torso_enforcer_ar_med) \
    THING(spr_torso_enforcer_ar_low) \
    THING(spr_torso_heavymg_high) \
    THING(spr_torso_heavymg_low) \
    THING(spr_torso_heavymg_med) \
    THING(spr_torso_heavyflamer_high) \
    THING(spr_torso_hypertrooper_high) \
    THING(spr_torso_riotshield_high) \
    THING(spr_torso_riotshield_med) \
    THING(spr_glider_railgun) \
    THING(spr_enm_gliderjet) \
    THING(spr_enm_gliderstriker) \
    THING(spr_glider_shotgun) \
    THING(spr_glidergatling) \
    THING(spr_enm_ballbot) \
    THING(spr_enm_ballbot_des) \
    THING(spr_enm_ballbot_attack) \
    THING(spr_ballbot_retract) \
    THING(spr_ballbot_defender) \
    THING(spr_ballbot_offender) \
    THING(spr_ballbot_offender_small) \
    THING(spr_ballbot_suicide) \
    THING(spr_enm_sawbladebot) \
    THING(spr_enm_sawbladebot_v3) \
    THING(spr_ballbot_medic) \
    THING(spr_dummy_spawner) \
    THING(spr_dummy_standard) \
    THING(spr_dummy_shield) \
    THING(spr_drone_missile) \
    THING(spr_drone_mg) \
    THING(spr_drone_beam) \
    THING(spr_drone_shield) \
    THING(spr_drone_engi) \
    THING(spr_drone_sniper) \
    THING(spr_drone_mortar) \
    THING(spr_boss_helicopter) \
    THING(spr_boss_heart) \
    THING(spr_weapon_heliturret) \
    THING(spr_boss_apc) \
    THING(spr_enm_blob) \
    THING(spr_enm_blob_spawner) \
    THING(spr_enm_blob_add) \
    THING(spr_bosscube_body) \
    THING(spr_bosscube_legs) \
    THING(spr_weapon_jetmg) \
    THING(spr_boss2_jet) \
    THING(spr_enm_redguard_high) \
    THING(spr_enm_redguard_med) \
    THING(spr_enm_redguard_low) \
    THING(spr_torso_redguard_shield_high) \
    THING(spr_torso_redguard_shield_med) \
    THING(spr_enm_redguard_plasma_high) \
    THING(spr_enm_redguard_plasma_med) \
    THING(spr_enm_redguard_plasma_low) \
    THING(spr_enm_turret_sniper) \
    THING(spr_enm_turret_sniper_des) \
    THING(spr_enm_turret_grenade) \
    THING(spr_enm_turret_grenade_des) \
    THING(spr_enm_turret_rocket) \
    THING(spr_enm_turret_rocket_des) \
    THING(spr_enm_turret_healing) \
    THING(spr_enm_turret_healing_des) \
    THING(spr_enm_turret_aura_des) \
    THING(spr_enm_turret_mortar) \
    THING(spr_enm_turret_mortar_des) \
    THING(spr_enm_turret_vierling) \
    THING(spr_enm_turret_vierling_des) \
    THING(spr_enm_turret_radar) \
    THING(spr_enm_turret_radar_des) \
    THING(spr_enm_turret_laser) \
    THING(spr_enm_turret_laser_des) \
    THING(spr_sentryturret) \
    THING(spr_sentrysniperturret) \
    THING(spr_minisentry) \
    THING(spr_turret_lightning_off) \
    THING(spr_turret_lightning) \
    THING(spr_enm_slowmissile) \
    THING(spr_enm_humanoid_des) \
    THING(spr_enm_carrierbot) \
    THING(spr_enm_treasureroomba) \
    THING(spr_enm_doomba) \
    THING(spr_enm_vacuumbot) \
    THING(spr_enm_vacuumbot_attack) \
    THING(spr_vacuum_clean) \
    THING(spr_enm_spidertruck) \
    THING(spr_enm_radartruck) \
    THING(spr_enm_crystal) \
    THING(spr_enm_crystalcharge) \
    THING(spr_circlingdrone_antibullet) \
    THING(spr_circlingdrone_supporter) \
    THING(spr_circlingdrone_heal) \
    THING(spr_circlingdrone_laserline) \
    THING(spr_shadow) \
    THING(spr_turret1_destroyed) \
    THING(spr_enm_POI) \
    THING(spr_attachment_0) \
    THING(spr_attachment_1) \
    THING(spr_attachment_2) \
    THING(spr_attachment_3) \
    THING(spr_attachment_4) \
    THING(spr_attachment_5) \
    THING(spr_attachment_6) \
    THING(spr_attachment_7) \
    THING(spr_attachment_8) \
    THING(spr_attachment_9) \
    THING(spr_attachment_10) \
    THING(spr_attachment_11) \
    THING(spr_attachment_12) \
    THING(spr_attachment_13) \
    THING(spr_attachment_14) \
    THING(spr_attachment_15) \
    THING(spr_attachment_impactcpu) \
    THING(spr_attachment_16) \
    THING(spr_attachment_17) \
    THING(spr_attachment_18) \
    THING(spr_attachment_ammoreg) \
    THING(spr_attachment_printer) \
    THING(spr_attachment_angledgrip) \
    THING(spr_attachment_laststraw) \
    THING(spr_attachment_customfit) \
    THING(spr_attachment_hotswawp) \
    THING(spr_attachment_compound) \
    THING(spr_attachment_quickswap) \
    THING(spr_attachment_spreader) \
    THING(spr_attachment_ammotp2) \
    THING(spr_attachment_silverbullet) \
    THING(spr_attachment_wormhole) \
    THING(spr_attachment_cranalcpu) \
    THING(spr_attachment_bolt) \
    THING(spr_attachment_eraser) \
    THING(spr_attachment_lucky) \
    THING(spr_attachment_rifling2) \
    THING(spr_attachment_rifling3) \
    THING(spr_attachment_button) \
    THING(spr_attachment_reducer) \
    THING(spr_upgrademenu_face_back) \
    THING(spr_line_upgrademenu1) \
    THING(spr_line_upgrademenu3) \
    THING(spr_line_upgrademenu2) \
    THING(spr_wepupgrade_arrow) \
    THING(spr_wepupgrade_back_smaller) \
    THING(spr_wepupgrade_back_lock) \
    THING(spr_wepupgrade_border) \
    THING(spr_wepupgrade_circlemove) \
    THING(spr_wepupgrade_back) \
    THING(spr_heatbar_flames) \
    THING(spr_windowsplash_zir) \
    THING(spr_CharacterSplashInterface4) \
    THING(spr_quest_generic) \
    THING(spr_char_talent) \
    THING(spr_exp_anchor) \
    THING(spr_hp_anchor) \
    THING(spr_exp_anchor_hitobx) \
    THING(spr_dodgecooldown) \
    THING(spr_strafecharge) \
    THING(spr_connect_server) \
    THING(spr_connect_direct) \
    THING(spr_server_help) \
    THING(spr_chat_arrow) \
    THING(spr_bullet_ammoswitch) \
    THING(spr_notification_icon) \
    THING(spr_pickup_icon) \
    THING(spr_missionselect_arrow) \
    THING(spr_minimap_grid) \
    THING(spr_curse_star) \
    THING(spr_token_up) \
    THING(spr_token_pow) \
    THING(spr_token_down) \
    THING(spr_blueprint_grid) \
    THING(spr_kill_marker) \
    THING(spr_threshold_arrow) \
    THING(spr_currency_backgroundwhite) \
    THING(spr_arrow_door) \
    THING(spr_movcube) \
    THING(spr_exp_ring) \
    THING(spr_teleporter_icon) \
    THING(spr_enemycounter_back) \
    THING(spr_stat_score) \
    THING(spr_stat_icons) \
    THING(spr_interest_back) \
    THING(spr_enemycounter_skull) \
    THING(spr_credits_sign) \
    THING(spr_displayprompt_border) \
    THING(spr_displayprompt_keycard) \
    THING(spr_item_activeframe) \
    THING(spr_itemstext1) \
    THING(spr_itemstext2) \
    THING(spr_questicon) \
    THING(spr_levelup_cube) \
    THING(spr_levelupframe) \
    THING(spr_expbar_lines) \
    THING(spr_tooltip_intelline) \
    THING(spr_shop_itemamount) \
    THING(spr_icon_keycards) \
    THING(spr_combo_rectangle) \
    THING(spr_currencybar) \
    THING(spr_crate_alert) \
    THING(spr_crate_keycard) \
    THING(spr_crate_lock) \
    THING(spr_lobby_lock) \
    THING(spr_ps4_square) \
    THING(spr_ps4_square_LT) \
    THING(spr_ps4_circle) \
    THING(spr_ps4_triangle) \
    THING(spr_ps4_cross) \
    THING(spr_lobby_ping) \
    THING(spr_arrow_curse) \
    THING(spr_plating_stack) \
    THING(spr_crate_arrow) \
    THING(spr_pausemenu_tile) \
    THING(spr_questionscreen_smallsprite) \
    THING(spr_questionscreen_blinking) \
    THING(spr_help_button1_n) \
    THING(spr_pausemenu_checkmark) \
    THING(spr_pausemenu_checkmark_red) \
    THING(spr_cursor_e) \
    THING(spr_cursor_r) \
    THING(spr_cursor_no) \
    THING(spr_cursor_circleanim) \
    THING(spr_cursor2) \
    THING(spr_cursor1) \
    THING(spr_cursor4) \
    THING(spr_hitconfirm) \
    THING(spr_hitconfirm_bigger2) \
    THING(spr_hitconfirm_bigger) \
    THING(spr_cursor_hitconfirm) \
    THING(spr_cursor_hitconfirm_larger) \
    THING(spr_cursor6) \
    THING(spr_destructible_prop) \
    THING(spr_cursor_circle) \
    THING(spr_cursor1_top) \
    THING(spr_cursor1_bot) \
    THING(spr_cursor1_right) \
    THING(spr_cursor1_left) \
    THING(spr_cursor_new_normal) \
    THING(spr_cursor_new_mouseover) \
    THING(spr_weaponframe_arrow) \
    THING(spr_fireswitch) \
    THING(spr_fireswitch_ammo) \
    THING(spr_wep_upgradeicon) \
    THING(spr_upgradeamount) \
    THING(spr_weaponvariantico) \
    THING(spr_reload_arrow) \
    THING(spr_reloadbar_line) \
    THING(spr_reloadbar_back) \
    THING(spr_reloadbar_backnew) \
    THING(spr_reloadbar_arrow) \
    THING(spr_moving_ammo_S2) \
    THING(spr_moving_ammo_S1) \
    THING(spr_reload_bar) \
    THING(spr_weapon_iconsprite) \
    THING(spr_vignette) \
    THING(spr_blackscreen) \
    THING(spr_ui_glow) \
    THING(spr_ui_glow_left) \
    THING(spr_screenredflash) \
    THING(spr_background_ui1) \
    THING(spr_levelup_backtiled) \
    THING(spr_levelup_backtiled2) \
    THING(spr_screenflash_1) \
    THING(spr_screenstealthflash) \
    THING(spr_vignettelvlup_top) \
    THING(spr_yellowflash) \
    THING(spr_screendarkrarity) \
    THING(spr_scanlines) \
    THING(spr_scanlines2) \
    THING(spr_multihitmarker) \
    THING(spr_multihitmarker6) \
    THING(spr_hp_glow) \
    THING(spr_lensdirt_bot) \
    THING(spr_lensdirt_hp) \
    THING(spr_lensdirt_ammo) \
    THING(spr_vignette_botred) \
    THING(spr_vignette_left) \
    THING(spr_vignette_right) \
    THING(spr_vignette_top) \
    THING(spr_vignette_bot) \
    THING(spr_vignette_top2) \
    THING(spr_tooltip_background) \
    THING(spr_vignette_top_scanlines) \
    THING(spr_vignette_bot_scanlines) \
    THING(spr_item_vig) \
    THING(spr_item_vig_bot) \
    THING(spr_cursor_dot) \
    THING(spr_black) \
    THING(sprite0) \
    THING(spr_light_vignette) \
    THING(spr_skill_back) \
    THING(spr_passive_back) \
    THING(spr_level_cube) \
    THING(spr_armorbar) \
    THING(spr_hpbar_leftend) \
    THING(spr_mouseover_healthbar) \
    THING(spr_terror_lines) \
    THING(spr_terror_lv) \
    THING(spr_terror_lv_6) \
    THING(spr_terror_vignette) \
    THING(spr_terror_0) \
    THING(spr_terror_text) \
    THING(spr_darkbackground) \
    THING(spr_loading_levelicon_heart) \
    THING(spr_loading_levelicon) \
    THING(spr_loading_levelline) \
    THING(spr_skyscraper) \
    THING(spr_pulse_effect) \
    THING(spr_kaida_logo) \
    THING(spr_leavebehind) \
    THING(spr_dead) \
    THING(spr_resources_collected) \
    THING(spr_shrine_tooltip_background) \
    THING(sprite1617) \
    THING(spr_arrow_rectangle) \
    THING(sprite1616) \
    THING(spr_shrine_headliner) \
    THING(spr_shrine_headliner_China) \
    THING(spr_terminal_yesno) \
    THING(spr_terminal_yes) \
    THING(spr_weapon_tooltip_rate) \
    THING(spr_core_tooltip) \
    THING(spr_tooltip_arrow) \
    THING(spr_weapon_tooltip_bar) \
    THING(spr_weapon_tooltip_damage) \
    THING(spr_weapon_tooltip_accuracy) \
    THING(spr_tooltip_icon) \
    THING(spr_tooltip_weapon_line) \
    THING(spr_tooltip_category) \
    THING(spr_tooltip_frame) \
    THING(spr_category_1) \
    THING(spr_breachmarker) \
    THING(spr_doubleexp) \
    THING(spr_missionicons) \
    THING(spr_arena_ads) \
    THING(spr_gamepad_dpad_icon) \
    THING(spr_weaponshop_decal) \
    THING(spr_weaponshop_decal2) \
    THING(spr_wavebar) \
    THING(spr_crystal_counter) \
    THING(spr_arena_ads_large) \
    THING(spr_platform_console) \
    THING(spr_platform_pc) \
    THING(spr_platform_ps4) \
    THING(spr_platform_switch) \
    THING(spr_platform_xbox) \
    THING(spr_rarityicons_start) \
    THING(spr_rarityicons_arrow) \
    THING(spr_currency_battery) \
    THING(spr_currency_chip) \
    THING(spr_currency_credits) \
    THING(spr_currency_keycard) \
    THING(spr_currency_kit) \
    THING(spr_currency_transistor) \
    THING(spr_currency_upgradekit) \
    THING(spr_currency_data) \
    THING(spr_frame_bosshpbar) \
    THING(spr_frame_notification) \
    THING(spr_tooltip) \
    THING(spr_control) \
    THING(spr_control_allgame) \
    THING(spr_null) \
    THING(spr_control_outgame) \
    THING(spr_bindings) \
    THING(spr_stats) \
    THING(spr_weaponstats) \
    THING(spr_itemstats) \
    THING(spr_color) \
    THING(spr_console) \
    THING(spr_ingame) \
    THING(spr_enmy) \
    THING(spr_surface) \
    THING(spr_surface_fog) \
    THING(spr_surface_light) \
    THING(spr_allitems) \
    THING(spr_room) \
    THING(spr_parent) \
    THING(spr_effect) \
    THING(spr_loading) \
    THING(spr_ui) \
    THING(spr_uimain) \
    THING(spr_bot) \
    THING(spr_left) \
    THING(spr_top) \
    THING(spr_right) \
    THING(spr_light) \
    THING(spr_light2) \
    THING(spr_spawn) \
    THING(spr_spawn_point_small) \
    THING(spr_spawn_point_medium) \
    THING(spr_spawn_point_big) \
    THING(spr_spawn_point_alarm) \
    THING(spr_spawn2) \
    THING(spr_spawn3) \
    THING(spr_spawn4) \
    THING(spr_spawn5) \
    THING(spr_spawn6) \
    THING(spr_marker) \
    THING(spr_specialobject_small) \
    THING(spr_cursor) \
    THING(spr_analytics) \
    THING(spr_icon_push) \
    THING(spr_icon_glow) \
    THING(spr_item_glowinside) \
    THING(spr_item_prompt_border) \
    THING(spr_item_prompt_border_arrow) \
    THING(spr_item_prompt_border_arrowtip) \
    THING(spr_item_prompt_passive) \
    THING(spr_icon_glowfull) \
    THING(spr_item_foreground) \
    THING(spr_item_empty) \
    THING(spr_item_iconsize) \
    THING(spr_c4_button) \
    THING(spr_item_delete) \
    THING(spr_item1_n) \
    THING(spr_icon_slot) \
    THING(spr_item_laststand) \
    THING(spr_item_construct) \
    THING(spr_item_livingbomb) \
    THING(spr_stickybomb) \
    THING(spr_minelaser) \
    THING(spr_minestun) \
    THING(spr_minepoison) \
    THING(spr_item_mindcontrol) \
    THING(spr_item_gundrone) \
    THING(spr_item2_n) \
    THING(spr_item_hyper) \
    THING(spr_item3_n) \
    THING(spr_item_crate) \
    THING(spr_item_crate_cb) \
    THING(spr_shieldsteal) \
    THING(spr_item_shieldburst) \
    THING(spr_item4_n) \
    THING(spr_item_teleporter) \
    THING(spr_item5_n) \
    THING(spr_item_tanto) \
    THING(spr_item_flare) \
    THING(spr_item_roadflare) \
    THING(spr_item6_n) \
    THING(spr_item7_n) \
    THING(spr_item_vialchaos) \
    THING(spr_cellreplacer) \
    THING(spr_lifesapper) \
    THING(spr_item8_n) \
    THING(spr_item9_n) \
    THING(spr_item11_n) \
    THING(spr_item12_n) \
    THING(spr_item13_n) \
    THING(spr_item_boots) \
    THING(spr_beartrap) \
    THING(spr_item_rosarius) \
    THING(spr_item_ring) \
    THING(spr_item_crystal) \
    THING(spr_item_crystal2) \
    THING(spr_item_crystal3) \
    THING(spr_item_sawblade) \
    THING(spr_item_dice) \
    THING(spr_item14_n) \
    THING(spr_item16_n) \
    THING(spr_item15_n) \
    THING(spr_item17_n) \
    THING(spr_item18_n) \
    THING(spr_item19_n) \
    THING(spr_item20_n) \
    THING(spr_item_colibri) \
    THING(spr_item_akira) \
    THING(spr_item_lightningorb) \
    THING(spr_item_fireorb) \
    THING(spr_item_ironorb) \
    THING(spr_item_21) \
    THING(spr_item_bouncer) \
    THING(spr_item_powershot) \
    THING(spr_item_reactivea) \
    THING(spr_item_facemelter) \
    THING(spr_item_pwrswitcher) \
    THING(spr_item_berserk) \
    THING(spr_item_heart) \
    THING(spr_item_battery) \
    THING(spr_item_beamblue) \
    THING(spr_item_beam_purple) \
    THING(spr_item_beam_red) \
    THING(spr_item_battery2) \
    THING(spr_item_incubus) \
    THING(spr_item_bloodrite) \
    THING(spr_item_ammoregen) \
    THING(spr_item_tube) \
    THING(spr_item_meth) \
    THING(spr_item_amphetamine) \
    THING(spr_item_stats) \
    THING(spr_item_perkkit) \
    THING(spr_item_perkcore) \
    THING(spr_item_tsunami) \
    THING(spr_item_droneanti) \
    THING(spr_item_uranium) \
    THING(spr_item_missile1) \
    THING(spr_item_missile2) \
    THING(spr_item_seeker) \
    THING(spr_item_turret1) \
    THING(spr_item_turret2) \
    THING(spr_item_turret3) \
    THING(spr_item_grenade_stun) \
    THING(spr_item_bloodthirst) \
    THING(spr_item_glass) \
    THING(spr_item_chip) \
    THING(spr_item_grenade_flash) \
    THING(spr_item_grenade_he) \
    THING(spr_item_grenade_smoke) \
    THING(spr_item_grenade_toxic) \
    THING(spr_item_grenade_frag) \
    THING(spr_item_slowfield) \
    THING(spr_item_glasses) \
    THING(spr_item_c4) \
    THING(spr_item_railgun_full) \
    THING(spr_item_railgun_emptry) \
    THING(spr_item_dronecircle) \
    THING(spr_item_droneheal) \
    THING(spr_item_aircom) \
    THING(spr_item_bullets) \
    THING(spr_item_mgl) \
    THING(spr_item_masterkey) \
    THING(spr_item_flechette) \
    THING(spr_item_kunai) \
    THING(spr_item_shuriken) \
    THING(spr_item_shurikenred) \
    THING(spr_item_fanknives) \
    THING(spr_item_flyingknife) \
    THING(spr_item_fireaura) \
    THING(spr_item_dagger) \
    THING(spr_item_bolt) \
    THING(spr_item_taser) \
    THING(spr_item_com2) \
    THING(spr_item_gliderjet) \
    THING(spr_item_spawner) \
    THING(spr_item_bloodbolt) \
    THING(spr_item_aimbot) \
    THING(spr_item_exp_popup) \
    THING(spr_item_exp_popup2) \
    THING(spr_item_exp_popup3) \
    THING(spr_item_lvup_text) \
    THING(spr_litem_vup_arrow) \
    THING(spr_decal_laststand) \
    THING(spr_mysteryitem) \
    THING(spr_madness) \
    THING(spr_madness1) \
    THING(spr_hyperadrenaline) \
    THING(spr_tactical) \
    THING(spr_mysteryboost) \
    THING(spr_perkboost) \
    THING(spr_shop_reroll) \
    THING(spr_shop_levelup) \
    THING(spr_shop_prestige) \
    THING(spr_prestige_icon) \
    THING(spr_prestige_icon_disabled) \
    THING(spr_prestige_icon_challenge) \
    THING(spr_prestige_icon_challenge_anim) \
    THING(spr_shop_none) \
    THING(spr_levelup_data) \
    THING(spr_aura_saw) \
    THING(spr_aura_cog) \
    THING(spr_aura_spike) \
    THING(spr_skill_button_back) \
    THING(spr_mat_background) \
    THING(spr_mat_processor) \
    THING(spr_mat_transistor) \
    THING(spr_mat_titanium) \
    THING(spr_mat_conductor) \
    THING(spr_mat_pvc) \
    THING(spr_mat_rubber) \
    THING(spr_mat_battery) \
    THING(spr_mat_fiberglass) \
    THING(spr_item_detonator) \
    THING(spr_item_battlecry) \
    THING(spr_item_airhorn) \
    THING(spr_item_breachingcharge) \
    THING(spr_item_brawndo) \
    THING(spr_item_eclipse) \
    THING(spr_pillsolo) \
    THING(spr_item_toolbox) \
    THING(spr_reloader2) \
    THING(spr_item_heatsink) \
    THING(spr_item_madnessbutton) \
    THING(spr_item_heatspreader) \
    THING(spr_item_magicmag) \
    THING(spr_item_decoy) \
    THING(spr_item_decoyshield) \
    THING(spr_item_gps) \
    THING(spr_item_goldnugget) \
    THING(spr_item_detector) \
    THING(spr_item_upgradekit2) \
    THING(spr_item_tomahawk) \
    THING(spr_item_powerpack) \
    THING(spr_item_madnesssystem) \
    THING(spr_item_ammopack2) \
    THING(spr_item_hardcover) \
    THING(spr_item_targetlaser) \
    THING(spr_item_missiledrone) \
    THING(spr_item_spidermine) \
    THING(spr_tt_power_glow) \
    THING(spr_perk_hebullets) \
    THING(spr_icon_dev) \
    THING(spr_item_riotshield) \
    THING(spr_item_dynamite) \
    THING(spr_item_command) \
    THING(spr_item_bandana) \
    THING(spr_item_sidearm) \
    THING(spr_item_link) \
    THING(spr_underbarrelchip) \
    THING(spr_orbitalrelay) \
    THING(spr_shieldlink) \
    THING(spr_trappersteleporter) \
    THING(spr_missilecontrol) \
    THING(spr_item_shaker) \
    THING(spr_item_elementalresonance) \
    THING(spr_item_firewater) \
    THING(spr_item_nitroclycerine) \
    THING(spr_item_fusionorb) \
    THING(spr_item_armageddonshard) \
    THING(spr_item_lasercaster) \
    THING(spr_item_itemlink) \
    THING(spr_item_psycloud) \
    THING(spr_item_firegrenade) \
    THING(spr_ejection_anim) \
    THING(spr_reload_anim) \
    THING(spr_item_minisentry) \
    THING(sprite2365) \
    THING(spr_mystery_daily) \
    THING(spr_building_iconframe) \
    THING(spr_mars_ironore) \
    THING(spr_weapon_1) \
    THING(spr_c4) \
    THING(spr_c4_breach) \
    THING(spr_dynamite) \
    THING(spr_pickup_outgame) \
    THING(spr_pickup_medikit) \
    THING(sprite1633) \
    THING(spr_pickup_keycard) \
    THING(spr_pickup_artefact) \
    THING(spr_pickup_crystal) \
    THING(spr_pickup_ammo) \
    THING(spr_ammo_pack) \
    THING(spr_ammopack2) \
    THING(spr_pickup_goldammo) \
    THING(spr_pickup_upgrade) \
    THING(spr_pickup_vial) \
    THING(spr_pickup_battery) \
    THING(spr_pickup_bolt) \
    THING(spr_pickup_upgradetool) \
    THING(spr_pickup_transistor) \
    THING(spr_pickup_weppart) \
    THING(spr_pickup_spirit) \
    THING(spr_pickup_shield) \
    THING(spr_pickup_dmg) \
    THING(spr_pickup_ammoreg) \
    THING(spr_pickup_speedbost) \
    THING(spr_pickup_doubleexp) \
    THING(spr_pickup_ring) \
    THING(spr_pickup_chip) \
    THING(spr_pickup_scrap) \
    THING(spr_pickup_heartcore) \
    THING(spr_pickup_perkkit) \
    THING(spr_pickup_credits) \
    THING(spr_pickup_data) \
    THING(spr_pickup_dogtag) \
    THING(spr_pickup_weapon) \
    THING(spr_pickup_ammobox_shadow) \
    THING(spr_item_cover) \
    THING(spr_wall_conc_vertcenter) \
    THING(spr_wall_fold_vertcenter) \
    THING(spr_wall_spike_vertcenter) \
    THING(spr_wall_electro_vertcenter) \
    THING(spr_wall_fence_vertcenter) \
    THING(spr_wall_conc_verttop) \
    THING(spr_wall_electro_verttop) \
    THING(spr_wall_fold_verttop) \
    THING(spr_wall_fence_verttop) \
    THING(spr_wall_spike_verttop) \
    THING(spr_wall_conc_bot) \
    THING(spr_wall_spike_bot) \
    THING(spr_wall_electro_bot) \
    THING(spr_wall_fence_bot) \
    THING(spr_wall_fold_bot) \
    THING(spr_wall_conc_hor) \
    THING(spr_wall_electro_hor) \
    THING(spr_wall_fold_hor) \
    THING(sprite1837) \
    THING(spr_wall_fence_hor) \
    THING(spr_wall_leftend) \
    THING(spr_wall_rightend) \
    THING(spr_wall_spike_hor) \
    THING(spr_wall_door_hor) \
    THING(spr_wall_barrier_hor) \
    THING(spr_wall_barrier_vert) \
    THING(spr_wall_fat1) \
    THING(spr_wall_fat2) \
    THING(spr_door_hearthack) \
    THING(spr_wall_heliBoss) \
    THING(spr_walls_bottom) \
    THING(spr_walls_bottomS) \
    THING(spr_disco_n) \
    THING(spr_walls_ao) \
    THING(spr_disco_m) \
    THING(spr_dark) \
    THING(spr_A) \
    THING(spr_B) \
    THING(spr_C) \
    THING(spr_D) \
    THING(spr_E) \
    THING(spr_F) \
    THING(spr_G) \
    THING(spr_1) \
    THING(spr_2) \
    THING(spr_3) \
    THING(spr_4) \
    THING(spr_5) \
    THING(spr_6) \
    THING(spr_RAND) \
    THING(spr_blockout_floor1) \
    THING(spr_specialcodewarning) \
    THING(spr_blockout_floor2) \
    THING(spr_concrete_decal) \
    THING(spr_conc_pillar_leftend) \
    THING(spr_conc_pillar_center_B) \
    THING(spr_conc_pillar_center_A) \
    THING(spr_conc_pillar_single) \
    THING(spr_conc_pyramid) \
    THING(spr_conc_tankbarrier) \
    THING(spr_conc_milestone) \
    THING(spr_conc_cube) \
    THING(spr_conc_rect_hor) \
    THING(spr_conc_rect_vert) \
    THING(spr_conc_barrier_hor) \
    THING(spr_conc_barrier_vert) \
    THING(spr_conc_wall_hor) \
    THING(spr_minecart_vertical) \
    THING(spr_upgrade_station) \
    THING(spr_shrine_classitem) \
    THING(spr_shrine_classweapon) \
    THING(spr_shrine_supply) \
    THING(spr_shrine_itemup) \
    THING(spr_shrine_god2) \
    THING(spr_shrine) \
    THING(spr_shrine_offline) \
    THING(spr_ammostation) \
    THING(spr_powerstation) \
    THING(spr_destroystation) \
    THING(spr_destroystation_hack) \
    THING(spr_destroystation_hack_destroyed) \
    THING(spr_hackstation) \
    THING(spr_hackstation_heart) \
    THING(spr_c4station) \
    THING(spr_constructor) \
    THING(spr_powerstation_off) \
    THING(spr_shrine_god) \
    THING(spr_pipes_valve) \
    THING(spr_station_button) \
    THING(spr_buffstation) \
    THING(spr_tower_aura) \
    THING(spr_tower_alarm) \
    THING(spr_tower_radarpole) \
    THING(spr_tower_soulcatcher) \
    THING(spr_tower_soulcatcher_electro) \
    THING(spr_conveyorbelt) \
    THING(spr_movingwall_hor) \
    THING(spr_movingwall_pillar_hor) \
    THING(spr_movingwall_pillar_ver) \
    THING(spr_movingwall_metal_hor) \
    THING(spr_movingwall_metal_vert) \
    THING(spr_trap_mine_antishield) \
    THING(spr_trap_mine_laserspike) \
    THING(spr_trap_mine_acid) \
    THING(spr_trap_mine_stun) \
    THING(spr_trap_mine_des) \
    THING(spr_trap_laserwire) \
    THING(spr_trap_spike_0) \
    THING(spr_trap_spike_1) \
    THING(spr_trap_spike_2) \
    THING(spr_trap_chainmine) \
    THING(spr_trap_barbedwire) \
    THING(spr_trap_barbedwire_vert) \
    THING(spr_trap_beartrap) \
    THING(spr_trap_firespewer) \
    THING(spr_trap_slow) \
    THING(spr_trap_mine) \
    THING(spr_trap_minelayer) \
    THING(spr_weaponshop_arena) \
    THING(spr_shrine_alchemy) \
    THING(spr_spawner_smallprop) \
    THING(spr_barrel_A) \
    THING(spr_barrel_B) \
    THING(spr_barrel_C) \
    THING(spr_barrel_gas) \
    THING(spr_barrel_oil_A) \
    THING(spr_barrel_oil_B) \
    THING(spr_barrel_electric) \
    THING(spr_barrel_explosive) \
    THING(spr_barrel_poison) \
    THING(spr_metal_decal) \
    THING(spr_barrel_special_destroyed) \
    THING(spr_barrel_normal_destroyed) \
    THING(spr_barrel_oil_destroyed) \
    THING(spr_barrel_gaz_destroyed) \
    THING(spr_treadmill_picker_holder) \
    THING(spr_treadmill) \
    THING(spr_treadmill_picker) \
    THING(spr_crate_ammo) \
    THING(spr_crate_medi) \
    THING(spr_crate_item_wood) \
    THING(spr_crate_item_metal_key) \
    THING(spr_crate_item_metal) \
    THING(spr_crate_item_timed) \
    THING(spr_crate_item_cursed) \
    THING(spr_crate_upgrade) \
    THING(spr_crate_wepupgrade) \
    THING(spr_crate_goldensmall) \
    THING(spr_crate_currency) \
    THING(spr_crate_mystery) \
    THING(spr_crate_artefact) \
    THING(spr_crate_ammounlock) \
    THING(spr_crate_classperk) \
    THING(spr_crate_weapon_wood) \
    THING(spr_crate_weapon_metal) \
    THING(spr_crate_weapon_metal_key) \
    THING(spr_crate_weapon_timed) \
    THING(spr_crate_weapon_cursed) \
    THING(spr_crate_weapon_challenge) \
    THING(spr_crate_boss) \
    THING(spr_crate_radio) \
    THING(spr_chunkedge_grid_top) \
    THING(spr_chunkedge_grid_right) \
    THING(spr_chunkedge_carrier) \
    THING(spr_trashcontainer_horizontal) \
    THING(spr_tcarrier_big) \
    THING(spr_trashcontainer_vertical) \
    THING(spr_cogwheel_big) \
    THING(spr_ventilation_big) \
    THING(spr_groundmachine_A) \
    THING(spr_barrier1_vert) \
    THING(spr_barrier1_hor) \
    THING(spr_stack_crate_small) \
    THING(spr_stack_crate_big) \
    THING(spr_tcarrierstack_big_hor) \
    THING(spr_plywoodstack) \
    THING(spr_carriercables_hor) \
    THING(spr_carrierpipes_hor) \
    THING(spr_rectpipe_stackhor) \
    THING(spr_tcarrierstack_big_vert) \
    THING(spr_cablestack) \
    THING(spr_plasticpipe_stack) \
    THING(spr_rectpipe_stack2) \
    THING(spr_rectpipe_stack) \
    THING(spr_pipelow_leftend) \
    THING(spr_pipelow_rightend) \
    THING(spr_pipelow_center) \
    THING(spr_pipelow_botend) \
    THING(spr_pipelow_vertcenter) \
    THING(spr_pipelow_topend) \
    THING(spr_pipeshigh_leftend) \
    THING(spr_pipeshigh_center) \
    THING(spr_pipeshigh_rightend) \
    THING(spr_container_horizontal_f1) \
    THING(spr_container_vertical_f1) \
    THING(spr_cylinder_f1) \
    THING(spr_containeroil_vert) \
    THING(spr_containeroil) \
    THING(spr_oilconv_low) \
    THING(spr_pipes_stack_low) \
    THING(spr_pipes_stack_high) \
    THING(spr_ventilation_floor1_moveB) \
    THING(spr_ventilation_floor1) \
    THING(spr_ventilation_floor1_moveA) \
    THING(spr_concpipestack) \
    THING(spr_oiltank_high) \
    THING(spr_oiltank_low) \
    THING(spr_oiltank_ball) \
    THING(spr_oiltank_long) \
    THING(spr_oiltank_long_hor) \
    THING(spr_generator_copper) \
    THING(spr_pipes_stack_big) \
    THING(spr_turbines2_big) \
    THING(spr_turbines_big) \
    THING(spr_oiltank_pipes) \
    THING(spr_container_hor_elec) \
    THING(spr_container_ver_elec) \
    THING(spr_cylinder_electro) \
    THING(spr_generatoralu_cube) \
    THING(spr_generatoralu_cube2) \
    THING(spr_generatoralu_cube3) \
    THING(spr_generatoralu_cube4) \
    THING(spr_generatoralu_high) \
    THING(spr_generatoralu_long_vert) \
    THING(spr_generator_transformator) \
    THING(spr_electroblock) \
    THING(spr_stackelectro_ver) \
    THING(spr_stackelectro_hor) \
    THING(spr_generatoralu_tube) \
    THING(spr_electrohouse_vert) \
    THING(spr_electrohouse_hor) \
    THING(spr_ground_vrm) \
    THING(spr_ground_electrotrap) \
    THING(spr_generatoralu_long) \
    THING(spr_generatorbattery) \
    THING(spr_bindercage_cable) \
    THING(spr_containerelectro_ver) \
    THING(spr_containerelectro) \
    THING(spr_soultower) \
    THING(spr_soulgenerator) \
    THING(spr_tower_prisma) \
    THING(spr_cylinder_f2_A) \
    THING(spr_cylinder_f2_B) \
    THING(spr_container_hor_F2) \
    THING(spr_container_ver_F2) \
    THING(spr_trainingcontainer_hor) \
    THING(spr_trainingcontainer_ver) \
    THING(spr_sandbags_vert) \
    THING(spr_sandbags_vert_small) \
    THING(spr_sandbags_hor) \
    THING(spr_sandbags_circle_top) \
    THING(spr_sandbags_circle_bot) \
    THING(spr_crawlpipe) \
    THING(spr_tirejump) \
    THING(spr_tirestack_medium) \
    THING(spr_tirestack_low) \
    THING(spr_clothbox) \
    THING(spr_euro_sandbags) \
    THING(spr_climbwall) \
    THING(spr_conctext_02) \
    THING(spr_sculpt_quad) \
    THING(spr_climbblock_vert) \
    THING(spr_radar_cube) \
    THING(spr_sculpt_quad_cover) \
    THING(spr_sculpt_quad_low) \
    THING(spr_sculpt_rect) \
    THING(spr_conc_tent) \
    THING(spr_conc_tent_hor) \
    THING(spr_conc_tank_vert) \
    THING(spr_conc_tank_hor) \
    THING(spr_conc_btr_vert) \
    THING(spr_backconc) \
    THING(spr_conc_btr_hor) \
    THING(spr_house_a0) \
    THING(spr_house_a1) \
    THING(spr_crystal_rect) \
    THING(spr_crystal_decal) \
    THING(spr_crystal_pyramid) \
    THING(spr_crystal_milestone45) \
    THING(spr_crystal_milestone) \
    THING(spr_crystal_cube) \
    THING(spr_crystal_rect_vert) \
    THING(spr_crystal_teleporter) \
    THING(spr_crystal_smallwall) \
    THING(spr_crystal_bigwall) \
    THING(spr_marker_crystal_beam) \
    THING(spr_marker_crystal_mortar) \
    THING(spr_crystalmortar) \
    THING(spr_crystal_turret_beam) \
    THING(spr_crystal_turret_beam_attack) \
    THING(spr_crystal_generator) \
    THING(spr_crystal_lamp) \
    THING(spr_crystal_pillarspike_medium) \
    THING(spr_crystal_pillarspike_big) \
    THING(spr_crystal_groundstones) \
    THING(spr_crystal_solopillar_low) \
    THING(spr_crystal_solopillar_med) \
    THING(spr_crystal_generatorline) \
    THING(spr_crystal_milestonespire) \
    THING(spr_crystal_spire_small) \
    THING(spr_crystal_spire_big) \
    THING(spr_crystal_floating_medium) \
    THING(spr_crystal_floating_big) \
    THING(spr_crystal_turret_mortar) \
    THING(spr_crystal_milestone_medium) \
    THING(spr_crystal_milestone_big) \
    THING(spr_crystal_big) \
    THING(spr_crytal_low) \
    THING(spr_crystal_med) \
    THING(spr_crystal_aura) \
    THING(spr_cylinder_rocket) \
    THING(spr_rocketfuel_hor) \
    THING(spr_rocketfuel_ver) \
    THING(spr_tankshell) \
    THING(spr_rocketstack_big_ver0) \
    THING(spr_rocketstack_big_ver1) \
    THING(spr_rocketstack_big_ver2) \
    THING(spr_rocketcover_hor0) \
    THING(spr_rocketstack_big_hor0) \
    THING(spr_rocketstack_big_hor1) \
    THING(spr_rocketstack_big_hor2) \
    THING(spr_rocketstack_big_hor3) \
    THING(spr_cogwheel_A) \
    THING(spr_militarycrate_hor) \
    THING(spr_militarycrate_vert) \
    THING(spr_militarycrate_cube) \
    THING(spr_container_verticalsmall_f4) \
    THING(spr_container_vertical_f4) \
    THING(spr_container_horizontal_f4) \
    THING(spr_container_horizontal_f5) \
    THING(spr_tubestack) \
    THING(spr_tankshellblock) \
    THING(spr_shellcylinder2) \
    THING(spr_rockettubestack) \
    THING(spr_rocketstack_small) \
    THING(spr_rocketstack) \
    THING(spr_tower_missile0) \
    THING(spr_tower_missile1) \
    THING(spr_heart_reactor) \
    THING(spr_heart_electropole) \
    THING(spr_rocketstackred_ver) \
    THING(spr_rocketstackred_hor) \
    THING(spr_missilepartred_ver) \
    THING(spr_missilepartred_hor) \
    THING(spr_heart_core) \
    THING(spr_globe_statue) \
    THING(spr_cylinder_f5) \
    THING(spr_prisma_tower_mars) \
    THING(spr_lightning_tower_mars) \
    THING(spr_zeus_tower_mars) \
    THING(spr_containerrocket_hor) \
    THING(spr_containerrocket_ver) \
    THING(spr_alublock_bigwide) \
    THING(spr_mars_researchlab) \
    THING(spr_mars_research) \
    THING(spr_mars_constructor) \
    THING(spr_mars_landingpod) \
    THING(spr_mars_mechbay) \
    THING(spr_mars_infantrybay) \
    THING(spr_mars_weaponprinter) \
    THING(spr_mars_researchlab_ammo) \
    THING(spr_mars_researchlab_android) \
    THING(spr_ventilation_floor4) \
    THING(spr_cylinder_mars) \
    THING(spr_battery_mars_large) \
    THING(spr_mars_silo) \
    THING(spr_mars_researchbuilding_1) \
    THING(spr_mars_researchbuilding_2) \
    THING(spr_mars_researchbuilding_3) \
    THING(spr_mars_researchbuilding_4) \
    THING(spr_mars_researchbuilding_5) \
    THING(spr_mars_solarpanel) \
    THING(spr_mars_storagebig) \
    THING(spr_alublock_big) \
    THING(spr_mars_alublock_storage) \
    THING(spr_mars_alublock_gen) \
    THING(spr_mars_plasmaconverter) \
    THING(spr_mars_alublock_ammo) \
    THING(spr_tower_radar) \
    THING(spr_mars_radar) \
    THING(spr_alublock_round) \
    THING(spr_mars_extractor) \
    THING(spr_mars_plasmagen) \
    THING(spr_tower_aura_mars) \
    THING(spr_tower_alarm_mars) \
    THING(spr_tower_soulcatcher_mars) \
    THING(spr_container_vertical_f5) \
    THING(spr_container_small_f5) \
    THING(spr_stack_crate_missile) \
    THING(spr_cylinder_silo) \
    THING(spr_missilesilo_big) \
    THING(spr_missilesilo_quad) \
    THING(spr_missilepart_high) \
    THING(spr_missilepart_low) \
    THING(spr_doublemissilestack) \
    THING(spr_missilelarge_vert) \
    THING(spr_missilecurve) \
    THING(spr_missilepod_large) \
    THING(spr_cylinder_f6) \
    THING(spr_containertransistor_ver) \
    THING(spr_containertransistor_hor) \
    THING(spr_transistor_cylinder) \
    THING(spr_transistor_bigs) \
    THING(spr_transistor_big) \
    THING(spr_transistor_tub) \
    THING(spr_transistor_stack) \
    THING(spr_transistor_6tube) \
    THING(spr_transistor_heatsink_huge) \
    THING(spr_transistor_dualtower) \
    THING(spr_transistor_heatsink_cube) \
    THING(spr_transistor_heatsink_small) \
    THING(spr_transistor_heatsink_tiny) \
    THING(spr_transistor_batteries) \
    THING(spr_transistor_12tube) \
    THING(spr_transistor_transformator) \
    THING(spr_spawner_crate) \
    THING(spr_woodcrate_normal_destroyed) \
    THING(spr_woodcrate_small_A) \
    THING(spr_woodcrate_small_B) \
    THING(spr_woodcrate_small_C) \
    THING(spr_woodcrate_big_verticalA) \
    THING(spr_woodcrate_big_verticalB) \
    THING(spr_woodcrate_big_vertical_destroyed) \
    THING(spr_woodcrate_big_horizontalA) \
    THING(spr_woodcrate_big_horizontalB) \
    THING(spr_woodcrate_big_horizontal_destroyed) \
    THING(spr_woodcrate_decal_large) \
    THING(spr_woodcrate_decal_small) \
    THING(spr_woodcrate_small) \
    THING(spr_woodcrate_tiny) \
    THING(spr_PropsBlock) \
    THING(spr_railing_end_vert_top) \
    THING(spr_railing_end_vert_top_S) \
    THING(spr_railing_end_vert_bot) \
    THING(spr_railing_end_vert_bot_S) \
    THING(spr_railing_end_top_L) \
    THING(spr_railing_end_top_L_S) \
    THING(spr_railing_end_top_R) \
    THING(spr_railing_end_top_R_S) \
    THING(spr_railing_end_bot_L) \
    THING(spr_railing_end_bot_L_S) \
    THING(spr_railing_end_bot_R) \
    THING(spr_railing_end_bot_R_S) \
    THING(spr_railing_left) \
    THING(spr_railing_left_S) \
    THING(spr_railing_right) \
    THING(spr_railing_right_S) \
    THING(spr_railing_bot) \
    THING(spr_railing_bot_S) \
    THING(spr_railing_top) \
    THING(spr_railing_top_S) \
    THING(spr_railing_topright) \
    THING(spr_railing_topright_S) \
    THING(spr_railing_topleft) \
    THING(spr_railing_topleft_S) \
    THING(spr_railing_botleft) \
    THING(spr_railing_botleft_S) \
    THING(spr_railing_botright) \
    THING(spr_railing_botright_S) \
    THING(spr_railing_inner_botleft) \
    THING(spr_railing_inner_botleft_S) \
    THING(spr_railling_inner_botright) \
    THING(spr_railing_inner_botright_S) \
    THING(spr_railing_inner_topright) \
    THING(spr_railing_inner_topright_S) \
    THING(spr_railing_inner_topleft) \
    THING(spr_railing_inner_topleft_S) \
    THING(spr_perk_moveframe) \
    THING(spr_perk_moveframe2) \
    THING(spr_perk_moveframe3) \
    THING(spr_buff_moveframe) \
    THING(spr_perk_moveframe_stop) \
    THING(spr_buff_backcircle) \
    THING(spr_perk_backframe) \
    THING(spr_perk_backframe_pure) \
    THING(spr_buff_statboosts) \
    THING(spr_buff_statboost_plus) \
    THING(spr_buff_chip) \
    THING(spr_buff_diamond) \
    THING(spr_buff_backcircle_anim) \
    THING(spr_buff_poison) \
    THING(spr_buff_bleeding) \
    THING(spr_buff_movespeed) \
    THING(spr_buff_movespeeddown) \
    THING(spr_buff_shield) \
    THING(spr_buff_plating) \
    THING(spr_buff_critchance) \
    THING(spr_buff_critchance_old) \
    THING(spr_buff_shieldreg) \
    THING(spr_buff_incdamage) \
    THING(spr_effect_armor) \
    THING(spr_buff_enmdmgresi) \
    THING(spr_buff_spreadcontrol) \
    THING(spr_buff_reloadspeed) \
    THING(spr_buff_headshot) \
    THING(spr_buff_headshot_skull) \
    THING(spr_effect_pickup) \
    THING(spr_efffect_credits) \
    THING(spr_effect_explosion) \
    THING(spr_buff_stun) \
    THING(spr_ammo_sleep) \
    THING(spr_buff_dodge) \
    THING(spr_buff_burning) \
    THING(spr_ammo_napalm) \
    THING(spr_debuff_curse0) \
    THING(spr_effect_curse) \
    THING(spr_effect_star) \
    THING(spr_effect_modular) \
    THING(spr_effect_attachment) \
    THING(spr_effect_accuracy) \
    THING(spr_effect_heat) \
    THING(spr_effect_laser) \
    THING(spr_effect_healthreg) \
    THING(spr_effect_healing) \
    THING(spr_stat_healing) \
    THING(spr_stat_healthreg) \
    THING(spr_stat_shield) \
    THING(spr_stat_shieldreg) \
    THING(spr_stat_armor) \
    THING(spr_stat_movespeed) \
    THING(spr_stat_luck) \
    THING(spr_stat_pickup) \
    THING(spr_stat_credits) \
    THING(spr_stat_ammogain) \
    THING(spr_stat_ammounlock) \
    THING(spr_stat_critchance) \
    THING(spr_stat_dodge) \
    THING(spr_effect_movespeed) \
    THING(spr_effect_critical) \
    THING(spr_effect_ammo) \
    THING(spr_effect_recycle) \
    THING(spr_effect_penetrationsrp) \
    THING(spr_effect_distance) \
    THING(spr_weapon_ModFoundSpr) \
    THING(spr_effect_noscope) \
    THING(spr_effect_shield) \
    THING(spr_effect_elite) \
    THING(spr_effect_firerate) \
    THING(spr_effect_ammogain) \
    THING(spr_effect_ammoloss) \
    THING(spr_effect_random) \
    THING(spr_effect_bounce) \
    THING(spr_effect_slowdown) \
    THING(spr_effect_overdrive) \
    THING(spr_effect_circle) \
    THING(spr_effect_credits) \
    THING(spr_effect_headshot) \
    THING(spr_effect_raute) \
    THING(spr_effect_info) \
    THING(spr_effect_info2) \
    THING(spr_sleep_icon) \
    THING(spr_mindcontrol_icon) \
    THING(spr_disorient_icon) \
    THING(spr_supporter_swords) \
    THING(spr_supporter_swords2) \
    THING(spr_supporter_arenaupgrade) \
    THING(spr_resource_plasma) \
    THING(spr_resource_energy) \
    THING(spr_resource_credits) \
    THING(spr_arrow_popup) \
    THING(spr_damagetext_headshot) \
    THING(spr_damagetext_normal) \
    THING(spr_damage_crit) \
    THING(spr_ammo_none) \
    THING(spr_ammo_antishield) \
    THING(spr_ammo_armorpiercing) \
    THING(spr_ammo_random) \
    THING(spr_ammo_powershot) \
    THING(spr_ammo_damage) \
    THING(spr_ammo_railgun) \
    THING(spr_ammo_bounce) \
    THING(spr_ammo_homing) \
    THING(spr_ammo_followmouse) \
    THING(spr_ammo_critical) \
    THING(spr_ammo_bleeding) \
    THING(spr_ammo_electro) \
    THING(spr_ammo_poison) \
    THING(spr_ammo_slug) \
    THING(spr_ammo_quad) \
    THING(spr_ammo_sawblade) \
    THING(spr_ammo_double) \
    THING(spr_ammo_bolt) \
    THING(spr_ammo_birdshot) \
    THING(spr_ammo_dumbfire) \
    THING(spr_ammo_stun) \
    THING(spr_ammo_fire) \
    THING(spr_ammo_dragonsbreath) \
    THING(spr_ammo_slow) \
    THING(spr_ammo_infusion) \
    THING(spr_ammo_hypersonic) \
    THING(spr_ammo_laserfire) \
    THING(spr_type_explosive) \
    THING(spr_type_fire) \
    THING(spr_type_fusion) \
    THING(spr_type_ion) \
    THING(spr_type_laser) \
    THING(spr_type_plasma) \
    THING(spr_type_shocklightning) \
    THING(spr_type_psyonic) \
    THING(spr_type_shrapnel) \
    THING(spr_type_physical) \
    THING(spr_type_physical_ap) \
    THING(spr_type_physical_antimaterial) \
    THING(spr_ammo_laser) \
    THING(spr_decal_bullet_metal) \
    THING(spr_decal_bullet_metal_medium) \
    THING(spr_decal_bullet_metal_big) \
    THING(spr_debris_anim_metal1) \
    THING(spr_particle_randomized) \
    THING(spr_debris_anim_metal2) \
    THING(spr_debris_anim_metal3) \
    THING(spr_debris_anim_hugechunks) \
    THING(spr_debris_anim_hugechunks2) \
    THING(spr_debris_anim_hugechunks3) \
    THING(spr_debris_anim_wood) \
    THING(spr_debris_anim_wood2) \
    THING(spr_debris_anim_concrete) \
    THING(spr_debris_oil) \
    THING(spr_blood_1) \
    THING(spr_blood_pool) \
    THING(spr_debris) \
    THING(spr_blood_splats) \
    THING(spr_blood_splats1) \
    THING(spr_impactparticles_blood1) \
    THING(spr_blood_splashes) \
    THING(spr_laser_line) \
    THING(spr_light_alarm) \
    THING(spr_glow_shell) \
    THING(spr_fog) \
    THING(spr_toxicblob) \
    THING(spr_smoke_big) \
    THING(spr_smoke_explo) \
    THING(spr_smoke_firing) \
    THING(spr_explo_decal) \
    THING(spr_ao_rect) \
    THING(spr_ao_big) \
    THING(spr_ao_small) \
    THING(spr_ring_thin) \
    THING(spr_explo_stun) \
    THING(spr_glow_plasma) \
    THING(spr_glow_laser) \
    THING(spr_glow_laser_sharp) \
    THING(spr_glow_laserlight) \
    THING(spr_drone_flashlight) \
    THING(spr_flash_hit1) \
    THING(spr_flash_hit2) \
    THING(spr_flash_hit3) \
    THING(spr_flash_hit4) \
    THING(spr_flash_hit5) \
    THING(spr_drone_flashlight2) \
    THING(spr_glow_trans_ggx) \
    THING(spr_glow_lines) \
    THING(spr_glow_star) \
    THING(spr_glow_trans) \
    THING(spr_glow_swirl) \
    THING(spr_glow_ring_sharp) \
    THING(spr_glow_ring_sharp1) \
    THING(spr_glow_ring_mortarshot) \
    THING(spr_glow_ring_soft) \
    THING(spr_glow_ring_spiky) \
    THING(spr_glow_ring_splash) \
    THING(spr_glow_rect) \
    THING(spr_glow_shield_ring) \
    THING(spr_laserspike_bot) \
    THING(spr_laserspike_top) \
    THING(spr_glow1) \
    THING(spr_glow_hor_wide) \
    THING(spr_glow_hor_center) \
    THING(spr_lensflare) \
    THING(spr_tanto_swing) \
    THING(spr_dagger_swing) \
    THING(spr_dagger_swing2) \
    THING(spr_shieldburst_circle) \
    THING(spr_ring_ammogain) \
    THING(spr_healing_circle) \
    THING(spr_slowfield_circle) \
    THING(spr_battlecry_center) \
    THING(spr_battlecry_sparks) \
    THING(spr_battlecry_center2) \
    THING(spr_boss_slowfield) \
    THING(spr_healing_particle) \
    THING(spr_impactparticle_spark3) \
    THING(spr_impactparticle_white) \
    THING(spr_impactparticle_spark_bounce) \
    THING(spr_impactparticle_spark) \
    THING(spr_muzzle_flash1) \
    THING(spr_muzzleflash_laser) \
    THING(spr_muzzleflash_laser2) \
    THING(spr_muzzleflash_sparks) \
    THING(spr_muzzleflashparticles) \
    THING(spr_impact_decal_glow) \
    THING(spr_drip) \
    THING(spr_drip1) \
    THING(spr_wind_swipe) \
    THING(spr_pool) \
    THING(spr_status_slow) \
    THING(spr_status_stun) \
    THING(spr_fire_tiny) \
    THING(spr_sprinkles) \
    THING(spr_explo_anim) \
    THING(spr_explo_anim2) \
    THING(spr_explo_anim3) \
    THING(spr_smoke_anim) \
    THING(spr_explo_anim_small1) \
    THING(spr_explo_anim_tiny) \
    THING(spr_smoke_anim_rocket) \
    THING(spr_lightning_impact) \
    THING(spr_lightning_impact_soft) \
    THING(spr_lightning_strike) \
    THING(spr_lightning_strike_stun) \
    THING(spr_ripper_line) \
    THING(spr_fangs_effect) \
    THING(spr_sparkimpact_anim) \
    THING(spr_flamethrower_anim) \
    THING(spr_chain_lightning_thin) \
    THING(spr_chain_beam) \
    THING(spr_orb_lightning) \
    THING(spr_orb_prestige) \
    THING(spr_orb_fire) \
    THING(spr_orb_wind) \
    THING(spr_orb_iron) \
    THING(spr_voidzone_heart) \
    THING(spr_explosion_crystal) \
    THING(spr_chain_lightning) \
    THING(spr_shield_effect) \
    THING(spr_shield_gone_effect) \
    THING(spr_explosion_akira) \
    THING(spr_explo_simple) \
    THING(spr_explo_sphere) \
    THING(spr_explosion_red) \
    THING(spr_explosion_plasma) \
    THING(spr_splat_impact2) \
    THING(spr_splat_impact3) \
    THING(spr_splat_impact) \
    THING(spr_sprinkles0) \
    THING(spr_sprinkles1) \
    THING(spr_spark_explosion_2) \
    THING(spr_spark_explosion_1) \
    THING(spr_spark_explosion_3) \
    THING(spr_spark_explosion_4) \
    THING(spr_spark_explosion_5) \
    THING(spr_impact_spark_cracker_6) \
    THING(spr_impact_spark_cracker_7) \
    THING(spr_impact_spark_cracker_8) \
    THING(spr_impact_spark_cracker_9) \
    THING(spr_impact_spark_cracker_10) \
    THING(spr_impact_spark_cracker_13) \
    THING(spr_impact_spark_normal) \
    THING(spr_impact_spark_large) \
    THING(spr_impact_dust) \
    THING(spr_noise_anim) \
    THING(spr_bullettrail_curved) \
    THING(sprite1933) \
    THING(spr_upgradecircle) \
    THING(spr_soul) \
    THING(spr_bulletglow) \
    THING(spr_chain_beam2) \
    THING(spr_portal_effect) \
    THING(spr_portal_effect2) \
    THING(spr_wave_effect) \
    THING(spr_wave_effect2) \
    THING(spr_explosion_plasma_ball) \
    THING(spr_tooltipframe_1) \
    THING(spr_settings_mm) \
    THING(spr_research_mm) \
    THING(spr_settings_close) \
    THING(spr_settings_main) \
    THING(spr_settings_key_a_controller) \
    THING(spr_settings_key_a) \
    THING(spr_settings_key_b_controller) \
    THING(spr_settings_key_b) \
    THING(spr_settings_help) \
    THING(spr_lock_mm) \
    THING(spr_earth_mm) \
    THING(spr_weaponmenu_mm) \
    THING(spr_itemmenu_mm) \
    THING(spr_difficulty_mm) \
    THING(spr_difficulty_mm2) \
    THING(spr_community_mm) \
    THING(spr_mm_classesswitch) \
    THING(spr_difficulty0) \
    THING(spr_download) \
    THING(spr_mm_curseicons) \
    THING(spr_difficulty_slider) \
    THING(spr_lobby_corner) \
    THING(spr_research_button) \
    THING(spr_lobby_loadoutback) \
    THING(spr_demo_lock) \
    THING(spr_lobby_back) \
    THING(spr_lobby_kick) \
    THING(spr_lobby_ready) \
    THING(spr_lobby_ready_solo) \
    THING(spr_lobby_ready_solo_CN) \
    THING(sprite1175) \
    THING(spr_earth) \
    THING(spr_online_tab) \
    THING(spr_item_arrowupanddown) \
    THING(spr_item_empower) \
    THING(spr_item_arrowdown) \
    THING(spr_item_empowerempty) \
    THING(spr_levelpoint) \
    THING(spr_item_arrowup) \
    THING(spr_mm_arrowwobble) \
    THING(spr_mm_crlv_icons) \
    THING(spr_mm_crlv_icons1) \
    THING(spr_mm_crlv_circle) \
    THING(spr_research_box) \
    THING(spr_core_circle) \
    THING(spr_stats_popup_icon) \
    THING(spr_checkmark_ready) \
    THING(spr_mm_stats_icon) \
    THING(spr_mm_modifiericons) \
    THING(spr_mm_researchicons) \
    THING(spr_lock_icon) \
    THING(spr_lock_icon1) \
    THING(spr_mm_settings_arrow) \
    THING(spr_itch) \
    THING(spr_ideas) \
    THING(spr_twitter) \
    THING(spr_voting) \
    THING(spr_discord) \
    THING(spr_reddit) \
    THING(spr_head_android) \
    THING(spr_head_zir) \
    THING(spr_head_spider) \
    THING(spr_mm_threadmill_extractor) \
    THING(spr_mm_threadmilll_end) \
    THING(spr_mm_threadmill) \
    THING(spr_mm_treadmill_start) \
    THING(spr_radio_button_true) \
    THING(spr_help) \
    THING(spr_bigbrother) \
    THING(spr_settings_icons) \
    THING(spr_radio_button_background) \
    THING(spr_wepoverlay) \
    THING(spr_mission_mm) \
    THING(spr_mm_missionscreens) \
    THING(spr_mm_missionlight) \
    THING(spr_deathstatistics_back) \
    THING(spr_cinematic_earth) \
    THING(spr_cinematic_computer) \
    THING(spr_cinematic_city_1) \
    THING(spr_cinematic_city_2) \
    THING(spr_cinematic_cpulimit) \
    THING(spr_cinematic_war) \
    THING(spr_cinematic_headquarters) \
    THING(spr_cinematic_labor) \
    THING(spr_cinematic_head) \
    THING(spr_cinematic_destroy) \
    THING(spr_cinematic_armageddon) \
    THING(spr_cinematic_city_3) \
    THING(spr_demolegion) \
    THING(spr_head_jet) \
    THING(spr_head_tank) \
    THING(spr_flag_english) \
    THING(spr_flag_german) \
    THING(spr_flag_spanish) \
    THING(spr_flag_french) \
    THING(spr_flag_russian) \
    THING(spr_flag_korean) \
    THING(spr_flag_chinese) \
    THING(spr_flag_brazilian) \
    THING(spr_flag_polish) \
    THING(spr_flag_italian) \
    THING(spr_flag_japanese) \
    THING(spr_menu_topbar) \
    THING(spr_playerframe_back) \
    THING(spr_coretext) \
    THING(spr_weapontext) \
    THING(spr_machinetext_long) \
    THING(spr_wall_top) \
    THING(spr_wall_test) \
    THING(spr_ground_pattern) \
    THING(spr_ground_variation) \
    THING(spr_ground_plates) \
    THING(spr_ground_crystal) \
    THING(spr_pattern_floor2) \
    THING(spr_pattern_lines) \
    THING(spr_pattern_isles) \
    THING(spr_pattern_isles3) \
    THING(spr_pattern_isles2) \
    THING(spr_pattern_technoise) \
    THING(spr_pattern_swirl) \
    THING(spr_pattern_inka) \
    THING(spr_pattern_crystal) \
    THING(spr_pattern_dollar) \
    THING(spr_pattern_diagonal) \
    THING(spr_pattern_checker) \
    THING(spr_pattern_oil) \
    THING(spr_pattern_plates) \
    THING(spr_pattern_camosmall) \
    THING(spr_pattern_sweden) \
    THING(spr_pattern_circuit) \
    THING(spr_pattern_water) \
    THING(spr_pattern_crazy) \
    THING(spr_pattern_angle) \
    THING(spr_building_grid) \
    THING(spr_room_bridge) \
    THING(spr_room_bridge_TypeB) \
    THING(spr_room_bridge_TypeA) \
    THING(spr_room_bridge_rng) \
    THING(spr_roomspawn) \
    THING(spr_room_64) \
    THING(spr_room_64_pivot_mid) \
    THING(spr_room_256) \
    THING(spr_force_surface) \
    THING(spr_superspecial) \
    THING(spr_nowall_extra) \
    THING(spr_nowall_big) \
    THING(spr_nowall_medium) \
    THING(spr_nowall_small) \
    THING(spr_wall_big) \
    THING(spr_wall_medium) \
    THING(spr_wall_small) \
    THING(spr_pathing_allowed) \
    THING(spr_special_2x2) \
    THING(scr_shrines_2x2) \
    THING(spr_special_3x3) \
    THING(spr_path_horizontal) \
    THING(spr_path_vertical) \
    THING(spr_path_left_bot) \
    THING(spr_path_bot_right) \
    THING(spr_path_right_top) \
    THING(spr_path_top_left) \
    THING(spr_field_1x1) \
    THING(spr_field_1x2) \
    THING(spr_field_1x3) \
    THING(spr_field_2x1) \
    THING(spr_field_2x2) \
    THING(spr_field_2x3) \
    THING(spr_field_3x1) \
    THING(spr_field_3x2) \
    THING(spr_field_3x3) \
    THING(spr_field_3x4) \
    THING(spr_field_4x3) \
    THING(spr_field_4x4) \
    THING(spr_field_pillar) \
    THING(spr_field_god_shrine) \
    THING(spr_field_forcePath) \
    THING(spr_field_forceInvisiblePath) \
    THING(spr_field_forceDummyPath) \
    THING(spr_field_teleporter) \
    THING(spr_field_special) \
    THING(spr_field_forceField) \
    THING(spr_field_godField) \
    THING(spr_field_forceSpecial) \
    THING(spr_field_forceShrine) \
    THING(spr_field_forceFree) \
    THING(spr_room_config) \
    THING(spr_enm_budget_plus5) \
    THING(spr_enm_budget_plus10) \
    THING(spr_enm_budget_minus5) \
    THING(spr_enm_budget_minus10) \
    THING(spr_artefact_0) \
    THING(spr_artefact_1) \
    THING(spr_artefact_2) \
    THING(spr_artefact_3) \
    THING(spr_artefact_4) \
    THING(spr_artefact_5) \
    THING(spr_artefact_6) \
    THING(spr_artefact_7) \
    THING(spr_artefact_8) \
    THING(spr_artefact_9) \
    THING(spr_artefact_10) \
    THING(spr_artefact_11) \
    THING(spr_artefact_12) \
    THING(spr_artefact_13) \
    THING(spr_artefact_14) \
    THING(spr_perk_ptl) \
    THING(spr_microchip) \
    THING(spr_perk_auto9) \
    THING(spr_perk_pxs) \
    THING(spr_perk_rev) \
    THING(spr_perk_lspistol) \
    THING(spr_perk_hon) \
    THING(spr_perk_startingupgrade) \
    THING(spr_perk_cellreplacement) \
    THING(spr_perk_credits) \
    THING(spr_perk_dodge) \
    THING(spr_perk_movespeed) \
    THING(spr_perk_scavenging) \
    THING(spr_perk_shield) \
    THING(spr_perk_health) \
    THING(spr_perk_shophack) \
    THING(spr_perk_packed) \
    THING(spr_perk_luck) \
    THING(spr_perk_pistol) \
    THING(spr_perk_prepared) \
    THING(spr_perk_NEW) \
    THING(spr_perk_guardian) \
    THING(spr_perk_guardiancore) \
    THING(spr_perk_breachercore) \
    THING(spr_perk_snipercore) \
    THING(spr_perk_assassincore) \
    THING(spr_perk_raidercore) \
    THING(spr_perk_heavygunnercore) \
    THING(spr_perk_engineercore) \
    THING(spr_perk_demolishercore) \
    THING(spr_perk_aegis) \
    THING(spr_perk_shieldoc) \
    THING(spr_perk_critreload) \
    THING(spr_perk_obsession) \
    THING(spr_perk_closer) \
    THING(spr_perk_forgedbyfire) \
    THING(spr_perk_infusion) \
    THING(spr_perk_lifeline) \
    THING(spr_perk_powerbolt) \
    THING(spr_perk_scrap) \
    THING(spr_perk_shotgun1) \
    THING(spr_perk_shotgun2) \
    THING(spr_perk_plating) \
    THING(spr_perk_lowhpregen) \
    THING(spr_perk_warmup) \
    THING(spr_perk_iframe) \
    THING(spr_perk_hframe) \
    THING(spr_perk_return) \
    THING(spr_perk_return2) \
    THING(spr_perk_berserk) \
    THING(spr_perk_fortress) \
    THING(spr_perk_roguecore) \
    THING(spr_perk_rogue) \
    THING(spr_perk_dodgeboost) \
    THING(spr_perk_poisonammo) \
    THING(spr_perk_backstab) \
    THING(spr_perk_shadowdance) \
    THING(spr_perk_mastercard) \
    THING(spr_perk_markdrone) \
    THING(spr_perk_discipline) \
    THING(spr_perk_powerstep) \
    THING(spr_perk_dexterity) \
    THING(spr_perk_perfection) \
    THING(spr_perk_specialized) \
    THING(spr_perk_tuning) \
    THING(spr_perk_headshotammo) \
    THING(spr_perk_steady) \
    THING(spr_perk_switchposition) \
    THING(spr_perk_revenge) \
    THING(spr_perk_stealback) \
    THING(spr_perk_keepcool) \
    THING(spr_perk_holdbreath) \
    THING(spr_perk_standstill) \
    THING(spr_perk_longrange) \
    THING(spr_perk_commando) \
    THING(spr_perk_commandocore) \
    THING(spr_perk_ultrachance) \
    THING(spr_perk_ultrashot) \
    THING(spr_perk_routine) \
    THING(spr_item_wepupgrade) \
    THING(spr_perk_scarred) \
    THING(spr_perk_revised) \
    THING(spr_perk_specammo) \
    THING(spr_perk_bleeding) \
    THING(spr_perk_reloadsurge) \
    THING(spr_perk_packapunch) \
    THING(spr_perk_cover) \
    THING(spr_perk_rations) \
    THING(spr_perk_fortify) \
    THING(spr_perk_edge) \
    THING(spr_perk_combo) \
    THING(spr_perk_heatcontrol) \
    THING(spr_perk_elementalcore) \
    THING(spr_perk_elemental) \
    THING(spr_perk_fine) \
    THING(spr_perk_grenadier) \
    THING(spr_perk_multiply) \
    THING(spr_item_elemental) \
    THING(spr_perk_selfrepair) \
    THING(spr_perk_itemheat) \
    THING(spr_perk_heatvent) \
    THING(spr_perk_craze) \
    THING(spr_perk_transmutate) \
    THING(spr_perk_dodgeheat) \
    THING(spr_perk_heato) \
    THING(spr_perk_battery) \
    THING(spr_perk_focus) \
    THING(spr_perk_contaminate) \
    THING(spr_perk_status) \
    THING(spr_levelclass_back) \
    THING(spr_levelclass_back2) \
    THING(spr_class_stats) \
    THING(spr_perk_back2_round) \
    THING(spr_testmode) \
    THING(spr_perk_back3_round) \
    THING(spr_perk_back3_hex) \
    THING(spr_perk_corners) \
    THING(spr_perk_circlemove) \
    THING(spr_dropdown_arrow) \
    THING(spr_perk_power1) \
    THING(spr_perk_power2) \
    THING(spr_perk_power3) \
    THING(spr_chip_power0) \
    THING(spr_chip_power1) \
    THING(spr_chip_power2) \
    THING(spr_perk_glow_inside) \
    THING(spr_perk_overdriveboni) \
    THING(spr_perk_item_back) \
    THING(spr_perk_item_backfull) \
    THING(spr_perk_item_glow) \
    THING(spr_checkmark) \
    THING(spr_RAM) \
    THING(spr_gods) \
    THING(spr_talent_starting) \
    THING(spr_factions) \
    THING(spr_microchip_reward) \
    THING(spr_talent_perk) \
    THING(spr_talent_stat) \
    THING(spr_talent_slot) \
    THING(spr_talent_item) \
    THING(spr_fullhdchecker) \
    THING(spr_talent_itemss) \
    THING(spr_talent_cross) \
    THING(spr_talent_crossleft) \
    THING(spr_talent_crosstop) \
    THING(spr_talent_crossbot) \
    THING(spr_talent_crossright) \
    THING(spr_talent_curve_botleft) \
    THING(spr_talent_curve_botright) \
    THING(spr_talent_curve_topleft) \
    THING(spr_talent_curve_topright) \
    THING(spr_talent_gabel) \
    THING(spr_talent_hor) \
    THING(spr_talent_vert) \
    THING(spr_talent_weapon) \
    THING(spr_levelmarker) \
    THING(spr_connecter) \
    THING(spr_talent_screendown) \
    THING(spr_talent_screenup) \
    THING(spr_panning_icon) \
    THING(spr_scrolling_icon) \
    THING(spr_scrolling_icon_CN) \
    THING(spr_rankicons) \
    THING(spr_classes) \
    THING(spr_texpage_fx) \
    THING(spr_texpage_allfloors) \
    THING(spr_texpage_mainmenu) \
    THING(spr_tutorial_reload0) \
    THING(spr_tutorial_perfectReload) \
    THING(spr_tutorial_healItem) \
    THING(spr_tutorial_accurateShot) \
    THING(spr_tutorial_inaccurateShot) \
    THING(spr_tutorial_chests) \
    THING(spr_tutorial_chestWeapon) \
    THING(spr_tutorial_chestItem) \
    THING(spr_tutorial_overheat) \
    THING(spr_upvote) \
    THING(spr_variant_timeless) \
    THING(spr_variant_divine) \
    THING(spr_variant_modular) \
    THING(spr_variant_scavenger) \
    THING(spr_variant_ultra) \
    THING(spr_variant_stabilized) \
    THING(spr_variant_print) \
    THING(spr_variant_timed) \
    THING(spr_variant_overclocked) \
    THING(spr_variant_hunter) \
    THING(spr_variant_heavy) \
    THING(spr_variant_prototype) \
    THING(spr_variant_milspec) \
    THING(spr_variant_relic) \
    THING(spr_variant_hyperburst) \
    THING(spr_variant_standard) \
    THING(spr_variant_siege) \
    THING(spr_variant_elite) \
    THING(spr_variant_light) \
    THING(spr_variant_alpha) \
    THING(spr_variant_cursed) \
    THING(spr_variant_burstplus) \
    THING(spr_variant_critical) \
    THING(spr_wavecounter) \
    THING(spr_sawbig_horizontal) \
    THING(spr_sawpillar) \
    THING(spr_directionswitch) \
    THING(spr_fire_big) \
    THING(spr_pro_plus) \
    THING(spr_pro_up) \
    THING(spr_pro) \
    THING(spr_lut_floor1_X) \
    THING(spr_lut_silo) \
    THING(spr_lut_floor1) \
    THING(spr_lut_floor2) \
    THING(spr_lut_floor_old) \
    THING(spr_lut_minimap) \
    THING(spr_lut_red) \
    THING(spr_teleporter) \
    THING(spr_bar1) \
    THING(spr_cursorbar) \
    THING(spr_cursorbar_big) \
    THING(spr_lightemitter_flicker) \
    THING(spr_patchbutton_update) \
    THING(obj_patchbutton_small) \
    THING(spr_patchbutton_home) \
    THING(spr_imgur_up) \
    THING(spr_patchbutton_community) \
    THING(spr_patchbutton_about) \
    THING(spr_patchbutton_planned) \
    THING(IntroScreen) \
    THING(IntroScreenArena) \
    THING(spr_cityscreen_mm) \
    THING(spr_mm_marsback) \
    THING(spr_cityscreen_light) \
    THING(spr_logo_ingame) \
    THING(spr_logo_ingame_mars) \
    THING(spr_logo_flowfire) \
    THING(spr_patchbutton_separator) \
    THING(spr_player1) \
    THING(spr_player2) \
    THING(spr_marker_object) \
    THING(spr_marker_generic) \
    THING(spr_marker_meet) \
    THING(spr_marker_target) \
    THING(spr_marker_radio) \
    THING(spr_marker_target2) \
    THING(spr_marker_detonator) \
    THING(spr_marker_care) \
    THING(spr_marker_help) \
    THING(spr_marker_quest_a) \
    THING(spr_marker_quest_b) \
    THING(spr_Crosshair1) \
    THING(spr_Crosshair2) \
    THING(spr_cross_hit) \
    THING(spr_language_flags) \
    THING(sDissolve1) \
    THING(sDissolve2) \
    THING(sDissolve3) \
    THING(spr_dissolve) \
    THING(sDissolve4) \
    THING(spr_plus_particle) \
    THING(spr_downvote_particle) \
    THING(CitadelLogo) \
    THING(background0) \
    THING(back_walls_lab1) \
    THING(Tileset_Text) \
    THING(back_cables) \
    THING(dusty_bg) \
    THING(halomask_bg) \
    THING(back_ground_stripes_hor) \
    THING(back_ground_stripes_hor5) \
    THING(back_ground_stripes_ver) \
    THING(back_ground_stripes_ver4) \
    THING(back_ground_stripes_ver5) \
    THING(back_ground_lines_ver) \
    THING(back_ground_lines_hor) \
    THING(back_ground_flat_hor) \
    THING(background_ground_dirt) \
    THING(background_ground_dirtsmall) \
    THING(dirtsmall_backup) \
    THING(background_explosion_decal) \
    THING(Tileset_floor1) \
    THING(back_mainmenu) \
    THING(Tileset_Details) \
    THING(back_floor1_pipes_opaque) \
    THING(back_floor1_pipes_trans) \
    THING(back_floor1_pipes) \
    THING(back_floor1_platform) \
    THING(back_border_transistion) \
    THING(Tileset_Details_Electro) \
    THING(Tileset_Details_2) \
    THING(back_floor2_spikes) \
    THING(back_floor2_tech) \
    THING(back_floor2_pipes) \
    THING(back_floor2_platform) \
    THING(background44) \
    THING(back_crystal_dirt) \
    THING(back_floor3_space) \
    THING(back_floor3_platform) \
    THING(back_floor3_grid) \
    THING(Tileset_Details_4) \
    THING(Tileset_Details_41) \
    THING(background43) \
    THING(back_floor4_pipes_opaque) \
    THING(back_floor4_back) \
    THING(back_floor4_pipes) \
    THING(back_floor4_platform) \
    THING(back_marsback) \
    THING(back_floor6_snow) \
    THING(back_floor6_snow_smaller) \
    THING(spr_smoke_firing2) \
    THING(spr_benefits_rank) \
    THING(spr_defense_ground) \
    THING(spr_freelook_eye) \
    THING(spr_headhunt_back) \
    THING(spr_null_0) \
    THING(spr_teleporter_ui) \
    THING(spr_logo_tencent) \
    THING(spr_lab_mainmenu) \
    THING(spr_vignette_hard) \
    THING(spr_camera_intro) \
    THING(spr_effect_curse_dev) \
    THING(spr_placeholder) \
    THING(s9Slice) \
    THING(spr_ability_back) \
    THING(spr_abilityframe_back) \
    THING(spr_heatframe_back) \
    THING(spr_locaintro_loading) \
    THING(spr_weapon_ModMissingSpr) \
    THING(IntroScreenLegion) \
    THING(spr_head_arenamasters) \
    THING(spr_moving_ammo_P2) \
    THING(spr_head_defender) \
    THING(ItemIconsX2Y) \
    THING(spr_logo_legion) \
    THING(CitadelLogo_tileset) \
    THING(back_walls_lab1_tileset) \
    THING(Tileset_Text_tileset) \
    THING(back_cables_tileset) \
    THING(back_ground_stripes_hor_tileset) \
    THING(back_ground_stripes_hor5_tileset) \
    THING(back_ground_stripes_ver_tileset) \
    THING(back_ground_stripes_ver4_tileset) \
    THING(back_ground_lines_ver_tileset) \
    THING(back_ground_lines_hor_tileset) \
    THING(back_ground_flat_hor_tileset) \
    THING(background_ground_dirt_tileset) \
    THING(background_ground_dirtsmall_tileset) \
    THING(dirtsmall_backup_tileset) \
    THING(background_explosion_decal_tileset) \
    THING(back_airport) \
    THING(back_mainmenu_tileset) \
    THING(back_floor1_pipes_tileset) \
    THING(back_floor1_platform_tileset) \
    THING(back_border_transistion_tileset) \
    THING(Tileset_Details_Electro_tileset) \
    THING(Tileset_Details_2_tileset) \
    THING(back_floor2_platform_tileset) \
    THING(background44_tileset) \
    THING(back_crystal_dirt_tileset) \
    THING(back_floor3_platform_tileset) \
    THING(background43_tileset) \
    THING(back_floor4_pipes_tileset) \
    THING(back_floor4_platform_tileset) \
    THING(back_spiderboss) \
    THING(path0) \
    THING(path1) \
    THING(demo_exp_curve) \
    THING(BlurFade) \
