#pragma once

#define SCRIPTS_DO(THING) \
    THING(gml_Script_scr_url_open) \
    THING(gml_Script_scr_mod_ini_read_string) \
    THING(gml_Script_scr_exception_handling) \
    THING(gml_Script_anon__2310) \
    THING(gml_Script_scr_localPlayer_add_screenshake) \
    THING(gml_Script_scr_mod_ini_read_real) \
    THING(gml_Script_scr_modweapon_init) \
    THING(gml_Script_macros) \
    THING(gml_Script_scr_create_bullet) \
    THING(gml_Script_scr_create_bullet_effects) \
    THING(gml_Script_scr_create_bullet_shell) \
    THING(gml_Script_scr_particle_effects_unit) \
    THING(gml_Script_scr_quest_rewards) \
    THING(gml_Script_scr_draw_interacting_bar) \
    THING(gml_Script_scr_chest_select_loottable) \
    THING(gml_Script_scr_chest_loottable_ammo) \
    THING(gml_Script_scr_mystery_reward) \
    THING(gml_Script_scr_chest_loottable_health) \
    THING(gml_Script_scr_shrine_effect_active) \
    THING(gml_Script_scr_display_prompt_tooltip) \
    THING(gml_Script_scr_weapon_descriptions) \
    THING(gml_Script_scr_ammotypes) \
    THING(gml_Script_scr_ammotypes_classbased) \
    THING(gml_Script_scr_roll_ammotype) \
    THING(gml_Script_scr_unlock_ammo) \
    THING(gml_Script_scr_weapon_firing) \
    THING(gml_Script_scr_weapon_init_free) \
    THING(gml_Script_scr_attachments_init) \
    THING(gml_Script_scr_attachments_init_ultimate) \
    THING(gml_Script_scr_attachments_apply) \
    THING(gml_Script_scr_attachments_apply_ultimate) \
    THING(gml_Script_scr_weapon_variants_init) \
    THING(gml_Script_scr_weapon_variants_init_ultimate) \
    THING(gml_Script_scr_weapon_pickup) \
    THING(gml_Script_scr_tooltipbig_weapons_getdata) \
    THING(gml_Script_scr_weapon_tooltipbars) \
    THING(gml_Script_scr_activereload) \
    THING(gml_Script_scr_weapon_drop) \
    THING(gml_Script_scr_player_currency_change) \
    THING(gml_Script_scr_player_data_change) \
    THING(gml_Script_scr_player_labfunds_change) \
    THING(gml_Script_scr_player_exp_change) \
    THING(gml_Script_scr_player_keycard_gain) \
    THING(gml_Script_scr_player_interest_change) \
    THING(gml_Script_scr_player_ammo_gaining) \
    THING(gml_Script_scr_player_health_healing) \
    THING(gml_Script_scr_plating_gaining) \
    THING(gml_Script_scr_microchip_gaining) \
    THING(gml_Script_scr_player_health_damage) \
    THING(gml_Script_scr_chest_loottable) \
    THING(gml_Script_scr_statboost) \
    THING(gml_Script_scr_randomstatboost_gaining) \
    THING(gml_Script_scr_glow_splat_draw) \
    THING(gml_Script_scr_popup) \
    THING(gml_Script_scr_vial_gaining) \
    THING(gml_Script_scr_questlog) \
    THING(gml_Script_scr_is_player_stuck) \
    THING(gml_Script_scr_reset_player) \
    THING(gml_Script_scr_get_interpolated_shifted_player_pos) \
    THING(gml_Script_scr_player_multiplayer_revive) \
    THING(gml_Script_scr_player_set_stealth) \
    THING(gml_Script_scr_badge_display) \
    THING(gml_Script_scr_classcheck) \
    THING(gml_Script_scr_class_sprites) \
    THING(gml_Script_scr_humanoid_attack_movement) \
    THING(gml_Script_scr_humanoid_attack_movement_create) \
    THING(gml_Script_scr_humanoid_movement) \
    THING(gml_Script_scr_basic_unit_defensive_stats_calc) \
    THING(gml_Script_scr_basic_unit_defense_stats) \
    THING(gml_Script_scr_damage_numbers) \
    THING(gml_Script_scr_bloodsplat_large) \
    THING(gml_Script_scr_statuseffects_collision) \
    THING(gml_Script_BallCreate) \
    THING(gml_Script_BallStep) \
    THING(gml_Script_DrawStatesDebug) \
    THING(gml_Script_scr_view_cone) \
    THING(gml_Script_scr_search_audio_at) \
    THING(gml_Script_scr_enm_knockback) \
    THING(gml_Script_scr_getSpawnInSpriteRect) \
    THING(gml_Script_scr_spawn_alarm_squad) \
    THING(gml_Script_scr_dispatch_headhunters) \
    THING(gml_Script_scr_AlertEnemy) \
    THING(gml_Script_scr_setup_patrolling) \
    THING(gml_Script_scr_select_from_spawntable) \
    THING(gml_Script_scr_enemy_ctrl_enforcerCoverPos) \
    THING(gml_Script_scr_enemy_get_closest_fire_pos) \
    THING(gml_Script_scr_enemy_grid_get_cell) \
    THING(gml_Script_scr_enemy_optimize_path) \
    THING(gml_Script_set_enemy_path) \
    THING(gml_Script_scr_enemy_reached_destination) \
    THING(gml_Script_scr_enemy_get_random_position) \
    THING(gml_Script_scr_enemy_stop_moving) \
    THING(gml_Script_scr_enm_base_destructor) \
    THING(gml_Script_scr_is_pos_in_enemy_view) \
    THING(gml_Script_scr_damage_bot) \
    THING(gml_Script_scr_heal_bot) \
    THING(gml_Script_scr_nearest_team_member) \
    THING(gml_Script_scr_get_spawn_pos_on_radius) \
    THING(gml_Script_scr_enm_voiceover) \
    THING(gml_Script_scr_enm_sensor_check) \
    THING(gml_Script_scr_item_descriptions) \
    THING(gml_Script_scr_item_tooltip) \
    THING(gml_Script_scr_raritycolors_init) \
    THING(gml_Script_scr_drop_item) \
    THING(gml_Script_scr_drop_bossLoot) \
    THING(gml_Script_scr_pickup_loottable) \
    THING(gml_Script_scr_item_activeandcooldown) \
    THING(gml_Script_scr_item_leveling) \
    THING(gml_Script_scr_item_variants_allitems_bonus) \
    THING(gml_Script_scr_indentifypotion_effect) \
    THING(gml_Script_scr_item_variants_init) \
    THING(gml_Script_scr_transfer_item_coop) \
    THING(gml_Script_scr_perks_chips) \
    THING(gml_Script_spr_perks_artefacts) \
    THING(gml_Script_scr_class_upgrades) \
    THING(gml_Script_scr_talent_desctiptions) \
    THING(gml_Script_scr_convert_talenttext) \
    THING(gml_Script_scr_curses_init) \
    THING(gml_Script_scr_perk_save) \
    THING(gml_Script_scr_find_talent_id) \
    THING(gml_Script_scr_find_talent_objectindex) \
    THING(gml_Script_scr_talents_new) \
    THING(gml_Script_scr_rebinding_button) \
    THING(gml_Script_scr_esc_video) \
    THING(gml_Script_scr_esc_game) \
    THING(gml_Script_scr_esc_other) \
    THING(gml_Script_scr_esc_help) \
    THING(gml_Script_scr_esc_help2) \
    THING(gml_Script_scr_esc_credits) \
    THING(gml_Script_scr_esc_bindings) \
    THING(gml_Script_scr_esc_bindings_items) \
    THING(gml_Script_scr_esc_language) \
    THING(gml_Script_scr_unlock_descriptions) \
    THING(gml_Script_scr_class_descriptions) \
    THING(gml_Script_scr_check_unlock) \
    THING(gml_Script_scr_color_transistion) \
    THING(gml_Script_scr_talent_selection) \
    THING(gml_Script_scr_get_percentage) \
    THING(gml_Script_scr_remap_valuerange) \
    THING(gml_Script_scr_sort_objList_by_dist) \
    THING(gml_Script_scr_sort_objList_by_depth) \
    THING(gml_Script_scr_distance_sqr) \
    THING(gml_Script_scr_sort_vectList_by_dist) \
    THING(gml_Script_scr_find_vect_in_list) \
    THING(gml_Script_scr_list_contains) \
    THING(gml_Script_scr_list_delete) \
    THING(gml_Script_scr_list_add_unique) \
    THING(gml_Script_scr_is_pos_in_rectangle) \
    THING(gml_Script_scr_object_is_parent) \
    THING(gml_Script_scr_is_parent) \
    THING(gml_Script_scr_find_highest_parent) \
    THING(gml_Script_scr_set_depth) \
    THING(gml_Script_scr_string_trim_whites) \
    THING(gml_Script_scr_localization) \
    THING(gml_Script_scr_instance_nearest) \
    THING(gml_Script_scr_random_gaussian) \
    THING(gml_Script_scr_random_exponential) \
    THING(gml_Script_scr_split_string) \
    THING(gml_Script____struct___0_scr_get_array_for_particle_gml_GlobalScript_scr_get_array_for_particle) \
    THING(gml_Script_scr_get_array_for_particle) \
    THING(gml_Script_scr_range_and_soundcheck) \
    THING(gml_Script_scr_prop_spawn_random) \
    THING(gml_Script_scr_array_choose) \
    THING(gml_Script_scr_object_debug) \
    THING(gml_Script_scr_terrorlevel_increase) \
    THING(gml_Script_scr_draw_pausebackground) \
    THING(gml_Script_scr_prop_shadow_ao_init) \
    THING(gml_Script_tmc_EASE_enums) \
    THING(gml_Script_tmc_ease_lerp) \
    THING(gml_Script_tmc_ease_progress) \
    THING(gml_Script_tmc_ease_start_end) \
    THING(gml_Script_DirtyBloom_define) \
    THING(gml_Script_DirtyBloom_enable) \
    THING(gml_Script_DirtyBloom_disable) \
    THING(gml_Script_DirtyBloom_enabled) \
    THING(gml_Script_DirtyBloom_set_strength) \
    THING(gml_Script_DirtyBloom_ghostsdefine) \
    THING(gml_Script_tmc_vect_to_vect3) \
    THING(gml_Script_tmc_vect_mult) \
    THING(gml_Script_tmc_vect2) \
    THING(gml_Script_tmc_vect3) \
    THING(gml_Script_tmc_vect4) \
    THING(gml_Script_tmc_vect_add) \
    THING(gml_Script_tmc_vect_rev) \
    THING(gml_Script_tmc_vect_scaler) \
    THING(gml_Script_tmc_vect_dot) \
    THING(gml_Script_tmc_vect_cross) \
    THING(gml_Script_tmc_vect_dist) \
    THING(gml_Script_tmc_vect_len) \
    THING(gml_Script_tmc_vect_divr) \
    THING(gml_Script_tmc_vect_perp) \
    THING(gml_Script_tmc_vect_multr) \
    THING(gml_Script_tmc_vect_norm) \
    THING(gml_Script_tmc_vect_to_vect4) \
    THING(gml_Script_tmc_vect_to_vect2) \
    THING(gml_Script_tmc_vect_div) \
    THING(gml_Script_tmc_vect_comp) \
    THING(gml_Script_tmc_vect2_rot) \
    THING(gml_Script_tmc_vect_is_zero) \
    THING(gml_Script_tmc_vect3_sqr) \
    THING(gml_Script_vect) \
    THING(gml_Script_cleanmem_init) \
    THING(gml_Script_cleanmem) \
    THING(gml_Script_cleanmem_get_mem) \
    THING(gml_Script_line_solid_intersection) \
    THING(gml_Script_lines_intersect) \
    THING(gml_Script_draw_rectangle_width) \
    THING(gml_Script_draw_circle_width) \
    THING(gml_Script_avoid_circle) \
    THING(gml_Script_avoid_rectangle) \
    THING(gml_Script_image_scale) \
    THING(gml_Script_draw_reset) \
    THING(gml_Script_draw_magnify) \
    THING(gml_Script_draw_magnify_fast) \
    THING(gml_Script_draw_magnify_ext) \
    THING(gml_Script_draw_magnify_path_circle) \
    THING(gml_Script_draw_magnify_path_simple) \
    THING(gml_Script_draw_magnify_path) \
    THING(gml_Script_draw_magnify_laser) \
    THING(gml_Script_draw_path_gradient) \
    THING(gml_Script_random_color) \
    THING(gml_Script_tolerance) \
    THING(gml_Script_path_random_circle) \
    THING(gml_Script_path_random) \
    THING(gml_Script_create_shockwave) \
    THING(gml_Script_scr_enter_next_floor) \
    THING(gml_Script_scr_colors_borderdecal_finder) \
    THING(gml_Script_scr_find_chunk_surface) \
    THING(gml_Script_scr_draw_decal_on_chunks) \
    THING(gml_Script_scr_is_field_In_rect_list) \
    THING(gml_Script_scr_fit_shape_in_rect_list) \
    THING(gml_Script_scr_spawn_chunk_field) \
    THING(gml_Script_scr_setup_chunk_fields) \
    THING(gml_Script_scr_fieldNodes_getFieldNodesForShape) \
    THING(gml_Script_scr_chunk_isPathConnected) \
    THING(gml_Script_scr_chunk_connect_path) \
    THING(gml_Script_scr_node_A_Star) \
    THING(gml_Script_scr_get_shape_dimensions) \
    THING(gml_Script_scr_chunk_getPathSet) \
    THING(gml_Script_scr_fieldNodes_distance) \
    THING(gml_Script_scr_chunk_helper_sets_connect) \
    THING(gml_Script_scr_fit_shape_in_node_list) \
    THING(gml_Script_scr_spawn_rnd_smallRoom) \
    THING(gml_Script_scr_spawn_rnd_extra) \
    THING(gml_Script_scr_spawn_rnd_smallRoom_noWalls) \
    THING(gml_Script_scr_spawn_room) \
    THING(gml_Script_scr_spawn_rnd_mediumRoom) \
    THING(gml_Script_scr_spawn_rnd_mediumRoom_noWalls) \
    THING(gml_Script_scr_spawn_rnd_bigRoom) \
    THING(gml_Script_scr_spawn_rnd_bigRoom_noWalls) \
    THING(gml_Script_draw_crosshair_quarter) \
    THING(gml_Script_draw_circle_curve) \
    THING(gml_Script_scr_roll_next_room) \
    THING(gml_Script_scr_goto_room) \
    THING(gml_Script_scr_quest_finished) \
    THING(gml_Script_scr_skyscraper_draw) \
    THING(gml_Script_scr_deathrecap) \
    THING(gml_Script_debug) \
    THING(gml_Script_scr_collision_line) \
    THING(gml_Script_scr_is_in_layer) \
    THING(gml_Script_scr_raycast) \
    THING(gml_Script_scr_filter_layer) \
    THING(gml_Script_scr_get_collision_normal_dir) \
    THING(gml_Script_scr_get_collision_rectangle) \
    THING(gml_Script_scr_get_collision_free) \
    THING(gml_Script_scr_invert_layer) \
    THING(gml_Script_scr_get_closest_obj_in_range) \
    THING(gml_Script_scr_grids_add_rectangle) \
    THING(gml_Script_scr_grids_clear_rectangle) \
    THING(gml_Script_scr_grids_add_circle) \
    THING(gml_Script_scr_grids_clear_circle) \
    THING(gml_Script_scr_get_random_pickup_pos) \
    THING(gml_Script_scr_networking_instantiate) \
    THING(gml_Script_scr_networking_instantiate_bullet) \
    THING(gml_Script_scr_networking_destroy) \
    THING(gml_Script_scr_get_inst_for_networkId) \
    THING(gml_Script_scr_send_packet) \
    THING(gml_Script_scr_MS_request_join_lobby) \
    THING(gml_Script_scr_MS_send_packet_queue) \
    THING(gml_Script_scr_send_MS_packet) \
    THING(gml_Script_scr_send_net_rpc) \
    THING(gml_Script____struct___1_scr_shared_networking_event_gml_GlobalScript_scr_shared_networking_event) \
    THING(gml_Script____struct___2_scr_shared_networking_event_gml_GlobalScript_scr_shared_networking_event) \
    THING(gml_Script____struct___3_scr_shared_networking_event_gml_GlobalScript_scr_shared_networking_event) \
    THING(gml_Script____struct___4_scr_shared_networking_event_gml_GlobalScript_scr_shared_networking_event) \
    THING(gml_Script_scr_shared_networking_event) \
    THING(gml_Script_scr_instance_create) \
    THING(gml_Script_scr_new_lobby_notification) \
    THING(gml_Script_scr_encrypt_password) \
    THING(gml_Script_scr_MS_send_Login) \
    THING(gml_Script_scr_MS_send_RequestPasswordReset) \
    THING(gml_Script_scr_MS_send_CreateAccount) \
    THING(gml_Script_scr_MS_send_PasswordReset) \
    THING(gml_Script_scr_MS_reopen_lobby) \
    THING(gml_Script_scr_send_global_chat_message) \
    THING(gml_Script_scr_MS_set_referal) \
    THING(gml_Script_scr_add_chat_entry) \
    THING(gml_Script_scr_send_LobbyUpdate) \
    THING(gml_Script_scr_send_ArenaMissionSelect) \
    THING(gml_Script_scr_networking_instantiateSingle) \
    THING(gml_Script_scr_net_subscribe_newsletter) \
    THING(gml_Script_scr_net_add_statuseffect) \
    THING(gml_Script_scr_net_cleanup_remote) \
    THING(gml_Script_scr_net_write_packet) \
    THING(gml_Script_scr_networking_receiving_server) \
    THING(gml_Script_scr_networking_receiving_client) \
    THING(gml_Script_scr_networking_get_region_name) \
    THING(gml_Script_scr_increase_packetID) \
    THING(gml_Script_scr_random_set_seed) \
    THING(gml_Script_scr_random_get_value) \
    THING(gml_Script_scr_random_irandom) \
    THING(gml_Script_scr_random_random) \
    THING(gml_Script_scr_random_random_range) \
    THING(gml_Script_scr_random_choose) \
    THING(gml_Script_scr_random_shuffle_list) \
    THING(gml_Script_scr_draw_targetlaser) \
    THING(gml_Script_scr_calculate_targetlaser_distance) \
    THING(gml_Script_scr_play_sound_at) \
    THING(gml_Script_scr_antibullet_laser) \
    THING(gml_Script_scr_healing_laser_turret) \
    THING(gml_Script_scr_mp_grid_cast) \
    THING(gml_Script_draw_SHADER_blur) \
    THING(gml_Script_scr_update_particle_pos) \
    THING(gml_Script_scr_bullet_chain_get_hits) \
    THING(gml_Script_scr_enemy_set_stateChanged) \
    THING(gml_Script_scr_mp_get_closest_grid_pos) \
    THING(gml_Script_README) \
    THING(gml_Script_gfx_blur) \
    THING(gml_Script_gfx_blur_directional) \
    THING(gml_Script_gfx_blur_gaussian) \
    THING(gml_Script_gfx_blur_masked) \
    THING(gml_Script_gfx_blur_radial) \
    THING(gml_Script_gfx_blur_twist) \
    THING(gml_Script_curve_get_value) \
    THING(gml_Script_scr_ini_open) \
    THING(gml_Script_scr_file_exists) \
    THING(gml_Script_scr_file_delete) \
    THING(gml_Script_scr_ini_write_string) \
    THING(gml_Script_scr_sound) \
    THING(gml_Script_draw_circular_progress_bar) \
    THING(gml_Script_scr_tooltip) \
    THING(gml_Script_scr_helptext) \
    THING(gml_Script_scr_notification) \
    THING(gml_Script_scr_button) \
    THING(gml_Script_scr_button_intro) \
    THING(gml_Script_scr_slider) \
    THING(gml_Script_scr_button_check) \
    THING(gml_Script_scr_healthbar) \
    THING(gml_Script_scr_DailyReward) \
    THING(gml_Script_scr_mouseover) \
    THING(gml_Script_scr_tween0) \
    THING(gml_Script_scr_list_create) \
    THING(gml_Script_scr_list_destroy) \
    THING(gml_Script_scr_get_input) \
    THING(gml_Script_scr_rebind_input) \
    THING(gml_Script_scr_get_input_name) \
    THING(gml_Script_scr_check_key) \
    THING(gml_Script_scr_check_gamepad_key) \
    THING(gml_Script_scr_gamepad_check_itemBlock) \
    THING(gml_Script_scr_get_gamepad_key_name) \
    THING(gml_Script_scr_get_key_name) \
    THING(gml_Script_scr_load_language) \
    THING(gml_Script_scr_load_language_backup) \
    THING(gml_Script_draw_healthbar_circular) \
    THING(gml_Script_scr_join_team) \
    THING(gml_Script_scr_leave_team) \
    THING(gml_Script_scr_get_other_team) \
    THING(gml_Script_scr_get_team) \
    THING(gml_Script_scr_get_all_teams) \
    THING(gml_Script_colorpicker) \
    THING(gml_Script_scp_set) \
    THING(gml_Script_scr_console_input) \
    THING(gml_Script_DissolveShader) \
    THING(gml_Script_DissolveSettings) \
    THING(gml_Script_action_current_room) \
    THING(gml_Script_action_end_game) \
    THING(gml_Script_action_kill_object) \
    THING(gml_Script_action_next_room) \
    THING(gml_Script_action_restart_game) \
    THING(gml_Script_action_wrap) \
    THING(gml_Script___init_action) \
    THING(gml_Script_background_get_texture) \
    THING(gml_Script_draw_background_tiled) \
    THING(gml_Script___background_get) \
    THING(gml_Script___background_get_colour) \
    THING(gml_Script___background_get_colour_element) \
    THING(gml_Script___background_get_element) \
    THING(gml_Script___background_get_internal) \
    THING(gml_Script___background_set) \
    THING(gml_Script___background_set_colour) \
    THING(gml_Script___background_set_element) \
    THING(gml_Script___background_set_internal) \
    THING(gml_Script___init_background) \
    THING(gml_Script_d3d_set_fog) \
    THING(gml_Script_d3d_transform_add_translation) \
    THING(gml_Script_d3d_transform_set_identity) \
    THING(gml_Script_d3d_transform_set_rotation_z) \
    THING(gml_Script___init_d3d) \
    THING(gml_Script_draw_set_alpha_test) \
    THING(gml_Script_draw_set_blend_mode) \
    THING(gml_Script_draw_set_blend_mode_ext) \
    THING(gml_Script_instance_create) \
    THING(gml_Script_object_get_depth) \
    THING(gml_Script_texture_set_repeat) \
    THING(gml_Script_tile_add) \
    THING(gml_Script_tile_delete) \
    THING(gml_Script_tile_exists) \
    THING(gml_Script_tile_get_background) \
    THING(gml_Script_tile_get_depth) \
    THING(gml_Script_tile_get_height) \
    THING(gml_Script_tile_get_ids) \
    THING(gml_Script_tile_get_left) \
    THING(gml_Script_tile_get_top) \
    THING(gml_Script_tile_get_width) \
    THING(gml_Script_tile_get_x) \
    THING(gml_Script_tile_get_y) \
    THING(gml_Script_tile_layer_find) \
    THING(gml_Script_tile_set_blend) \
    THING(gml_Script___view_get) \
    THING(gml_Script___view_set) \
    THING(gml_Script___view_set_internal) \
    THING(gml_Script___init_view) \
    THING(gml_Script___init_global) \
    THING(gml_Script___global_object_depths) \
    THING(gml_Script_scr_rumble) \
    THING(gml_Script_scr_reset_tokens) \
    THING(gml_Script_scr_powerup) \
    THING(gml_Script_scr_perks_mars) \
    THING(gml_Script_scr_has_supporter_pack) \
    THING(gml_Script_scr_has_supporter_pack2) \
    THING(gml_Script_scr_has_arena_pack) \
    THING(gml_Script_scr_has_synthetik) \
    THING(gml_Script_scr_load_languages_fixed) \
    THING(gml_Script_scr_perk_system) \
    THING(gml_Script_scr_pauseCheck) \
    THING(gml_Script_scr_fightCheck) \
    THING(gml_Script_scr_check_DLCS) \
    THING(gml_Script_scr_KPI_Arena) \
    THING(gml_Script_scr_change_gamemode) \
    THING(gml_Script_scr_load_progress) \
    THING(gml_Script_scr_savegame_ini) \
    THING(gml_Script_scr_progress_ini_save) \
    THING(gml_Script_scr_load_statistics) \
    THING(gml_Script_scr_statistics_ini) \
    THING(gml_Script_scr_statistics_saving) \
    THING(gml_Script_scr_settings_load) \
    THING(gml_Script_scr_settings_ini) \
    THING(gml_Script_scr_settings_ini_save) \
    THING(gml_Script_scr_map_to_string) \
    THING(gml_Script_scr_handle_switch_online) \
    THING(gml_Script_scr_check_achievements) \
    THING(gml_Script_scr_set_Achievement) \
    THING(gml_Script_scr_unlock_outgame_progress) \
    THING(gml_Script_scr_boss_dialogs) \
    THING(gml_Script_scr_ds_grid_get) \
    THING(gml_Script_scr_mp_grid_get_cell) \
    THING(gml_Script_scr_ds_grid_set) \
    THING(gml_Script_scr_ds_grid_set_region) \
    THING(gml_Script_DOCUMENTATION_README) \
    THING(gml_Script_draw_9slice) \
    THING(gml_Script_slice_init) \
    THING(gml_Script_slice_pragma) \
    THING(gml_Script_scr_technologies) \
    THING(gml_Script_scr_prefetch_queue) \
    THING(gml_Script____struct___5_gml_Object_outgame_Create_0) \
    THING(gml_Script____struct___6_gml_Object_obj_enm_base_parent_Create_0) \
    THING(gml_Script____struct___7_gml_Object_obj_moving_entity_PARENT_Other_22) \
    THING(gml_Script____struct___8_gml_Object_obj_moving_entity_PARENT_Other_22)