#ifndef __OBJ_LIST_H__
#define __OBJ_LIST_H__

/* obj_null */
/* outgame */
/* obj_stats */
/* obj_control */
/* obj_allgame */
/* obj_room_ctrl */
/* obj_enemy_ctrl */
/* obj_ingame_ctrl */
/* obj_effect_draw_ground */
/* obj_effect_draw_foreground */
/* obj_effect_draw_flying */
/* obj_net_rpc */
/* obj_loca_button */
/* obj_patchhistory */
/* obj_servermessage */
/* obj_patchpage_parent */
/* obj_patchlog_parent */
/* obj_patchlog_about */
/* obj_patchpage_home */
/* obj_patchlog_planned */
/* obj_patchlog_1 */
/* obj_patchlog_2 */
/* obj_patchlog_currentpatch */
/* obj_separator */
/* obj_patchbutton_parent */
/* obj_patchbutton_about */
/* obj_patchbutton_planned */
/* obj_patchbutton_community */
/* obj_patchbutton_1 */
/* obj_patchbutton_2 */
/* obj_patchbutton_currentpatch */
/* obj_patchbutton_4 */
/* obj_launcher_newsletter */
/* obj_debug_save */
/* obj_perk_parent */
/* obj_buff_talent */
/* obj_perk_healthy */
/* obj_perk_classweapon */
/* obj_perk_killshield */
/* obj_perk_shophack */
/* obj_perk_itemslot */
/* obj_perk_healroom */
/* obj_perk_prepared */
/* obj_perk_credits */
/* obj_perk_luck */
/* obj_perk_scavenging */
/* obj_perk_nimble */
/* obj_perk_none */
/* obj_perk_terrorlevel */
/* obj_artefact_parent */
/* obj_artefact_weaponcarry */
/* obj_artefact_itemupgrade */
/* obj_artefact_ricochet */
/* obj_artefact_terrorlevel */
/* obj_artefact_elemental */
/* obj_artefact_ultradrop */
/* obj_artefact_friendlyfire */
/* obj_artefact_slowdown */
/* obj_artefact_healing */
/* obj_artefact_shop */
/* obj_artefact_crit */
/* obj_artefact_strafe */
/* obj_artefact_powerup */
/* obj_artefact_buff */
/* obj_artefact_pistol */
/* obj_artefact_madness */
/* obj_artefact_mysterybonus */
/* obj_artefact_instagib */
/* obj_artefact_tactical */
/* obj_chip_parent */
/* obj_chip_health */
/* obj_chip_dodge */
/* obj_chip_scavenging */
/* obj_chip_ammogain */
/* obj_chip_luck */
/* obj_chip_credits */
/* obj_chip_armor */
/* obj_chip_shield */
/* obj_chip_heat */
/* obj_chip_movespeed */
/* obj_chip_accuracy */
/* obj_perk_guardian */
/* obj_perk_warmup */
/* obj_perk_iframe */
/* obj_perk_aegis */
/* obj_perk_aegis2 */
/* obj_perk_enrage */
/* obj_perk_heatup */
/* obj_perk_closer */
/* obj_perk_shotgun */
/* obj_perk_shotgunmaster */
/* obj_perk_shieldoc */
/* obj_perk_bloodinfusion */
/* obj_perk_lowhpregen */
/* obj_perk_scraparmor */
/* obj_perk_scavengerbits */
/* obj_perk_lifeline */
/* obj_perk_return */
/* obj_perk_berserk */
/* obj_perk_reloadsurge2 */
/* obj_perk_rogue */
/* object1537 */
/* obj_perk_longrange */
/* obj_perk_ejectsurge */
/* obj_perk_dodgeboost */
/* obj_perk_powertuning */
/* obj_perk_marksman */
/* obj_perk_mastercard */
/* obj_perk_crossbow */
/* obj_perk_backstab */
/* obj_perk_discipline */
/* obj_perk_headshotammo */
/* obj_perk_perfection */
/* obj_perk_specialized */
/* obj_perk_customammo */
/* obj_perk_mindmg */
/* obj_perk_holdbreathold */
/* obj_perk_reactivereload */
/* obj_perk_standstill */
/* obj_perk_stealback */
/* obj_perk_commando */
/* obj_perk_ultrashot */
/* obj_perk_drill */
/* obj_perk_rankup */
/* obj_perk_fieldration */
/* obj_perk_specializedammo */
/* obj_perk_reloadstack */
/* obj_perk_obsession */
/* obj_perk_powerstep */
/* obj_perk_itemcdvariant */
/* obj_perk_killer */
/* obj_perk_stubborn */
/* obj_perk_reloadsurge */
/* obj_perk_fortify */
/* obj_perk_holdbreath */
/* obj_perk_hollowpoint */
/* obj_perk_cover */
/* obj_perk_edge */
/* obj_perk_scarred */
/* obj_perk_combo */
/* obj_perk_elemental */
/* obj_perk_heatcontrol */
/* obj_perk_pistolextender */
/* obj_perk_statusextender */
/* obj_perk_hframe */
/* obj_perk_focus */
/* obj_perk_grenadier */
/* obj_perk_calm */
/* obj_perk_m79 */
/* obj_perk_force */
/* obj_perk_dodgeheat */
/* obj_perk_sunrise */
/* obj_perk_selfrepair */
/* obj_perk_ammoregen */
/* obj_perk_heatrecharge */
/* obj_perk_transmutate */
/* obj_perk_drone1 */
/* obj_perk_elementalpower */
/* obj_perk_morph */
/* obj_perk_cultist */
/* obj_perk_coolhead */
/* obj_perk_steady */
/* obj_perk_healthcrate */
/* obj_perk_barrier */
/* obj_cursor */
/* obj_cursor_camera */
/* obj_cursor_lockon */
/* obj_weapon_mouseover */
/* obj_interest_mouseover */
/* obj_enemyleft_mouseover */
/* obj_passive_mouseover */
/* obj_health_mouseover */
/* obj_buffs_debuffs */
/* obj_buff_statboosts */
/* obj_buff_movespeed */
/* obj_debuff_movespeed */
/* obj_debuff_move_barbed */
/* obj_debuff_maxhealth_curse */
/* obj_debuff_loop */
/* obj_buff_healthreg */
/* obj_buff_firerate */
/* obj_buff_healing */
/* obj_debuff_healing */
/* obj_buff_shield */
/* obj_buff_shieldreg */
/* obj_buff_incdamage */
/* obj_buff_damageresi */
/* obj_buff_instagib */
/* obj_buff_enmdmgresi */
/* obj_buff_timed */
/* obj_buff_dodge */
/* obj_buff_ammoreg */
/* obj_buff_reloadspeed */
/* obj_buff_spreadcontrol */
/* obj_buff_flaregun */
/* obj_buff_smokescreen */
/* obj_buff_critchance */
/* obj_debuff_poison */
/* obj_debuff_bleeding */
/* obj_debuff_burning */
/* obj_debuff_stun */
/* obj_debuff_antishield */
/* obj_buff_speedboost */
/* obj_buff_stimpack */
/* obj_buff_expboost */
/* obj_tooltip_gold */
/* obj_tooltip_hp */
/* obj_delete_newgame */
/* obj_menu_visibility */
/* obj_creditsdisplay */
/* obj_audiovoice */
/* obj_lastkill */
/* obj_hit_circle_marker */
/* obj_levelup */
/* obj_combos */
/* obj_upgrademenu */
/* obj_loadingscreen */
/* obj_splash_screen */
/* obj_control.main_ui */
/* obj_control.main_ui_weapon */
/* obj_selection_menu */
/* obj_selection_menu_perk */
/* obj_selection_menu_artefact */
/* obj_selection_menu_stat */
/* obj_selection_menu_ammo */
/* obj_escapesettings */
/* object1784 */
/* obj_androidconsole */
/* obj_dialog_ui */
/* obj_poison_area */
/* obj_escapescreen */
/* obj_pausemenu */
/* obj_reloading */
/* obj_helpmenu */
/* obj_logmenu */
/* obj_quests */
/* obj_deathstatistics */
/* obj_questlog_slots */
/* obj_questlog_parent */
/* obj_questlog_generic */
/* obj_control.weaponstats */
/* obj_itemstats */
/* obj_statistics */
/* obj_color */
/* obj_bindings */
/* obj_colorpicker */
/* obj_overlays_aboveui */
/* obj_overlays_belowui */
/* obj_kill_marker */
/* obj_terrorlevel */
/* obj_decaldraw */
/* obj_class_upgrade */
/* obj_tooltip_terrorlevel */
/* obj_tooltip */
/* obj_tooltipbig_weapons */
/* obj_tooltipbig */
/* obj_tooltip_damagetext */
/* obj_popup_notice */
/* obj_popup_skillduration */
/* obj_popup_announcement */
/* obj_popup_exp */
/* obj_console */
/* obj_music_track_loop */
/* obj_eula_popup */
/* obj_bigbrother_mode */
/* obj_deathscreenshot */
/* obj_chromaticabberation */
/* obj_surface_light */
/* obj_surface_Fog */
/* obj_blur_surface */
/* obj_blur_draw */
/* obj_blur_background */
/* obj_blur_pregame */
/* obj_blur_slomo */
/* obj_blur_bokeh */
/* DirtyBloom_obj */
/* obj_FogOfWar */
/* obj_LUT_end */
/* obj_LUT_start */
/* obj_player */
/* obj_localPlayer */
/* obj_remotePlayer */
/* obj_turret_spwn */
/* obj_enm_turret_parent */
/* obj_enm_turret_sniper */
/* obj_enm_turret_rocket */
/* obj_enm_turret_vierling */
/* obj_enm_turret_laser */
/* obj_enm_turret_flamer */
/* obj_enm_turret_radar */
/* obj_enm_turret_grenade */
/* obj_enm_turret_aura */
/* obj_enm_turret_healing */
/* obj_enm_turret_point_defense */
/* obj_enm_turret_mortar */
/* obj_enm_crystalturret_mortar */
/* obj_enm_crystalturret_laser */
/* obj_turret_dummie */
/* obj_firingrange_dummy_parent */
/* obj_firingrange_dummy_standard */
/* obj_firingrange_dummy_armored */
/* obj_firingrange_dummy_shield */
/* obj_firingrange_dummy_plating */
/* obj_enm_sentryturret */
/* obj_enm_sentrysniper */
/* obj_enm_custom_parent */
/* obj_boss_parent */
/* obj_enm_bossweapon_parent */
/* obj_enm_BW_jet_mg */
/* obj_enm_BW_heli_turret */
/* obj_deathlocation_boss */
/* obj_conveyorbelt */
/* obj_blockpath */
/* obj_damagezone */
/* obj_boss_intro */
/* obj_boss2_Jet */
/* obj_boss_heart */
/* obj_heart_kill */
/* obj_heart_room_events */
/* obj_quest_hearthack */
/* obj_boss_APC */
/* obj_boss_heartwall1 */
/* obj_boss_fortress */
/* obj_boss_triple_spawn */
/* obj_boss_triple */
/* obj_boss_sam */
/* obj_boss_helicopter */
/* obj_boss_blob_core */
/* obj_boss_blob_add */
/* obj_boss_blob_spawner */
/* obj_boss_spider */
/* obj_enm_RG_plasma_boss */
/* obj_enm_RG_riotshield_boss */
/* obj_enm_RG_sniper_boss */
/* obj_boss1_cube */
/* obj_boss1_cubecore */
/* obj_noncombat_propsHover */
/* obj_noncombat_drone_randomMove */
/* obj_noncombat_target */
/* obj_nonbombat_vacuum_randomMove */
/* obj_noncombat_ground_Parent */
/* obj_drone_parent */
/* obj_drone_mainmenu */
/* obj_drone_antibullet */
/* obj_drone_player */
/* obj_drone_healing_turret */
/* obj_drone_laserline */
/* obj_drones_shadow */
/* obj_circlemotion */
/* obj_enm_target_point */
/* obj_enm_dissolve */
/* obj_enm_worldspaceui */
/* obj_enm_parent_all */
/* obj_enm_base_parent */
/* obj_enm_humanoid */
/* ____HUMANOIDS____ */
/* obj_enm_enforcer */
/* obj_enm_redguard_sniper */
/* obj_enm_redguard_riotshield */
/* obj_enm_redguard_plasma */
/* obj_enm_headhunter */
/* obj_enm_headhunter_quest */
/* obj_enm_workerbot */
/* obj_enm_workerbot_quest */
/* obj_enm_rocketeer */
/* obj_enm_mg */
/* obj_enm_hypertrooper */
/* obj_enm_flamer */
/* obj_enm_riotshield */
/* obj_enm_chrono */
/* obj_enm_elite_sg */
/* obj_enm_assassin */
/* obj_enm_phaser */
/* obj_enm_phaser_quest */
/* obj_enm_sniper */
/* obj_enm_sniper_itemoff */
/* ____SPIDERBOTS____ */
/* obj_enm_spider_explo */
/* obj_enm_slowmissile */
/* obj_enm_spider_disco */
/* obj_enm_spider_rocket */
/* obj_enm_spider_antibullet */
/* obj_enm_alarm_o_bot */
/* obj_enm_treasureroomba */
/* ____HOVERBOTS___ */
/* obj_enm_hover_parent */
/* obj_enm_balldefender */
/* obj_enm_drone_mg */
/* obj_enm_drone_shield */
/* obj_enm_drone_missile */
/* obj_enm_gliderrailgun */
/* obj_enm_glidershotgun */
/* obj_enm_gliderjet */
/* obj_enm_hovertank */
/* ____OTHERBOTS____ */
/* obj_enm_spidertruck */
/* obj_enm_antibulletbot */
/* obj_enm_flamethrower */
/* obj_enm_overseer */
/* obj_enm_carrierbot */
/* obj_enm_MELEE */
/* obj_enm_ballretract */
/* obj_enm_ballbot */
/* obj_enm_sawbladebot */
/* obj_enm_tank_parent */
/* obj_enm_mainbattletank */
/* obj_enm_flaktank */
/* ____W_I_P_BOTS____ */
/* obj_enm_camera_right */
/* obj_enm_crystal */
/* obj_enm_vacuumbot */
/* obj_enm_ghost */
/* obj_enm_crystalmarker */
/* obj_enm_crystal_trail */
/* obj_vehiclespawn */
/* obj_boss1_head */
/* obj_boss1_base */
/* obj_boss1_serverblock */
/* obj_boss_1Server */
/* obj_enm_destroyed */
/* obj_enm_hitcollision */
/* obj_dynamic_collision */
/* obj_headshot_collision_parent */
/* obj_moving_entity_PARENT */
/* obj_weapon_toggler */
/* obj_weapon_PARENT */
/* obj_weapon_SRP_1 */
/* obj_weapon_CL_2 */
/* obj_weapon_OICW_3 */
/* obj_weapon_DB_4 */
/* obj_weapon_MG5_5 */
/* obj_weapon_PTL_6 */
/* obj_weapon_BFR_7 */
/* obj_weapon_CLG_8 */
/* obj_weapon_REV_9 */
/* obj_weapon_PXS_10 */
/* obj_weapon_REP_11 */
/* obj_weapon_DMR_12 */
/* obj_weapon_SPC_13 */
/* obj_weapon_FMG_14 */
/* obj_weapon_R5K_15 */
/* obj_weapon_4G_16 */
/* obj_weapon_LSG_17 */
/* obj_weapon_LSMG_18 */
/* obj_weapon_12G_19 */
/* obj_weapon_GM6_20 */
/* obj_weapon_LSP_21 */
/* obj_weapon_LDMR_22 */
/* obj_weapon_M32_23 */
/* obj_weapon_AMD_24 */
/* obj_weapon_ION_25 */
/* obj_weapon_MG42_26 */
/* obj_weapon_CAR_27 */
/* obj_weapon_DMN_28 */
/* obj_weapon_CRGE_29 */
/* obj_weapon_VEC_30 */
/* obj_weapon_S12_31 */
/* obj_weapon_ML_32 */
/* obj_weapon_TMP_33 */
/* obj_weapon_HON_34 */
/* obj_weapon_FT_35 */
/* obj_weapon_FC_36 */
/* obj_weapon_CG_37 */
/* obj_weapon_CP_38 */
/* obj_weapon_DS_39 */
/* obj_weapon_LAR_40 */
/* obj_weapon_AEK_41 */
/* obj_weapon_VAL_42 */
/* obj_weapon_AA_43 */
/* obj_weapon_RPK_44 */
/* obj_weapon_SB_45 */
/* obj_weapon_RG_46 */
/* obj_weapon_HMG_47 */
/* obj_weapon_NG_48 */
/* obj_weapon_PC_49 */
/* obj_weapon_BRN_50 */
/* obj_weapon_EXP_51 */
/* obj_weapon_FB_52 */
/* obj_weapon_BOW_53 */
/* obj_weapon_INT_54 */
/* obj_weapon_A9_55 */
/* obj_weapon_AB_56 */
/* obj_weapon_RPG_57 */
/* obj_weapon_ACR_58 */
/* obj_weapon_K98_59 */
/* obj_weapon_KSG_60 */
/* obj_weapon_DE_61 */
/* obj_weapon_MC_62 */
/* obj_weapon_G17_63 */
/* obj_weapon_HLP_64 */
/* obj_weapon_UMP_65 */
/* obj_weapon_ANH_66 */
/* obj_wep_burstspecial */
/* obj_weapon_spawner */
/* obj_weapon_uber_parent */
/* obj_weapon_item_parent */
/* obj_weapon_enm_taser */
/* obj_weapon_enm_masterkey */
/* obj_weapon_enm_grenade */
/* obj_weapon_enm_plasmagrenade */
/* obj_weapon_enm_plasmagrenade_boss */
/* obj_weapon_enm_stungrenade */
/* obj_weapon_enm_stungrenade2 */
/* obj_weapon_enm_stungrenade_boss */
/* obj_weapon_itemMissile */
/* obj_weapon_minelayer */
/* obj_weapon_itemLaser */
/* obj_weapon_droneplayer_laser */
/* obj_weapon_droneplayer_laserfire */
/* obj_weapon_droneplayer_plasma */
/* obj_weapon_itemRailgun */
/* obj_weapon_itemShieldburst */
/* obj_weapon_itemHomingMissile */
/* obj_weapon_itemlightningorb */
/* obj_weapon_itemSeekers */
/* obj_weapon_itemBloodbolt */
/* obj_weapon_itemGrenadelauncher */
/* obj_weapon_itemStickybomb */
/* obj_weapon_itemPowerbolt */
/* obj_weapon_itemMasterkey */
/* obj_weapon_itemMasterkey2 */
/* obj_weapon_itemTaser */
/* obj_weapon_itemFlare */
/* obj_weapon_itemFireorb */
/* obj_weapon_item_kunai */
/* obj_weapon_item_shuriken1 */
/* obj_weapon_item_shuriken2 */
/* obj_weapon_item_fanknives */
/* obj_weapon_item_flyingknife */
/* obj_weapon_jet_seeking */
/* obj_weapon_jet_rocketbarrage */
/* obj_weapon_helicopter_missile */
/* obj_weapon_APC_seeker */
/* obj_weapon_APC_minelayer */
/* obj_weapon_Heart_minelayer */
/* obj_weapon_Heart_missile */
/* obj_weapon_Heart_main */
/* obj_weapon_bosscube_rocket */
/* obj_weapon_bosscube_rocket_homing */
/* obj_weapon_bosscube_laser */
/* obj_weapon_bullethell */
/* obj_weapon_boss_hmg */
/* obj_weapon_APC_mg */
/* obj_weapon_boss_vierling */
/* obj_weapon_OICWGrenade */
/* obj_weapon_Damnation */
/* obj_weapon_sawblade */
/* obj_bullet_sniperturret */
/* obj_bullet_enemysniper */
/* obj_bullet_enemy_stun */
/* obj_bullet_enemy_poison */
/* obj_bullet_enemypistol */
/* obj_bullet_laser_worker */
/* obj_bullet_turret_grenade */
/* obj_bullet_turret_mortar */
/* obj_bullet_turret_crystalmortar */
/* obj_bullet_rocket_parent */
/* obj_bullet_rocket_boss2_A */
/* obj_bullet_rocket_boss2_B */
/* obj_bullet_rocket_heart */
/* obj_bullet_rocket_turret */
/* obj_bullet_rocket_turret_2 */
/* obj_bullet_rocket_turret_3 */
/* obj_bullet_rocket_turret_crazy */
/* obj_bullet_rocket_upvote */
/* obj_bullet_rocket_particle */
/* obj_bullet_rocket_rapidfire */
/* obj_bullet_rocket_rapidfire_xm29 */
/* obj_bullet_rocket_homing */
/* obj_bullet_rocket_homingslow */
/* obj_bullet_bloodbolt */
/* obj_bullet_bloodbolt_chaos */
/* obj_bullet_bloodbolt_damn */
/* obj_bullet_bloodbolt_boss */
/* obj_bullet_flyingknife */
/* obj_bullet_seeker_item */
/* obj_bullet_needler */
/* obj_bullet_rocket_followmouse */
/* obj_bullet_jetmg */
/* obj_bullet_turretvierling */
/* obj_bullet_bullethell */
/* obj_all_bullets */
/* obj_bullet_lists */
/* obj_player_bullets */
/* object1910 */
/* SHEAVY_______________ */
/* obj_bullet_144_sc */
/* obj_bullet_144_krkn */
/* obj_bullet_144_sabot */
/* obj_bullet_127_sc */
/* obj_bullet_127_toxic */
/* obj_bullet_127_sabot */
/* obj_bullet_arrow_sc */
/* obj_bullet_arrow_toxic */
/* HEAVY_______________ */
/* obj_bullet_88_sc */
/* obj_bullet_88_ap */
/* obj_bullet_88_hs */
/* obj_bullet_88_cata */
/* obj_bullet_88_toxic */
/* MED_________________ */
/* obj_bullet_556_sc */
/* obj_bullet_556_toxic */
/* obj_bullet_556_hp */
/* obj_bullet_556_sabot */
/* obj_bullet_556_sp */
/* obj_bullet_473_sc */
/* obj_bullet_473_alt */
/* SMALL_______________ */
/* obj_bullet_9mm_sc */
/* obj_bullet_9mm_ap */
/* obj_bullet_9mm_hs */
/* obj_bullet_9mm_hp */
/* obj_bullet_9mm_sp */
/* object1451 */
/* obj_bullet_vierling */
/* PELLETS_____________ */
/* obj_bullet_10g_buck */
/* obj_bullet_10g_bird */
/* obj_bullet_10g_flech */
/* obj_bullet_10g_slug */
/* obj_bullet_10g_fire */
/* obj_bullet_10g_masterkey */
/* obj_bullet_10g_masterkey2 */
/* obj_bullet_10g_bolt */
/* obj_bullet_10g_helsing */
/* obj_bullet_coil_x1 */
/* obj_bullet_nail_sc */
/* obj_bullet_nail_bleed */
/* obj_bullet_coil_x4 */
/* GRENADES__________ */
/* obj_bullet_fireball */
/* obj_bullet_flamethrower */
/* obj_bullet_flak1 */
/* obj_bullet_scatter */
/* obj_bullet_grenade_impact */
/* obj_bullet_grenade_bounce */
/* obj_bullet_grenade_stickyitem */
/* obj_bullet_particle_explo */
/* obj_bullet_annihilator */
/* obj_bullet_grenade_enm */
/* obj_bullet_mineemp */
/* obj_bullet_minelaser */
/* obj_bullet_grenade_enm_aircom */
/* obj_bullet_grenade_enm_stun */
/* obj_bullet_sawblade */
/* obj_bullet_sawblade_ultra */
/* obj_bullet_sawblade_item */
/* obj_bullet_kunai */
/* obj_bullet_fanknives */
/* obj_bullet_shuriken */
/* obj_bullet_shuriken2 */
/* obj_bullet_rocket_flare */
/* obj_bullet_taser */
/* obj_bullet_taser_enm */
/* LASER_____________ */
/* obj_bullet_laser_parent */
/* obj_bullet_laser_line */
/* obj_bullet_laser_shieldnuke */
/* obj_bullet_laser_line_reducedDMG */
/* obj_bullet_laser_line_fire */
/* obj_bullet_laser_line_pellet */
/* obj_bullet_laser_spray */
/* obj_bullet_laser_beam */
/* obj_bullet_laser_crystal */
/* obj_bullet_laser_slow */
/* obj_bullet_laser_ion */
/* obj_bullet_laser_fusion */
/* obj_bullet_laser_fusion_slow */
/* obj_bullet_laser_railgun */
/* obj_bullet_laser_railgun2 */
/* obj_bullet_laser_plasma */
/* obj_shell_parentOLD */
/* obj_shell_big_4 */
/* obj_shell_big_3 */
/* obj_shell_grenade */
/* obj_shell_shotgun */
/* obj_shell_cl */
/* obj_shell_2 */
/* obj_shell_1 */
/* obj_bullet_chain */
/* obj_bullet_chain_orb */
/* obj_chest_spwn */
/* obj_chest_parent */
/* obj_chest_weapon_wood */
/* obj_chest_weapon_metal */
/* obj_chest_weapon_metal_cost */
/* obj_chest_weapon_challenge */
/* obj_chest_weapon_cursed */
/* obj_chest_weapon_timed */
/* obj_chest_ammo */
/* obj_chest_health */
/* obj_chest_item_wood */
/* obj_chest_item_metal */
/* obj_chest_item_metal_cost */
/* obj_chest_item_cursed */
/* obj_chest_item_timed */
/* obj_chest_upgrade */
/* obj_chest_wepupgrade */
/* obj_chest_artefact */
/* obj_chest_classperk */
/* obj_chest_unlockammo */
/* obj_chest_mystery */
/* obj_chest_currency */
/* obj_chest_goldensmall */
/* obj_shrine */
/* obj_shrine_tooltip */
/* obj_shrine_spawn */
/* obj_shrine_spawn_normal */
/* obj_shrine_spawn_atm */
/* obj_shrine_spawn_item */
/* obj_shrine_spawn_curse */
/* obj_shrine_spawn_itemupgr */
/* obj_shrine_spawn_weaponbuy */
/* obj_shrine_spawn_weaponupgrade */
/* obj_shrine_spawn_classitem */
/* obj_shrine_spawn_classweapon */
/* obj_shrine_spawn_supplyweapon */
/* obj_shrine_spawn_supplyitem */
/* obj_upgrade_station */
/* obj_shrine_spawn_god */
/* obj_shrine_spawn_teleport */
/* obj_station_trigger */
/* obj_firingrange_trigger */
/* obj_firingrange_tutorial */
/* obj_station_spawner */
/* obj_c4station */
/* obj_buffstation */
/* object1623 */
/* obj_generator */
/* obj_defuseammostation */
/* obj_questvalve */
/* obj_questhack */
/* obj_hearthack_station */
/* obj_pointdefense_station */
/* obj_heart_station */
/* obj_pointdefense_spawnpos */
/* obj_soulcatcher */
/* obj_alarmpole */
/* obj_lightpole */
/* obj_auratower */
/* obj_constructor */
/* obj_mine_c4 */
/* obj_trap_mine_parent */
/* obj_trap_mine_stealthparent */
/* obj_trap_mine_stun */
/* obj_trap_mine_antishield */
/* obj_trap_mine_toxic */
/* obj_trap_mine_laserspike_player */
/* obj_trap_mine_laserspike */
/* obj_trap_parent */
/* obj_trap_minelayer */
/* obj_trap_minimine */
/* obj_trap_chainmine */
/* obj_trap_firespewer */
/* obj_trap_spike */
/* obj_trap_electrofield */
/* obj_trap_slow */
/* obj_trap_slowfield */
/* obj_trap_barbedwire */
/* obj_trap_barbedwire_vert */
/* obj_movingspikes_hor */
/* obj_movingspikes_ver */
/* obj_movingwall_metal_vert */
/* obj_movingwall_parent */
/* obj_minecart_vertical_spwn */
/* obj_minecart_vertical */
/* obj_treadmill */
/* obj_treadmill_picker_holder */
/* obj_treadmill_band */
/* obj_treadmill_picker */
/* obj_disco_tile */
/* obj_all_solid */
/* obj_props_solid_parent */
/* obj_props_notsolid_parent */
/* obj_hazards */
/* obj_props_destructible */
/* obj_prop_destroyed */
/* obj_quest_headhunter_spawn */
/* obj_spawnnextroom */
/* obj_questcontrol_parent */
/* obj_questcontrol_defuseammo */
/* obj_questcontrol_valve */
/* obj_questcontrol_hack */
/* obj_questcontrol_headhunters */
/* obj_questcontrol_soulcatcher */
/* obj_questcontrol_defense */
/* obj_questcontrol_buffstation */
/* obj_questcontrol_c4station */
/* obj_questcontrol_emp */
/* obj_questcontrol_nightvision */
/* obj_questcontrol_alert */
/* obj_questcontrol_patrol */
/* obj_questcontrol_instagib */
/* obj_questcontrol_massacre */
/* obj_questcontrol_generator */
/* obj_questcontrol_dummies */
/* obj_quest_arrow */
/* obj_quest_destroy_generator */
/* obj_quest_destroy_emp */
/* obj_quest_hold_shrine */
/* obj_bumper_direction */
/* obj_sawbig_parent */
/* obj_sawbig_horizontal */
/* obj_sawbig_vertical */
/* obj_sawpillar_vertical */
/* obj_sawpillar_horizontal */
/* obj_PropsBlock */
/* obj_pickup_parent */
/* obj_pickup_outgame */
/* obj_pickup_ring */
/* obj_pickup_chip */
/* obj_pickup_item */
/* obj_pickup_quest */
/* obj_pickup_arenatoken */
/* obj_pickup_upgrade */
/* obj_pickup_vial */
/* obj_pickup_medikit */
/* obj_pickup_ammopack */
/* obj_pickup_keycard */
/* obj_pickup_artefact */
/* obj_pickup_bolt */
/* obj_pickup_scrap */
/* obj_pickup_transistor */
/* obj_pickup_upgradetool */
/* obj_pickup_weppart */
/* obj_pickup_heartcore */
/* obj_pickup_perkkit */
/* obj_pickup_credits */
/* obj_pickup_data */
/* obj_pickup_battery */
/* obj_pickup_spirit */
/* obj_pickup_shield */
/* obj_pickup_ammoreg */
/* obj_pickup_speed */
/* obj_pickup_doubleexp */
/* obj_pickup_damage */
/* obj_all_items */
/* obj_item_drop */
/* obj_item_parent */
/* obj_item1_chaospotion */
/* obj_item2_hyperfeed */
/* obj_item3_splash */
/* obj_item4_cloak */
/* obj_item5_crystal */
/* obj_item6_reloader */
/* obj_item7_vial */
/* obj_item8_injection */
/* obj_item9_fang */
/* obj_item10_overdrive */
/* obj_item11_revive */
/* obj_item12_reflector */
/* obj_item13_devilsdice */
/* obj_item14_goggles */
/* obj_item15_shield */
/* obj_item16_upgradekit */
/* obj_item17_ironorb */
/* obj_item18_potion */
/* obj_item19_lightningorb */
/* obj_item20_fireorb */
/* obj_item21_orbwind */
/* obj_item22_bloodrite */
/* obj_item23_extrashot */
/* obj_item24_heart */
/* obj_item25_refresher */
/* obj_item26_statskit */
/* obj_item27_berserk */
/* obj_item28_dronelaser */
/* obj_item29_slowmo */
/* obj_item30_methadone */
/* obj_item31_vampirism */
/* obj_item32_tsunami */
/* obj_item33_shieldburst */
/* obj_item34_grenade_he */
/* obj_item35_grenade_flash */
/* obj_item36_grenade_stun */
/* obj_item37_grenade_plasma */
/* obj_item38_grenade_toxic */
/* obj_item39_slowfield */
/* obj_item40_steeltrap */
/* obj_item41_powershot */
/* obj_item42_plating */
/* obj_item43_switcher */
/* obj_item44_exploheadshot */
/* obj_item45_uranium */
/* obj_item46_missile */
/* obj_item47_missilehoming */
/* obj_item48_laser */
/* obj_item49_mindcontrol */
/* obj_item50_laststand */
/* obj_item51_stinger */
/* offrail */
/* obj_item52_bombardment */
/* obj_item53_chargeshot */
/* obj_item54_c4 */
/* obj_item55_stim */
/* obj_item56_spawner */
/* obj_item57_gundrone */
/* obj_item58_seekers */
/* obj_item59_noobtube */
/* obj_item60_aimbot */
/* obj_item61_rosarius */
/* obj_item62_colibri */
/* obj_item63_cellreplacer */
/* obj_item64_chalice */
/* obj_item65_stunbolt */
/* obj_item66_akira */
/* obj_item67_boots */
/* obj_item68_ring */
/* obj_item69_taser */
/* obj_item70_bloodbolt */
/* obj_item71_sentry */
/* obj_item72_snipersentry */
/* obj_item73_sentryfuture */
/* obj_item74_perkkit */
/* obj_item75_glass */
/* obj_item76_bloodthirst */
/* obj_item77_chip */
/* obj_item78_sawblade */
/* obj_item79_bolt */
/* obj_item80_masterkey */
/* obj_item81_tanto */
/* obj_item82_flare */
/* obj_item83_grenade_smoke */
/* obj_item84_flechette */
/* obj_item85_kunai */
/* obj_item86_commandoflare */
/* obj_item87_beamblue */
/* obj_item88_beampurple */
/* obj_item89_beamred */
/* obj_item90_shuriken1 */
/* obj_item91_shuriken2 */
/* obj_item92_fanknives */
/* obj_item93_flyingknife */
/* obj_item94_dagger */
/* obj_item95_livingbomb */
/* obj_item96_stickybomb */
/* obj_item97_minelaser */
/* obj_item75_ */
/* obj_item_slot */
/* obj_orb_parent */
/* obj_orb_lightning */
/* obj_orb_class */
/* obj_orb_fire */
/* obj_orb_wind */
/* obj_orb_ripper */
/* obj_orb_iron */
/* obj_aura_effect */
/* obj_mysterybonus */
/* obj_mystery_item */
/* obj_mystery_perk */
/* obj_mystery_starterweapon */
/* obj_mystery_madness */
/* obj_mystery_tactical */
/* obj_mystery_instagib */
/* obj_beartrap */
/* obj_ammo_pack */
/* obj_effect_parent */
/* obj_lightemitter_arealight */
/* obj_lightemitter_heart0 */
/* obj_lightemitter_heart1 */
/* obj_lightemitter_heart2 */
/* obj_lightemitter_flickering */
/* obj_lightemitter_arealight_huge */
/* obj_lightemitter_arealight_firingrange */
/* obj_lightemitter_arealight_boss */
/* obj_lightemitter_alarm_ctrl */
/* obj_lightemitter_alarm */
/* obj_lightemitter_mainmenu */
/* obj_lightemitter_mainmenu_small */
/* obj_debris_metal1 */
/* obj_debris_wood1 */
/* obj_blood_1 */
/* obj_impactparticles_blood1 */
/* obj_blood_splats */
/* obj_blood_sprinkles */
/* obj_kill_splat */
/* obj_blood_pools */
/* obj_status_burn */
/* obj_status_slow */
/* obj_status_stun */
/* obj_status_slow_effect */
/* obj_status_toxicblob */
/* obj_status_healing */
/* obj_status_healing_particle */
/* obj_status_healing_particle_spark */
/* obj_particle_multiplayer */
/* obj_explosion_parent */
/* obj_explosion_big */
/* obj_explosion_small */
/* obj_explosion_frag */
/* obj_3_explos */
/* obj_2_epxlos */
/* obj_explosion_akira */
/* obj_explosion_plasma */
/* obj_explosion_red */
/* obj_explosion_simple */
/* obj_explosion_sphere */
/* obj_explosion_player */
/* obj_explosion_crystal */
/* obj_explosion_drone */
/* obj_explosion_flak */
/* obj_explosion_bullet */
/* obj_explosion_stun */
/* obj_explosion_laserspike */
/* obj_explosion_antishield */
/* obj_explosion_flash */
/* obj_explosion_flare */
/* obj_explosion_smoke */
/* obj_explosion_scatter */
/* obj_explosion_beam_parent */
/* obj_explosion_beam_bigred */
/* obj_explosion_beam_heartbig */
/* obj_explosion_beam_heartsmall */
/* obj_explosion_beam_item_blue */
/* obj_explosion_beam_item_purple */
/* obj_explosion_beam_item_red */
/* obj_explosion_stun_colorgrading */
/* obj_explosion_poison */
/* obj_trail_rocket */
/* obj_trail_bloodbolt */
/* obj_trail_needler */
/* obj_trail_seeker */
/* obj_trail_crazyrocket */
/* obj_smoke_parent */
/* obj_particle_gravity_parent */
/* obj_offrail_marker */
/* obj_grenade_marker */
/* obj_grenade_marker_he */
/* obj_grenade_marker_plasma */
/* obj_grenade_marker_flash */
/* obj_grenade_marker_stun */
/* obj_grenade_marker_poison */
/* obj_grenade_marker_cluster */
/* obj_grenade_marker_aircom */
/* obj_grenade_marker_slowfield */
/* obj_fangs_effect */
/* obj_stickygrenade_item */
/* obj_shieldbreak_particle */
/* obj_tsunami_effect */
/* obj_shieldboost_effect */
/* obj_tanto_swing */
/* obj_dagger_stab_effect */
/* obj_shield_effect */
/* obj_shield_effect_jet */
/* obj_shield_gone_effect */
/* obj_steeltrap_effect */
/* obj_lightning_strike */
/* obj_lightning_strike_stun */
/* obj_lightning_hit */
/* obj_shield_explode_particle */
/* obj_shield_explode */
/* obj_grenade_primer */
/* obj_primer_he */
/* obj_primer_plasma */
/* obj_primer_flash */
/* obj_primer_stun */
/* obj_primer_poison */
/* obj_primer_cluster */
/* obj_strafe_ghosting_spawner */
/* obj_strafe_ghosting */
/* obj_dodge_ghosting */
/* obj_smoke_impact */
/* obj_smoke_player */
/* obj_smoke_explo_effect */
/* obj_oil_pool */
/* obj_poison_pool */
/* obj_groundeffect_crystal */
/* obj_decal_bullet_metal */
/* obj_decal_bullet_metal_medium */
/* obj_decal_bullet_metal_big */
/* obj_line_effect */
/* obj_healing_circle */
/* obj_effect_laststand */
/* obj_followunit_parent */
/* obj_voidzone_parent */
/* obj_voidzone_antiheal */
/* obj_voidzone_spiderboss */
/* obj_voidzone_heart */
/* obj_voidzone_heart_safe */
/* obj_voidzone_ballbot */
/* obj_effect_slowcircle */
/* obj_enemyteleport_spot */
/* obj_enemyteleport_dronemg */
/* obj_enemyteleport_spiderdisco */
/* obj_enmemyteleport_ */
/* obj_enmteleport_dronemissile */
/* obj_effect_slowcircle_spark */
/* obj_turret_auraspark */
/* obj_notification_circle */
/* obj_inspire_effect */
/* obj_hit_circle_effect */
/* obj_splash_effect */
/* obj_plating_effect */
/* obj_particle_parent */
/* obj_impact_spark1 */
/* obj_impact_spark2 */
/* obj_impact_spark3 */
/* obj_impact_sparks_large */
/* obj_impact_sparks_cracker */
/* obj_impact_dust */
/* obj_spark_explosion */
/* obj_impact_spark_bounce */
/* obj_impact_spark_effect */
/* obj_levelup_spark */
/* obj_hit_decal_glow */
/* obj_muzzleflash_1 */
/* obj_muzzleflash_glow */
/* obj_muzzleflash_laser */
/* obj_muzzleflashparticles */
/* obj_muzzleflashparticles2 */
/* obj_curse_star */
/* obj_mortarshot_parent */
/* obj_mortarshot */
/* obj_mortarshot_ballistic */
/* obj_mortarshot_small */
/* obj_mortarshot_crystal */
/* obj_mortarshot_shadow */
/* obj_sonar_ping_effect */
/* obj_lightemitter_firing */
/* obj_lightemitter_hit */
/* obj_menu_particle */
/* obj_menu_particleemitter */
/* obj_lightemitter_parent */
/* obj_flamethrower_particle */
/* obj_flamethrower_particle_ball */
/* obj_flamethrower_particle_old */
/* obj_exp_anchor */
/* obj_exp_gain_ring */
/* obj_soulcatcher_soul */
/* obj_exp_particle_death */
/* obj_credits_particle */
/* obj_plus_particle */
/* obj_downvote_particle */
/* obj_eraser_particle */
/* obj_dust_particle */
/* obj_exp_particle_death2 */
/* obj_hit_circle */
/* obj_hitmarker_world */
/* obj_fire_tiny */
/* obj_particle_base */
/* obj_particles_laserline_spark */
/* obj_particles_rockettrail */
/* obj_particles_explo_dirt */
/* obj_particles_explo_chunky_metal */
/* obj_particles_explo_concrete */
/* obj_particles_explo_chunky_metal_big */
/* obj_particles_explo_chunky_wood */
/* obj_particles_huge_chunks */
/* obj_particles_huge_chunks2 */
/* obj_particles_impact_metal */
/* obj_particles_impact_concrete */
/* obj_particles_impact_oil */
/* obj_particles_oilpools_small */
/* obj_particles_oilpools_flying */
/* obj_particles_impact_concrete_chunky */
/* obj_particles_impact_wood_chunky */
/* obj_particles_impact_wood_chunky2 */
/* obj_particles_impact_wood */
/* obj_particles_shell */
/* obj_destructible_flash */
/* obj_particles_impact_sparks */
/* obj_perk_wepupgrade */
/* o_grid */
/* o_magnifier */
/* o_shockwave */
/* o_laserturret */
/* o_bullet */
/* o_magnifier_path */
/* tmc_vect_test_obj */
/* obj_restart */
/* obj_CRT */
/* obj_scaling */
/* obj_glow1 */
/* obj_chromatic */
/* obj_audio_emitter */
/* obj_audio_emitter_water */
/* obj_defense_buyprop */
/* obj_buy_defense_2x1 */
/* obj_buy_constructor */
/* obj_ground_text_parent */
/* obj_building_grid */
/* obj_tutorial_mode */
/* obj_defense_mode */
/* obj_firingrange_mode */
/* obj_survival_mode */
/* obj_arena_mode */
/* obj_firingrange_spawner_1 */
/* obj_player_spawn */
/* obj_building_effect */
/* obj_conc_pillar_solo */
/* obj_conc_pillar_wall_left */
/* obj_conc_pillar_wall */
/* obj_conc_pillar_destroyed */
/* obj_conc_pyramid */
/* obj_conc_tankbarrier */
/* obj_conc_milestone */
/* obj_conc_cube */
/* obj_conc_rect_hor */
/* obj_conc_rect_vert */
/* obj_conc_barrier_hor */
/* obj_conc_barrier_vert */
/* obj_conc_wall_hor */
/* obj_wall_parent */
/* obj_wall_vert_center */
/* obj_wall_fence_vert_center */
/* obj_wall_metal_vert_center */
/* obj_wall_conc_vert_center */
/* obj_wall_vert_bot */
/* obj_wall_vert_top */
/* obj_wall_hor_center */
/* obj_wall_leftend */
/* obj_wall_rightend */
/* obj_wall_fence_hor */
/* obj_wall_fence_gate */
/* obj_wall_metal_hor */
/* obj_wall_metal_hor2 */
/* obj_wall_metal_fat2 */
/* obj_wall_metal_fat1 */
/* obj_door_parent */
/* obj_door_spawner */
/* obj_door_hearthack */
/* obj_door_hearttank */
/* obj_door_heartenter */
/* obj_helicopterBoss_parent */
/* obj_helicopterBoss_dynTest */
/* obj_specialcodewarning */
/* obj_cratesmall_spawner */
/* obj_barrel_spawner */
/* obj_cylinderspawn */
/* obj_wall_barrier_hor */
/* obj_wall_barrier_vert */
/* obj_wall_top */
/* obj_wall_test */
/* obj_chunkedge_grid_right */
/* obj_chunkedge_grid_top */
/* obj_chunkedge_pillar_right */
/* obj_container_horizontal */
/* obj_container_vertical */
/* obj_ventilationground_large */
/* obj_rectpipe_stack */
/* obj_cablestack */
/* obj_rectpipe_stack2 */
/* obj_rectpipe_stack2_hor */
/* obj_rectcable_stack_hor */
/* obj_stack_spawner_ver */
/* obj_stack_spawner_hor */
/* obj_containeroil_vert_spawner */
/* obj_containeroil_hor_spawner */
/* obj_stack_crates */
/* obj_stack_crate_small */
/* obj_tcarrier_rect */
/* obj_plywoodstack */
/* obj_tcarrier_hor */
/* obj_tcarrierstack_big */
/* obj_tcarrier_big */
/* obj_trashcontainer_vertical */
/* obj_trashcontainer_horizontal */
/* obj_tcarrierstack_big_vert */
/* obj_tcarrierstack_big_hor */
/* obj_woodcrate_big_horizontal */
/* obj_woodcrate_normal */
/* obj_woodcrate_big_vertical */
/* obj_woodcrate_decal */
/* obj_concrete_decal */
/* obj_metal_decal */
/* obj_metalcrate_normal */
/* obj_barrel */
/* obj_barrel_oil */
/* obj_barrel_poison */
/* obj_barrel_explosive */
/* obj_barrel_electric */
/* obj_barrel_explosive_gaz */
/* obj_barrel_tankshell */
/* obj_cylinder_f1_spawn */
/* obj_cylinder_f1 */
/* obj_oiltank_long */
/* obj_oiltank_long_hor */
/* obj_oiltank_high */
/* obj_oiltank_low */
/* obj_oilconv_low */
/* obj_pipes_large_stack */
/* obj_pipes_large_vert */
/* obj_pipes_valveprop */
/* obj_generator_copper */
/* obj_generator_turbine2 */
/* obj_oiltank_pipes */
/* obj_generator_turbine */
/* obj_oiltank_ball */
/* obj_pillar_platform */
/* obj_pillar_platform_below */
/* obj_concpipe */
/* obj_ventilation_floor1 */
/* obj_pipe_center_parent */
/* obj_pipelow_leftend */
/* obj_pipelow_center */
/* obj_pipelow_rightend */
/* obj_pipelow_topend */
/* obj_pipelow_vertcenter */
/* obj_pipelow_botend */
/* obj_pipehigh_leftend */
/* obj_pipehigh_center */
/* obj_pipeshigh_rightend */
/* obj_cylinder_electro */
/* obj_bindercage_cable */
/* obj_generator_alu_cube2 */
/* obj_generator_alu_cube3 */
/* obj_generator_alu_cube4 */
/* obj_generator_alu_cube */
/* obj_generator_alu_high */
/* obj_electroblock */
/* obj_electrohouse_vert */
/* obj_electrohouse_hor */
/* obj_stackelectro_hor */
/* obj_stackelecto_ver */
/* obj_generatoralu_battery */
/* obj_generator_alu_hor */
/* obj_generator_alu_ver */
/* obj_generatoralu_tube */
/* obj_ground_transformator */
/* obj_ground_vrm */
/* obj_cylinder_f2 */
/* obj_cylinder_f2_b */
/* obj_sandbags_vert */
/* obj_sandbags_vert_small */
/* obj_sandbags_hor */
/* obj_sandbags_circle_bot */
/* obj_sandbags_circle_top */
/* obj_crawlpipe */
/* obj_sculpt_quad */
/* obj_clothbox */
/* obj_radar_cube */
/* obj_sculpt_rect */
/* obj_conctext_02 */
/* obj_conc_tent_vert */
/* obj_conc_tent_hor */
/* obj_climbblock_vert */
/* obj_conc_tank_vert */
/* obj_conc_tank_hor */
/* obj_conc_btr_hor */
/* obj_conc_btr_vert */
/* obj_climbwall */
/* obj_tirejump */
/* obj_trainingcontainer_hor */
/* obj_trainingcontainer_ver */
/* obj_tirestack_medium */
/* obj_tirestack_low */
/* obj_concback_parent */
/* obj_house_a0 */
/* obj_house_a1 */
/* obj_euro_sandbags */
/* obj_crystal_greenglow */
/* obj_crystal_groundstones */
/* obj_crystal_d_rect */
/* obj_crystal_d_rect_vert */
/* obj_crystal_d_pyramid */
/* obj_crystal_d_milestone */
/* obj_crystal_d_cube */
/* obj_crystal_d_milestone45 */
/* obj_crystal_floating_big */
/* obj_crystal_floating_medium */
/* obj_crystal_milestone_medium */
/* obj_crystal_medium */
/* obj_crystal_low */
/* obj_crystal_big */
/* obj_crystal_milestone_big */
/* obj_crystal_generator */
/* obj_crystal_genetorline */
/* obj_crystal_solopillar_med */
/* obj_crystal_solopillar_low */
/* obj_crystal_lamp */
/* obj_crystal_smallwall */
/* obj_crystal_bigwall */
/* spr_crystal_spire_milestone */
/* obj_crystal_pillarspike_medium */
/* obj_crystal_pillarspike_big */
/* obj_crystal_spire_small */
/* obj_crystal_spire_big */
/* obj_flyingcrystals_tiny */
/* obj_crystal_teleporter_A */
/* obj_crystal_decal */
/* obj_cogwheelground_large */
/* obj_machine_ground_A */
/* obj_cogwheel_A */
/* obj_rocketcover_hor0 */
/* obj_rocketstack_big_hor0 */
/* obj_rocketstack_big_hor1 */
/* obj_rocketstack_big_hor2 */
/* obj_rocketstack_big_hor4 */
/* obj_rocketstack_big_ver0 */
/* obj_rocketstack_big_ver1 */
/* obj_rocketstack_big_ver2 */
/* obj_tankshells */
/* obj_quadstackrocket */
/* spr_shellscylinders */
/* obj_rocketstack_small */
/* obj_militarycrate_hor */
/* obj_militarycrate_ver */
/* obj_militarycrate_cube */
/* obj_cylinder_f4 */
/* obj_rocketstack */
/* obj_tower_radar */
/* obj_tower_missile0 */
/* obj_tower_missile1 */
/* obj_cylinder_f5 */
/* obj_cylinder_silo */
/* obj_missilepart_low */
/* obj_missilepart_high */
/* obj_missilesilo_big */
/* obj_missilesilo_quad */
/* obj_missilepod_large */
/* obj_doublemissilestack */
/* obj_missilelarge_vert */
/* obj_missilecurve */
/* obj_alublock_big */
/* obj_alublock_round */
/* obj_alublock_bigwide */
/* obj_ventilation_floor4 */
/* obj_cylinder_f6 */
/* obj_stack_canister */
/* obj_oiltank_huge */
/* obj_bindercage_double */
/* obj_cablebinder_single */
/* obj_bindercage_hor */
/* obj_bindercage_vert */
/* obj_research_button_PARENT */
/* rb_skillreset */
/* rb_dailybonus */
/* rb_booster */
/* rb_allweapondata */
/* rb_allitemdata */
/* obj_talent_selection */
/* obj_talent_screenbutton */
/* obj_talent_screendown */
/* obj_talent_screenup */
/* obj_connecter */
/* obj_levelmarker */
/* obj_godmove */
/* obj_fullhdchecker */
/* obj_viewcenter */
/* T_CTRL */
/* T_PARENT_ALL_BONI */
/* T_Path_PARENT */
/* T_overdrive_token */
/* T_Path_vert */
/* T_Path_hor */
/* T_path_cross */
/* T_path_crosstop */
/* T_path_crossbot */
/* T_path_crossright */
/* T_path_crossleft */
/* T_Path_curve_topright */
/* T_Path_curve_topleft */
/* T_Path_curve_botright */
/* T_Path_curve_botleft */
/* T_Path_start_PARENT */
/* T_Path_start_tank */
/* T_Path_start_rogue */
/* T_Path_start_support */
/* T_path_start_elite */
/* T_path_start_alchemy */
/* T_path_start_psyonic */
/* T_path_start_general */
/* T_path_start_drone */
/* T_path_god_start_PARENT */
/* T_path_start_god0 */
/* T_path_start_god1 */
/* T_path_start_god2 */
/* T_item_PARENT */
/* T_item_grenadehe */
/* T_item_grenadeflash */
/* T_item_grenadeheal */
/* T_item_grenadefrag */
/* T_item_stimpack */
/* T_item_ammopack */
/* T_item_healthvial */
/* T_item_chaos */
/* T_item_injection */
/* T_item_healingcrystal */
/* T_item_vial */
/* T_item_methadone */
/* T_item_amphetamine */
/* T_item_laststand */
/* T_item_teleport */
/* T_slot_PARENT */
/* T_slot_free0 */
/* T_slot_free1 */
/* T_slot_free2 */
/* T_slot_free3 */
/* T_slot_free4 */
/* T_slot_free5 */
/* T_slot_free6 */
/* T_slot_free7 */
/* T_slot_free8 */
/* T_slot_free9 */
/* T_slot_free10 */
/* T_slot_free11 */
/* T_slot_free12 */
/* T_slot_free13 */
/* T_slot_free14 */
/* T_stat_PARENT */
/* T_stat_shield */
/* T_stat_killshield */
/* T_stat_scavenging */
/* T_stat_scavenging2 */
/* T_stat_healthy */
/* T_stat_health2 */
/* T_stat_terrorlevel */
/* T_stat_threat_plus */
/* T_stat_luck */
/* T_stat_luck2 */
/* T_stat_credits */
/* T_stat_credits2 */
/* T_stat_dodge */
/* T_stat_dodge2 */
/* T_stat_data */
/* T_stat_data2 */
/* T_stat_movespeed */
/* T_perk_PARENT */
/* T_perk_general_PARENT */
/* T_perk_addict */
/* T_perk_shortcd */
/* T_perk_longcd */
/* T_perk_recycler */
/* T_perk_reckless */
/* T_perk_pistolultimate */
/* T_perk_vialcharge */
/* T_perk_itemslot */
/* T_perk_healroom */
/* T_perk_bossheal */
/* T_perk_threat_minus */
/* T_perk_elite_PARENT */
/* T_perk_reloadstack */
/* T_perk_recoilctrl */
/* T_perk_nightvision */
/* T_perk_nightvisioncd */
/* T_perk_assaultrifle */
/* T_perk_bleedingmammo */
/* T_perk_hollowpoint */
/* T_perk_ultrashot */
/* T_perk_ultrachance */
/* T_perk_weaponslot */
/* T_perk_combo */
/* T_perk_powerstep */
/* T_perk_powertreads */
/* T_perk_fury */
/* T_perk_drill */
/* T_perk_elitecore */
/* T_perk_itemcdsmall */
/* T_perk_itemcdvariant */
/* T_perk_psyonic_PARENT */
/* T_perk_ */
/* T_perk_teleport2 */
/* T_perk_laserpen */
/* T_perk_laserfire */
/* T_perk_adrenaline */
/* T_perk_smgspec */
/* T_perk_smallcaliber */
/* T_perk_ascendance */
/* T_perk_killstealth */
/* T_perk_minimapenemies */
/* T_perk_support_PARENT */
/* T_perk_pistolspec */
/* T_perk_commander */
/* T_perk_hitshield */
/* T_perk_mindcontrol */
/* T_perk_infusionvial */
/* T_perk_softpoint */
/* T_perk_pistolvariants */
/* T_perk_commander2 */
/* T_perk_riot */
/* T_perk_unitdeath */
/* T_perk_healing */
/* T_perk_platingstart */
/* T_perk_pistolspec2 */
/* T_perk_calm */
/* T_perk_grenadier */
/* T_perk_rally */
/* T_perk_poweroverflow */
/* T_perk_statusextender */
/* T_perk_sharingcaring */
/* T_perk_threatminussup */
/* T_perk_sharingcaring2 */
/* T_perk_alchemist_PARENT */
/* T_perk_markheal */
/* T_perk_refinement */
/* T_perk_craze */
/* T_perk_dodgeheat */
/* T_perk_dodgeheat2 */
/* T_perk_selfrepair */
/* T_perk_selfrepair2 */
/* T_perk_elementalpower */
/* T_perk_itemheat */
/* T_perk_contaminate */
/* T_perk_pistolextender */
/* T_perk_ammoregen */
/* T_perk_itempower */
/* T_perk_doublepickup */
/* T_perk_launchers */
/* T_perk_minimapchests */
/* T_perk_reforge */
/* T_perk_shrapnel */
/* T_perk_playfire */
/* T_perk_wepupgrade */
/* T_perk_rogue_PARENT */
/* T_perk_shophack */
/* T_perk_poisonammo */
/* T_perk_bounces */
/* T_perk_deviation */
/* T_perk_dodgeboost */
/* T_perk_reloadsurge */
/* T_perk_ADS */
/* T_perk_coolhead */
/* T_perk_dexterity */
/* T_perk_perfection */
/* T_perk_mastercard */
/* T_perk_shadow */
/* T_perk_discipline */
/* T_perk_markdrone */
/* T_perk_prepared */
/* T_perk_roguecore */
/* T_perk_headshotammo */
/* T_perk_headshotheal */
/* T_perk_moneyshot */
/* T_perk_specialized */
/* T_perk_tank_PARENT */
/* T_perk_aegis */
/* T_perk_laststand */
/* T_perk_shotgunmaster */
/* T_perk_shotgun */
/* T_perk_standfirm */
/* T_perk_lowhpregen */
/* T_perk_scavengerbits */
/* T_perk_platingcapacity */
/* T_perk_shieldoc */
/* T_perk_bloodinfusion */
/* T_perk_laststand2 */
/* T_perk_warmup */
/* T_perk_fortify */
/* T_perk_healthreg */
/* T_perk_cover */
/* T_perk_reactivearmor */
/* T_perk_powerbolt */
/* T_perk_scraparmor */
/* T_perk_guardianfate */
/* T_perk_closer */
/* T_perk_heatup */
/* T_perk_iframe */
/* T_perk_hframe */
/* T_perk_lifeline */
/* T_perk_lifesteal */
/* T_weapon_PARENT */
/* T_weapon_PXS */
/* T_weapon_PTL */
/* T_weapon_REV */
/* T_weapon_REP */
/* T_weapon_LSPT */
/* T_weapon_HON */
/* obj_cursor_mainmenu */
/* obj_mm_research_trigger */
/* obj_mm_ground */
/* obj_mm_arrowwobble */
/* obj_mm_creditsdisplay */
/* obj_pregame_darkoverlay */
/* obj_mm_weaponlocker */
/* obj_mm_computer */
/* obj_mm_kitselect */
/* obj_mm_progress */
/* obj_scrolling_log */
/* obj_mainmenu */
/* obj_mm_cityscreen */
/* obj_mm_menu_parent */
/* obj_player_mainmenu */
/* obj_mm_startgamedecal */
/* outgame.readylobby */
/* obj_mm_talentselection_menu */
/* obj_mm_multiplayer_menu */
/* obj_mm_itemselect_menu */
/* obj_mm_weaponmenu */
/* obj_mm_secret_menu */
/* obj_mm_statistics_menu */
/* obj_mm_community_menu */
/* obj_mm_difficultymenu */
/* obj_mm_unlocks_menu */
/* obj_mm_classes_menu */
/* obj_intro_notes */
/* obj_start_game */
/* obj_startgame */
/* obj_bigbrothermode_ */
/* obj_mm_switchtalent_effect */
/* obj_mm_research */
/* obj_mm_glow */
/* obj_threadmill_creator */
/* obj_threadmill_start */
/* obj_treadmill_contains */
/* obj_threadmill_end */
/* obj_treadmill_rollband */
/* obj_treadmill_extractor */
/* obj_mainmenu_backgroundglow */
/* obj_research_button */
/* obj_researchmenu */
/* obj_research_box */
/* obj_research_box_cursor */
/* obj_research_box_daily */
/* obj_research_box_patchlog */
/* obj_research_box_activitylog */
/* obj_research_box_income */
/* obj_research_box_visor */
/* obj_research_box_weapon */
/* obj_research_box_cores */
/* obj_research_box_bios */
/* obj_research_cursor */
/* obj_mm_acc_input_parent */
/* obj_mm_login_box */
/* obj_mm_reset_password */
/* obj_set_lobby_config */
/* obj_mm_generic_input_box */
/* obj_name_input */
/* obj_mm_new_pw_box */
/* obj_mm_network_error */
/* obj_mm_join_lobby_pw */
/* obj_mm_portforwarding */
/* obj_mm_create_account_box */
/* obj_enm_spawn_point */
/* obj_enm_POI */
/* obj_enm_spawn_point_small */
/* obj_enm_spawn_point_big */
/* obj_enm_alarm */
/* obj_enm_budget_parent */
/* obj_enm_budget_plus5 */
/* obj_enm_budget_plus10 */
/* obj_enm_budget_minus5 */
/* obj_nem_budget_minus10 */
/* obj_teleporter */
/* obj_field_special */
/* obj_turretshrinespawn */
/* obj_specialobject_small */
/* obj_specialobject_big */
/* obj_railing_parent */
/* obj_railing_straights */
/* obj_railing_corner */
/* obj_railing_end_vert_bot */
/* obj_railing_end_vert_top */
/* obj_railing_end_top_R */
/* obj_railing_end_top_L */
/* obj_railing_end_bot_R */
/* obj_railing_end_bot_L */
/* obj_railing_top */
/* obj_railing_bot */
/* obj_railing_right */
/* obj_railing_topleft */
/* obj_railing_left */
/* obj_railing_topright */
/* obj_railing_botleft */
/* obj_railing_botright */
/* obj_railing_inner_botleft */
/* obj_railing_inner_botright */
/* obj_railing_inner_topleft */
/* obj_railing_inner_topright */
/* obj_bossroom */
/* obj_prebossroom */
/* obj_boss_transition */
/* obj_walls_fog */
/* obj_walls */
/* obj_wall_lab1 */
/* obj_wall_lab3 */
/* obj_wall_lab1_s */
/* obj_wall_lab1_triple */
/* obj_wall_lab1_doorframe */
/* obj_wall_lab1_door_open */
/* obj_wall_lab1_door_closed */
/* obj_wall_borderright_x1 */
/* obj_wall_cornertopright_x1 */
/* obj_collision_blockout_parent */
/* obj_collision_blockout_A */
/* obj_collision_blockout_B */
/* obj_collision_blockout_C */
/* obj_collision_blockout_D */
/* obj_collision_blockout_E */
/* obj_collision_blockout_F */
/* obj_collision_blockout_1X */
/* obj_collision_blockout_2X */
/* obj_collision_blockout_3Y */
/* obj_collision_blockout_4Y */
/* obj_collision_blockout_5Z */
/* obj_collision_blockout_6Z */
/* obj_collision_blockout_RAND */
/* obj_collision_blockout_fog */
/* obj_floor_blockout_parent */
/* obj_floor1_blockout */
/* obj_floor2_blockout */
/* obj_field_node */
/* obj_force_surfacedraw */
/* obj_field_parent */
/* obj_special_2x2 */
/* obj_shrine_2x2 */
/* obj_special_3x3 */
/* obj_field_1x1 */
/* obj_field_1x2 */
/* obj_field_1x3 */
/* obj_field_2x1 */
/* obj_field_2x2 */
/* obj_field_2x3 */
/* obj_field_3x1 */
/* obj_field_3x2 */
/* obj_field_3x3 */
/* obj_field_3x4 */
/* obj_field_4x3 */
/* obj_field_4x4 */
/* obj_path_horizontal */
/* obj_path_vertical */
/* obj_path_left_bot */
/* obj_path_bot_right */
/* obj_path_right_top */
/* obj_path_top_left */
/* obj_field_pillar */
/* obj_field_godShrine */
/* obj_field_bossHelicopter */
/* obj_field_forcePath */
/* obj_field_forceInvisiblePath */
/* obj_field_forceDummyPath */
/* obj_field_forceSpecialPath */
/* obj_field_forceField */
/* obj_field_forceFree */
/* obj_field_forceSpecial */
/* obj_field_forceShrine */
/* obj_field_teleporter */
/* obj_field_teleporter_start */
/* obj_field_teleporter_end */
/* obj_fields_parent */
/* obj_chunk_A */
/* obj_chunk_B */
/* obj_chunk_X */
/* obj_chunk_Y */
/* obj_chunk_Z */
/* obj_FOG_back */
/* obj_FOG_top */
/* obj_back_colorchange */
/* obj_back_ambientlight */
/* obj_background_pipes */
/* obj_memory_manager */
/* obj_levelAsObj */
/* obj_levelManager */
/* obj_bridge_1 */
/* obj_bridge_TypeB */
/* obj_bridge_TypeA */
/* obj_bridge_1_rng */
/* obj_pathfinding_allowed */
/* obj_chunk */
/* obj_chunk_parent */
/* obj_chunk_surfacedraw */
/* obj_chunk_ao */
/* obj_chunk_floor */
/* obj_placeroom_movablespace */
/* obj_placeroom_manualfloor */
/* obj_placeroomchunk_extra */
/* obj_placeroomchunk_small */
/* obj_placeroomchunk_medium */
/* obj_placeroomchunk_small_walls */
/* obj_placeroomchunk_medium_walls */
/* obj_nowall_manual */
/* obj_nowall_extra */
/* obj_nowall_small */
/* obj_nowall_medium */
/* obj_nowall_quest */
/* obj_wall_small */
/* obj_wall_medium */
/* obj_room_config */
/* knownbugs */
/* obj_networking_server */
/* obj_networking_client */
/* obj_networking_parent */
/* net_MS_client */
/* obj_networking_lobby_ping */
/* MasterServerHTTPReq */
/* obj_chat_parent */
/* obj_net_chat */
/* obj_net_global_chat */
/* obj_multiplayer_marker */
/* obj_marker_come */
/* obj_marker_generic */
/* obj_marker_help */
/* obj_marker_care */
/* obj_marker_object */
/* obj_marker_enemy */
/* obj_net_add_newsletter */
/* obj_net_beta_forceOnline */
/* obj_net_file_upload */
/* obj_voice_chat */
/* obj_analytics */
/* objSolidCircle */
/* objSolidRectangle */
/* obj_progressbar */
/* o_controller_lut */
/* obj_blur_test */
/* obj_background_linespregame */
/* obj_radio_button */
/* obj_slider_input */
/* obj_slider_input_mastervol */
/* obj_slider_input_musicvol */
/* obj_text_input */
/* obj_list_debugger */
/* obj_Localization */
/* obj_HTML_fakeINI */
/* o_shader_start */
/* obj_steam_init */
/* obj_random */
/* o_shader_end */
/* obj_last */

#endif