#pragma once
#include <vector>
#define ROOMS_DO(THING) \
    THING(LocaIntro) \
    THING(Load) \
    THING(Intro) \
    THING(main_menu) \
    THING(room_researchmenu) \
    THING(roompregame) \
    THING(multiplayer_lobby) \
    THING(roompregameold) \
    THING(roomtransistion) \
    THING(researchtest) \
    THING(room_death) \
    THING(R056_triangle_B) \
    THING(R056_openfield) \
    THING(R056_islands) \
    THING(R056_small) \
    THING(R0__Circle_Backup) \
    THING(R_all_circle) \
    THING(R_all_curve1) \
    THING(R_all_curve2) \
    THING(R_all_updown) \
    THING(R_all_containers) \
    THING(R_all_cube) \
    THING(R_all_cube2) \
    THING(R_all_straight_vert) \
    THING(R_all_port) \
    THING(R_all_river) \
    THING(SEP_) \
    THING(R_Electro_1) \
    THING(COPYROOM) \
    THING(room_1_Pipes_B) \
    THING(R6_containers_B) \
    THING(room_1_Warehouse_B) \
    THING(R2_small) \
    THING(R_2_Paintball) \
    THING(room_2_A) \
    THING(room_2_B_arena) \
    THING(room_2_C) \
    THING(room_3_A) \
    THING(room_3_B) \
    THING(room_3_C) \
    THING(room_4_Square) \
    THING(room_4_1) \
    THING(R_4_center) \
    THING(R_4_river) \
    THING(R6_VertIsland) \
    THING(Floor_7_Snow_A) \
    THING(R_Boss_Jet) \
    THING(R_Boss_Jet1) \
    THING(R_Boss_Heart) \
    THING(R_Boss_Heart_Afterroom) \
    THING(R_Boss_Helicopter) \
    THING(R_Boss_Threadmill) \
    THING(R_Boss_APC) \
    THING(R_Boss_Sawblade) \
    THING(R_Boss_Blob) \
    THING(R_Marstest) \
    THING(R_Boss_Spider) \
    THING(R_Boss_Defense) \
    THING(R_Boss_Triple) \
    THING(R_Boss_MBT) \
    THING(R_Boss_Fortress) \
    THING(R_Boss_Armageddon) \
    THING(Chunk_Medium_Lab1_Wall) \
    THING(Chunk_Small_Lab1_Wall) \
    THING(Chunk_Medium_Lab1) \
    THING(Chunk_Medium_Lab2) \
    THING(Chunk_Medium_Lab3) \
    THING(Chunk_Medium_Lab4) \
    THING(Chunk_Medium_Lab5) \
    THING(Chunk_Medium_Lab6) \
    THING(Chunk_Medium_Lab7) \
    THING(Chunk_Medium_Lab8) \
    THING(Chunk_Medium_Lab9) \
    THING(Chunk_Small_Lab1) \
    THING(Chunk_Small_Lab2) \
    THING(Chunk_Small_Lab3) \
    THING(Chunk_Small_Lab4) \
    THING(Chunk_Small_Lab5) \
    THING(Chunk_Small_Lab6) \
    THING(Chunk_Small_Lab7) \
    THING(Chunk_Extra_Lab1) \
    THING(R_Challenge_Tank) \
    THING(R_Challenge_Flak) \
    THING(R_Challenge_Spider) \
    THING(R_Challenge_Radar) \
    THING(R_Challenge_Saws) \
    THING(R_Challenge_Defense) \
    THING(R_Challenge_Drones) \
    THING(FieldsTS1_1x1) \
    THING(FieldsTS1_1x2) \
    THING(FieldsTS1_1x3) \
    THING(FieldsTS1_2x1) \
    THING(FieldsTS1_2x2) \
    THING(FieldsTS1_2x3) \
    THING(FieldsTS1_3x1) \
    THING(FieldsTS1_3x3_Special) \
    THING(FieldsTS1_3x3) \
    THING(FieldsTS9_God) \
    THING(FieldsTS1_2x2_Special) \
    THING(FieldsTS1_1x1_Path_Hor) \
    THING(FieldsTS1_1x1_Path_Vert) \
    THING(FieldsTS1_1x1_Path_Left_Bot) \
    THING(FieldsTS1_1x1_Path_Bot_Right) \
    THING(FieldsTS1_1x1_Path_Right_Top) \
    THING(FieldsTS1_1x1_Path_Top_Left) \
    THING(FieldsTS1_4x4) \
    THING(FieldsTS6_1x1) \
    THING(FieldsTS6_1x2) \
    THING(FieldsTS6_1x3) \
    THING(FieldsTS6_2x1) \
    THING(FieldsTS6_2x2) \
    THING(FieldsTS6_2x3) \
    THING(FieldsTS6_3x1) \
    THING(FieldsTS6_3x2) \
    THING(FieldsTS6_God) \
    THING(FieldsTS6_2x2_Special) \
    THING(FieldsTS6_3x3) \
    THING(FieldsTS6_2x2_Shrine) \
    THING(FieldsTS6_1x1_Path_Hor) \
    THING(FieldsTS6_1x1_Path_Vert) \
    THING(FieldsTS7_1x1) \
    THING(FieldsTS7_1x3) \
    THING(FieldsTS7_2x1) \
    THING(FieldsTS7_2x2) \
    THING(FieldsTS7_3x3) \
    THING(FieldsTS7_2x2_Special) \
    THING(FieldsTS7_1x1_Path_Hor) \
    THING(FieldsTS7_1x1_Path_Vert) \
    THING(FieldsTS2_1x1) \
    THING(FieldsTS2_1x2) \
    THING(FieldsTS2_2x1) \
    THING(FieldsTS2_2x2) \
    THING(FieldsTS2_2x2_Special) \
    THING(FieldsTS2_God) \
    THING(FieldsTS2_3x3) \
    THING(room133) \
    THING(FieldsTS2_1x1_Path_Hor) \
    THING(FieldsTS2_1x1_Path_Vert) \
    THING(FieldsTS3_1x1) \
    THING(FieldsTS3_4x4) \
    THING(FieldsTS3_3x3) \
    THING(FieldsTS3_God) \
    THING(FieldsTS4_1x1) \
    THING(FieldsTS4_1x2) \
    THING(FieldsTS4_1x3) \
    THING(FieldsTS4_2x1) \
    THING(FieldsTS4_2x2) \
    THING(FieldsTS4_3x3) \
    THING(FieldsTS4_4x4) \
    THING(FieldsTS4_3x1) \
    THING(FieldsTS4_2x2_Special) \
    THING(FieldsTS4_1x1_Path_Hor) \
    THING(FieldsTS4_1x1_Path_Vert) \
    THING(FieldsTS9_1x1) \
    THING(FieldsTS9_1x2) \
    THING(FieldsTS9_2x1) \
    THING(FieldsTS9_2x2) \
    THING(FieldsTS1_God) \
    THING(FieldsTS9_2x2_Special) \
    THING(FieldsTS9_3x1) \
    THING(FieldsTS9_3x3) \
    THING(FieldsTS5_1x1) \
    THING(FieldsTS5_2x1) \
    THING(FieldsTS5_2x2) \
    THING(FieldsTS5_1x2) \
    THING(FieldsTS8_1x1) \
    THING(room_talents_god0) \
    THING(room_talents_generic) \
    THING(room_talents_2) \
    THING(ARENA_COPY_ROOM) \
    THING(D_Hack_Rocket) \
    THING(D_Core_TrainingOld) \
    THING(D_Core_Training) \
    THING(D_Core_Training2) \
    THING(D_Core_Rocket) \
    THING(D_Core_Rocket2) \
    THING(D_Core_Rocket3) \
    THING(D_Core_Rocket_Alt) \
    THING(D_Core_Electro) \
    THING(D_Core_Electro2) \
    THING(D_Core_Electro3) \
    THING(S_Electro2) \
    THING(A_Survival_Training) \
    THING(A_Survival_Training2) \
    THING(A_Outposts_Military) \
    THING(A_Headhunt_Pipes) \
    THING(S_Soulcharger_Electro) \
    THING(S_Soulcharger_Electro1) \
    THING(S_AirBubbles_Crystal) \
    THING(R_Arena_Pipes) \
    THING(R_Core_Pipes) \
    THING(R_Core_Pipes2) \
    THING(aiTest) \
    THING(room_storyintro) \
    THING(room_tutorial_old) \
    THING(tutorial_new) \
    THING(room_tutorial_A) \
    THING(room_firingrange_A) \
    THING(room_arena_A) \
    THING(room_defense_A) \
    THING(room_defense_Ab) \
    THING(room_defense_B) \
    THING(R_Arena_Mars) \
    THING(weapontest) \
    THING(R_all_Z_1) \
    THING(R4_twins2) \
    THING(R4_mirror) \
    THING(R_all_zones2) \
    THING(R1_PipesTanks) \
    THING(R_2_Trainingcity) \
    THING(R4_Trainingcity) \
    THING(RE_AnnexBig) \
    THING(RE_AnnexMed) \
    THING(RE_Horizontal) \
    THING(R2_rareStraight) \
    THING(R2_street) \
    THING(R2_straightHorizontal) \
    THING(R2_rareSpawn) \
    THING(room_3_D) \
    THING(room_3_H) \
    THING(room_3_H2) \
    THING(room_3_F) \
    THING(R4_cross2) \
    THING(R1_PipesPumps) \
    THING(room_3_G) \
    THING(R_all_sCurve1) \
    THING(R_all_test2) \
    THING(R_all_snail) \
    THING(R4_mirror2) \
    THING(R2_zones1) \
    THING(R4_cross) \
    THING(R4_twins) \
    THING(room_3_E) \
    THING(MOBA_TEST) \
    THING(FieldsBossHelicopter)

#ifndef MAKE_STRINGS
#define MAKE_STRINGS(THINGNAME) #THINGNAME,
#endif
#ifndef MAKE_ENUM
#define MAKE_ENUM(THINGNAME) THINGNAME,
#endif

#ifndef ORGANIK_ROOMS
#define ORGANIK_ROOMS
namespace Organik
{
    struct Rooms
    {
        enum
        {
            ROOMS_DO(MAKE_ENUM)
        };
        static std::vector<int32_t> AssetIndexes;
        static const char* const RoomNamesArr[];
    };
}
#endif