#ifndef __ROOM_FN_H__
#define __ROOM_FN_H__
/* gml_RoomCC_Intro_0_Create */
/* gml_RoomCC_main_menu_0_Create */
/* gml_RoomCC_roompregame_0_Create */
/* gml_RoomCC_roompregame_1_Create */
/* gml_RoomCC_roompregame_2_Create */
/* gml_RoomCC_roompregame_3_Create */
/* gml_RoomCC_roompregame_4_Create */
/* gml_RoomCC_researchtest_1_Create */
/* gml_RoomCC_R_all_circle_0_Create */
/* gml_RoomCC_R_all_circle_1_Create */
/* gml_RoomCC_R_all_circle_2_Create */
/* gml_RoomCC_R_all_circle_3_Create */
/* gml_RoomCC_R_all_circle_4_Create */
/* gml_RoomCC_R_all_circle_5_Create */
/* gml_RoomCC_R_all_circle_6_Create */
/* gml_RoomCC_R_all_circle_7_Create */
/* gml_RoomCC_R_all_circle_8_Create */
/* gml_RoomCC_R_all_circle_9_Create */
/* gml_RoomCC_R_all_circle_10_Create */
/* gml_RoomCC_R_all_circle_11_Create */
/* gml_RoomCC_R_all_circle_12_Create */
/* gml_RoomCC_R_all_circle_13_Create */
/* gml_RoomCC_R_all_circle_14_Create */
/* gml_RoomCC_R_all_circle_15_Create */
/* gml_RoomCC_R_all_circle_17_Create */
/* gml_RoomCC_R_all_circle_18_Create */
/* gml_RoomCC_R_all_circle_19_Create */
/* gml_RoomCC_R_all_circle_20_Create */
/* gml_RoomCC_R_all_circle_21_Create */
/* gml_RoomCC_R_all_circle_22_Create */
/* gml_RoomCC_R_all_circle_23_Create */
/* gml_RoomCC_R_all_circle_24_Create */
/* gml_RoomCC_R_all_circle_25_Create */
/* gml_RoomCC_R_all_circle_26_Create */
/* gml_RoomCC_R_all_circle_27_Create */
/* gml_RoomCC_R_all_circle_28_Create */
/* gml_RoomCC_R_all_circle_29_Create */
/* gml_RoomCC_R_all_curve1_0_Create */
/* gml_RoomCC_R_all_curve1_1_Create */
/* gml_RoomCC_R_all_curve1_2_Create */
/* gml_RoomCC_R_all_curve1_3_Create */
/* gml_RoomCC_R_all_curve1_4_Create */
/* gml_RoomCC_R_all_curve1_5_Create */
/* gml_RoomCC_R_all_curve1_6_Create */
/* gml_RoomCC_R_all_curve1_7_Create */
/* gml_RoomCC_R_all_curve1_8_Create */
/* gml_RoomCC_R_all_curve1_9_Create */
/* gml_RoomCC_R_all_curve1_10_Create */
/* gml_RoomCC_R_all_curve1_11_Create */
/* gml_RoomCC_R_all_curve1_12_Create */
/* gml_RoomCC_R_all_curve1_13_Create */
/* gml_RoomCC_R_all_curve1_14_Create */
/* gml_RoomCC_R_all_curve1_15_Create */
/* gml_RoomCC_R_all_curve1_16_Create */
/* gml_RoomCC_R_all_curve1_17_Create */
/* gml_RoomCC_R_all_curve1_18_Create */
/* gml_RoomCC_R_all_curve1_19_Create */
/* gml_RoomCC_R_all_curve1_20_Create */
/* gml_RoomCC_R_all_curve1_21_Create */
/* gml_RoomCC_R_all_curve1_22_Create */
/* gml_RoomCC_R_all_curve1_23_Create */
/* gml_RoomCC_R_all_curve1_24_Create */
/* gml_RoomCC_R_all_curve1_25_Create */
/* gml_RoomCC_R_all_curve1_26_Create */
/* gml_RoomCC_R_all_curve1_27_Create */
/* gml_RoomCC_R_all_curve1_28_Create */
/* gml_RoomCC_R_all_curve1_29_Create */
/* gml_RoomCC_R_all_curve1_30_Create */
/* gml_RoomCC_R_all_curve1_31_Create */
/* gml_RoomCC_R_all_curve1_32_Create */
/* gml_RoomCC_R_all_curve1_33_Create */
/* gml_RoomCC_R_all_curve1_34_Create */
/* gml_RoomCC_R_all_curve1_35_Create */
/* gml_RoomCC_R_all_curve1_36_Create */
/* gml_RoomCC_R_all_updown_0_Create */
/* gml_RoomCC_R_all_updown_1_Create */
/* gml_RoomCC_R_all_updown_2_Create */
/* gml_RoomCC_R_all_updown_3_Create */
/* gml_RoomCC_R_all_updown_4_Create */
/* gml_RoomCC_R_all_updown_5_Create */
/* gml_RoomCC_R_all_updown_6_Create */
/* gml_RoomCC_R_all_updown_7_Create */
/* gml_RoomCC_R_all_updown_8_Create */
/* gml_RoomCC_R_all_updown_9_Create */
/* gml_RoomCC_R_all_updown_10_Create */
/* gml_RoomCC_R_all_containers_0_Create */
/* gml_RoomCC_R_all_containers_1_Create */
/* gml_RoomCC_R_all_containers_2_Create */
/* gml_RoomCC_R_all_containers_3_Create */
/* gml_RoomCC_R_all_containers_4_Create */
/* gml_RoomCC_R_all_containers_5_Create */
/* gml_RoomCC_R_all_containers_6_Create */
/* gml_RoomCC_R_all_containers_7_Create */
/* gml_RoomCC_R_all_containers_8_Create */
/* gml_RoomCC_R_all_containers_9_Create */
/* gml_RoomCC_R_all_containers_10_Create */
/* gml_RoomCC_R_all_containers_11_Create */
/* gml_RoomCC_R_all_containers_12_Create */
/* gml_RoomCC_R_all_containers_13_Create */
/* gml_RoomCC_R_all_containers_14_Create */
/* gml_RoomCC_R_all_containers_15_Create */
/* gml_RoomCC_R_all_containers_16_Create */
/* gml_RoomCC_R_all_containers_17_Create */
/* gml_RoomCC_R_all_containers_18_Create */
/* gml_RoomCC_R_all_containers_19_Create */
/* gml_RoomCC_R_all_containers_20_Create */
/* gml_RoomCC_R_all_containers_21_Create */
/* gml_RoomCC_R_all_containers_22_Create */
/* gml_RoomCC_R_all_containers_23_Create */
/* gml_RoomCC_R_all_containers_24_Create */
/* gml_RoomCC_R_all_containers_25_Create */
/* gml_RoomCC_R_all_containers_26_Create */
/* gml_RoomCC_R_all_containers_27_Create */
/* gml_RoomCC_R_all_containers_28_Create */
/* gml_RoomCC_R_all_containers_29_Create */
/* gml_RoomCC_R_all_containers_30_Create */
/* gml_RoomCC_R_all_containers_31_Create */
/* gml_RoomCC_R_all_containers_32_Create */
/* gml_RoomCC_R_all_containers_33_Create */
/* gml_RoomCC_R_all_containers_34_Create */
/* gml_RoomCC_R_all_containers_35_Create */
/* gml_RoomCC_R_all_containers_36_Create */
/* gml_RoomCC_R_all_containers_37_Create */
/* gml_RoomCC_R_all_containers_38_Create */
/* gml_RoomCC_R_all_containers_39_Create */
/* gml_RoomCC_R_all_containers_40_Create */
/* gml_RoomCC_R_all_containers_41_Create */
/* gml_RoomCC_R_all_containers_42_Create */
/* gml_RoomCC_R_all_containers_43_Create */
/* gml_RoomCC_R_all_containers_44_Create */
/* gml_RoomCC_R_all_containers_45_Create */
/* gml_RoomCC_R_all_containers_46_Create */
/* gml_RoomCC_R_all_containers_47_Create */
/* gml_RoomCC_R_all_containers_48_Create */
/* gml_RoomCC_R_all_containers_49_Create */
/* gml_RoomCC_R_all_containers_50_Create */
/* gml_RoomCC_R_all_containers_51_Create */
/* gml_RoomCC_R_all_containers_52_Create */
/* gml_RoomCC_R_all_containers_53_Create */
/* gml_RoomCC_R_all_containers_54_Create */
/* gml_RoomCC_R_all_containers_55_Create */
/* gml_RoomCC_R_all_containers_56_Create */
/* gml_RoomCC_R_all_containers_57_Create */
/* gml_RoomCC_R_all_containers_58_Create */
/* gml_RoomCC_R_all_containers_59_Create */
/* gml_RoomCC_R_all_containers_60_Create */
/* gml_RoomCC_R_all_containers_61_Create */
/* gml_RoomCC_R_all_containers_62_Create */
/* gml_RoomCC_R_all_containers_63_Create */
/* gml_RoomCC_R_all_containers_64_Create */
/* gml_RoomCC_R_all_containers_65_Create */
/* gml_RoomCC_R_all_containers_66_Create */
/* gml_RoomCC_R_all_containers_67_Create */
/* gml_RoomCC_R_all_containers_68_Create */
/* gml_RoomCC_R_all_containers_69_Create */
/* gml_RoomCC_R_all_containers_70_Create */
/* gml_RoomCC_R_all_containers_71_Create */
/* gml_RoomCC_R_all_containers_72_Create */
/* gml_RoomCC_R_all_containers_73_Create */
/* gml_RoomCC_R_all_containers_74_Create */
/* gml_RoomCC_R_all_containers_75_Create */
/* gml_RoomCC_R_all_containers_76_Create */
/* gml_RoomCC_R_all_containers_77_Create */
/* gml_RoomCC_R_all_containers_78_Create */
/* gml_RoomCC_R_all_containers_79_Create */
/* gml_RoomCC_R_all_containers_80_Create */
/* gml_RoomCC_R_all_containers_81_Create */
/* gml_RoomCC_R_all_containers_82_Create */
/* gml_RoomCC_R_all_containers_83_Create */
/* gml_RoomCC_R_all_containers_84_Create */
/* gml_RoomCC_R_all_containers_85_Create */
/* gml_RoomCC_R_all_containers_86_Create */
/* gml_RoomCC_R_all_containers_87_Create */
/* gml_RoomCC_R_all_containers_88_Create */
/* gml_RoomCC_R_all_containers_89_Create */
/* gml_RoomCC_R_all_containers_90_Create */
/* gml_RoomCC_R_all_containers_91_Create */
/* gml_RoomCC_R_all_containers_92_Create */
/* gml_RoomCC_R_all_containers_93_Create */
/* gml_RoomCC_R_all_containers_94_Create */
/* gml_RoomCC_R_all_containers_95_Create */
/* gml_RoomCC_R_all_containers_96_Create */
/* gml_RoomCC_R_all_containers_97_Create */
/* gml_RoomCC_R_all_containers_98_Create */
/* gml_RoomCC_R_all_containers_99_Create */
/* gml_RoomCC_R_all_containers_100_Create */
/* gml_RoomCC_R_all_containers_101_Create */
/* gml_RoomCC_R_all_containers_102_Create */
/* gml_RoomCC_R_all_containers_103_Create */
/* gml_RoomCC_R_all_containers_104_Create */
/* gml_RoomCC_R_all_containers_105_Create */
/* gml_RoomCC_R_all_cube_0_Create */
/* gml_RoomCC_R_all_cube_1_Create */
/* gml_RoomCC_R_all_cube_2_Create */
/* gml_RoomCC_R_all_cube_3_Create */
/* gml_RoomCC_R_all_cube_4_Create */
/* gml_RoomCC_R_all_cube_5_Create */
/* gml_RoomCC_R_all_cube_6_Create */
/* gml_RoomCC_R_all_cube_7_Create */
/* gml_RoomCC_R_all_cube_8_Create */
/* gml_RoomCC_R_all_cube_9_Create */
/* gml_RoomCC_R_all_cube_10_Create */
/* gml_RoomCC_R_all_cube_11_Create */
/* gml_RoomCC_R_all_cube_12_Create */
/* gml_RoomCC_R_all_cube_13_Create */
/* gml_RoomCC_R_all_cube_14_Create */
/* gml_RoomCC_R_all_cube_15_Create */
/* gml_RoomCC_R_all_cube_16_Create */
/* gml_RoomCC_R_all_cube_17_Create */
/* gml_RoomCC_R_all_cube_18_Create */
/* gml_RoomCC_R_all_cube_19_Create */
/* gml_RoomCC_R_all_cube_20_Create */
/* gml_RoomCC_R_all_cube_21_Create */
/* gml_RoomCC_R_all_cube_22_Create */
/* gml_RoomCC_R_all_cube_23_Create */
/* gml_RoomCC_R_all_cube2_0_Create */
/* gml_RoomCC_R_all_cube2_1_Create */
/* gml_RoomCC_R_all_cube2_2_Create */
/* gml_RoomCC_R_all_cube2_3_Create */
/* gml_RoomCC_R_all_cube2_4_Create */
/* gml_RoomCC_R_all_cube2_5_Create */
/* gml_RoomCC_R_all_cube2_6_Create */
/* gml_RoomCC_R_all_cube2_7_Create */
/* gml_RoomCC_R_all_cube2_8_Create */
/* gml_RoomCC_R_all_cube2_9_Create */
/* gml_RoomCC_R_all_cube2_10_Create */
/* gml_RoomCC_R_all_cube2_11_Create */
/* gml_RoomCC_R_all_cube2_12_Create */
/* gml_RoomCC_R_all_cube2_13_Create */
/* gml_RoomCC_R_all_cube2_14_Create */
/* gml_RoomCC_R_all_cube2_15_Create */
/* gml_RoomCC_R_all_cube2_16_Create */
/* gml_RoomCC_R_all_straight_vert_0_Create */
/* gml_RoomCC_R_all_straight_vert_1_Create */
/* gml_RoomCC_R_all_straight_vert_2_Create */
/* gml_RoomCC_R_Boss_Jet_0_Create */
/* gml_RoomCC_R_Boss_Jet_1_Create */
/* gml_RoomCC_R_Boss_Jet_2_Create */
/* gml_RoomCC_R_Boss_Jet_3_Create */
/* gml_RoomCC_R_Boss_Jet1_0_Create */
/* gml_RoomCC_R_Boss_Jet1_1_Create */
/* gml_RoomCC_R_Boss_Jet1_2_Create */
/* gml_RoomCC_R_Boss_Jet1_3_Create */
/* gml_Room_R_Boss_Heart_Create */
/* gml_RoomCC_R_Boss_Heart_0_Create */
/* gml_RoomCC_R_Boss_Heart_1_Create */
/* gml_RoomCC_R_Boss_Heart_2_Create */
/* gml_RoomCC_R_Boss_Heart_3_Create */
/* gml_RoomCC_R_Boss_Helicopter_0_Create */
/* gml_RoomCC_R_Boss_Helicopter_1_Create */
/* gml_RoomCC_R_Boss_Threadmill_0_Create */
/* gml_RoomCC_R_Boss_Threadmill_1_Create */
/* gml_RoomCC_R_Boss_APC_0_Create */
/* gml_RoomCC_R_Boss_APC_1_Create */
/* gml_RoomCC_R_Boss_APC_2_Create */
/* gml_RoomCC_R_Boss_APC_3_Create */
/* gml_RoomCC_R_Boss_APC_4_Create */
/* gml_RoomCC_R_Boss_APC_5_Create */
/* gml_RoomCC_R_Boss_APC_6_Create */
/* gml_RoomCC_R_Boss_Sawblade_0_Create */
/* gml_RoomCC_R_Boss_Blob_0_Create */
/* gml_RoomCC_R_Boss_Blob_1_Create */
/* gml_RoomCC_R_Marstest_0_Create */
/* gml_RoomCC_R_Boss_Spider_0_Create */
/* gml_RoomCC_R_Boss_Spider_1_Create */
/* gml_RoomCC_R_Boss_Spider_2_Create */
/* gml_RoomCC_R_Boss_Spider_3_Create */
/* gml_RoomCC_R_Boss_Defense_0_Create */
/* gml_RoomCC_R_Boss_Defense_1_Create */
/* gml_RoomCC_R_Boss_Defense_2_Create */
/* gml_RoomCC_R_Boss_Defense_3_Create */
/* gml_RoomCC_R_Boss_Triple_0_Create */
/* gml_RoomCC_R_Boss_Triple_1_Create */
/* gml_RoomCC_R_Boss_Triple_2_Create */
/* gml_RoomCC_R_Boss_Triple_3_Create */
/* gml_RoomCC_R_Boss_MBT_0_Create */
/* gml_RoomCC_R_Boss_MBT_1_Create */
/* gml_RoomCC_R_Boss_Fortress_0_Create */
/* gml_RoomCC_R_Boss_Fortress_1_Create */
/* gml_RoomCC_R_Boss_Fortress_2_Create */
/* gml_RoomCC_R_Boss_Fortress_3_Create */
/* gml_RoomCC_R_Boss_Fortress_4_Create */
/* gml_RoomCC_R_Boss_Fortress_5_Create */
/* gml_RoomCC_R_Boss_Armageddon_0_Create */
/* gml_RoomCC_R_Boss_Armageddon_1_Create */
/* gml_RoomCC_R_Boss_Armageddon_2_Create */
/* gml_RoomCC_R_Challenge_Tank_0_Create */
/* gml_RoomCC_R_Challenge_Tank_1_Create */
/* gml_RoomCC_R_Challenge_Flak_0_Create */
/* gml_RoomCC_R_Challenge_Flak_1_Create */
/* gml_RoomCC_R_Challenge_Spider_0_Create */
/* gml_RoomCC_R_Challenge_Spider_1_Create */
/* gml_RoomCC_R_Challenge_Radar_0_Create */
/* gml_RoomCC_R_Challenge_Radar_1_Create */
/* gml_RoomCC_R_Challenge_Saws_0_Create */
/* gml_RoomCC_R_Challenge_Saws_1_Create */
/* gml_RoomCC_R_Challenge_Defense_0_Create */
/* gml_RoomCC_R_Challenge_Defense_1_Create */
/* gml_RoomCC_room_talents_2_0_Create */
/* gml_RoomCC_room_talents_2_1_Create */
/* gml_RoomCC_room_talents_2_2_Create */
/* gml_RoomCC_room_talents_2_3_Create */
/* gml_RoomCC_room_talents_2_4_Create */
/* gml_RoomCC_room_talents_2_5_Create */
/* gml_RoomCC_room_talents_2_6_Create */
/* gml_RoomCC_room_talents_2_7_Create */
/* gml_RoomCC_room_talents_2_8_Create */
/* gml_RoomCC_room_talents_2_9_Create */
/* gml_RoomCC_room_talents_2_10_Create */
/* gml_RoomCC_room_talents_2_11_Create */
/* gml_RoomCC_room_talents_2_12_Create */
/* gml_RoomCC_room_talents_2_13_Create */
/* gml_RoomCC_room_talents_2_14_Create */
/* gml_RoomCC_room_talents_2_15_Create */
/* gml_RoomCC_room_talents_2_16_Create */
/* gml_RoomCC_room_talents_2_17_Create */
/* gml_RoomCC_room_talents_2_18_Create */
/* gml_RoomCC_room_talents_2_19_Create */
/* gml_RoomCC_room_talents_2_20_Create */
/* gml_RoomCC_room_talents_2_21_Create */
/* gml_RoomCC_room_talents_2_22_Create */
/* gml_RoomCC_room_talents_2_23_Create */
/* gml_RoomCC_room_talents_2_24_Create */
/* gml_RoomCC_room_talents_2_25_Create */
/* gml_RoomCC_room_talents_2_26_Create */
/* gml_RoomCC_room_talents_2_27_Create */
/* gml_RoomCC_room_talents_2_28_Create */
/* gml_RoomCC_room_talents_2_29_Create */
/* gml_RoomCC_room_talents_2_30_Create */
/* gml_RoomCC_room_talents_2_31_Create */
/* gml_RoomCC_room_talents_2_32_Create */
/* gml_RoomCC_room_talents_2_33_Create */
/* gml_RoomCC_room_talents_2_34_Create */
/* gml_RoomCC_room_talents_2_35_Create */
/* gml_RoomCC_room_talents_2_36_Create */
/* gml_RoomCC_room_talents_2_37_Create */
/* gml_RoomCC_room_talents_2_38_Create */
/* gml_RoomCC_room_talents_2_39_Create */
/* gml_RoomCC_room_talents_2_40_Create */
/* gml_RoomCC_room_talents_2_41_Create */
/* gml_RoomCC_D_Core_TrainingOld_0_Create */
/* gml_RoomCC_D_Core_TrainingOld_1_Create */
/* gml_RoomCC_D_Core_TrainingOld_2_Create */
/* gml_RoomCC_D_Core_TrainingOld_3_Create */
/* gml_RoomCC_D_Core_TrainingOld_4_Create */
/* gml_RoomCC_D_Core_Training_0_Create */
/* gml_RoomCC_D_Core_Training_1_Create */
/* gml_RoomCC_D_Core_Training_2_Create */
/* gml_RoomCC_D_Core_Training_3_Create */
/* gml_RoomCC_D_Core_Training_4_Create */
/* gml_RoomCC_D_Core_Training_5_Create */
/* gml_RoomCC_D_Core_Training_6_Create */
/* gml_RoomCC_D_Core_Training2_0_Create */
/* gml_RoomCC_D_Core_Training2_1_Create */
/* gml_RoomCC_D_Core_Training2_2_Create */
/* gml_RoomCC_D_Core_Training2_3_Create */
/* gml_RoomCC_D_Core_Training2_4_Create */
/* gml_RoomCC_D_Core_Training2_5_Create */
/* gml_RoomCC_D_Core_Training2_6_Create */
/* gml_RoomCC_D_Core_Rocket_0_Create */
/* gml_RoomCC_D_Core_Rocket_1_Create */
/* gml_RoomCC_D_Core_Rocket_2_Create */
/* gml_RoomCC_D_Core_Rocket_3_Create */
/* gml_RoomCC_D_Core_Rocket_4_Create */
/* gml_RoomCC_D_Core_Rocket2_0_Create */
/* gml_RoomCC_D_Core_Rocket2_1_Create */
/* gml_RoomCC_D_Core_Rocket2_2_Create */
/* gml_RoomCC_D_Core_Rocket2_3_Create */
/* gml_RoomCC_D_Core_Rocket2_4_Create */
/* gml_RoomCC_D_Core_Rocket2_5_Create */
/* gml_RoomCC_D_Core_Rocket3_0_Create */
/* gml_RoomCC_D_Core_Rocket3_1_Create */
/* gml_RoomCC_D_Core_Rocket3_2_Create */
/* gml_RoomCC_D_Core_Rocket3_3_Create */
/* gml_RoomCC_D_Core_Rocket3_4_Create */
/* gml_RoomCC_D_Core_Rocket3_5_Create */
/* gml_RoomCC_D_Core_Electro_0_Create */
/* gml_RoomCC_D_Core_Electro_1_Create */
/* gml_RoomCC_D_Core_Electro_2_Create */
/* gml_RoomCC_D_Core_Electro_3_Create */
/* gml_RoomCC_D_Core_Electro_4_Create */
/* gml_RoomCC_D_Core_Electro_5_Create */
/* gml_RoomCC_D_Core_Electro2_0_Create */
/* gml_RoomCC_D_Core_Electro2_1_Create */
/* gml_RoomCC_D_Core_Electro2_2_Create */
/* gml_RoomCC_D_Core_Electro2_3_Create */
/* gml_RoomCC_D_Core_Electro2_4_Create */
/* gml_RoomCC_D_Core_Electro2_5_Create */
/* gml_RoomCC_D_Core_Electro2_6_Create */
/* gml_RoomCC_D_Core_Electro2_7_Create */
/* gml_RoomCC_D_Core_Electro3_0_Create */
/* gml_RoomCC_D_Core_Electro3_1_Create */
/* gml_RoomCC_D_Core_Electro3_2_Create */
/* gml_RoomCC_D_Core_Electro3_3_Create */
/* gml_RoomCC_D_Core_Electro3_4_Create */
/* gml_RoomCC_D_Core_Electro3_5_Create */
/* gml_RoomCC_D_Core_Electro3_6_Create */
/* gml_RoomCC_S_Electro2_0_Create */
/* gml_RoomCC_S_Electro2_1_Create */
/* gml_RoomCC_S_Electro2_2_Create */
/* gml_RoomCC_A_Survival_Training_0_Create */
/* gml_RoomCC_A_Survival_Training_1_Create */
/* gml_RoomCC_A_Survival_Training2_0_Create */
/* gml_RoomCC_A_Survival_Training2_1_Create */
/* gml_RoomCC_A_Survival_Training2_2_Create */
/* gml_RoomCC_S_Soulcharger_Electro_0_Create */
/* gml_RoomCC_S_Soulcharger_Electro_1_Create */
/* gml_RoomCC_S_Soulcharger_Electro1_0_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_0_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_1_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_2_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_3_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_4_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_5_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_6_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_7_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_8_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_9_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_10_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_11_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_12_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_13_Create */
/* gml_RoomCC_S_AirBubbles_Crystal_14_Create */
/* gml_RoomCC_R_Arena_Pipes_0_Create */
/* gml_RoomCC_R_Arena_Pipes_1_Create */
/* gml_RoomCC_R_Arena_Pipes_2_Create */
/* gml_RoomCC_R_Core_Pipes_0_Create */
/* gml_RoomCC_R_Core_Pipes_1_Create */
/* gml_RoomCC_R_Core_Pipes_2_Create */
/* gml_RoomCC_R_Core_Pipes_3_Create */
/* gml_RoomCC_R_Core_Pipes_4_Create */
/* gml_RoomCC_R_Core_Pipes_5_Create */
/* gml_RoomCC_R_Core_Pipes2_0_Create */
/* gml_RoomCC_R_Core_Pipes2_1_Create */
/* gml_RoomCC_R_Core_Pipes2_2_Create */
/* gml_RoomCC_R_Core_Pipes2_3_Create */
/* gml_RoomCC_R_Core_Pipes2_4_Create */
/* gml_RoomCC_R_Core_Pipes2_5_Create */
/* gml_RoomCC_aiTest_0_Create */
/* gml_RoomCC_aiTest_1_Create */
/* gml_RoomCC_room_storyintro_0_Create */
/* gml_RoomCC_room_tutorial_old_0_Create */
/* gml_RoomCC_room_tutorial_old_1_Create */
/* gml_RoomCC_room_tutorial_old_2_Create */
/* gml_RoomCC_room_tutorial_old_3_Create */
/* gml_RoomCC_tutorial_new_0_Create */
/* gml_RoomCC_tutorial_new_1_Create */
/* gml_RoomCC_tutorial_new_2_Create */
/* gml_RoomCC_tutorial_new_3_Create */
/* gml_RoomCC_tutorial_new_4_Create */
/* gml_RoomCC_tutorial_new_5_Create */
/* gml_RoomCC_tutorial_new_6_Create */
/* gml_RoomCC_tutorial_new_7_Create */
/* gml_RoomCC_tutorial_new_8_Create */
/* gml_RoomCC_tutorial_new_9_Create */
/* gml_RoomCC_tutorial_new_10_Create */
/* gml_RoomCC_tutorial_new_11_Create */
/* gml_RoomCC_tutorial_new_12_Create */
/* gml_RoomCC_tutorial_new_13_Create */
/* gml_RoomCC_tutorial_new_14_Create */
/* gml_RoomCC_tutorial_new_15_Create */
/* gml_RoomCC_tutorial_new_16_Create */
/* gml_RoomCC_tutorial_new_17_Create */
/* gml_RoomCC_tutorial_new_18_Create */
/* gml_RoomCC_tutorial_new_19_Create */
/* gml_RoomCC_tutorial_new_20_Create */
/* gml_RoomCC_tutorial_new_21_Create */
/* gml_RoomCC_tutorial_new_22_Create */
/* gml_RoomCC_tutorial_new_23_Create */
/* gml_RoomCC_tutorial_new_24_Create */
/* gml_RoomCC_room_tutorial_A_0_Create */
/* gml_RoomCC_room_tutorial_A_1_Create */
/* gml_RoomCC_room_tutorial_A_2_Create */
/* gml_RoomCC_room_tutorial_A_3_Create */
/* gml_RoomCC_room_tutorial_A_4_Create */
/* gml_RoomCC_room_tutorial_A_5_Create */
/* gml_RoomCC_room_tutorial_A_6_Create */
/* gml_RoomCC_room_tutorial_A_7_Create */
/* gml_RoomCC_room_tutorial_A_8_Create */
/* gml_RoomCC_room_firingrange_A_0_Create */
/* gml_RoomCC_room_firingrange_A_1_Create */
/* gml_RoomCC_room_firingrange_A_2_Create */
/* gml_RoomCC_room_defense_Ab_0_Create */
/* gml_RoomCC_R_all_Z_1_0_Create */
/* gml_RoomCC_R_all_Z_1_1_Create */
/* gml_RoomCC_R_all_Z_1_2_Create */
/* gml_RoomCC_R_all_Z_1_3_Create */
/* gml_RoomCC_R_all_Z_1_4_Create */
/* gml_RoomCC_R_all_Z_1_5_Create */
/* gml_RoomCC_R_all_Z_1_6_Create */
/* gml_RoomCC_R_all_Z_1_7_Create */
/* gml_RoomCC_R_all_Z_1_8_Create */
/* gml_RoomCC_R_all_Z_1_9_Create */
/* gml_RoomCC_R_all_Z_1_10_Create */
/* gml_RoomCC_R_all_Z_1_11_Create */
/* gml_RoomCC_R_all_Z_1_12_Create */
/* gml_RoomCC_R_all_Z_1_13_Create */
/* gml_RoomCC_R_all_Z_1_14_Create */
/* gml_RoomCC_R_all_Z_1_15_Create */
/* gml_RoomCC_R_all_Z_1_16_Create */
/* gml_RoomCC_R_all_Z_1_17_Create */
/* gml_RoomCC_R_all_Z_1_18_Create */
/* gml_RoomCC_R_all_Z_1_19_Create */
/* gml_RoomCC_R_all_Z_1_20_Create */
/* gml_RoomCC_R_all_Z_1_21_Create */
/* gml_RoomCC_R_all_Z_1_22_Create */
/* gml_RoomCC_R_all_zones2_0_Create */
/* gml_RoomCC_R_all_zones2_1_Create */
/* gml_RoomCC_R_all_zones2_2_Create */
/* gml_RoomCC_R_all_zones2_3_Create */
/* gml_RoomCC_R_all_zones2_4_Create */
/* gml_RoomCC_R_all_zones2_5_Create */
/* gml_RoomCC_R_all_zones2_6_Create */
/* gml_RoomCC_R_all_zones2_7_Create */
/* gml_RoomCC_R_all_zones2_8_Create */
/* gml_RoomCC_R_all_zones2_9_Create */
/* gml_RoomCC_R_all_zones2_10_Create */
/* gml_RoomCC_R_all_zones2_11_Create */
/* gml_RoomCC_R_all_zones2_12_Create */
/* gml_RoomCC_R_all_zones2_13_Create */
/* gml_RoomCC_R_all_zones2_14_Create */
/* gml_RoomCC_R_all_zones2_15_Create */
/* gml_RoomCC_R_all_zones2_16_Create */
/* gml_RoomCC_R_all_zones2_17_Create */
/* gml_RoomCC_R_all_zones2_18_Create */
/* gml_RoomCC_RE_AnnexBig_0_Create */
/* gml_RoomCC_RE_AnnexMed_0_Create */
/* gml_RoomCC_R2_street_0_Create */
/* gml_RoomCC_R2_street_1_Create */
/* gml_RoomCC_R2_street_2_Create */
/* gml_RoomCC_R2_street_3_Create */
/* gml_RoomCC_R2_street_4_Create */
/* gml_RoomCC_R2_street_5_Create */
/* gml_RoomCC_R2_street_6_Create */
/* gml_RoomCC_R2_street_7_Create */
/* gml_RoomCC_R2_street_8_Create */
/* gml_RoomCC_R2_straightHorizontal_0_Create */
/* gml_RoomCC_R2_straightHorizontal_1_Create */
/* gml_RoomCC_R2_straightHorizontal_2_Create */
/* gml_RoomCC_R2_straightHorizontal_3_Create */
/* gml_RoomCC_R2_straightHorizontal_4_Create */
/* gml_RoomCC_R2_straightHorizontal_5_Create */
/* gml_RoomCC_R2_straightHorizontal_6_Create */
/* gml_RoomCC_R2_straightHorizontal_7_Create */
/* gml_RoomCC_R_all_sCurve1_0_Create */
/* gml_RoomCC_R_all_sCurve1_1_Create */
/* gml_RoomCC_R_all_test2_0_Create */
/* gml_RoomCC_R_all_test2_1_Create */
/* gml_RoomCC_R_all_test2_2_Create */
/* gml_RoomCC_R_all_test2_3_Create */
/* gml_RoomCC_R_all_test2_4_Create */
/* gml_RoomCC_MOBA_TEST_0_Create */
/* gml_RoomCC_MOBA_TEST_1_Create */
/* gml_RoomCC_MOBA_TEST_2_Create */
/* gml_RoomCC_MOBA_TEST_3_Create */
/* gml_RoomCC_MOBA_TEST_4_Create */
/* gml_RoomCC_MOBA_TEST_5_Create */
/* gml_RoomCC_MOBA_TEST_6_Create */
/* gml_RoomCC_MOBA_TEST_7_Create */

#endif