#ifndef __SCRIPT_FN_H__
#define __SCRIPT_FN_H__
/* gml_Script_scr_url_open */
/* gml_GlobalScript_scr_url_open */
/* gml_Script_scr_mod_ini_read_string */
/* gml_GlobalScript_scr_mod_ini_read_string */
/* gml_Script_scr_exception_handling */
/* gml_Script_anon__2310 */
/* gml_GlobalScript_scr_exception_handling */
/* gml_Script_scr_localPlayer_add_screenshake */
/* gml_GlobalScript_scr_localPlayer_add_screenshake */
/* gml_Script_scr_mod_ini_read_real */
/* gml_GlobalScript_scr_mod_ini_read_real */
/* gml_Script_scr_modweapon_init */
/* gml_GlobalScript_scr_modweapon_init */
/* gml_Script_macros */
/* gml_GlobalScript_macros */
/* gml_Script_scr_create_bullet */
/* gml_GlobalScript_scr_create_bullet */
/* gml_Script_scr_create_bullet_effects */
/* gml_GlobalScript_scr_create_bullet_effects */
/* gml_Script_scr_create_bullet_shell */
/* gml_GlobalScript_scr_create_bullet_shell */
/* gml_Script_scr_particle_effects_unit */
/* gml_GlobalScript_scr_particle_effects_unit */
/* gml_Script_scr_quest_rewards */
/* gml_GlobalScript_scr_quest_rewards */
/* gml_Script_scr_draw_interacting_bar */
/* gml_GlobalScript_scr_draw_interacting_bar */
/* gml_Script_scr_chest_select_loottable */
/* gml_GlobalScript_scr_chest_select_loottable */
/* gml_Script_scr_chest_loottable_ammo */
/* gml_GlobalScript_scr_chest_loottable_ammo */
/* gml_Script_scr_mystery_reward */
/* gml_GlobalScript_scr_mystery_reward */
/* gml_Script_scr_chest_loottable_health */
/* gml_GlobalScript_scr_chest_loottable_health */
/* gml_Script_scr_shrine_effect_active */
/* gml_GlobalScript_scr_shrine_effect_active */
/* gml_Script_scr_display_prompt_tooltip */
/* gml_GlobalScript_scr_display_prompt_tooltip */
/* gml_Script_scr_weapon_descriptions */
/* gml_GlobalScript_scr_weapon_descriptions */
/* gml_Script_scr_ammotypes */
/* gml_GlobalScript_scr_ammotypes */
/* gml_Script_scr_ammotypes_classbased */
/* gml_GlobalScript_scr_ammotypes_classbased */
/* gml_Script_scr_roll_ammotype */
/* gml_GlobalScript_scr_roll_ammotype */
/* gml_Script_scr_unlock_ammo */
/* gml_GlobalScript_scr_unlock_ammo */
/* gml_Script_scr_weapon_firing */
/* gml_GlobalScript_scr_weapon_firing */
/* gml_Script_scr_weapon_init_free */
/* gml_GlobalScript_scr_weapon_init_free */
/* gml_Script_scr_attachments_init */
/* gml_GlobalScript_scr_attachments_init */
/* gml_Script_scr_attachments_init_ultimate */
/* gml_GlobalScript_scr_attachments_init_ultimate */
/* gml_Script_scr_attachments_apply */
/* gml_GlobalScript_scr_attachments_apply */
/* gml_Script_scr_attachments_apply_ultimate */
/* gml_GlobalScript_scr_attachments_apply_ultimate */
/* gml_Script_scr_weapon_variants_init */
/* gml_GlobalScript_scr_weapon_variants_init */
/* gml_Script_scr_weapon_variants_init_ultimate */
/* gml_GlobalScript_scr_weapon_variants_init_ultimate */
/* gml_Script_scr_weapon_pickup */
/* gml_GlobalScript_scr_weapon_pickup */
/* gml_Script_scr_tooltipbig_weapons_getdata */
/* gml_GlobalScript_scr_tooltipbig_weapons_getdata */
/* gml_Script_scr_weapon_tooltipbars */
/* gml_GlobalScript_scr_weapon_tooltipbars */
/* gml_Script_scr_activereload */
/* gml_GlobalScript_scr_activereload */
/* gml_Script_scr_weapon_drop */
/* gml_GlobalScript_scr_weapon_drop */
/* gml_Script_scr_player_currency_change */
/* gml_GlobalScript_scr_player_currency_change */
/* gml_Script_scr_player_data_change */
/* gml_GlobalScript_scr_player_data_change */
/* gml_Script_scr_player_labfunds_change */
/* gml_GlobalScript_scr_player_labfunds_change */
/* gml_Script_scr_player_exp_change */
/* gml_GlobalScript_scr_player_exp_change */
/* gml_Script_scr_player_keycard_gain */
/* gml_GlobalScript_scr_player_keycard_gain */
/* gml_Script_scr_player_interest_change */
/* gml_GlobalScript_scr_player_interest_change */
/* gml_Script_scr_player_ammo_gaining */
/* gml_GlobalScript_scr_player_ammo_gaining */
/* gml_Script_scr_player_health_healing */
/* gml_GlobalScript_scr_player_health_healing */
/* gml_Script_scr_plating_gaining */
/* gml_GlobalScript_scr_plating_gaining */
/* gml_Script_scr_microchip_gaining */
/* gml_GlobalScript_scr_microchip_gaining */
/* gml_Script_scr_player_health_damage */
/* gml_GlobalScript_scr_player_health_damage */
/* gml_Script_scr_chest_loottable */
/* gml_GlobalScript_scr_chest_loottable */
/* gml_Script_scr_statboost */
/* gml_GlobalScript_scr_statboost */
/* gml_Script_scr_randomstatboost_gaining */
/* gml_GlobalScript_scr_randomstatboost_gaining */
/* gml_Script_scr_glow_splat_draw */
/* gml_GlobalScript_scr_glow_splat_draw */
/* gml_Script_scr_popup */
/* gml_GlobalScript_scr_popup */
/* gml_Script_scr_vial_gaining */
/* gml_GlobalScript_scr_vial_gaining */
/* gml_Script_scr_questlog */
/* gml_GlobalScript_scr_questlog */
/* gml_Script_scr_is_player_stuck */
/* gml_GlobalScript_scr_is_player_stuck */
/* gml_Script_scr_reset_player */
/* gml_GlobalScript_scr_reset_player */
/* gml_Script_scr_get_interpolated_shifted_player_pos */
/* gml_GlobalScript_scr_get_interpolated_shifted_player_pos */
/* gml_Script_scr_player_multiplayer_revive */
/* gml_GlobalScript_scr_player_multiplayer_revive */
/* gml_Script_scr_player_set_stealth */
/* gml_GlobalScript_scr_player_set_stealth */
/* gml_Script_scr_badge_display */
/* gml_GlobalScript_scr_badge_display */
/* gml_Script_scr_classcheck */
/* gml_GlobalScript_scr_classcheck */
/* gml_Script_scr_class_sprites */
/* gml_GlobalScript_scr_class_sprites */
/* gml_Script_scr_humanoid_attack_movement */
/* gml_GlobalScript_scr_humanoid_attack_movement */
/* gml_Script_scr_humanoid_attack_movement_create */
/* gml_GlobalScript_scr_humanoid_attack_movement_create */
/* gml_Script_scr_humanoid_movement */
/* gml_GlobalScript_scr_humanoid_movement */
/* gml_Script_scr_basic_unit_defensive_stats_calc */
/* gml_GlobalScript_scr_basic_unit_defensive_stats_calc */
/* gml_Script_scr_basic_unit_defense_stats */
/* gml_GlobalScript_scr_basic_unit_defense_stats */
/* gml_Script_scr_damage_numbers */
/* gml_GlobalScript_scr_damage_numbers */
/* gml_Script_scr_bloodsplat_large */
/* gml_GlobalScript_scr_bloodsplat_large */
/* gml_Script_scr_statuseffects_collision */
/* gml_GlobalScript_scr_statuseffects_collision */
/* gml_Script_BallCreate */
/* gml_GlobalScript_BallCreate */
/* gml_Script_BallStep */
/* gml_GlobalScript_BallStep */
/* gml_Script_DrawStatesDebug */
/* gml_GlobalScript_DrawStatesDebug */
/* gml_Script_scr_view_cone */
/* gml_GlobalScript_scr_view_cone */
/* gml_Script_scr_search_audio_at */
/* gml_GlobalScript_scr_search_audio_at */
/* gml_Script_scr_enm_knockback */
/* gml_GlobalScript_scr_enm_knockback */
/* gml_Script_scr_getSpawnInSpriteRect */
/* gml_GlobalScript_scr_getSpawnInSpriteRect */
/* gml_Script_scr_spawn_alarm_squad */
/* gml_GlobalScript_scr_spawn_alarm_squad */
/* gml_Script_scr_dispatch_headhunters */
/* gml_GlobalScript_scr_dispatch_headhunters */
/* gml_Script_scr_AlertEnemy */
/* gml_GlobalScript_scr_AlertEnemy */
/* gml_Script_scr_setup_patrolling */
/* gml_GlobalScript_scr_setup_patrolling */
/* gml_Script_scr_select_from_spawntable */
/* gml_GlobalScript_scr_select_from_spawntable */
/* gml_Script_scr_enemy_ctrl_enforcerCoverPos */
/* gml_GlobalScript_scr_enemy_ctrl_enforcerCoverPos */
/* gml_Script_scr_enemy_get_closest_fire_pos */
/* gml_GlobalScript_scr_enemy_get_closest_fire_pos */
/* gml_Script_scr_enemy_grid_get_cell */
/* gml_GlobalScript_scr_enemy_grid_get_cell */
/* gml_Script_scr_enemy_optimize_path */
/* gml_GlobalScript_scr_enemy_optimize_path */
/* gml_Script_set_enemy_path */
/* gml_GlobalScript_set_enemy_path */
/* gml_Script_scr_enemy_reached_destination */
/* gml_GlobalScript_scr_enemy_reached_destination */
/* gml_Script_scr_enemy_get_random_position */
/* gml_GlobalScript_scr_enemy_get_random_position */
/* gml_Script_scr_enemy_stop_moving */
/* gml_GlobalScript_scr_enemy_stop_moving */
/* gml_Script_scr_enm_base_destructor */
/* gml_GlobalScript_scr_enm_base_destructor */
/* gml_Script_scr_is_pos_in_enemy_view */
/* gml_GlobalScript_scr_is_pos_in_enemy_view */
/* gml_Script_scr_damage_bot */
/* gml_GlobalScript_scr_damage_bot */
/* gml_Script_scr_heal_bot */
/* gml_GlobalScript_scr_heal_bot */
/* gml_Script_scr_nearest_team_member */
/* gml_GlobalScript_scr_nearest_team_member */
/* gml_Script_scr_get_spawn_pos_on_radius */
/* gml_GlobalScript_scr_get_spawn_pos_on_radius */
/* gml_Script_scr_enm_voiceover */
/* gml_GlobalScript_scr_enm_voiceover */
/* gml_Script_scr_enm_sensor_check */
/* gml_GlobalScript_scr_enm_sensor_check */
/* gml_Script_scr_item_descriptions */
/* gml_GlobalScript_scr_item_descriptions */
/* gml_Script_scr_item_tooltip */
/* gml_GlobalScript_scr_item_tooltip */
/* gml_Script_scr_raritycolors_init */
/* gml_GlobalScript_scr_raritycolors_init */
/* gml_Script_scr_drop_item */
/* gml_GlobalScript_scr_drop_item */
/* gml_Script_scr_drop_bossLoot */
/* gml_GlobalScript_scr_drop_bossLoot */
/* gml_Script_scr_pickup_loottable */
/* gml_GlobalScript_scr_pickup_loottable */
/* gml_Script_scr_item_activeandcooldown */
/* gml_GlobalScript_scr_item_activeandcooldown */
/* gml_Script_scr_item_leveling */
/* gml_GlobalScript_scr_item_leveling */
/* gml_Script_scr_item_variants_allitems_bonus */
/* gml_GlobalScript_scr_item_variants_allitems_bonus */
/* gml_Script_scr_indentifypotion_effect */
/* gml_GlobalScript_scr_indentifypotion_effect */
/* gml_Script_scr_item_variants_init */
/* gml_GlobalScript_scr_item_variants_init */
/* gml_Script_scr_transfer_item_coop */
/* gml_GlobalScript_scr_transfer_item_coop */
/* gml_Script_scr_perks_chips */
/* gml_GlobalScript_scr_perks_chips */
/* gml_Script_spr_perks_artefacts */
/* gml_GlobalScript_spr_perks_artefacts */
/* gml_Script_scr_class_upgrades */
/* gml_GlobalScript_scr_class_upgrades */
/* gml_Script_scr_talent_desctiptions */
/* gml_GlobalScript_scr_talent_desctiptions */
/* gml_Script_scr_convert_talenttext */
/* gml_GlobalScript_scr_convert_talenttext */
/* gml_Script_scr_curses_init */
/* gml_GlobalScript_scr_curses_init */
/* gml_Script_scr_perk_save */
/* gml_GlobalScript_scr_perk_save */
/* gml_Script_scr_find_talent_id */
/* gml_GlobalScript_scr_find_talent_id */
/* gml_Script_scr_find_talent_objectindex */
/* gml_GlobalScript_scr_find_talent_objectindex */
/* gml_Script_scr_talents_new */
/* gml_GlobalScript_scr_talents_new */
/* gml_Script_scr_rebinding_button */
/* gml_GlobalScript_scr_rebinding_button */
/* gml_Script_scr_esc_video */
/* gml_GlobalScript_scr_esc_video */
/* gml_Script_scr_esc_game */
/* gml_GlobalScript_scr_esc_game */
/* gml_Script_scr_esc_other */
/* gml_GlobalScript_scr_esc_other */
/* gml_Script_scr_esc_help */
/* gml_GlobalScript_scr_esc_help */
/* gml_Script_scr_esc_help2 */
/* gml_GlobalScript_scr_esc_help2 */
/* gml_Script_scr_esc_credits */
/* gml_GlobalScript_scr_esc_credits */
/* gml_Script_scr_esc_bindings */
/* gml_GlobalScript_scr_esc_bindings */
/* gml_Script_scr_esc_bindings_items */
/* gml_GlobalScript_scr_esc_bindings_items */
/* gml_Script_scr_esc_language */
/* gml_GlobalScript_scr_esc_language */
/* gml_Script_scr_unlock_descriptions */
/* gml_GlobalScript_scr_unlock_descriptions */
/* gml_Script_scr_class_descriptions */
/* gml_GlobalScript_scr_class_descriptions */
/* gml_Script_scr_check_unlock */
/* gml_GlobalScript_scr_check_unlock */
/* gml_Script_scr_color_transistion */
/* gml_GlobalScript_scr_color_transistion */
/* gml_Script_scr_talent_selection */
/* gml_GlobalScript_scr_talent_selection */
/* gml_Script_scr_get_percentage */
/* gml_GlobalScript_scr_get_percentage */
/* gml_Script_scr_remap_valuerange */
/* gml_GlobalScript_scr_remap_valuerange */
/* gml_Script_scr_sort_objList_by_dist */
/* gml_GlobalScript_scr_sort_objList_by_dist */
/* gml_Script_scr_sort_objList_by_depth */
/* gml_GlobalScript_scr_sort_objList_by_depth */
/* gml_Script_scr_distance_sqr */
/* gml_GlobalScript_scr_distance_sqr */
/* gml_Script_scr_sort_vectList_by_dist */
/* gml_GlobalScript_scr_sort_vectList_by_dist */
/* gml_Script_scr_find_vect_in_list */
/* gml_GlobalScript_scr_find_vect_in_list */
/* gml_Script_scr_list_contains */
/* gml_GlobalScript_scr_list_contains */
/* gml_Script_scr_list_delete */
/* gml_GlobalScript_scr_list_delete */
/* gml_Script_scr_list_add_unique */
/* gml_GlobalScript_scr_list_add_unique */
/* gml_Script_scr_is_pos_in_rectangle */
/* gml_GlobalScript_scr_is_pos_in_rectangle */
/* gml_Script_scr_object_is_parent */
/* gml_GlobalScript_scr_object_is_parent */
/* gml_Script_scr_is_parent */
/* gml_GlobalScript_scr_is_parent */
/* gml_Script_scr_find_highest_parent */
/* gml_GlobalScript_scr_find_highest_parent */
/* gml_Script_scr_set_depth */
/* gml_GlobalScript_scr_set_depth */
/* gml_Script_scr_string_trim_whites */
/* gml_GlobalScript_scr_string_trim_whites */
/* gml_Script_scr_localization */
/* gml_GlobalScript_scr_localization */
/* gml_Script_scr_instance_nearest */
/* gml_GlobalScript_scr_instance_nearest */
/* gml_Script_scr_random_gaussian */
/* gml_GlobalScript_scr_random_gaussian */
/* gml_Script_scr_random_exponential */
/* gml_GlobalScript_scr_random_exponential */
/* gml_Script_scr_split_string */
/* gml_GlobalScript_scr_split_string */
/* gml_Script____struct___0_scr_get_array_for_particle_gml_GlobalScript_scr_get_array_for_particle */
/* gml_Script_scr_get_array_for_particle */
/* gml_GlobalScript_scr_get_array_for_particle */
/* gml_Script_scr_range_and_soundcheck */
/* gml_GlobalScript_scr_range_and_soundcheck */
/* gml_Script_scr_prop_spawn_random */
/* gml_GlobalScript_scr_prop_spawn_random */
/* gml_Script_scr_array_choose */
/* gml_GlobalScript_scr_array_choose */
/* gml_Script_scr_object_debug */
/* gml_GlobalScript_scr_object_debug */
/* gml_Script_scr_terrorlevel_increase */
/* gml_GlobalScript_scr_terrorlevel_increase */
/* gml_Script_scr_draw_pausebackground */
/* gml_GlobalScript_scr_draw_pausebackground */
/* gml_Script_scr_prop_shadow_ao_init */
/* gml_GlobalScript_scr_prop_shadow_ao_init */
/* gml_Script_tmc_EASE_enums */
/* gml_GlobalScript_tmc_EASE_enums */
/* gml_Script_tmc_ease_lerp */
/* gml_GlobalScript_tmc_ease_lerp */
/* gml_Script_tmc_ease_progress */
/* gml_GlobalScript_tmc_ease_progress */
/* gml_Script_tmc_ease_start_end */
/* gml_GlobalScript_tmc_ease_start_end */
/* gml_Script_DirtyBloom_define */
/* gml_GlobalScript_DirtyBloom_define */
/* gml_Script_DirtyBloom_enable */
/* gml_GlobalScript_DirtyBloom_enable */
/* gml_Script_DirtyBloom_disable */
/* gml_GlobalScript_DirtyBloom_disable */
/* gml_Script_DirtyBloom_enabled */
/* gml_GlobalScript_DirtyBloom_enabled */
/* gml_Script_DirtyBloom_set_strength */
/* gml_GlobalScript_DirtyBloom_set_strength */
/* gml_Script_DirtyBloom_ghostsdefine */
/* gml_GlobalScript_DirtyBloom_ghostsdefine */
/* gml_Script_tmc_vect_to_vect3 */
/* gml_GlobalScript_tmc_vect_to_vect3 */
/* gml_Script_tmc_vect_mult */
/* gml_GlobalScript_tmc_vect_mult */
/* gml_Script_tmc_vect2 */
/* gml_GlobalScript_tmc_vect2 */
/* gml_Script_tmc_vect3 */
/* gml_GlobalScript_tmc_vect3 */
/* gml_Script_tmc_vect4 */
/* gml_GlobalScript_tmc_vect4 */
/* gml_Script_tmc_vect_add */
/* gml_GlobalScript_tmc_vect_add */
/* gml_Script_tmc_vect_rev */
/* gml_GlobalScript_tmc_vect_rev */
/* gml_Script_tmc_vect_scaler */
/* gml_GlobalScript_tmc_vect_scaler */
/* gml_Script_tmc_vect_dot */
/* gml_GlobalScript_tmc_vect_dot */
/* gml_Script_tmc_vect_cross */
/* gml_GlobalScript_tmc_vect_cross */
/* gml_Script_tmc_vect_dist */
/* gml_GlobalScript_tmc_vect_dist */
/* gml_Script_tmc_vect_len */
/* gml_GlobalScript_tmc_vect_len */
/* gml_Script_tmc_vect_divr */
/* gml_GlobalScript_tmc_vect_divr */
/* gml_Script_tmc_vect_perp */
/* gml_GlobalScript_tmc_vect_perp */
/* gml_Script_tmc_vect_multr */
/* gml_GlobalScript_tmc_vect_multr */
/* gml_Script_tmc_vect_norm */
/* gml_GlobalScript_tmc_vect_norm */
/* gml_Script_tmc_vect_to_vect4 */
/* gml_GlobalScript_tmc_vect_to_vect4 */
/* gml_Script_tmc_vect_to_vect2 */
/* gml_GlobalScript_tmc_vect_to_vect2 */
/* gml_Script_tmc_vect_div */
/* gml_GlobalScript_tmc_vect_div */
/* gml_Script_tmc_vect_comp */
/* gml_GlobalScript_tmc_vect_comp */
/* gml_Script_tmc_vect2_rot */
/* gml_GlobalScript_tmc_vect2_rot */
/* gml_Script_tmc_vect_is_zero */
/* gml_GlobalScript_tmc_vect_is_zero */
/* gml_Script_tmc_vect3_sqr */
/* gml_GlobalScript_tmc_vect3_sqr */
/* gml_Script_vect */
/* gml_GlobalScript_vect */
/* gml_Script_cleanmem_init */
/* gml_GlobalScript_cleanmem_init */
/* gml_Script_cleanmem */
/* gml_GlobalScript_cleanmem */
/* gml_Script_cleanmem_get_mem */
/* gml_GlobalScript_cleanmem_get_mem */
/* gml_Script_line_solid_intersection */
/* gml_GlobalScript_line_solid_intersection */
/* gml_Script_lines_intersect */
/* gml_GlobalScript_lines_intersect */
/* gml_Script_draw_rectangle_width */
/* gml_GlobalScript_draw_rectangle_width */
/* gml_Script_draw_circle_width */
/* gml_GlobalScript_draw_circle_width */
/* gml_Script_avoid_circle */
/* gml_GlobalScript_avoid_circle */
/* gml_Script_avoid_rectangle */
/* gml_GlobalScript_avoid_rectangle */
/* gml_Script_image_scale */
/* gml_GlobalScript_image_scale */
/* gml_Script_draw_reset */
/* gml_GlobalScript_draw_reset */
/* gml_Script_draw_magnify */
/* gml_GlobalScript_draw_magnify */
/* gml_Script_draw_magnify_fast */
/* gml_GlobalScript_draw_magnify_fast */
/* gml_Script_draw_magnify_ext */
/* gml_GlobalScript_draw_magnify_ext */
/* gml_Script_draw_magnify_path_circle */
/* gml_GlobalScript_draw_magnify_path_circle */
/* gml_Script_draw_magnify_path_simple */
/* gml_GlobalScript_draw_magnify_path_simple */
/* gml_Script_draw_magnify_path */
/* gml_GlobalScript_draw_magnify_path */
/* gml_Script_draw_magnify_laser */
/* gml_GlobalScript_draw_magnify_laser */
/* gml_Script_draw_path_gradient */
/* gml_GlobalScript_draw_path_gradient */
/* gml_Script_random_color */
/* gml_GlobalScript_random_color */
/* gml_Script_tolerance */
/* gml_GlobalScript_tolerance */
/* gml_Script_path_random_circle */
/* gml_GlobalScript_path_random_circle */
/* gml_Script_path_random */
/* gml_GlobalScript_path_random */
/* gml_Script_create_shockwave */
/* gml_GlobalScript_create_shockwave */
/* gml_Script_scr_enter_next_floor */
/* gml_GlobalScript_scr_enter_next_floor */
/* gml_Script_scr_colors_borderdecal_finder */
/* gml_GlobalScript_scr_colors_borderdecal_finder */
/* gml_Script_scr_find_chunk_surface */
/* gml_GlobalScript_scr_find_chunk_surface */
/* gml_Script_scr_draw_decal_on_chunks */
/* gml_GlobalScript_scr_draw_decal_on_chunks */
/* gml_Script_scr_is_field_In_rect_list */
/* gml_GlobalScript_scr_is_field_In_rect_list */
/* gml_Script_scr_fit_shape_in_rect_list */
/* gml_GlobalScript_scr_fit_shape_in_rect_list */
/* gml_Script_scr_spawn_chunk_field */
/* gml_GlobalScript_scr_spawn_chunk_field */
/* gml_Script_scr_setup_chunk_fields */
/* gml_GlobalScript_scr_setup_chunk_fields */
/* gml_Script_scr_fieldNodes_getFieldNodesForShape */
/* gml_GlobalScript_scr_fieldNodes_getFieldNodesForShape */
/* gml_Script_scr_chunk_isPathConnected */
/* gml_GlobalScript_scr_chunk_isPathConnected */
/* gml_Script_scr_chunk_connect_path */
/* gml_GlobalScript_scr_chunk_connect_path */
/* gml_Script_scr_node_A_Star */
/* gml_GlobalScript_scr_node_A_Star */
/* gml_Script_scr_get_shape_dimensions */
/* gml_GlobalScript_scr_get_shape_dimensions */
/* gml_Script_scr_chunk_getPathSet */
/* gml_GlobalScript_scr_chunk_getPathSet */
/* gml_Script_scr_fieldNodes_distance */
/* gml_GlobalScript_scr_fieldNodes_distance */
/* gml_Script_scr_chunk_helper_sets_connect */
/* gml_GlobalScript_scr_chunk_helper_sets_connect */
/* gml_Script_scr_fit_shape_in_node_list */
/* gml_GlobalScript_scr_fit_shape_in_node_list */
/* gml_Script_scr_spawn_rnd_smallRoom */
/* gml_GlobalScript_scr_spawn_rnd_smallRoom */
/* gml_Script_scr_spawn_rnd_extra */
/* gml_GlobalScript_scr_spawn_rnd_extra */
/* gml_Script_scr_spawn_rnd_smallRoom_noWalls */
/* gml_GlobalScript_scr_spawn_rnd_smallRoom_noWalls */
/* gml_Script_scr_spawn_room */
/* gml_GlobalScript_scr_spawn_room */
/* gml_Script_scr_spawn_rnd_mediumRoom */
/* gml_GlobalScript_scr_spawn_rnd_mediumRoom */
/* gml_Script_scr_spawn_rnd_mediumRoom_noWalls */
/* gml_GlobalScript_scr_spawn_rnd_mediumRoom_noWalls */
/* gml_Script_scr_spawn_rnd_bigRoom */
/* gml_GlobalScript_scr_spawn_rnd_bigRoom */
/* gml_Script_scr_spawn_rnd_bigRoom_noWalls */
/* gml_GlobalScript_scr_spawn_rnd_bigRoom_noWalls */
/* gml_Script_draw_crosshair_quarter */
/* gml_GlobalScript_draw_crosshair_quarter */
/* gml_Script_draw_circle_curve */
/* gml_GlobalScript_draw_circle_curve */
/* gml_Script_scr_roll_next_room */
/* gml_GlobalScript_scr_roll_next_room */
/* gml_Script_scr_goto_room */
/* gml_GlobalScript_scr_goto_room */
/* gml_Script_scr_quest_finished */
/* gml_GlobalScript_scr_quest_finished */
/* gml_Script_scr_skyscraper_draw */
/* gml_GlobalScript_scr_skyscraper_draw */
/* gml_Script_scr_deathrecap */
/* gml_GlobalScript_scr_deathrecap */
/* gml_Script_debug */
/* gml_GlobalScript_debug */
/* gml_Script_scr_collision_line */
/* gml_GlobalScript_scr_collision_line */
/* gml_Script_scr_is_in_layer */
/* gml_GlobalScript_scr_is_in_layer */
/* gml_Script_scr_raycast */
/* gml_GlobalScript_scr_raycast */
/* gml_Script_scr_filter_layer */
/* gml_GlobalScript_scr_filter_layer */
/* gml_GlobalScript_scr_get_collision_normal_dir */
/* gml_Script_scr_get_collision_rectangle */
/* gml_GlobalScript_scr_get_collision_rectangle */
/* gml_Script_scr_get_collision_free */
/* gml_GlobalScript_scr_get_collision_free */
/* gml_Script_scr_invert_layer */
/* gml_GlobalScript_scr_invert_layer */
/* gml_Script_scr_get_closest_obj_in_range */
/* gml_GlobalScript_scr_get_closest_obj_in_range */
/* gml_Script_scr_grids_add_rectangle */
/* gml_GlobalScript_scr_grids_add_rectangle */
/* gml_Script_scr_grids_clear_rectangle */
/* gml_GlobalScript_scr_grids_clear_rectangle */
/* gml_Script_scr_grids_add_circle */
/* gml_GlobalScript_scr_grids_add_circle */
/* gml_Script_scr_grids_clear_circle */
/* gml_GlobalScript_scr_grids_clear_circle */
/* gml_Script_scr_get_random_pickup_pos */
/* gml_GlobalScript_scr_get_random_pickup_pos */
/* gml_Script_scr_networking_instantiate */
/* gml_GlobalScript_scr_networking_instantiate */
/* gml_Script_scr_networking_instantiate_bullet */
/* gml_GlobalScript_scr_networking_instantiate_bullet */
/* gml_Script_scr_networking_destroy */
/* gml_GlobalScript_scr_networking_destroy */
/* gml_Script_scr_get_inst_for_networkId */
/* gml_GlobalScript_scr_get_inst_for_networkId */
/* gml_Script_scr_send_packet */
/* gml_GlobalScript_scr_send_packet */
/* gml_Script_scr_MS_request_join_lobby */
/* gml_GlobalScript_scr_MS_request_join_lobby */
/* gml_Script_scr_MS_send_packet_queue */
/* gml_GlobalScript_scr_MS_send_packet_queue */
/* gml_Script_scr_send_MS_packet */
/* gml_GlobalScript_scr_send_MS_packet */
/* gml_Script_scr_send_net_rpc */
/* gml_GlobalScript_scr_send_net_rpc */
/* gml_Script____struct___1_scr_shared_networking_event_gml_GlobalScript_scr_shared_networking_event */
/* gml_Script____struct___2_scr_shared_networking_event_gml_GlobalScript_scr_shared_networking_event */
/* gml_Script____struct___3_scr_shared_networking_event_gml_GlobalScript_scr_shared_networking_event */
/* gml_Script____struct___4_scr_shared_networking_event_gml_GlobalScript_scr_shared_networking_event */
/* gml_Script_scr_shared_networking_event */
/* gml_GlobalScript_scr_shared_networking_event */
/* gml_Script_scr_instance_create */
/* gml_GlobalScript_scr_instance_create */
/* gml_Script_scr_new_lobby_notification */
/* gml_GlobalScript_scr_new_lobby_notification */
/* gml_Script_scr_encrypt_password */
/* gml_GlobalScript_scr_encrypt_password */
/* gml_Script_scr_MS_send_Login */
/* gml_GlobalScript_scr_MS_send_Login */
/* gml_Script_scr_MS_send_RequestPasswordReset */
/* gml_GlobalScript_scr_MS_send_RequestPasswordReset */
/* gml_Script_scr_MS_send_CreateAccount */
/* gml_GlobalScript_scr_MS_send_CreateAccount */
/* gml_Script_scr_MS_send_PasswordReset */
/* gml_GlobalScript_scr_MS_send_PasswordReset */
/* gml_Script_scr_MS_reopen_lobby */
/* gml_GlobalScript_scr_MS_reopen_lobby */
/* gml_Script_scr_send_global_chat_message */
/* gml_GlobalScript_scr_send_global_chat_message */
/* gml_Script_scr_MS_set_referal */
/* gml_GlobalScript_scr_MS_set_referal */
/* gml_Script_scr_add_chat_entry */
/* gml_GlobalScript_scr_add_chat_entry */
/* gml_Script_scr_send_LobbyUpdate */
/* gml_GlobalScript_scr_send_LobbyUpdate */
/* gml_Script_scr_send_ArenaMissionSelect */
/* gml_GlobalScript_scr_send_ArenaMissionSelect */
/* gml_Script_scr_networking_instantiateSingle */
/* gml_GlobalScript_scr_networking_instantiateSingle */
/* gml_Script_scr_net_subscribe_newsletter */
/* gml_GlobalScript_scr_net_subscribe_newsletter */
/* gml_Script_scr_net_add_statuseffect */
/* gml_GlobalScript_scr_net_add_statuseffect */
/* gml_Script_scr_net_cleanup_remote */
/* gml_GlobalScript_scr_net_cleanup_remote */
/* gml_Script_scr_net_write_packet */
/* gml_GlobalScript_scr_net_write_packet */
/* gml_Script_scr_networking_receiving_server */
/* gml_GlobalScript_scr_networking_receiving_server */
/* gml_Script_scr_networking_receiving_client */
/* gml_GlobalScript_scr_networking_receiving_client */
/* gml_Script_scr_networking_get_region_name */
/* gml_GlobalScript_scr_networking_get_region_name */
/* gml_Script_scr_increase_packetID */
/* gml_GlobalScript_scr_increase_packetID */
/* gml_Script_scr_random_set_seed */
/* gml_GlobalScript_scr_random_set_seed */
/* gml_Script_scr_random_get_value */
/* gml_GlobalScript_scr_random_get_value */
/* gml_Script_scr_random_irandom */
/* gml_GlobalScript_scr_random_irandom */
/* gml_Script_scr_random_random */
/* gml_GlobalScript_scr_random_random */
/* gml_Script_scr_random_random_range */
/* gml_GlobalScript_scr_random_random_range */
/* gml_Script_scr_random_choose */
/* gml_GlobalScript_scr_random_choose */
/* gml_Script_scr_random_shuffle_list */
/* gml_GlobalScript_scr_random_shuffle_list */
/* gml_Script_scr_draw_targetlaser */
/* gml_GlobalScript_scr_draw_targetlaser */
/* gml_Script_scr_calculate_targetlaser_distance */
/* gml_GlobalScript_scr_calculate_targetlaser_distance */
/* gml_Script_scr_play_sound_at */
/* gml_GlobalScript_scr_play_sound_at */
/* gml_Script_scr_antibullet_laser */
/* gml_GlobalScript_scr_antibullet_laser */
/* gml_Script_scr_healing_laser_turret */
/* gml_GlobalScript_scr_healing_laser_turret */
/* gml_Script_scr_mp_grid_cast */
/* gml_GlobalScript_scr_mp_grid_cast */
/* gml_Script_draw_SHADER_blur */
/* gml_GlobalScript_draw_SHADER_blur */
/* gml_Script_scr_update_particle_pos */
/* gml_GlobalScript_scr_update_particle_pos */
/* gml_Script_scr_bullet_chain_get_hits */
/* gml_GlobalScript_scr_bullet_chain_get_hits */
/* gml_Script_scr_enemy_set_stateChanged */
/* gml_GlobalScript_scr_enemy_set_stateChanged */
/* gml_Script_scr_mp_get_closest_grid_pos */
/* gml_GlobalScript_scr_mp_get_closest_grid_pos */
/* gml_Script_README */
/* gml_GlobalScript_README */
/* gml_Script_gfx_blur */
/* gml_GlobalScript_gfx_blur */
/* gml_Script_gfx_blur_directional */
/* gml_GlobalScript_gfx_blur_directional */
/* gml_Script_gfx_blur_gaussian */
/* gml_GlobalScript_gfx_blur_gaussian */
/* gml_Script_gfx_blur_masked */
/* gml_GlobalScript_gfx_blur_masked */
/* gml_Script_gfx_blur_radial */
/* gml_GlobalScript_gfx_blur_radial */
/* gml_Script_gfx_blur_twist */
/* gml_GlobalScript_gfx_blur_twist */
/* gml_Script_curve_get_value */
/* gml_GlobalScript_curve_get_value */
/* gml_Script_scr_ini_open */
/* gml_GlobalScript_scr_ini_open */
/* gml_Script_scr_file_exists */
/* gml_GlobalScript_scr_file_exists */
/* gml_Script_scr_file_delete */
/* gml_GlobalScript_scr_file_delete */
/* gml_Script_scr_ini_write_string */
/* gml_GlobalScript_scr_ini_write_string */
/* gml_Script_scr_sound */
/* gml_GlobalScript_scr_sound */
/* gml_Script_draw_circular_progress_bar */
/* gml_GlobalScript_draw_circular_progress_bar */
/* gml_Script_scr_tooltip */
/* gml_GlobalScript_scr_tooltip */
/* gml_Script_scr_helptext */
/* gml_GlobalScript_scr_helptext */
/* gml_Script_scr_notification */
/* gml_GlobalScript_scr_notification */
/* gml_Script_scr_button */
/* gml_GlobalScript_scr_button */
/* gml_Script_scr_button_intro */
/* gml_GlobalScript_scr_button_intro */
/* gml_Script_scr_slider */
/* gml_GlobalScript_scr_slider */
/* gml_Script_scr_button_check */
/* gml_GlobalScript_scr_button_check */
/* gml_Script_scr_healthbar */
/* gml_GlobalScript_scr_healthbar */
/* gml_Script_scr_DailyReward */
/* gml_GlobalScript_scr_DailyReward */
/* gml_Script_scr_mouseover */
/* gml_GlobalScript_scr_mouseover */
/* gml_Script_scr_tween0 */
/* gml_GlobalScript_scr_tween0 */
/* gml_Script_scr_list_create */
/* gml_GlobalScript_scr_list_create */
/* gml_Script_scr_list_destroy */
/* gml_GlobalScript_scr_list_destroy */
/* gml_Script_scr_get_input */
/* gml_GlobalScript_scr_get_input */
/* gml_Script_scr_rebind_input */
/* gml_GlobalScript_scr_rebind_input */
/* gml_Script_scr_get_input_name */
/* gml_GlobalScript_scr_get_input_name */
/* gml_Script_scr_check_key */
/* gml_GlobalScript_scr_check_key */
/* gml_Script_scr_check_gamepad_key */
/* gml_GlobalScript_scr_check_gamepad_key */
/* gml_Script_scr_gamepad_check_itemBlock */
/* gml_GlobalScript_scr_gamepad_check_itemBlock */
/* gml_Script_scr_get_gamepad_key_name */
/* gml_GlobalScript_scr_get_gamepad_key_name */
/* gml_Script_scr_get_key_name */
/* gml_GlobalScript_scr_get_key_name */
/* gml_Script_scr_load_language */
/* gml_GlobalScript_scr_load_language */
/* gml_Script_scr_load_language_backup */
/* gml_GlobalScript_scr_load_language_backup */
/* gml_Script_draw_healthbar_circular */
/* gml_GlobalScript_draw_healthbar_circular */
/* gml_Script_scr_join_team */
/* gml_GlobalScript_scr_join_team */
/* gml_Script_scr_leave_team */
/* gml_GlobalScript_scr_leave_team */
/* gml_Script_scr_get_other_team */
/* gml_GlobalScript_scr_get_other_team */
/* gml_Script_scr_get_team */
/* gml_GlobalScript_scr_get_team */
/* gml_Script_scr_get_all_teams */
/* gml_GlobalScript_scr_get_all_teams */
/* gml_Script_colorpicker */
/* gml_GlobalScript_colorpicker */
/* gml_Script_scp_set */
/* gml_GlobalScript_scp_set */
/* gml_Script_scr_console_input */
/* gml_GlobalScript_scr_console_input */
/* gml_Script_DissolveShader */
/* gml_GlobalScript_DissolveShader */
/* gml_GlobalScript_DissolveSettings */
/* gml_Script_action_current_room */
/* gml_GlobalScript_action_current_room */
/* gml_Script_action_end_game */
/* gml_GlobalScript_action_end_game */
/* gml_Script_action_kill_object */
/* gml_GlobalScript_action_kill_object */
/* gml_Script_action_next_room */
/* gml_GlobalScript_action_next_room */
/* gml_Script_action_restart_game */
/* gml_GlobalScript_action_restart_game */
/* gml_Script_action_wrap */
/* gml_GlobalScript_action_wrap */
/* gml_Script___init_action */
/* gml_GlobalScript___init_action */
/* gml_Script_background_get_texture */
/* gml_GlobalScript_background_get_texture */
/* gml_Script_draw_background_tiled */
/* gml_GlobalScript_draw_background_tiled */
/* gml_Script___background_get */
/* gml_GlobalScript___background_get */
/* gml_Script___background_get_colour */
/* gml_GlobalScript___background_get_colour */
/* gml_Script___background_get_colour_element */
/* gml_GlobalScript___background_get_colour_element */
/* gml_Script___background_get_element */
/* gml_GlobalScript___background_get_element */
/* gml_Script___background_get_internal */
/* gml_GlobalScript___background_get_internal */
/* gml_Script___background_set */
/* gml_GlobalScript___background_set */
/* gml_Script___background_set_colour */
/* gml_GlobalScript___background_set_colour */
/* gml_Script___background_set_element */
/* gml_GlobalScript___background_set_element */
/* gml_Script___background_set_internal */
/* gml_GlobalScript___background_set_internal */
/* gml_Script___init_background */
/* gml_GlobalScript___init_background */
/* gml_Script_d3d_set_fog */
/* gml_GlobalScript_d3d_set_fog */
/* gml_Script_d3d_transform_add_translation */
/* gml_GlobalScript_d3d_transform_add_translation */
/* gml_Script_d3d_transform_set_identity */
/* gml_GlobalScript_d3d_transform_set_identity */
/* gml_Script_d3d_transform_set_rotation_z */
/* gml_GlobalScript_d3d_transform_set_rotation_z */
/* gml_Script___init_d3d */
/* gml_GlobalScript___init_d3d */
/* gml_Script_draw_set_alpha_test */
/* gml_GlobalScript_draw_set_alpha_test */
/* gml_Script_draw_set_blend_mode */
/* gml_GlobalScript_draw_set_blend_mode */
/* gml_Script_draw_set_blend_mode_ext */
/* gml_GlobalScript_draw_set_blend_mode_ext */
/* gml_Script_instance_create */
/* gml_GlobalScript_instance_create */
/* gml_Script_object_get_depth */
/* gml_GlobalScript_object_get_depth */
/* gml_Script_texture_set_repeat */
/* gml_GlobalScript_texture_set_repeat */
/* gml_Script_tile_add */
/* gml_GlobalScript_tile_add */
/* gml_Script_tile_delete */
/* gml_GlobalScript_tile_delete */
/* gml_Script_tile_exists */
/* gml_GlobalScript_tile_exists */
/* gml_Script_tile_get_background */
/* gml_GlobalScript_tile_get_background */
/* gml_Script_tile_get_depth */
/* gml_GlobalScript_tile_get_depth */
/* gml_Script_tile_get_height */
/* gml_GlobalScript_tile_get_height */
/* gml_Script_tile_get_ids */
/* gml_GlobalScript_tile_get_ids */
/* gml_Script_tile_get_left */
/* gml_GlobalScript_tile_get_left */
/* gml_Script_tile_get_top */
/* gml_GlobalScript_tile_get_top */
/* gml_Script_tile_get_width */
/* gml_GlobalScript_tile_get_width */
/* gml_Script_tile_get_x */
/* gml_GlobalScript_tile_get_x */
/* gml_Script_tile_get_y */
/* gml_GlobalScript_tile_get_y */
/* gml_Script_tile_layer_find */
/* gml_GlobalScript_tile_layer_find */
/* gml_Script_tile_set_blend */
/* gml_GlobalScript_tile_set_blend */
/* gml_Script___view_get */
/* gml_GlobalScript___view_get */
/* gml_Script___view_set */
/* gml_GlobalScript___view_set */
/* gml_Script___view_set_internal */
/* gml_GlobalScript___view_set_internal */
/* gml_Script___init_view */
/* gml_GlobalScript___init_view */
/* gml_Script___init_global */
/* gml_GlobalScript___init_global */
/* gml_Script___global_object_depths */
/* gml_GlobalScript___global_object_depths */
/* gml_Script_scr_rumble */
/* gml_GlobalScript_scr_rumble */
/* gml_Script_scr_reset_tokens */
/* gml_GlobalScript_scr_reset_tokens */
/* gml_Script_scr_powerup */
/* gml_GlobalScript_scr_powerup */
/* gml_Script_scr_perks_mars */
/* gml_GlobalScript_scr_perks_mars */
/* gml_Script_scr_has_supporter_pack */
/* gml_GlobalScript_scr_has_supporter_pack */
/* gml_Script_scr_has_supporter_pack2 */
/* gml_GlobalScript_scr_has_supporter_pack2 */
/* gml_Script_scr_has_arena_pack */
/* gml_GlobalScript_scr_has_arena_pack */
/* gml_Script_scr_has_synthetik */
/* gml_GlobalScript_scr_has_synthetik */
/* gml_Script_scr_load_languages_fixed */
/* gml_GlobalScript_scr_load_languages_fixed */
/* gml_Script_scr_perk_system */
/* gml_GlobalScript_scr_perk_system */
/* gml_Script_scr_pauseCheck */
/* gml_GlobalScript_scr_pauseCheck */
/* gml_Script_scr_fightCheck */
/* gml_GlobalScript_scr_fightCheck */
/* gml_Script_scr_check_DLCS */
/* gml_GlobalScript_scr_check_DLCS */
/* gml_Script_scr_KPI_Arena */
/* gml_GlobalScript_scr_KPI_Arena */
/* gml_Script_scr_change_gamemode */
/* gml_GlobalScript_scr_change_gamemode */
/* gml_Script_scr_load_progress */
/* gml_GlobalScript_scr_load_progress */
/* gml_Script_scr_savegame_ini */
/* gml_GlobalScript_scr_savegame_ini */
/* gml_Script_scr_progress_ini_save */
/* gml_GlobalScript_scr_progress_ini_save */
/* gml_Script_scr_load_statistics */
/* gml_GlobalScript_scr_load_statistics */
/* gml_Script_scr_statistics_ini */
/* gml_GlobalScript_scr_statistics_ini */
/* gml_Script_scr_statistics_saving */
/* gml_GlobalScript_scr_statistics_saving */
/* gml_Script_scr_settings_load */
/* gml_GlobalScript_scr_settings_load */
/* gml_Script_scr_settings_ini */
/* gml_GlobalScript_scr_settings_ini */
/* gml_Script_scr_settings_ini_save */
/* gml_GlobalScript_scr_settings_ini_save */
/* gml_Script_scr_map_to_string */
/* gml_GlobalScript_scr_map_to_string */
/* gml_Script_scr_handle_switch_online */
/* gml_GlobalScript_scr_handle_switch_online */
/* gml_Script_scr_check_achievements */
/* gml_GlobalScript_scr_check_achievements */
/* gml_Script_scr_set_Achievement */
/* gml_GlobalScript_scr_set_Achievement */
/* gml_Script_scr_unlock_outgame_progress */
/* gml_GlobalScript_scr_unlock_outgame_progress */
/* gml_Script_scr_boss_dialogs */
/* gml_GlobalScript_scr_boss_dialogs */
/* gml_Script_scr_ds_grid_get */
/* gml_GlobalScript_scr_ds_grid_get */
/* gml_Script_scr_mp_grid_get_cell */
/* gml_GlobalScript_scr_mp_grid_get_cell */
/* gml_Script_scr_ds_grid_set */
/* gml_GlobalScript_scr_ds_grid_set */
/* gml_Script_scr_ds_grid_set_region */
/* gml_GlobalScript_scr_ds_grid_set_region */
/* gml_Script_DOCUMENTATION_README */
/* gml_GlobalScript_DOCUMENTATION_README */
/* gml_Script_draw_9slice */
/* gml_GlobalScript_draw_9slice */
/* gml_Script_slice_init */
/* gml_GlobalScript_slice_init */
/* gml_Script_slice_pragma */
/* gml_GlobalScript_slice_pragma */
/* gml_Script_scr_technologies */
/* gml_GlobalScript_scr_technologies */
/* gml_Script_scr_prefetch_queue */
/* gml_GlobalScript_scr_prefetch_queue */
/* gml_Script____struct___5_gml_Object_outgame_Create_0 */
/* gml_Script____struct___6_gml_Object_obj_enm_base_parent_Create_0 */
/* gml_Script____struct___7_gml_Object_obj_moving_entity_PARENT_Other_22 */
/* gml_Script____struct___8_gml_Object_obj_moving_entity_PARENT_Other_22 */
/* gml_GlobalScript_0 */
/* gml_GlobalScript_1 */
/* gml_GlobalScript_2 */
/* gml_GlobalScript_3 */
/* gml_GlobalScript_4 */
/* gml_Script_scr_get_collision_normal_dir */
/* gml_Script_DissolveSettings */

#endif